import { DetailedProblemData } from '../leetcodeSolutions'

export const backtrackingSolutions: Record<string, DetailedProblemData> = {
  "Subsets": {
    intuition: "At each element nums[i], we have two choices: INCLUDE nums[i] in the current subset or EXCLUDE nums[i]. Recursively branch on both choices down to index n to generate all 2^n power set subsets in O(n * 2^n) time.",
    bottleneck: "Bitmask enumeration also works. DFS backtracking generates subsets in-place with single append/pop per branch.",
    keyInvariant: "At index i, all decisions for elements 0..i-1 are fixed, exploring all possible subsets.",
    constraints: ["1 <= nums.length <= 10", "-10 <= nums[i] <= 10", "All numbers in nums are unique."],
    examples: [{"input": "nums = [1,2,3]", "output": "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]", "explanation": "All 2^3 = 8 subsets."}],
    companies: ["Amazon", "Meta", "Google", "Microsoft"],
    acceptanceRate: "76.8%",
    frequency: "95%",
    edgeCases: ["Single element array", "Empty subset is always included"],
    interviewTips: ["Draw the binary decision tree (include vs exclude) to explain the 2^n complexity."],
    optimal: {
      title: "DFS Backtracking Binary Inclusion Tree",
      subtitle: "O(n * 2^n) time and O(n) space power set generation",
      timeComplexity: "O(n * 2^n)",
      timeComplexityDetail: "Generates exactly 2^n subsets, copying each of size up to n.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Call stack depth and current subset buffer.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dfs(i): append copy of cur if i == n. Branch 1: include nums[i], dfs(i+1), backtrack. Branch 2: exclude nums[i], dfs(i+1).",
      keySteps: ["1. res = [], cur = [].", "2. dfs(i): if i == len(nums): res.append(cur[:]); return. cur.append(nums[i]); dfs(i + 1); cur.pop(); dfs(i + 1).", "3. dfs(0), return res."],
      code: {
        python: ["class Solution:", "    def subsets(self, nums: List[int]) -> List[List[int]]:", "        res, cur = [], []", "        def dfs(i):", "            if i >= len(nums):", "                res.append(cur[:])", "                return", "            cur.append(nums[i])", "            dfs(i + 1)", "            cur.pop()", "            dfs(i + 1)", "        dfs(0)", "        return res"],
        cpp: ["#include <vector>", "using namespace std;", "class Solution {", "public:", "    vector<vector<int>> subsets(vector<int>& nums) {", "        vector<vector<int>> res;", "        vector<int> cur;", "        auto dfs = [&](auto& self, int i) -> void {", "            if (i >= nums.size()) { res.push_back(cur); return; }", "            cur.push_back(nums[i]); self(self, i + 1);", "            cur.pop_back(); self(self, i + 1);", "        };", "        dfs(dfs, 0);", "        return res;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public List<List<Integer>> subsets(int[] nums) {", "        List<List<Integer>> res = new ArrayList<>();", "        dfs(0, nums, new ArrayList<>(), res);", "        return res;", "    }", "    private void dfs(int i, int[] nums, List<Integer> cur, List<List<Integer>> res) {", "        if (i >= nums.length) { res.add(new ArrayList<>(cur)); return; }", "        cur.add(nums[i]); dfs(i + 1, nums, cur, res);", "        cur.remove(cur.size() - 1); dfs(i + 1, nums, cur, res);", "    }", "}"],
        typescript: ["function subsets(nums: number[]): number[][] {", "  const res: number[][] = [], cur: number[] = [];", "  const dfs = (i: number) => {", "    if (i >= nums.length) { res.push([...cur]); return; }", "    cur.push(nums[i]); dfs(i + 1);", "    cur.pop(); dfs(i + 1);", "  };", "  dfs(0); return res;", "}"],
      },
    },
    bruteForce: {
      title: "Bitmask Iteration",
      subtitle: "O(n * 2^n) time",
      timeComplexity: "O(n * 2^n)",
      timeComplexityDetail: "Iterate 0 to 2^n - 1.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "No stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "For mask in 0..2^n-1: include nums[j] if mask & (1 << j).",
      keySteps: ["1. Loop masks 0 to 2^n-1.", "2. Extract subset."],
      code: {
        python: ["# Bitmask"],
        cpp: ["// Bitmask"],
        java: ["// Bitmask"],
        typescript: ["// Bitmask"],
      },
    },
  },
  "Subsets II": {
    intuition: "Array contains DUPLICATES. First SORT `nums`. At each recursion step, we choose to include `nums[i]` and recurse on `i + 1`. For the exclusion branch, SKIP all adjacent duplicate elements: `while i + 1 < len(nums) and nums[i] == nums[i + 1]: i += 1`. This guarantees every duplicate subset is generated exactly once without using a set.",
    bottleneck: "Using a hash set to deduplicate subsets takes O(n * 2^n) time with high hash overhead. Sorting + skipping adjacent duplicates prunes duplicates at source in O(n * 2^n) time.",
    keyInvariant: "Skipping identical elements on the exclusion branch guarantees unique subset combinations.",
    constraints: ["1 <= nums.length <= 10", "-10 <= nums[i] <= 10"],
    examples: [{"input": "nums = [1,2,2]", "output": "[[],[1],[1,2],[1,2,2],[2],[2,2]]", "explanation": "Unique subsets only."}],
    companies: ["Amazon", "Meta", "Google"],
    acceptanceRate: "57.4%",
    frequency: "88%",
    edgeCases: ["All elements identical (e.g. [2,2,2,2])", "Single element array"],
    interviewTips: ["Always emphasize that sorting is the mandatory first step for duplicate pruning."],
    optimal: {
      title: "Sort + Backtracking with Duplicate Branch Pruning",
      subtitle: "O(n * 2^n) time and O(n) space unique subset generation",
      timeComplexity: "O(n * 2^n)",
      timeComplexityDetail: "Generates each unique subset once.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Recursion stack depth.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Sort array. Include nums[i], dfs(i+1). Exclude: skip all nums[i] == nums[i+1], dfs(next_diff).",
      keySteps: ["1. nums.sort(), res = [], cur = [].", "2. dfs(i): if i >= len(nums): res.append(cur[:]); return. cur.append(nums[i]); dfs(i + 1); cur.pop(). While i + 1 < len(nums) and nums[i] == nums[i + 1]: i += 1. dfs(i + 1).", "3. dfs(0), return res."],
      code: {
        python: ["class Solution:", "    def subsetsWithDup(self, nums: List[int]) -> List[List[int]]:", "        nums.sort()", "        res, cur = [], []", "        def dfs(i):", "            if i >= len(nums):", "                res.append(cur[:])", "                return", "            cur.append(nums[i])", "            dfs(i + 1)", "            cur.pop()", "            while i + 1 < len(nums) and nums[i] == nums[i + 1]:", "                i += 1", "            dfs(i + 1)", "        dfs(0)", "        return res"],
        cpp: ["// Subsets II cpp"],
        java: ["// Subsets II java"],
        typescript: ["// Subsets II ts"],
      },
    },
    bruteForce: {
      title: "Generate All and Filter with Hash Set",
      subtitle: "O(n * 2^n) time and O(n * 2^n) space",
      timeComplexity: "O(n * 2^n)",
      timeComplexityDetail: "Hash set deduplication.",
      spaceComplexity: "O(n * 2^n)",
      spaceComplexityDetail: "Set storage.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Sort each subset and add to a hash set of tuples.",
      keySteps: ["1. Generate all.", "2. Set deduplicate."],
      code: {
        python: ["# Hash set"],
        cpp: ["// Set"],
        java: ["// Set"],
        typescript: ["// Set"],
      },
    },
  },
  "Combination Sum": {
    intuition: "The same candidate number may be chosen an UNLIMITED number of times. Sort candidates. At index i: 1) If `total == target`, record subset. 2) If `total > target` or `i >= len(candidates)`, backtrack. 3) Branch 1: include `candidates[i]` and recurse on the SAME index `i` (`dfs(i, cur, total + candidates[i])`). 4) Branch 2: exclude `candidates[i]` and recurse on `i + 1`.",
    bottleneck: "Generating permutations and filtering takes exponential time. Fixed-index backtracking only generates combinations in lexicographical order in O(2^(T/min)) time.",
    keyInvariant: "Passing index i allows reusing candidates[i] without re-exploring earlier elements, preventing permutation duplicates.",
    constraints: ["1 <= candidates.length <= 30", "2 <= candidates[i] <= 40", "All elements of candidates are distinct.", "1 <= target <= 40"],
    examples: [{"input": "candidates = [2,3,6,7], target = 7", "output": "[[2,2,3],[7]]", "explanation": "Combinations summing to 7."}],
    companies: ["Amazon", "Meta", "Google", "Microsoft", "Apple"],
    acceptanceRate: "70.8%",
    frequency: "96%",
    edgeCases: ["Target smaller than minimum candidate (returns [])", "Single candidate divides target"],
    interviewTips: ["Explain why `dfs(i, ...)` (not `i + 1`) enables unlimited reuse of the same number."],
    optimal: {
      title: "Backtracking with Self-Index Reuse",
      subtitle: "O(2^(target / min_val)) time and O(target / min_val) space",
      timeComplexity: "O(2^(target / min_val))",
      timeComplexityDetail: "Branching bounded by max tree depth.",
      spaceComplexity: "O(target / min_val)",
      spaceComplexityDetail: "Recursion call stack.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dfs(i, cur, total): branch on including candidates[i] (stay at i) or moving to i+1.",
      keySteps: ["1. res = [].", "2. dfs(i, cur, total): if total == target: res.append(cur[:]); return. If total > target or i >= len(candidates): return. cur.append(candidates[i]); dfs(i, cur, total + candidates[i]); cur.pop(); dfs(i + 1, cur, total).", "3. dfs(0, [], 0), return res."],
      code: {
        python: ["class Solution:", "    def combinationSum(self, candidates: List[int], target: int) -> List[List[int]]:", "        res = []", "        def dfs(i, cur, total):", "            if total == target:", "                res.append(cur[:])", "                return", "            if total > target or i >= len(candidates):", "                return", "            cur.append(candidates[i])", "            dfs(i, cur, total + candidates[i])", "            cur.pop()", "            dfs(i + 1, cur, total)", "        dfs(0, [], 0)", "        return res"],
        cpp: ["// Combination Sum cpp"],
        java: ["// Combination Sum java"],
        typescript: ["// Combination Sum ts"],
      },
    },
    bruteForce: {
      title: "Exhaustive BFS Combination Search",
      subtitle: "O(K^N) time",
      timeComplexity: "O(K^N)",
      timeComplexityDetail: "Queue state explosion.",
      spaceComplexity: "O(K^N)",
      spaceComplexityDetail: "Queue.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Explore combinations with queue tracking sum.",
      keySteps: ["1. Queue combinations."],
      code: {
        python: ["# BFS combinations"],
        cpp: ["// BFS"],
        java: ["// BFS"],
        typescript: ["// BFS"],
      },
    },
  },
  "Combination Sum II": {
    intuition: "Each number in candidates may only be used ONCE, and candidates may contain duplicates. 1) SORT `candidates`. 2) Loop `for j in range(i, len(candidates))`: if `j > i and candidates[j] == candidates[j - 1]`, skip to prevent duplicate combinations at the same depth level. 3) If `candidates[j] > target`, break early (pruning). 4) Recurse on `j + 1`.",
    bottleneck: "Hash set deduplication is slow. Sorting + level loop `if j > i and candidates[j] == candidates[j-1]: continue` prunes duplicate branches cleanly in O(2^n) time.",
    keyInvariant: "At the same tree depth level, duplicate elements are skipped (`j > i and candidates[j] == candidates[j-1]`).",
    constraints: ["1 <= candidates.length <= 100", "1 <= candidates[i] <= 50", "1 <= target <= 30"],
    examples: [{"input": "candidates = [10,1,2,7,6,1,5], target = 8", "output": "[[1,1,6],[1,2,5],[1,7],[2,6]]", "explanation": "Unique combinations."}],
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    acceptanceRate: "55.1%",
    frequency: "92%",
    edgeCases: ["Candidates with multiple identical numbers", "Target cannot be formed"],
    interviewTips: ["Explain the difference between `j > i` (same level duplicate skip) vs `j == i` (first time seeing this number)."],
    optimal: {
      title: "Sort + Level-Based Duplicate Pruning Backtracking",
      subtitle: "O(2^n) time and O(n) space unique combinations",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Each unique subset combination visited once.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack depth.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Sort array. Loop j from i to end, skip duplicates when j > i, break if candidates[j] > remain.",
      keySteps: ["1. candidates.sort(), res = [].", "2. dfs(start, cur, remain): if remain == 0: res.append(cur[:]); return. For j in range(start, len(candidates)): if candidates[j] > remain: break; if j > start and candidates[j] == candidates[j-1]: continue; cur.append(candidates[j]); dfs(j + 1, cur, remain - candidates[j]); cur.pop().", "3. dfs(0, [], target), return res."],
      code: {
        python: ["class Solution:", "    def combinationSum2(self, candidates: List[int], target: int) -> List[List[int]]:", "        candidates.sort()", "        res = []", "        def dfs(start, cur, remain):", "            if remain == 0:", "                res.append(cur[:])", "                return", "            for j in range(start, len(candidates)):", "                if candidates[j] > remain: break", "                if j > start and candidates[j] == candidates[j - 1]: continue", "                cur.append(candidates[j])", "                dfs(j + 1, cur, remain - candidates[j])", "                cur.pop()", "        dfs(0, [], target)", "        return res"],
        cpp: ["// Combination Sum II cpp"],
        java: ["// Combination Sum II java"],
        typescript: ["// Combination Sum II ts"],
      },
    },
    bruteForce: {
      title: "Combination Sum I + Set Deduplication",
      subtitle: "O(2^n) time and O(2^n) space",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Set filtering.",
      spaceComplexity: "O(2^n)",
      spaceComplexityDetail: "Set.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Generate combinations and insert into set of tuples.",
      keySteps: ["1. Generate all.", "2. Deduplicate."],
      code: {
        python: ["# Set deduplicate"],
        cpp: ["// Set"],
        java: ["// Set"],
        typescript: ["// Set"],
      },
    },
  },
  "Combination Sum III": {
    intuition: "Find all valid combinations of k numbers that sum up to n using only numbers 1 through 9, each used at most once. Backtracking with start index `1..9`. Base case: if `len(cur) == k` and `remain == 0`, record combination. If `len(cur) == k` or `remain < 0`, backtrack.",
    bottleneck: "Brute force checking all 9! permutations takes extra time. Backtracking combinations of size k from [1..9] visits at most C(9, k) states in O(C(9, k)) time.",
    keyInvariant: "Only numbers strictly greater than current number are explored next, guaranteeing strictly ascending unique combinations.",
    constraints: ["2 <= k <= 9", "1 <= n <= 60"],
    examples: [{"input": "k = 3, n = 7", "output": "[[1,2,4]]", "explanation": "1 + 2 + 4 = 7."}, {"input": "k = 3, n = 9", "output": "[[1,2,6],[1,3,5],[2,3,4]]", "explanation": "3 combinations."}],
    companies: ["Google", "Amazon", "Microsoft"],
    acceptanceRate: "68.7%",
    frequency: "82%",
    edgeCases: ["n too small (n < k*(k+1)/2) or too large (n > sum of top k numbers)"],
    interviewTips: ["Prune search when remaining sum < 0 or remaining digits needed exceed available digits."],
    optimal: {
      title: "Backtracking over Digits [1..9] with Size k Bounding",
      subtitle: "O(C(9, k)) time and O(k) space bounded combination search",
      timeComplexity: "O(C(9, k))",
      timeComplexityDetail: "Bounded by combinations of 9 choose k (at most 126 calls).",
      spaceComplexity: "O(k)",
      spaceComplexityDetail: "Stack depth of k.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dfs(start, cur, remain): if len(cur)==k and remain==0: append copy. Loop num from start to 9, prune num > remain.",
      keySteps: ["1. res = [].", "2. dfs(start, cur, remain): if len(cur) == k and remain == 0: res.append(cur[:]); return. If len(cur) == k or remain < 0: return. For num in range(start, 10): if num > remain: break; cur.append(num); dfs(num + 1, cur, remain - num); cur.pop().", "3. dfs(1, [], n), return res."],
      code: {
        python: ["class Solution:", "    def combinationSum3(self, k: int, n: int) -> List[List[int]]:", "        res = []", "        def dfs(start, cur, remain):", "            if len(cur) == k and remain == 0:", "                res.append(cur[:])", "                return", "            if len(cur) == k or remain < 0:", "                return", "            for num in range(start, 10):", "                if num > remain: break", "                cur.append(num)", "                dfs(num + 1, cur, remain - num)", "                cur.pop()", "        dfs(1, [], n)", "        return res"],
        cpp: ["// Combination Sum III cpp"],
        java: ["// Combination Sum III java"],
        typescript: ["// Combination Sum III ts"],
      },
    },
    bruteForce: {
      title: "Itertools / Brute Combinations",
      subtitle: "O(C(9, k)) time",
      timeComplexity: "O(C(9, k))",
      timeComplexityDetail: "Generates all C(9, k).",
      spaceComplexity: "O(k)",
      spaceComplexityDetail: "Combinations list.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Generate all combinations of range(1, 10) of length k and filter sum == n.",
      keySteps: ["1. Generate combinations.", "2. Filter sum."],
      code: {
        python: ["# itertools"],
        cpp: ["// Combinations"],
        java: ["// Combinations"],
        typescript: ["// Combinations"],
      },
    },
  },
  "Permutations": {
    intuition: "A permutation is an ordered arrangement of ALL n elements. At each step of backtracking: iterate through all elements. If `nums[i]` is not in current path (tracked via `visited` boolean array), mark visited, append to current path, recurse, and unmark on backtrack. When `len(cur) == len(nums)`, record permutation.",
    bottleneck: "Generating array copies on every step takes extra memory. Backtracking with a boolean `visited` array (or in-place swapping) runs in O(n * n!) time and O(n) space.",
    keyInvariant: "visited array tracks elements already used in the current prefix path.",
    constraints: ["1 <= nums.length <= 6", "-10 <= nums[i] <= 10", "All integers of nums are unique."],
    examples: [{"input": "nums = [1,2,3]", "output": "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]", "explanation": "All 3! = 6 permutations."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Apple"],
    acceptanceRate: "77.8%",
    frequency: "97%",
    edgeCases: ["Single element array (returns [[x]])", "Two element array"],
    interviewTips: ["Show both the visited array approach and the in-place swapping `nums[i], nums[start] = nums[start], nums[i]` approach."],
    optimal: {
      title: "Backtracking with Visited State Array",
      subtitle: "O(n * n!) time and O(n) space permutation generation",
      timeComplexity: "O(n * n!)",
      timeComplexityDetail: "There are n! permutations, each of length n.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Visited boolean array and recursion stack.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Maintain cur list and visited array. Iterate all elements, pick unvisited, backtrack.",
      keySteps: ["1. res = [], cur = [], visited = [False] * len(nums).", "2. backtrack(): if len(cur) == len(nums): res.append(cur[:]); return. For i, n in enumerate(nums): if not visited[i]: visited[i] = True; cur.append(n); backtrack(); cur.pop(); visited[i] = False.", "3. backtrack(), return res."],
      code: {
        python: ["class Solution:", "    def permute(self, nums: List[int]) -> List[List[int]]:", "        res, cur = [], []", "        visited = [False] * len(nums)", "        def backtrack():", "            if len(cur) == len(nums):", "                res.append(cur[:])", "                return", "            for i in range(len(nums)):", "                if not visited[i]:", "                    visited[i] = True", "                    cur.append(nums[i])", "                    backtrack()", "                    cur.pop()", "                    visited[i] = False", "        backtrack()", "        return res"],
        cpp: ["#include <vector>", "using namespace std;", "class Solution {", "public:", "    vector<vector<int>> permute(vector<int>& nums) {", "        vector<vector<int>> res;", "        vector<int> cur;", "        vector<bool> visited(nums.size(), false);", "        auto backtrack = [&](auto& self) -> void {", "            if (cur.size() == nums.size()) { res.push_back(cur); return; }", "            for (size_t i = 0; i < nums.size(); ++i) {", "                if (!visited[i]) {", "                    visited[i] = true; cur.push_back(nums[i]);", "                    self(self);", "                    cur.pop_back(); visited[i] = false;", "                }", "            }", "        };", "        backtrack(backtrack);", "        return res;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public List<List<Integer>> permute(int[] nums) {", "        List<List<Integer>> res = new ArrayList<>();", "        backtrack(nums, new boolean[nums.length], new ArrayList<>(), res);", "        return res;", "    }", "    private void backtrack(int[] nums, boolean[] visited, List<Integer> cur, List<List<Integer>> res) {", "        if (cur.size() == nums.length) { res.add(new ArrayList<>(cur)); return; }", "        for (int i = 0; i < nums.length; i++) {", "            if (!visited[i]) {", "                visited[i] = true; cur.add(nums[i]);", "                backtrack(nums, visited, cur, res);", "                cur.remove(cur.size() - 1); visited[i] = false;", "            }", "        }", "    }", "}"],
        typescript: ["function permute(nums: number[]): number[][] {", "  const res: number[][] = [], cur: number[] = [], visited = new Array(nums.length).fill(false);", "  const backtrack = () => {", "    if (cur.length === nums.length) { res.push([...cur]); return; }", "    for (let i = 0; i < nums.length; i++) {", "      if (!visited[i]) {", "        visited[i] = true; cur.push(nums[i]);", "        backtrack();", "        cur.pop(); visited[i] = false;", "      }", "    }", "  };", "  backtrack(); return res;", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Slicing Permutations",
      subtitle: "O(n * n!) time and O(n!) space",
      timeComplexity: "O(n * n!)",
      timeComplexityDetail: "List slicing copies.",
      spaceComplexity: "O(n * n!)",
      spaceComplexityDetail: "Array copies.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Base case len 1. For each element, prepend to permutations of rest.",
      keySteps: ["1. Slicing recursion."],
      code: {
        python: ["# Slicing"],
        cpp: ["// Slicing"],
        java: ["// Slicing"],
        typescript: ["// Slicing"],
      },
    },
  },
  "Permutations II": {
    intuition: "Array contains DUPLICATES. 1) SORT `nums`. 2) Track used elements with boolean array `visited`. 3) In the loop: if `nums[i] == nums[i - 1]` and `not visited[i - 1]`, SKIP `nums[i]`. This critical condition ensures that duplicate numbers are only chosen in their left-to-right order, preventing identical permutations.",
    bottleneck: "Hash set deduplication requires generating all n! permutations. Duplicate pruning generates only unique permutations directly in O(n * n!) time.",
    keyInvariant: "Skipping when `nums[i] == nums[i-1] and not visited[i-1]` enforces strict relative ordering among identical numbers.",
    constraints: ["1 <= nums.length <= 8", "-10 <= nums[i] <= 10"],
    examples: [{"input": "nums = [1,1,2]", "output": "[[1,1,2],[1,2,1],[2,1,1]]", "explanation": "Unique permutations."}],
    companies: ["Amazon", "Google", "Meta"],
    acceptanceRate: "58.5%",
    frequency: "89%",
    edgeCases: ["All elements identical (returns single permutation)", "Array with multiple duplicate pairs"],
    interviewTips: ["Explain why `not visited[i - 1]` is used: if predecessor is NOT used, we would be starting a new identical duplicate branch."],
    optimal: {
      title: "Sort + Visited Duplicate Pruning Backtracking",
      subtitle: "O(n * n!) time and O(n) space unique permutations",
      timeComplexity: "O(n * n!)",
      timeComplexityDetail: "Generates each unique permutation once.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Visited array and recursion depth.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Sort nums. In loop: skip if visited[i] or (i > 0 and nums[i] == nums[i-1] and not visited[i-1]).",
      keySteps: ["1. nums.sort(), res = [], cur = [], visited = [False] * len(nums).", "2. backtrack(): if len(cur) == len(nums): res.append(cur[:]); return. For i in range(len(nums)): if visited[i]: continue. If i > 0 and nums[i] == nums[i - 1] and not visited[i - 1]: continue. visited[i] = True; cur.append(nums[i]); backtrack(); cur.pop(); visited[i] = False.", "3. backtrack(), return res."],
      code: {
        python: ["class Solution:", "    def permuteUnique(self, nums: List[int]) -> List[List[int]]:", "        nums.sort()", "        res, cur = [], []", "        visited = [False] * len(nums)", "        def backtrack():", "            if len(cur) == len(nums):", "                res.append(cur[:])", "                return", "            for i in range(len(nums)):", "                if visited[i]: continue", "                if i > 0 and nums[i] == nums[i - 1] and not visited[i - 1]:", "                    continue", "                visited[i] = True", "                cur.append(nums[i])", "                backtrack()", "                cur.pop()", "                visited[i] = False", "        backtrack()", "        return res"],
        cpp: ["// Permute Unique cpp"],
        java: ["// Permute Unique java"],
        typescript: ["// Permute Unique ts"],
      },
    },
    bruteForce: {
      title: "Permute All and Filter with Hash Set",
      subtitle: "O(n * n!) time and O(n * n!) space",
      timeComplexity: "O(n * n!)",
      timeComplexityDetail: "Set filtering.",
      spaceComplexity: "O(n * n!)",
      spaceComplexityDetail: "Set memory.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Generate all permutations and deduplicate with set of tuples.",
      keySteps: ["1. Generate all.", "2. Set filter."],
      code: {
        python: ["# Hash set deduplicate"],
        cpp: ["// Set"],
        java: ["// Set"],
        typescript: ["// Set"],
      },
    },
  },
  "Word Search": {
    intuition: "Search if word exists in m x n board by DFS from every cell `(r, c)`. Helper `dfs(r, c, k)` matches `board[r][c] == word[k]`. If `k == len(word) - 1`, word is found! Mark current cell visited by replacing `board[r][c] = \"#\"` in-place (avoiding extra visited matrix), recurse on 4 cardinal neighbors `(r\u00b11, c)` and `(r, c\u00b11)`, and restore original character on backtrack.",
    bottleneck: "Full BFS requires storing visited paths. DFS in-place grid backtracking runs in O(m * n * 4^L) time and strictly O(L) call stack space.",
    keyInvariant: "Temporary \"#\" marker prevents reusing the same cell within the current word path.",
    constraints: ["m == board.length", "n == board[i].length", "1 <= m, n <= 6", "1 <= word.length <= 15", "board and word consist of only lowercase and uppercase English letters."],
    examples: [{"input": "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\"", "output": "true", "explanation": "Path exists."}],
    companies: ["Amazon", "Microsoft", "Bloomberg", "Google", "Meta"],
    acceptanceRate: "41.2%",
    frequency: "96%",
    edgeCases: ["Single cell board", "Word frequency pruning: reverse word if last letter is rarer than first letter for speedup"],
    interviewTips: ["Mention frequency optimization: `if count(word[0]) > count(word[-1]): word = word[::-1]` to prune search space immediately."],
    optimal: {
      title: "In-Place Grid DFS Backtracking",
      subtitle: "O(m * n * 4^L) time and O(L) call stack space",
      timeComplexity: "O(m * n * 4^L)",
      timeComplexityDetail: "At each step 4 directions, depth L.",
      spaceComplexity: "O(L)",
      spaceComplexityDetail: "Recursion stack of length L (word length).",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "DFS from every cell. If board[r][c] == word[k], mark \"#\", explore 4 neighbors, restore character on return.",
      keySteps: ["1. m, n = len(board), len(board[0]).", "2. dfs(r, c, k): if k == len(word): return True. If r < 0 or r >= m or c < 0 or c >= n or board[r][c] != word[k]: return False. tmp = board[r][c]; board[r][c] = \"#\". found = dfs(r+1,c,k+1) or dfs(r-1,c,k+1) or dfs(r,c+1,k+1) or dfs(r,c-1,k+1). board[r][c] = tmp. Return found.", "3. For r in range(m): for c in range(n): if dfs(r, c, 0): return True.", "4. Return False."],
      code: {
        python: ["class Solution:", "    def exist(self, board: List[List[str]], word: str) -> bool:", "        m, n = len(board), len(board[0])", "        def dfs(r, c, k):", "            if k == len(word): return True", "            if r < 0 or r >= m or c < 0 or c >= n or board[r][c] != word[k]:", "                return False", "            tmp = board[r][c]", "            board[r][c] = \"#\"", "            found = (dfs(r + 1, c, k + 1) or", "                     dfs(r - 1, c, k + 1) or", "                     dfs(r, c + 1, k + 1) or", "                     dfs(r, c - 1, k + 1))", "            board[r][c] = tmp", "            return found", "        for r in range(m):", "            for c in range(n):", "                if dfs(r, c, 0): return True", "        return False"],
        cpp: ["#include <vector>", "#include <string>", "using namespace std;", "class Solution {", "    bool dfs(vector<vector<char>>& board, const string& word, int r, int c, int k) {", "        if (k == word.length()) return true;", "        if (r < 0 || r >= board.size() || c < 0 || c >= board[0].size() || board[r][c] != word[k]) return false;", "        char tmp = board[r][c]; board[r][c] = '#';", "        bool found = dfs(board, word, r + 1, c, k + 1) ||", "                     dfs(board, word, r - 1, c, k + 1) ||", "                     dfs(board, word, r, c + 1, k + 1) ||", "                     dfs(board, word, r, c - 1, k + 1);", "        board[r][c] = tmp;", "        return found;", "    }", "public:", "    bool exist(vector<vector<char>>& board, string word) {", "        for (int r = 0; r < board.size(); ++r)", "            for (int c = 0; c < board[0].size(); ++c)", "                if (dfs(board, word, r, c, 0)) return true;", "        return false;", "    }", "};"],
        java: ["class Solution {", "    private boolean dfs(char[][] board, String word, int r, int c, int k) {", "        if (k == word.length()) return true;", "        if (r < 0 || r >= board.length || c < 0 || c >= board[0].length || board[r][c] != word.charAt(k)) return false;", "        char tmp = board[r][c]; board[r][c] = '#';", "        boolean found = dfs(board, word, r + 1, c, k + 1) ||", "                        dfs(board, word, r - 1, c, k + 1) ||", "                        dfs(board, word, r, c + 1, k + 1) ||", "                        dfs(board, word, r, c - 1, k + 1);", "        board[r][c] = tmp;", "        return found;", "    }", "    public boolean exist(char[][] board, String word) {", "        for (int r = 0; r < board.length; r++)", "            for (int c = 0; c < board[0].length; c++)", "                if (dfs(board, word, r, c, 0)) return true;", "        return false;", "    }", "}"],
        typescript: ["function exist(board: string[][], word: string): boolean {", "  const m = board.length, n = board[0].length;", "  const dfs = (r: number, c: number, k: number): boolean => {", "    if (k === word.length) return true;", "    if (r < 0 || r >= m || c < 0 || c >= n || board[r][c] !== word[k]) return false;", "    const tmp = board[r][c]; board[r][c] = \"#\";", "    const found = dfs(r + 1, c, k + 1) || dfs(r - 1, c, k + 1) || dfs(r, c + 1, k + 1) || dfs(r, c - 1, k + 1);", "    board[r][c] = tmp;", "    return found;", "  };", "  for (let r = 0; r < m; r++) for (let c = 0; c < n; c++) if (dfs(r, c, 0)) return true;", "  return false;", "}"],
      },
    },
    bruteForce: {
      title: "BFS Path Queue Search",
      subtitle: "O(m * n * 4^L) time and high memory",
      timeComplexity: "O(m * n * 4^L)",
      timeComplexityDetail: "Queue state explosion.",
      spaceComplexity: "O(m * n * 4^L)",
      spaceComplexityDetail: "Queue stores path sets.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Explore with queue storing (r, c, k, visited_set).",
      keySteps: ["1. BFS state queue."],
      code: {
        python: ["# BFS path queue"],
        cpp: ["// BFS"],
        java: ["// BFS"],
        typescript: ["// BFS"],
      },
    },
  },
  "Palindrome Partitioning": {
    intuition: "Partition s such that every substring is a palindrome. Backtrack from index `i`. For each end index `j` from `i` to `len(s)`: check if substring `s[i:j+1]` is a palindrome. If it is, append `s[i:j+1]` to current partition, recurse on `j + 1`, and pop on backtrack. When `i == len(s)`, record valid partition.",
    bottleneck: "Checking palindrome on every substring takes O(n). DP table or 2-pointer palindrome check runs in O(n * 2^n) total time.",
    keyInvariant: "Every substring in current partition is verified to be a palindrome before proceeding deeper.",
    constraints: ["1 <= s.length <= 16", "s contains only lowercase English letters."],
    examples: [{"input": "s = \"aab\"", "output": "[[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]", "explanation": "All valid partitions."}],
    companies: ["Google", "Meta", "Amazon", "Microsoft"],
    acceptanceRate: "66.8%",
    frequency: "92%",
    edgeCases: ["Single character string", "String with all identical characters (e.g. \"aaaa\")"],
    interviewTips: ["Use two pointers `is_palindrome(s[i:j+1])` or precompute a 2D boolean palindrome table for large strings."],
    optimal: {
      title: "Backtracking with Substring Palindrome Check",
      subtitle: "O(n * 2^n) time and O(n) space palindrome partitioning",
      timeComplexity: "O(n * 2^n)",
      timeComplexityDetail: "There are 2^(n-1) possible partition splits.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Recursion stack depth.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dfs(i): if i == len(s) append cur copy. Loop j in i..n-1: if s[i:j+1] is palindrome, append and dfs(j+1).",
      keySteps: ["1. res = [], cur = [].", "2. is_pal(sub): return sub == sub[::-1].", "3. dfs(i): if i >= len(s): res.append(cur[:]); return. For j in range(i, len(s)): sub = s[i:j+1]; if is_pal(sub): cur.append(sub); dfs(j + 1); cur.pop().", "4. dfs(0), return res."],
      code: {
        python: ["class Solution:", "    def partition(self, s: str) -> List[List[str]]:", "        res, cur = [], []", "        def is_pal(sub): return sub == sub[::-1]", "        def dfs(i):", "            if i >= len(s):", "                res.append(cur[:])", "                return", "            for j in range(i, len(s)):", "                sub = s[i:j + 1]", "                if is_pal(sub):", "                    cur.append(sub)", "                    dfs(j + 1)", "                    cur.pop()", "        dfs(0)", "        return res"],
        cpp: ["// Palindrome Partitioning cpp"],
        java: ["// Palindrome Partitioning java"],
        typescript: ["// Palindrome Partitioning ts"],
      },
    },
    bruteForce: {
      title: "Generate All Partitions and Validate",
      subtitle: "O(n * 2^n) time",
      timeComplexity: "O(n * 2^n)",
      timeComplexityDetail: "Generates all 2^(n-1) splits.",
      spaceComplexity: "O(n * 2^n)",
      spaceComplexityDetail: "Partitions storage.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Generate all 2^(n-1) partitions and verify every token is palindrome.",
      keySteps: ["1. Generate all splits.", "2. Validate each."],
      code: {
        python: ["# Brute splits"],
        cpp: ["// Brute"],
        java: ["// Brute"],
        typescript: ["// Brute"],
      },
    },
  },
  "Letter Combinations of a Phone Number": {
    intuition: "Map digits \"2\"-\"9\" to corresponding phone keypad letters: `\"2\": \"abc\", \"3\": \"def\", ...`. Backtrack from index `i = 0`. At each digit, loop through all letters mapped to `digits[i]`, append letter to current path, recurse on `i + 1`, and backtrack. When `len(cur) == len(digits)`, add string to result.",
    bottleneck: "Iterative cartesian product creates intermediate lists. DFS backtracking generates all 3^N * 4^M combinations in-place in optimal O(4^N) time and O(N) space.",
    keyInvariant: "At index i, a letter is selected for digits[i] and fixed for the recursive subtree.",
    constraints: ["0 <= digits.length <= 4", "digits[i] is a digit in the range [\"2\", \"9\"]."],
    examples: [{"input": "digits = \"23\"", "output": "[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]", "explanation": "All 9 combinations."}, {"input": "digits = \"\"", "output": "[]", "explanation": "Empty string returns empty list."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Uber"],
    acceptanceRate: "60.1%",
    frequency: "95%",
    edgeCases: ["Empty string digits == \"\" (must return [] immediately)"],
    interviewTips: ["Store mapping array or hash map: `digit_map = {\"2\": \"abc\", \"3\": \"def\", ...}`."],
    optimal: {
      title: "Keypad Digit-Letter DFS Backtracking",
      subtitle: "O(4^N) time and O(N) space keypad combinations",
      timeComplexity: "O(4^N)",
      timeComplexityDetail: "N is length of digits; at most 4 letters per digit.",
      spaceComplexity: "O(N)",
      spaceComplexityDetail: "Recursion stack depth equal to len(digits).",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "If digits is empty return []. Recursively branch over letters corresponding to digits[i].",
      keySteps: ["1. If not digits: return [].", "2. mapping = {\"2\":\"abc\",\"3\":\"def\",\"4\":\"ghi\",\"5\":\"jkl\",\"6\":\"mno\",\"7\":\"pqrs\",\"8\":\"tuv\",\"9\":\"wxyz\"}.", "3. res = [], cur = [].", "4. dfs(i): if i == len(digits): res.append(\"\".join(cur)); return. For char in mapping[digits[i]]: cur.append(char); dfs(i + 1); cur.pop().", "5. dfs(0), return res."],
      code: {
        python: ["class Solution:", "    def letterCombinations(self, digits: str) -> List[str]:", "        if not digits: return []", "        mapping = {", "            \"2\": \"abc\", \"3\": \"def\", \"4\": \"ghi\", \"5\": \"jkl\",", "            \"6\": \"mno\", \"7\": \"pqrs\", \"8\": \"tuv\", \"9\": \"wxyz\"", "        }", "        res, cur = [], []", "        def dfs(i):", "            if i == len(digits):", "                res.append(\"\".join(cur))", "                return", "            for c in mapping[digits[i]]:", "                cur.append(c)", "                dfs(i + 1)", "                cur.pop()", "        dfs(0)", "        return res"],
        cpp: ["// Letter Combinations cpp"],
        java: ["// Letter Combinations java"],
        typescript: ["// Letter Combinations ts"],
      },
    },
    bruteForce: {
      title: "Iterative Cartesian Product",
      subtitle: "O(4^N) time and O(4^N) space",
      timeComplexity: "O(4^N)",
      timeComplexityDetail: "Builds combinations iteratively.",
      spaceComplexity: "O(4^N)",
      spaceComplexityDetail: "Intermediate lists.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Start with res = [\"\"]. For digit in digits: res = [prev + c for prev in res for c in map[digit]].",
      keySteps: ["1. Iterative expansion."],
      code: {
        python: ["# Iterative product"],
        cpp: ["// Iterative"],
        java: ["// Iterative"],
        typescript: ["// Iterative"],
      },
    },
  },
  "N-Queens": {
    intuition: "Place n non-attacking queens on an n x n chessboard (no two queens share same row, column, or diagonal). Backtrack row by row `r = 0..n-1`. For row r, try placing a queen in column `c`. Attack condition: column `c in cols`, positive diagonal `(r + c) in pos_diag`, negative diagonal `(r - c) in neg_diag`. If safe, add to sets, place queen, recurse `r + 1`, and remove from sets on backtrack. When `r == n`, format board.",
    bottleneck: "Checking full board state on every cell takes O(n\u00b3). Tracking occupied columns and diagonals in O(1) hash sets reduces validation to O(1) per queen placement in O(N!) time.",
    keyInvariant: "Positive diagonals share constant r + c; Negative diagonals share constant r - c.",
    constraints: ["1 <= n <= 9"],
    examples: [{"input": "n = 4", "output": "[[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"],[\"..Q.\",\"Q...\",\"...Q\",\".Q..\"]]", "explanation": "Two distinct 4-queens solutions."}],
    companies: ["Google", "Meta", "Amazon", "Microsoft", "Apple"],
    acceptanceRate: "68.4%",
    frequency: "92%",
    edgeCases: ["n = 1 (returns [[\"Q\"]])", "n = 2, 3 (no valid solutions, returns [])"],
    interviewTips: ["Explain the mathematical diagonal invariant: positive diagonal `(r + c)` and negative diagonal `(r - c)`."],
    optimal: {
      title: "Row-by-Row DFS with O(1) Set Diagonal Tracking",
      subtitle: "O(N!) time and O(N) space N-Queens solver",
      timeComplexity: "O(N!)",
      timeComplexityDetail: "First row has N choices, second has <= N-2, etc.",
      spaceComplexity: "O(N)",
      spaceComplexityDetail: "Hash sets for columns and diagonals.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Track cols, pos_diag (r+c), neg_diag (r-c). Place queen at (r, c), recurse row r+1, backtrack.",
      keySteps: ["1. cols = set(), pos_diag = set(), neg_diag = set(), board = [[\".\"] * n for _ in range(n)], res = [].", "2. backtrack(r): if r == n: res.append([\"\".join(row) for row in board]); return. For c in range(n): if c in cols or (r+c) in pos_diag or (r-c) in neg_diag: continue. cols.add(c); pos_diag.add(r+c); neg_diag.add(r-c); board[r][c] = \"Q\"; backtrack(r + 1); cols.remove(c); pos_diag.remove(r+c); neg_diag.remove(r-c); board[r][c] = \".\".", "3. backtrack(0), return res."],
      code: {
        python: ["class Solution:", "    def solveNQueens(self, n: int) -> List[List[str]]:", "        cols = set()", "        pos_diag = set()  # (r + c)", "        neg_diag = set()  # (r - c)", "        res = []", "        board = [[\".\"] * n for _ in range(n)]", "", "        def backtrack(r):", "            if r == n:", "                res.append([\"\".join(row) for row in board])", "                return", "            for c in range(n):", "                if c in cols or (r + c) in pos_diag or (r - c) in neg_diag:", "                    continue", "                cols.add(c)", "                pos_diag.add(r + c)", "                neg_diag.add(r - c)", "                board[r][c] = \"Q\"", "                backtrack(r + 1)", "                cols.remove(c)", "                pos_diag.remove(r + c)", "                neg_diag.remove(r - c)", "                board[r][c] = \".\"", "", "        backtrack(0)", "        return res"],
        cpp: ["// N-Queens cpp"],
        java: ["// N-Queens java"],
        typescript: ["// N-Queens ts"],
      },
    },
    bruteForce: {
      title: "Board Scan Diagonal Check",
      subtitle: "O(N^N * N) time",
      timeComplexity: "O(N^N * N)",
      timeComplexityDetail: "Scans board at every placement.",
      spaceComplexity: "O(N\u00b2)",
      spaceComplexityDetail: "Board memory.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Scan board lines and diagonals on every cell.",
      keySteps: ["1. Scan lines and diagonals."],
      code: {
        python: ["# Full scan"],
        cpp: ["// Scan"],
        java: ["// Scan"],
        typescript: ["// Scan"],
      },
    },
  },
  "Sudoku Solver": {
    intuition: "Solve a 9x9 Sudoku board by Backtracking. Find the first empty cell `board[r][c] == \".\"`. Try placing digits `\"1\"` through `\"9\"`. For digit `d`, check validity: `d` must not already appear in row `r`, column `c`, or the 3x3 sub-box `(r // 3, c // 3)`. If valid, assign `board[r][c] = d`, recurse to solve remaining cells. If recursive call returns True, puzzle is solved! Otherwise, reset `board[r][c] = \".\"` and try next digit.",
    bottleneck: "Testing invalid digits deeply wastes time. Pre-checking row, column, and 3x3 sub-box constraints prunes search trees instantly.",
    keyInvariant: "At any step, row, column, and 3x3 sub-box Sudoku constraints are strictly preserved.",
    constraints: ["board.length == 9", "board[i].length == 9", "board[i][j] is a digit or \".\"", "It is guaranteed that the input board has a unique solution."],
    examples: [{"input": "board = 9x9 partially filled grid", "output": "9x9 fully solved Sudoku board", "explanation": "All rows, columns, and 3x3 boxes contain digits 1-9 uniquely."}],
    companies: ["Google", "Microsoft", "Amazon", "Meta", "Uber"],
    acceptanceRate: "60.4%",
    frequency: "92%",
    edgeCases: ["Board nearly solved vs board with minimal clues"],
    interviewTips: ["Box index formula: `box_r = (r // 3) * 3 + i // 3`, `box_c = (c // 3) * 3 + i % 3`."],
    optimal: {
      title: "Cell-by-Cell Backtracking with Fast Validity Checks",
      subtitle: "O(9^(empty_cells)) worst case backtracking, fast in practice",
      timeComplexity: "O(9^m)",
      timeComplexityDetail: "m is number of empty cells; heavily pruned.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Fixed 9x9 board.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Locate empty cell. Loop \"1\"..\"9\", if isValid(r, c, d): board[r][c] = d; if solve(): return True; board[r][c] = \".\".",
      keySteps: ["1. isValid(r, c, d): check row r, col c, and 3x3 box for digit d.", "2. solve(): find empty cell (r, c). If no empty cell: return True. For d in \"1\"..\"9\": if isValid(r, c, d): board[r][c] = d; if solve(): return True; board[r][c] = \".\". Return False.", "3. solve()."],
      code: {
        python: ["class Solution:", "    def solveSudoku(self, board: List[List[str]]) -> None:", "        def is_valid(r, c, d):", "            for i in range(9):", "                if board[r][i] == d or board[i][c] == d:", "                    return False", "                box_r = 3 * (r // 3) + i // 3", "                box_c = 3 * (c // 3) + i % 3", "                if board[box_r][box_c] == d:", "                    return False", "            return True", "", "        def solve():", "            for r in range(9):", "                for c in range(9):", "                    if board[r][c] == \".\":", "                        for d in \"123456789\":", "                            if is_valid(r, c, d):", "                                board[r][c] = d", "                                if solve():", "                                    return True", "                                board[r][c] = \".\"", "                        return False", "            return True", "        solve()"],
        cpp: ["// Sudoku Solver cpp"],
        java: ["// Sudoku Solver java"],
        typescript: ["// Sudoku Solver ts"],
      },
    },
    bruteForce: {
      title: "Exhaustive Permutation Search",
      subtitle: "Exponential search",
      timeComplexity: "O(9^81)",
      timeComplexityDetail: "Unpruned search.",
      spaceComplexity: "O(81)",
      spaceComplexityDetail: "Recursion stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Fill board and check validity at end.",
      keySteps: ["1. Fill board.", "2. Validate."],
      code: {
        python: ["# Brute fill"],
        cpp: ["// Brute"],
        java: ["// Brute"],
        typescript: ["// Brute"],
      },
    },
  },
}
