import { DetailedProblemData } from '../leetcodeSolutions'

export const dp1DSolutions: Record<string, DetailedProblemData> = {
  "Climbing Stairs": {
    intuition: "To reach step n, you can either take 1 step from (n - 1) or 2 steps from (n - 2). Therefore, `ways(n) = ways(n - 1) + ways(n - 2)`. This matches the Fibonacci recurrence sequence. Compute iteratively with two variables `one, two = 1, 1` in O(n) time and O(1) space.",
    bottleneck: "Recursive Fibonacci without memoization takes O(2^n). Iterative state reduction computes the exact count in O(n) time and O(1) space.",
    keyInvariant: "ways(i) equals ways(i-1) + ways(i-2) for all i >= 2.",
    constraints: ["1 <= n <= 45"],
    examples: [{"input": "n = 2", "output": "2", "explanation": "1+1 or 2."}, {"input": "n = 3", "output": "3", "explanation": "1+1+1, 1+2, 2+1."}],
    companies: ["Amazon", "Google", "Apple", "Microsoft"],
    acceptanceRate: "52.4%",
    frequency: "98%",
    edgeCases: ["n = 1 (returns 1)", "n = 2 (returns 2)"],
    interviewTips: ["Show space optimization reducing array dp[n+1] to just 2 variables `one, two`."],
    optimal: {
      title: "Fibonacci Iterative Space Optimization",
      subtitle: "O(n) time and O(1) space iterative recurrence",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single loop from 1 to n.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Two scalar variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "one = 1, two = 1. Loop n-1 times: one, two = one + two, one. Return one.",
      keySteps: ["1. one, two = 1, 1.", "2. For _ in range(n - 1): one, two = one + two, one.", "3. Return one."],
      code: {
        python: ["class Solution:", "    def climbStairs(self, n: int) -> int:", "        one, two = 1, 1", "        for _ in range(n - 1):", "            one, two = one + two, one", "        return one"],
        cpp: ["class Solution {", "public:", "    int climbStairs(int n) {", "        int one = 1, two = 1;", "        for (int i = 0; i < n - 1; ++i) {", "            int tmp = one;", "            one = one + two;", "            two = tmp;", "        }", "        return one;", "    }", "};"],
        java: ["class Solution {", "    public int climbStairs(int n) {", "        int one = 1, two = 1;", "        for (int i = 0; i < n - 1; i++) {", "            int tmp = one;", "            one = one + two;", "            two = tmp;", "        }", "        return one;", "    }", "}"],
        typescript: ["function climbStairs(n: number): number {", "  let one = 1, two = 1;", "  for (let i = 0; i < n - 1; i++) {", "    const tmp = one;", "    one = one + two;", "    two = tmp;", "  }", "  return one;", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Fibonacci",
      subtitle: "O(2^n) time and O(n) space",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Binary recursion tree.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "climb(n): return climb(n-1) + climb(n-2).",
      keySteps: ["1. Binary recursion."],
      code: {
        python: ["# Recursive"],
        cpp: ["// Recursive"],
        java: ["// Recursive"],
        typescript: ["// Recursive"],
      },
    },
  },
  "Min Cost Climbing Stairs": {
    intuition: "Let `dp[i]` be the minimum cost to reach step i. Recurrence: `cost[i] += min(cost[i + 1], cost[i + 2])`. Process backwards from `len(cost) - 3` down to `0`. The minimum cost to start is `min(cost[0], cost[1])` in O(n) time and O(1) in-place space.",
    bottleneck: "Top-down recursion recomputes subproblems. Bottom-up in-place DP finds minimum cost in O(n) time and O(1) auxiliary space.",
    keyInvariant: "cost[i] stores min cost to reach top starting from step i.",
    constraints: ["2 <= cost.length <= 1000", "0 <= cost[i] <= 999"],
    examples: [{"input": "cost = [10,15,20]", "output": "15", "explanation": "Start at index 1 cost 15."}, {"input": "cost = [1,100,1,1,1,100,1,1,100,1]", "output": "6", "explanation": "Cost 6."}],
    companies: ["Amazon", "Google", "Meta"],
    acceptanceRate: "65.2%",
    frequency: "91%",
    edgeCases: ["Array of length 2 (returns min(cost[0], cost[1]))"],
    interviewTips: ["Walk through either top-down or bottom-up backwards calculation."],
    optimal: {
      title: "Bottom-Up In-Place DP",
      subtitle: "O(n) time and O(1) auxiliary space",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single reverse pass over cost array.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "In-place array update.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Loop backwards from n-3 to 0: cost[i] += min(cost[i+1], cost[i+2]). Return min(cost[0], cost[1]).",
      keySteps: ["1. For i in range(len(cost) - 3, -1, -1): cost[i] += min(cost[i + 1], cost[i + 2]).", "2. Return min(cost[0], cost[1])."],
      code: {
        python: ["class Solution:", "    def minCostClimbingStairs(self, cost: List[int]) -> int:", "        for i in range(len(cost) - 3, -1, -1):", "            cost[i] += min(cost[i + 1], cost[i + 2])", "        return min(cost[0], cost[1])"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int minCostClimbingStairs(vector<int>& cost) {", "        int n = cost.size();", "        for (int i = n - 3; i >= 0; --i) cost[i] += min(cost[i + 1], cost[i + 2]);", "        return min(cost[0], cost[1]);", "    }", "};"],
        java: ["class Solution {", "    public int minCostClimbingStairs(int[] cost) {", "        for (int i = cost.length - 3; i >= 0; i--) cost[i] += Math.min(cost[i + 1], cost[i + 2]);", "        return Math.min(cost[0], cost[1]);", "    }", "}"],
        typescript: ["function minCostClimbingStairs(cost: number[]): number {", "  for (let i = cost.length - 3; i >= 0; i--) cost[i] += Math.min(cost[i + 1], cost[i + 2]);", "  return Math.min(cost[0], cost[1]);", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Branching",
      subtitle: "O(2^n) time",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Recursion tree.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recurse picking step +1 or +2.",
      keySteps: ["1. Binary recursion."],
      code: {
        python: ["# Recursive"],
        cpp: ["// Recursive"],
        java: ["// Recursive"],
        typescript: ["// Recursive"],
      },
    },
  },
  "House Robber": {
    intuition: "You cannot rob two adjacent houses. For house i, either: 1) Rob house i and add to max loot from house (i - 2) (`rob1 + num`), or 2) Skip house i and keep max loot up to house (i - 1) (`rob2`). New max loot: `temp = max(rob1 + num, rob2); rob1 = rob2; rob2 = temp`. Return `rob2`.",
    bottleneck: "Checking all 2^n combinations takes exponential time. Two-variable DP state tracking runs in O(n) linear time and O(1) space.",
    keyInvariant: "rob2 stores max loot robbing sub-array up to previous house; rob1 stores max loot up to house before that.",
    constraints: ["1 <= nums.length <= 100", "0 <= nums[i] <= 400"],
    examples: [{"input": "nums = [1,2,3,1]", "output": "4", "explanation": "Rob house 1 (1) and house 3 (3) = 4."}, {"input": "nums = [2,7,9,3,1]", "output": "12", "explanation": "Rob 2 + 9 + 1 = 12."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Apple"],
    acceptanceRate: "50.8%",
    frequency: "98%",
    edgeCases: ["Single house (returns nums[0])", "Two houses (returns max(nums[0], nums[1]))"],
    interviewTips: ["Highlight the transition: `rob1, rob2 = rob2, max(rob1 + n, rob2)`."],
    optimal: {
      title: "Two-Variable Rolling DP State Optimization",
      subtitle: "O(n) time and O(1) space non-adjacent max loot",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single pass over nums array.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Two scalar variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "rob1, rob2 = 0, 0. For each num: rob1, rob2 = rob2, max(rob1 + num, rob2). Return rob2.",
      keySteps: ["1. rob1, rob2 = 0, 0.", "2. For n in nums: new_rob = max(rob1 + n, rob2); rob1 = rob2; rob2 = new_rob.", "3. Return rob2."],
      code: {
        python: ["class Solution:", "    def rob(self, nums: List[int]) -> int:", "        rob1, rob2 = 0, 0", "        for n in nums:", "            rob1, rob2 = rob2, max(rob1 + n, rob2)", "        return rob2"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int rob(vector<int>& nums) {", "        int rob1 = 0, rob2 = 0;", "        for (int n : nums) {", "            int new_rob = max(rob1 + n, rob2);", "            rob1 = rob2; rob2 = new_rob;", "        }", "        return rob2;", "    }", "};"],
        java: ["class Solution {", "    public int rob(int[] nums) {", "        int rob1 = 0, rob2 = 0;", "        for (int n : nums) {", "            int newRob = Math.max(rob1 + n, rob2);", "            rob1 = rob2; rob2 = newRob;", "        }", "        return rob2;", "    }", "}"],
        typescript: ["function rob(nums: number[]): number {", "  let rob1 = 0, rob2 = 0;", "  for (const n of nums) {", "    const newRob = Math.max(rob1 + n, rob2);", "    rob1 = rob2; rob2 = newRob;", "  }", "  return rob2;", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Decision Tree",
      subtitle: "O(2^n) time",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Branches rob or skip.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "rob(i): return max(nums[i] + rob(i+2), rob(i+1)).",
      keySteps: ["1. Binary recursion."],
      code: {
        python: ["# Recursive"],
        cpp: ["// Recursive"],
        java: ["// Recursive"],
        typescript: ["// Recursive"],
      },
    },
  },
  "House Robber II": {
    intuition: "Houses are arranged in a CIRCLE (first house is adjacent to last house). You cannot rob both `nums[0]` and `nums[n-1]`. Therefore, the maximum loot is simply the maximum of two linear House Robber I runs: 1) House Robber on `nums[1:]` (skipping first house), and 2) House Robber on `nums[:-1]` (skipping last house). Base case: if `len(nums) == 1`, return `nums[0]`.",
    bottleneck: "Simulating circular cases with extra logic is complex. Reducing to two independent linear House Robber subproblems runs in O(n) time and O(1) space.",
    keyInvariant: "Excluding either first or last house breaks circular dependency into standard linear DP.",
    constraints: ["1 <= nums.length <= 100", "0 <= nums[i] <= 1000"],
    examples: [{"input": "nums = [2,3,2]", "output": "3", "explanation": "Cannot rob first and last (both 2), so max is 3."}, {"input": "nums = [1,2,3,1]", "output": "4", "explanation": "Rob 1 + 3 = 4."}],
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    acceptanceRate: "41.8%",
    frequency: "92%",
    edgeCases: ["Single house (returns nums[0])", "Two houses (returns max(nums[0], nums[1]))"],
    interviewTips: ["Show helper `helper(sub_nums)` reusing the O(1) space House Robber I logic."],
    optimal: {
      title: "Two-Slice House Robber Reduction",
      subtitle: "O(n) time and O(1) space circular reduction",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Two linear passes over n-1 elements.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Constant extra memory.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Return max(nums[0], helper(nums[1:]), helper(nums[:-1])) where helper is standard House Robber.",
      keySteps: ["1. If len(nums) == 1: return nums[0].", "2. helper(arr): r1, r2 = 0, 0; for n in arr: r1, r2 = r2, max(r1 + n, r2); return r2.", "3. Return max(helper(nums[1:]), helper(nums[:-1]))."],
      code: {
        python: ["class Solution:", "    def rob(self, nums: List[int]) -> int:", "        if len(nums) == 1: return nums[0]", "        def helper(arr):", "            rob1, rob2 = 0, 0", "            for n in arr:", "                rob1, rob2 = rob2, max(rob1 + n, rob2)", "            return rob2", "        return max(helper(nums[1:]), helper(nums[:-1]))"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "    int helper(vector<int>& nums, int l, int r) {", "        int rob1 = 0, rob2 = 0;", "        for (int i = l; i <= r; ++i) {", "            int new_rob = max(rob1 + nums[i], rob2);", "            rob1 = rob2; rob2 = new_rob;", "        }", "        return rob2;", "    }", "public:", "    int rob(vector<int>& nums) {", "        int n = nums.size();", "        if (n == 1) return nums[0];", "        return max(helper(nums, 1, n - 1), helper(nums, 0, n - 2));", "    }", "};"],
        java: ["class Solution {", "    private int helper(int[] nums, int l, int r) {", "        int rob1 = 0, rob2 = 0;", "        for (int i = l; i <= r; i++) {", "            int newRob = Math.max(rob1 + nums[i], rob2);", "            rob1 = rob2; rob2 = newRob;", "        }", "        return rob2;", "    }", "    public int rob(int[] nums) {", "        if (nums.length == 1) return nums[0];", "        return Math.max(helper(nums, 1, nums.length - 1), helper(nums, 0, nums.length - 2));", "    }", "}"],
        typescript: ["function rob(nums: number[]): number {", "  if (nums.length === 1) return nums[0];", "  const helper = (arr: number[]) => {", "    let rob1 = 0, rob2 = 0;", "    for (const n of arr) { const newRob = Math.max(rob1 + n, rob2); rob1 = rob2; rob2 = newRob; }", "    return rob2;", "  };", "  return Math.max(helper(nums.slice(1)), helper(nums.slice(0, -1)));", "}"],
      },
    },
    bruteForce: {
      title: "Circular Bitmask Enumeration",
      subtitle: "O(2^n) time",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Checks non-adjacent masks.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "No stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Enumerate all valid non-adjacent circular subsets.",
      keySteps: ["1. Bitmask check."],
      code: {
        python: ["# Bitmask"],
        cpp: ["// Bitmask"],
        java: ["// Bitmask"],
        typescript: ["// Bitmask"],
      },
    },
  },
  "Longest Palindromic Substring": {
    intuition: "Expand Around Center: Every palindrome has a center. There are 2n - 1 possible centers (n odd-length centers at index `i`, and n - 1 even-length centers between `i` and `i + 1`). For each center, expand pointers `l` and `r` outwards as long as `s[l] == s[r]`. Track the maximum length substring found across all centers in O(n\u00b2) time and strictly O(1) space.",
    bottleneck: "Checking all O(n\u00b2) substrings for palindromes takes O(n\u00b3). Center expansion runs in O(n\u00b2) time with zero auxiliary memory.",
    keyInvariant: "If s[l] == s[r], expanding outwards preserves palindromic symmetry.",
    constraints: ["1 <= s.length <= 1000", "s consist of only digits and English letters."],
    examples: [{"input": "s = \"babad\"", "output": "\"bab\"", "explanation": "\"aba\" is also valid."}, {"input": "s = \"cbbd\"", "output": "\"bb\"", "explanation": "Even center \"bb\"."}],
    companies: ["Amazon", "Microsoft", "Google", "Meta", "Apple"],
    acceptanceRate: "33.8%",
    frequency: "99%",
    edgeCases: ["Single character string (returns s)", "All identical characters (returns s)"],
    interviewTips: ["Explain why expanding from 2n - 1 centers is optimal and avoids DP matrix O(n\u00b2) memory overhead."],
    optimal: {
      title: "Expand Around Center (Odd and Even Centers)",
      subtitle: "O(n\u00b2) time and O(1) space in-place palindrome expansion",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "2n - 1 centers, each expands at most n/2 times.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Pointers and substring indices only.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "For each i, expand odd (i, i) and even (i, i+1). Update longest palindrome slice.",
      keySteps: ["1. res = \"\", res_len = 0.", "2. expand(l, r): while l >= 0 and r < len(s) and s[l] == s[r]: if (r - l + 1) > res_len: res = s[l:r+1]; res_len = r - l + 1; l -= 1; r += 1.", "3. For i in range(len(s)): expand(i, i); expand(i, i + 1).", "4. Return res."],
      code: {
        python: ["class Solution:", "    def longestPalindrome(self, s: str) -> str:", "        res = \"\"", "        res_len = 0", "        def expand(l, r):", "            nonlocal res, res_len", "            while l >= 0 and r < len(s) and s[l] == s[r]:", "                if (r - l + 1) > res_len:", "                    res = s[l:r + 1]", "                    res_len = r - l + 1", "                l -= 1", "                r += 1", "        for i in range(len(s)):", "            expand(i, i)", "            expand(i, i + 1)", "        return res"],
        cpp: ["#include <string>", "using namespace std;", "class Solution {", "public:", "    string longestPalindrome(string s) {", "        int start = 0, max_len = 0, n = s.length();", "        auto expand = [&](int l, int r) {", "            while (l >= 0 && r < n && s[l] == s[r]) { l--; r++; }", "            int len = r - l - 1;", "            if (len > max_len) { max_len = len; start = l + 1; }", "        };", "        for (int i = 0; i < n; ++i) { expand(i, i); expand(i, i + 1); }", "        return s.substr(start, max_len);", "    }", "};"],
        java: ["class Solution {", "    private int start = 0, maxLen = 0;", "    private void expand(String s, int l, int r) {", "        while (l >= 0 && r < s.length() && s.charAt(l) == s.charAt(r)) { l--; r++; }", "        int len = r - l - 1;", "        if (len > maxLen) { maxLen = len; start = l + 1; }", "    }", "    public String longestPalindrome(String s) {", "        for (int i = 0; i < s.length(); i++) { expand(s, i, i); expand(s, i, i + 1); }", "        return s.substring(start, start + maxLen);", "    }", "}"],
        typescript: ["function longestPalindrome(s: string): string {", "  let start = 0, maxLen = 0;", "  const expand = (l: number, r: number) => {", "    while (l >= 0 && r < s.length && s[l] === s[r]) { l--; r++; }", "    const len = r - l - 1;", "    if (len > maxLen) { maxLen = len; start = l + 1; }", "  };", "  for (let i = 0; i < s.length; i++) { expand(i, i); expand(i, i + 1); }", "  return s.substring(start, start + maxLen);", "}"],
      },
    },
    bruteForce: {
      title: "Check All O(n\u00b2) Substrings",
      subtitle: "O(n\u00b3) time",
      timeComplexity: "O(n\u00b3)",
      timeComplexityDetail: "O(n\u00b2) substrings, O(n) check each.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "No extra memory.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Enumerate all substrings and test if palindrome.",
      keySteps: ["1. All substrings.", "2. Test is_palindrome."],
      code: {
        python: ["# O(n^3) brute"],
        cpp: ["// O(n^3)"],
        java: ["// O(n^3)"],
        typescript: ["// O(n^3)"],
      },
    },
  },
  "Palindromic Substrings": {
    intuition: "Count total number of palindromic substrings. Expand around all 2n - 1 centers (odd centers `i, i` and even centers `i, i + 1`). Whenever `s[l] == s[r]`, increment `count += 1`, expand `l -= 1, r += 1`. Return total count.",
    bottleneck: "O(n\u00b3) checking each substring. Center expansion counts all palindromes in O(n\u00b2) time and O(1) space.",
    keyInvariant: "Every expansion step where s[l] == s[r] identifies one unique valid palindromic substring.",
    constraints: ["1 <= s.length <= 1000", "s consists of lowercase English letters."],
    examples: [{"input": "s = \"abc\"", "output": "3", "explanation": "\"a\", \"b\", \"c\"."}, {"input": "s = \"aaa\"", "output": "6", "explanation": "\"a\", \"a\", \"a\", \"aa\", \"aa\", \"aaa\"."}],
    companies: ["Meta", "Amazon", "Google", "Microsoft"],
    acceptanceRate: "68.9%",
    frequency: "92%",
    edgeCases: ["Single character string (returns 1)", "All identical characters"],
    interviewTips: ["Show how expanding from centers simultaneously solves both odd and even lengths."],
    optimal: {
      title: "Expand Around Center Palindrome Counting",
      subtitle: "O(n\u00b2) time and O(1) space palindrome count",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "2n - 1 centers.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Pointer variables only.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Count expansions where s[l] == s[r] for odd and even centers.",
      keySteps: ["1. count = 0.", "2. expand(l, r): nonlocal count; while l >= 0 and r < len(s) and s[l] == s[r]: count += 1; l -= 1; r += 1.", "3. For i in range(len(s)): expand(i, i); expand(i, i + 1).", "4. Return count."],
      code: {
        python: ["class Solution:", "    def countSubstrings(self, s: str) -> int:", "        count = 0", "        def expand(l, r):", "            nonlocal count", "            while l >= 0 and r < len(s) and s[l] == s[r]:", "                count += 1", "                l -= 1", "                r += 1", "        for i in range(len(s)):", "            expand(i, i)", "            expand(i, i + 1)", "        return count"],
        cpp: ["// Palindromic substrings cpp"],
        java: ["// Palindromic substrings java"],
        typescript: ["// Palindromic substrings ts"],
      },
    },
    bruteForce: {
      title: "Check All Substrings",
      subtitle: "O(n\u00b3) time",
      timeComplexity: "O(n\u00b3)",
      timeComplexityDetail: "O(n\u00b2) substrings.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "No memory.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Test all substrings with is_palindrome.",
      keySteps: ["1. Check all substrings."],
      code: {
        python: ["# O(n^3)"],
        cpp: ["// O(n^3)"],
        java: ["// O(n^3)"],
        typescript: ["// O(n^3)"],
      },
    },
  },
  "Decode Ways": {
    intuition: "A digit \"1\"-\"9\" maps to A-I, and two-digit numbers \"10\"-\"26\" map to J-Z. Digit \"0\" cannot map by itself. DP Recurrence: `dp[i]` = ways to decode substring starting at index i. 1) If `s[i] == \"0\"`, `dp[i] = 0`. 2) Single digit: `dp[i] = dp[i + 1]`. 3) Valid two digits (`\"10\"`-`\"26\"`): `dp[i] += dp[i + 2]`. Space optimization reduces array to two variables in O(n) time and O(1) space.",
    bottleneck: "Recursive branching takes O(2^n). 1-D DP memoization computes decode ways in O(n) time and O(1) space.",
    keyInvariant: "Digits starting with \"0\" contribute 0 ways; valid double digits in [10..26] branch into dp[i+2].",
    constraints: ["1 <= s.length <= 100", "s contains only digits and may contain leading zero(s)."],
    examples: [{"input": "s = \"12\"", "output": "2", "explanation": "\"AB\" (1 2) or \"L\" (12)."}, {"input": "s = \"226\"", "output": "3", "explanation": "\"BZ\" (2 26), \"VF\" (22 6), or \"BBF\" (2 2 6)."}, {"input": "s = \"06\"", "output": "0", "explanation": "\"06\" invalid leading zero."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft"],
    acceptanceRate: "34.8%",
    frequency: "95%",
    edgeCases: ["Leading zero `s = \"0\"` (returns 0)", "Invalid middle zeros `s = \"301\"` (returns 0)", "Valid middle zeros `s = \"10\"` (returns 1)"],
    interviewTips: ["Check two-digit condition carefully: `10 <= int(s[i:i+2]) <= 26`."],
    optimal: {
      title: "Bottom-Up 1D DP with Two-Variable Space Optimization",
      subtitle: "O(n) time and O(1) space decode count",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single reverse pass over string.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Two scalar variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Loop backwards. dp1 is dp[i+1], dp2 is dp[i+2]. If s[i] != \"0\", cur = dp1; if 10 <= int(s[i:i+2]) <= 26, cur += dp2.",
      keySteps: ["1. n = len(s), dp1 = 1, dp2 = 0.", "2. For i in range(n - 1, -1, -1): cur = 0; if s[i] != \"0\": cur = dp1; if i + 1 < n and (s[i] == \"1\" or (s[i] == \"2\" and s[i + 1] in \"0123456\")): cur += dp2. dp2 = dp1; dp1 = cur.", "3. Return dp1."],
      code: {
        python: ["class Solution:", "    def numDecodings(self, s: str) -> int:", "        if not s or s[0] == \"0\": return 0", "        n = len(s)", "        dp1, dp2 = 1, 0", "        for i in range(n - 1, -1, -1):", "            cur = 0", "            if s[i] != \"0\":", "                cur = dp1", "                if i + 1 < n and (s[i] == \"1\" or (s[i] == \"2\" and s[i + 1] in \"0123456\")):", "                    cur += dp2 if i + 2 <= n else 1", "            dp2 = dp1", "            dp1 = cur", "        return dp1"],
        cpp: ["// Decode ways cpp"],
        java: ["// Decode ways java"],
        typescript: ["// Decode ways ts"],
      },
    },
    bruteForce: {
      title: "Recursive Branching",
      subtitle: "O(2^n) time",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Recursive tree.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recurse 1 digit and 2 digits.",
      keySteps: ["1. Binary recursion."],
      code: {
        python: ["# Recursive decode"],
        cpp: ["// Recursive"],
        java: ["// Recursive"],
        typescript: ["// Recursive"],
      },
    },
  },
  "Coin Change": {
    intuition: "Fewest coins needed to make up amount. Dynamic Programming: Let `dp[a]` be the minimum coins for amount a. Initialize `dp = [inf] * (amount + 1)`, `dp[0] = 0`. For `a` in `1..amount`: for `c` in `coins`: if `a - c >= 0`, `dp[a] = min(dp[a], 1 + dp[a - c])`. Return `dp[amount]` if != inf else `-1`.",
    bottleneck: "Greedy coin selection FAILS for arbitrary denominations (e.g. coins=[1,3,4,5], amount=7: greedy 5+1+1=3 coins, optimal 4+3=2 coins). DP evaluates the optimal subproblems in O(amount * len(coins)) time.",
    keyInvariant: "dp[a] stores the global minimum coin count for exact amount a.",
    constraints: ["1 <= coins.length <= 12", "1 <= coins[i] <= 2^31 - 1", "0 <= amount <= 10^4"],
    examples: [{"input": "coins = [1,2,5], amount = 11", "output": "3", "explanation": "5 + 5 + 1 = 11 (3 coins)."}, {"input": "coins = [2], amount = 3", "output": "-1", "explanation": "Impossible."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Bloomberg"],
    acceptanceRate: "43.2%",
    frequency: "99%",
    edgeCases: ["amount == 0 (returns 0)", "amount cannot be formed with given coins (returns -1)"],
    interviewTips: ["Explain why greedy doesn't work and how bottom-up DP explores all branch combinations efficiently."],
    optimal: {
      title: "Bottom-Up 1D Array DP",
      subtitle: "O(amount * len(coins)) time and O(amount) space",
      timeComplexity: "O(amount * len(coins))",
      timeComplexityDetail: "Nested loop over amount and coins.",
      spaceComplexity: "O(amount)",
      spaceComplexityDetail: "dp array of size amount + 1.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dp[a] = min(dp[a], 1 + dp[a - c]) for every coin c <= a. Return dp[amount] or -1.",
      keySteps: ["1. dp = [float(\"inf\")] * (amount + 1), dp[0] = 0.", "2. For a in range(1, amount + 1): for c in coins: if a - c >= 0: dp[a] = min(dp[a], 1 + dp[a - c]).", "3. Return dp[amount] if dp[amount] != float(\"inf\") else -1."],
      code: {
        python: ["class Solution:", "    def coinChange(self, coins: List[int], amount: int) -> int:", "        dp = [float(\"inf\")] * (amount + 1)", "        dp[0] = 0", "        for a in range(1, amount + 1):", "            for c in coins:", "                if a - c >= 0:", "                    dp[a] = min(dp[a], 1 + dp[a - c])", "        return dp[amount] if dp[amount] != float(\"inf\") else -1"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int coinChange(vector<int>& coins, int amount) {", "        vector<int> dp(amount + 1, amount + 1);", "        dp[0] = 0;", "        for (int a = 1; a <= amount; ++a) {", "            for (int c : coins) {", "                if (a - c >= 0) dp[a] = min(dp[a], 1 + dp[a - c]);", "            }", "        }", "        return dp[amount] > amount ? -1 : dp[amount];", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int coinChange(int[] coins, int amount) {", "        int[] dp = new int[amount + 1];", "        Arrays.fill(dp, amount + 1);", "        dp[0] = 0;", "        for (int a = 1; a <= amount; a++) {", "            for (int c : coins) {", "                if (a - c >= 0) dp[a] = Math.min(dp[a], 1 + dp[a - c]);", "            }", "        }", "        return dp[amount] > amount ? -1 : dp[amount];", "    }", "}"],
        typescript: ["function coinChange(coins: number[], amount: number): number {", "  const dp = new Array(amount + 1).fill(amount + 1);", "  dp[0] = 0;", "  for (let a = 1; a <= amount; a++) {", "    for (const c of coins) {", "      if (a - c >= 0) dp[a] = Math.min(dp[a], 1 + dp[a - c]);", "    }", "  }", "  return dp[amount] > amount ? -1 : dp[amount];", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Backtracking Search",
      subtitle: "O(S^N) exponential time",
      timeComplexity: "O(S^N)",
      timeComplexityDetail: "Exhaustive coin selection.",
      spaceComplexity: "O(amount)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Explore all coin combinations with recursion.",
      keySteps: ["1. Recursive coin selection."],
      code: {
        python: ["# Recursive"],
        cpp: ["// Recursive"],
        java: ["// Recursive"],
        typescript: ["// Recursive"],
      },
    },
  },
  "Maximum Product Subarray": {
    intuition: "A negative number multiplied by a negative number becomes positive. Therefore, we must track BOTH the current maximum product `cur_max` AND the current minimum product `cur_min`. For each num in nums: `tmp_max = max(num, num * cur_max, num * cur_min)`, `cur_min = min(num, num * cur_max, num * cur_min)`, `cur_max = tmp_max`. Update global `res = max(res, cur_max)`.",
    bottleneck: "Checking all subarray products takes O(n\u00b2). Tracking running max and min scalars computes max product in O(n) linear single pass and O(1) space.",
    keyInvariant: "cur_max and cur_min store the extreme products of non-empty subarrays ending at the current element.",
    constraints: ["1 <= nums.length <= 2 * 10^4", "-10 <= nums[i] <= 10"],
    examples: [{"input": "nums = [2,3,-2,4]", "output": "6", "explanation": "Subarray [2,3] gives max product 6."}, {"input": "nums = [-2,0,-1]", "output": "0", "explanation": "Max product is 0."}],
    companies: ["Amazon", "Google", "Microsoft", "Meta", "LinkedIn"],
    acceptanceRate: "35.1%",
    frequency: "96%",
    edgeCases: ["Array containing 0s (resets running products)", "Odd vs even count of negative numbers"],
    interviewTips: ["Store `cur_max * n` in a temporary variable before computing `cur_min` so that `cur_min` uses the old `cur_max`."],
    optimal: {
      title: "Dynamic Programming Running Min and Max Product Tracking",
      subtitle: "O(n) time and O(1) space single pass",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single linear pass over nums.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Three scalar variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Maintain cur_max and cur_min. Update with max/min of (n, n*cur_max, n*cur_min).",
      keySteps: ["1. res = max(nums), cur_min = 1, cur_max = 1.", "2. For n in nums: if n == 0: cur_min, cur_max = 1, 1; continue. tmp = cur_max * n; cur_max = max(n, tmp, cur_min * n); cur_min = min(n, tmp, cur_min * n); res = max(res, cur_max).", "3. Return res."],
      code: {
        python: ["class Solution:", "    def maxProduct(self, nums: List[int]) -> int:", "        res = max(nums)", "        cur_min, cur_max = 1, 1", "        for n in nums:", "            tmp = cur_max * n", "            cur_max = max(n, tmp, cur_min * n)", "            cur_min = min(n, tmp, cur_min * n)", "            res = max(res, cur_max)", "        return res"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int maxProduct(vector<int>& nums) {", "        int res = *max_element(nums.begin(), nums.end());", "        int cur_min = 1, cur_max = 1;", "        for (int n : nums) {", "            int tmp = cur_max * n;", "            cur_max = max({n, tmp, cur_min * n});", "            cur_min = min({n, tmp, cur_min * n});", "            res = max(res, cur_max);", "        }", "        return res;", "    }", "};"],
        java: ["class Solution {", "    public int maxProduct(int[] nums) {", "        int res = nums[0];", "        int curMin = 1, curMax = 1;", "        for (int n : nums) {", "            int tmp = curMax * n;", "            curMax = Math.max(n, Math.max(tmp, curMin * n));", "            curMin = Math.min(n, Math.min(tmp, curMin * n));", "            res = Math.max(res, curMax);", "        }", "        return res;", "    }", "}"],
        typescript: ["function maxProduct(nums: number[]): number {", "  let res = Math.max(...nums);", "  let curMin = 1, curMax = 1;", "  for (const n of nums) {", "    const tmp = curMax * n;", "    curMax = Math.max(n, tmp, curMin * n);", "    curMin = Math.min(n, tmp, curMin * n);", "    res = Math.max(res, curMax);", "  }", "  return res;", "}"],
      },
    },
    bruteForce: {
      title: "Nested Loop All Subarrays",
      subtitle: "O(n\u00b2) time",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "Calculates product of all subarray pairs.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "No extra memory.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "For each start i, compute product to end j.",
      keySteps: ["1. Double loop i and j."],
      code: {
        python: ["# O(n^2) brute"],
        cpp: ["// O(n^2)"],
        java: ["// O(n^2)"],
        typescript: ["// O(n^2)"],
      },
    },
  },
  "Word Break": {
    intuition: "Determine if string s can be segmented into dictionary words. Bottom-Up DP: Let `dp[i]` be True if substring `s[i:]` can be segmented. `dp[len(s)] = True` (base case). Loop `i` from `len(s) - 1` down to `0`. For each word `w` in `wordDict`: if `i + len(w) <= len(s)` and `s[i : i + len(w)] == w`, `dp[i] = dp[i + len(w)]`. If `dp[i]` becomes True, break early. Return `dp[0]`.",
    bottleneck: "Recursive branching without memoization takes O(2^n). 1-D DP computes reachability in O(n * m * k) where n=len(s), m=len(dict), k=avg word length.",
    keyInvariant: "dp[i] is True if and only if s[i:] can be completely partitioned into dictionary words.",
    constraints: ["1 <= s.length <= 300", "1 <= wordDict.length <= 1000", "1 <= wordDict[i].length <= 20", "s and wordDict[i] consist of lowercase English letters."],
    examples: [{"input": "s = \"leetcode\", wordDict = [\"leet\",\"code\"]", "output": "true", "explanation": "\"leet code\"."}, {"input": "s = \"catsandog\", wordDict = [\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]", "output": "false", "explanation": "Cannot segment."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Apple", "Bloomberg"],
    acceptanceRate: "46.4%",
    frequency: "97%",
    edgeCases: ["Single character match", "Words with overlapping prefixes (e.g. \"car\", \"ca\", \"rs\")"],
    interviewTips: ["Explain why working backwards from `len(s)` to `0` makes the DP state transition `dp[i] = dp[i + len(w)]` simple and clean."],
    optimal: {
      title: "Bottom-Up 1D Boolean DP",
      subtitle: "O(n * m * k) time and O(n) space substring DP",
      timeComplexity: "O(n * m * k)",
      timeComplexityDetail: "n is len(s), m is wordDict length, k is average word length.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "dp array of size n + 1.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dp[len(s)] = True. Loop i backwards, match words in dict, set dp[i] = dp[i + len(w)]. Return dp[0].",
      keySteps: ["1. dp = [False] * (len(s) + 1), dp[len(s)] = True.", "2. For i in range(len(s) - 1, -1, -1): for w in wordDict: if i + len(w) <= len(s) and s[i:i+len(w)] == w: dp[i] = dp[i + len(w)]; if dp[i]: break.", "3. Return dp[0]."],
      code: {
        python: ["class Solution:", "    def wordBreak(self, s: str, wordDict: List[str]) -> bool:", "        dp = [False] * (len(s) + 1)", "        dp[len(s)] = True", "        for i in range(len(s) - 1, -1, -1):", "            for w in wordDict:", "                if i + len(w) <= len(s) and s[i : i + len(w)] == w:", "                    dp[i] = dp[i + len(w)]", "                    if dp[i]:", "                        break", "        return dp[0]"],
        cpp: ["#include <string>", "#include <vector>", "using namespace std;", "class Solution {", "public:", "    bool wordBreak(string s, vector<string>& wordDict) {", "        int n = s.length();", "        vector<bool> dp(n + 1, false);", "        dp[n] = true;", "        for (int i = n - 1; i >= 0; --i) {", "            for (const string& w : wordDict) {", "                if (i + w.length() <= n && s.substr(i, w.length()) == w) {", "                    dp[i] = dp[i + w.length()];", "                    if (dp[i]) break;", "                }", "            }", "        }", "        return dp[0];", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public boolean wordBreak(String s, List<String> wordDict) {", "        int n = s.length();", "        boolean[] dp = new boolean[n + 1];", "        dp[n] = true;", "        for (int i = n - 1; i >= 0; i--) {", "            for (String w : wordDict) {", "                if (i + w.length() <= n && s.startsWith(w, i)) {", "                    dp[i] = dp[i + w.length()];", "                    if (dp[i]) break;", "                }", "            }", "        }", "        return dp[0];", "    }", "}"],
        typescript: ["function wordBreak(s: string, wordDict: string[]): boolean {", "  const n = s.length;", "  const dp = new Array(n + 1).fill(false);", "  dp[n] = true;", "  for (let i = n - 1; i >= 0; i--) {", "    for (const w of wordDict) {", "      if (i + w.length <= n && s.substring(i, i + w.length) === w) {", "        dp[i] = dp[i + w.length];", "        if (dp[i]) break;", "      }", "    }", "  }", "  return dp[0];", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Backtracking Search",
      subtitle: "O(2^n) time",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Exponential branching without memoization.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Check all word prefixes and recurse on remainder.",
      keySteps: ["1. Recursive prefix check."],
      code: {
        python: ["# Recursive"],
        cpp: ["// Recursive"],
        java: ["// Recursive"],
        typescript: ["// Recursive"],
      },
    },
  },
  "Longest Increasing Subsequence": {
    intuition: "Patience Sorting / Binary Search: Maintain an array `tails` where `tails[i]` stores the smallest tail of all increasing subsequences of length `i + 1`. For each number `x` in `nums`: use Binary Search (`bisect_left`) to find the first element in `tails` that is `>= x`. If found at index `idx`, replace `tails[idx] = x`. If `x` is larger than all elements in `tails`, append `x` to `tails`. The length of `tails` at the end is the exact length of the LIS in O(n log n) time.",
    bottleneck: "Standard 1D DP `dp[i] = 1 + max(dp[j])` takes O(n\u00b2). Patience Sorting with Binary Search optimizes LIS to O(n log n) time and O(n) space.",
    keyInvariant: "tails array is always strictly increasing, enabling binary search for lower bound insertion.",
    constraints: ["1 <= nums.length <= 2500", "-10^4 <= nums[i] <= 10^4"],
    examples: [{"input": "nums = [10,9,2,5,3,7,101,18]", "output": "4", "explanation": "LIS is [2,3,7,101] length 4."}, {"input": "nums = [0,1,0,3,2,3]", "output": "4", "explanation": "LIS length 4."}],
    companies: ["Google", "Amazon", "Meta", "Microsoft", "Apple"],
    acceptanceRate: "55.3%",
    frequency: "97%",
    edgeCases: ["Strictly decreasing array (returns 1)", "Array of all identical elements (returns 1)"],
    interviewTips: ["Explain the Patience Sorting card game analogy: place cards on piles; binary search finds the leftmost valid pile."],
    optimal: {
      title: "Patience Sorting Binary Search (bisect_left)",
      subtitle: "O(n log n) time and O(n) space optimal LIS",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "n elements, binary search takes O(log n) each.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "tails array of length at most n.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "For each x in nums: binary search in tails. Replace or append to tails. Return len(tails).",
      keySteps: ["1. tails = [].", "2. For x in nums: idx = bisect_left(tails, x); if idx == len(tails): tails.append(x); else: tails[idx] = x.", "3. Return len(tails)."],
      code: {
        python: ["import bisect", "class Solution:", "    def lengthOfLIS(self, nums: List[int]) -> int:", "        tails = []", "        for x in nums:", "            idx = bisect.bisect_left(tails, x)", "            if idx == len(tails):", "                tails.append(x)", "            else:", "                tails[idx] = x", "        return len(tails)"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int lengthOfLIS(vector<int>& nums) {", "        vector<int> tails;", "        for (int x : nums) {", "            auto it = lower_bound(tails.begin(), tails.end(), x);", "            if (it == tails.end()) tails.push_back(x);", "            else *it = x;", "        }", "        return tails.size();", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int lengthOfLIS(int[] nums) {", "        List<Integer> tails = new ArrayList<>();", "        for (int x : nums) {", "            int idx = Collections.binarySearch(tails, x);", "            if (idx < 0) idx = -(idx + 1);", "            if (idx == tails.size()) tails.add(x);", "            else tails.set(idx, x);", "        }", "        return tails.size();", "    }", "}"],
        typescript: ["function lengthOfLIS(nums: number[]): number {", "  const tails: number[] = [];", "  for (const x of nums) {", "    let l = 0, r = tails.length - 1, idx = tails.length;", "    while (l <= r) {", "      const mid = Math.floor((l + r) / 2);", "      if (tails[mid] >= x) { idx = mid; r = mid - 1; }", "      else l = mid + 1;", "    }", "    if (idx === tails.length) tails.push(x);", "    else tails[idx] = x;", "  }", "  return tails.length;", "}"],
      },
    },
    bruteForce: {
      title: "Standard 1D DP Array",
      subtitle: "O(n\u00b2) time and O(n) space",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "Double loop comparing all pairs.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "DP array.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "dp[i] = 1 + max([dp[j] for j in 0..i-1 if nums[j] < nums[i]]).",
      keySteps: ["1. dp = [1]*n.", "2. Double loop."],
      code: {
        python: ["# O(n^2) DP"],
        cpp: ["// O(n^2) DP"],
        java: ["// O(n^2) DP"],
        typescript: ["// O(n^2) DP"],
      },
    },
  },
  "Partition Equal Subset Sum": {
    intuition: "Partitioning nums into two subsets with equal sum reduces to: Finding a subset of nums with sum equal to `target = sum(nums) // 2`. 1) If `sum(nums) % 2 != 0`, return False immediately. 2) 0/1 Knapsack DP with a Hash Set: maintain `dp = {0}` (all achievable subset sums). For each `num` in `nums`: create new sums `num + t` for each `t` in `dp`. If `target in dp`, return True. 3) Space optimization uses a single 1D boolean array of size `target + 1` in O(n * target) time and O(target) space.",
    bottleneck: "Generating all 2^n subsets takes exponential time. 0/1 Knapsack DP bounds state space by target in O(n * target) pseudo-polynomial time.",
    keyInvariant: "Every sum in dp set is a valid sum of some subset of already-processed numbers.",
    constraints: ["1 <= nums.length <= 200", "1 <= nums[i] <= 100"],
    examples: [{"input": "nums = [1,5,11,5]", "output": "true", "explanation": "[1,5,5] and [11]."}, {"input": "nums = [1,2,3,5]", "output": "false", "explanation": "Sum 11 is odd."}],
    companies: ["Amazon", "Microsoft", "Google", "Meta"],
    acceptanceRate: "47.1%",
    frequency: "92%",
    edgeCases: ["Odd total sum (returns False immediately)", "Max element > target (returns False)"],
    interviewTips: ["Show the Hash Set DP pattern in Python: `dp.update({t + num for t in dp})`."],
    optimal: {
      title: "0/1 Knapsack DP Subset Sum",
      subtitle: "O(n * target) time and O(target) space",
      timeComplexity: "O(n * target)",
      timeComplexityDetail: "target = sum(nums) / 2.",
      spaceComplexity: "O(target)",
      spaceComplexityDetail: "Set of reachable sums <= target.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "target = sum(nums) // 2. Maintain set of reachable sums, expand with each num.",
      keySteps: ["1. total = sum(nums). If total % 2 != 0: return False. target = total // 2.", "2. dp = {0}.", "3. For num in nums: next_dp = set(dp); for t in dp: if t + num == target: return True; if t + num < target: next_dp.add(t + num); dp = next_dp.", "4. Return target in dp."],
      code: {
        python: ["class Solution:", "    def canPartition(self, nums: List[int]) -> bool:", "        total = sum(nums)", "        if total % 2 != 0: return False", "        target = total // 2", "        dp = {0}", "        for num in nums:", "            next_dp = set(dp)", "            for t in dp:", "                if t + num == target: return True", "                if t + num < target:", "                    next_dp.add(t + num)", "            dp = next_dp", "        return target in dp"],
        cpp: ["#include <vector>", "#include <numeric>", "using namespace std;", "class Solution {", "public:", "    bool canPartition(vector<int>& nums) {", "        int total = accumulate(nums.begin(), nums.end(), 0);", "        if (total % 2 != 0) return false;", "        int target = total / 2;", "        vector<bool> dp(target + 1, false);", "        dp[0] = true;", "        for (int num : nums) {", "            for (int j = target; j >= num; --j) {", "                dp[j] = dp[j] || dp[j - num];", "            }", "        }", "        return dp[target];", "    }", "};"],
        java: ["class Solution {", "    public boolean canPartition(int[] nums) {", "        int total = 0; for (int n : nums) total += n;", "        if (total % 2 != 0) return false;", "        int target = total / 2;", "        boolean[] dp = new boolean[target + 1];", "        dp[0] = true;", "        for (int num : nums) {", "            for (int j = target; j >= num; j--) {", "                dp[j] = dp[j] || dp[j - num];", "            }", "        }", "        return dp[target];", "    }", "}"],
        typescript: ["function canPartition(nums: number[]): boolean {", "  const total = nums.reduce((a, b) => a + b, 0);", "  if (total % 2 !== 0) return false;", "  const target = total / 2;", "  const dp = new Array(target + 1).fill(false);", "  dp[0] = true;", "  for (const num of nums) {", "    for (let j = target; j >= num; j--) {", "      dp[j] = dp[j] || dp[j - num];", "    }", "  }", "  return dp[target];", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Power Set Check",
      subtitle: "O(2^n) time",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Exhaustive subset generation.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Generate all subsets and check if any equals total // 2.",
      keySteps: ["1. Generate subsets."],
      code: {
        python: ["# Recursive"],
        cpp: ["// Recursive"],
        java: ["// Recursive"],
        typescript: ["// Recursive"],
      },
    },
  },
  "Perfect Squares": {
    intuition: "Find the least number of perfect square numbers that sum to n. 1) Dynamic Programming: `dp[i] = min(dp[i - s] + 1)` for all square numbers `s <= i`. 2) Lagrange's Four-Square Theorem (Math): Every natural number is a sum of at most 4 integer squares. If `n = 4^k * (8m + 7)`, answer is 4. If n is a square, answer is 1. If n is sum of two squares, answer is 2. Otherwise 3.",
    bottleneck: "Recursive branching takes O(4^n). DP runs in O(n * sqrt(n)) time and Legendre's Math theorem executes in O(sqrt(n)) optimal time.",
    keyInvariant: "dp[i] stores the minimum count of perfect squares that sum to i.",
    constraints: ["1 <= n <= 10^4"],
    examples: [{"input": "n = 12", "output": "3", "explanation": "4 + 4 + 4 = 12 (3 squares)."}, {"input": "n = 13", "output": "2", "explanation": "4 + 9 = 13 (2 squares)."}],
    companies: ["Google", "Amazon", "Meta", "Microsoft"],
    acceptanceRate: "53.6%",
    frequency: "89%",
    edgeCases: ["n is itself a perfect square (returns 1)", "n = 7 (returns 4: 4 + 1 + 1 + 1)"],
    interviewTips: ["Present the DP solution O(n * sqrt(n)) first, then mention Lagrange's Four-Square Theorem O(sqrt(n))."],
    optimal: {
      title: "Bottom-Up 1D DP across Square Multiples",
      subtitle: "O(n * sqrt(n)) time and O(n) space",
      timeComplexity: "O(n * sqrt(n))",
      timeComplexityDetail: "Outer loop n, inner loop sqrt(n).",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "dp array of size n + 1.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dp[i] = min(dp[i], 1 + dp[i - s*s]) for s from 1 up to sqrt(i). Return dp[n].",
      keySteps: ["1. dp = [float(\"inf\")] * (n + 1), dp[0] = 0.", "2. For i in range(1, n + 1): s = 1; while s * s <= i: dp[i] = min(dp[i], 1 + dp[i - s * s]); s += 1.", "3. Return dp[n]."],
      code: {
        python: ["class Solution:", "    def numSquares(self, n: int) -> int:", "        dp = [float(\"inf\")] * (n + 1)", "        dp[0] = 0", "        for i in range(1, n + 1):", "            s = 1", "            while s * s <= i:", "                dp[i] = min(dp[i], 1 + dp[i - s * s])", "                s += 1", "        return dp[n]"],
        cpp: ["// Perfect squares cpp"],
        java: ["// Perfect squares java"],
        typescript: ["// Perfect squares ts"],
      },
    },
    bruteForce: {
      title: "BFS Level Order Shortest Path",
      subtitle: "O(n * sqrt(n)) time",
      timeComplexity: "O(n * sqrt(n))",
      timeComplexityDetail: "BFS level queue.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Queue.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Find shortest path from n to 0 using BFS subtracting squares.",
      keySteps: ["1. BFS queue from n."],
      code: {
        python: ["# BFS squares"],
        cpp: ["// BFS"],
        java: ["// BFS"],
        typescript: ["// BFS"],
      },
    },
  },
  "Combination Sum IV": {
    intuition: "Find the number of possible combinations that add up to target where DIFFERENT ORDERINGS COUNT AS DIFFERENT COMBINATIONS (i.e. permutations). Dynamic Programming: Let `dp[t]` be the number of permutations summing to t. Base case: `dp[0] = 1`. For `t` in `1..target`: `dp[t] = sum(dp[t - num] for num in nums if t - num >= 0)`. Return `dp[target]` in O(target * len(nums)) time and O(target) space.",
    bottleneck: "Recursive tree recomputes target differences. Bottom-up DP computes all combinations in O(target * len(nums)) time.",
    keyInvariant: "Iterating target in the outer loop and nums in the inner loop generates all permutation orderings.",
    constraints: ["1 <= nums.length <= 200", "1 <= nums[i] <= 1000", "All elements of nums are unique.", "1 <= target <= 1000"],
    examples: [{"input": "nums = [1,2,3], target = 4", "output": "7", "explanation": "7 combinations (permutations): (1,1,1,1), (1,1,2), (1,2,1), (1,3), (2,1,1), (2,2), (3,1)."}],
    companies: ["Google", "Amazon", "Meta"],
    acceptanceRate: "53.8%",
    frequency: "86%",
    edgeCases: ["Target smaller than minimum num (returns 0)", "Single element in nums"],
    interviewTips: ["Contrast with Coin Change II: target in outer loop = permutations (Comb Sum IV); coins in outer loop = combinations (Coin Change II)."],
    optimal: {
      title: "Bottom-Up 1D DP (Target Outer Loop)",
      subtitle: "O(target * len(nums)) time and O(target) space",
      timeComplexity: "O(target * len(nums))",
      timeComplexityDetail: "Nested loops.",
      spaceComplexity: "O(target)",
      spaceComplexityDetail: "dp array of size target + 1.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dp[t] = sum(dp[t - n]) for all n <= t. Return dp[target].",
      keySteps: ["1. dp = [0] * (target + 1), dp[0] = 1.", "2. For t in range(1, target + 1): for n in nums: if t - n >= 0: dp[t] += dp[t - n].", "3. Return dp[target]."],
      code: {
        python: ["class Solution:", "    def combinationSum4(self, nums: List[int], target: int) -> int:", "        dp = [0] * (target + 1)", "        dp[0] = 1", "        for t in range(1, target + 1):", "            for n in nums:", "                if t - n >= 0:", "                    dp[t] += dp[t - n]", "        return dp[target]"],
        cpp: ["#include <vector>", "using namespace std;", "class Solution {", "public:", "    int combinationSum4(vector<int>& nums, int target) {", "        vector<unsigned int> dp(target + 1, 0);", "        dp[0] = 1;", "        for (int t = 1; t <= target; ++t) {", "            for (int n : nums) {", "                if (t - n >= 0) dp[t] += dp[t - n];", "            }", "        }", "        return dp[target];", "    }", "};"],
        java: ["class Solution {", "    public int combinationSum4(int[] nums, int target) {", "        int[] dp = new int[target + 1];", "        dp[0] = 1;", "        for (int t = 1; t <= target; t++) {", "            for (int n : nums) {", "                if (t - n >= 0) dp[t] += dp[t - n];", "            }", "        }", "        return dp[target];", "    }", "}"],
        typescript: ["function combinationSum4(nums: number[], target: number): number {", "  const dp = new Array(target + 1).fill(0);", "  dp[0] = 1;", "  for (let t = 1; t <= target; t++) {", "    for (const n of nums) {", "      if (t - n >= 0) dp[t] += dp[t - n];", "    }", "  }", "  return dp[target];", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Permutation Branching",
      subtitle: "O(N^target) time",
      timeComplexity: "O(N^target)",
      timeComplexityDetail: "Recursion tree.",
      spaceComplexity: "O(target)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "dfs(remain): sum(dfs(remain - n) for n in nums).",
      keySteps: ["1. Recursive summation."],
      code: {
        python: ["# Recursive"],
        cpp: ["// Recursive"],
        java: ["// Recursive"],
        typescript: ["// Recursive"],
      },
    },
  },
}
