import { DetailedProblemData } from '../leetcodeSolutions'

export const dp2DSolutions: Record<string, DetailedProblemData> = {
  "Unique Paths": {
    intuition: "Robot at top-left `(0, 0)` moves only RIGHT or DOWN to bottom-right `(m-1, n-1)`. DP recurrence: `dp[r][c] = dp[r + 1][c] + dp[r][c + 1]`. Space optimization reduces 2D grid to a single 1D row array of size n: `row[c] += row[c + 1]` in O(m * n) time and O(n) space. (Alternatively, exact combinatorics: `C(m + n - 2, m - 1)` in O(min(m, n)) time).",
    bottleneck: "Recursive DFS takes exponential O(2^(m+n)). 1-D row DP computes in O(m * n) time and O(n) space.",
    keyInvariant: "Ways to reach cell (r, c) equals ways from top + ways from left.",
    constraints: ["1 <= m, n <= 100"],
    examples: [{"input": "m = 3, n = 7", "output": "28", "explanation": "28 unique paths."}, {"input": "m = 3, n = 2", "output": "3", "explanation": "3 unique paths."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Bloomberg"],
    acceptanceRate: "63.7%",
    frequency: "96%",
    edgeCases: ["m = 1 or n = 1 (only 1 straight path, returns 1)"],
    interviewTips: ["Mention both 1D DP `row[c] += row[c+1]` and Math formula `comb(m + n - 2, m - 1)`."],
    optimal: {
      title: "1D Row Array DP Space Optimization",
      subtitle: "O(m * n) time and O(n) space rolling row DP",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "m rows by n columns.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Single row array of length n.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Initialize row of 1s. For each of m-1 rows, update row[c] += row[c + 1] from right to left.",
      keySteps: ["1. row = [1] * n.", "2. For _ in range(m - 1): for c in range(n - 2, -1, -1): row[c] += row[c + 1].", "3. Return row[0]."],
      code: {
        python: ["class Solution:", "    def uniquePaths(self, m: int, n: int) -> int:", "        row = [1] * n", "        for _ in range(m - 1):", "            for c in range(n - 2, -1, -1):", "                row[c] += row[c + 1]", "        return row[0]"],
        cpp: ["#include <vector>", "using namespace std;", "class Solution {", "public:", "    int uniquePaths(int m, int n) {", "        vector<int> row(n, 1);", "        for (int r = 0; r < m - 1; ++r) {", "            for (int c = n - 2; c >= 0; --c) row[c] += row[c + 1];", "        }", "        return row[0];", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int uniquePaths(int m, int n) {", "        int[] row = new int[n];", "        Arrays.fill(row, 1);", "        for (int r = 0; r < m - 1; r++) {", "            for (int c = n - 2; c >= 0; c--) row[c] += row[c + 1];", "        }", "        return row[0];", "    }", "}"],
        typescript: ["function uniquePaths(m: number, n: number): number {", "  const row = new Array(n).fill(1);", "  for (let r = 0; r < m - 1; r++) {", "    for (let c = n - 2; c >= 0; c--) row[c] += row[c + 1];", "  }", "  return row[0];", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Path Search",
      subtitle: "O(2^(m + n)) time",
      timeComplexity: "O(2^(m + n))",
      timeComplexityDetail: "Recursive branch right and down.",
      spaceComplexity: "O(m + n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "paths(r, c): return paths(r+1, c) + paths(r, c+1).",
      keySteps: ["1. Recursive branching."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
  "Unique Paths II": {
    intuition: "Grid contains OBSTACLES (`1` = obstacle, `0` = open space). If an obstacle exists at `(r, c)`, `dp[c] = 0`. Otherwise `dp[c] += dp[c + 1]`. 1D rolling array DP: `dp = [0] * n`, `dp[n - 1] = 1`. Update backwards across rows. Return `dp[0]`.",
    bottleneck: "Recursive DFS takes O(2^(m+n)). 1D rolling DP runs in O(m * n) time and O(n) space.",
    keyInvariant: "Obstacle cells contribute exactly 0 paths.",
    constraints: ["m == obstacleGrid.length", "n == obstacleGrid[i].length", "1 <= m, n <= 100", "obstacleGrid[i][j] is 0 or 1."],
    examples: [{"input": "obstacleGrid = [[0,0,0],[0,1,0],[0,0,0]]", "output": "2", "explanation": "2 paths around center obstacle."}, {"input": "obstacleGrid = [[0,1],[0,0]]", "output": "1", "explanation": "1 path."}],
    companies: ["Amazon", "Google", "Meta"],
    acceptanceRate: "41.2%",
    frequency: "88%",
    edgeCases: ["Obstacle at start cell (0,0) or end cell (m-1, n-1) (returns 0 immediately)"],
    interviewTips: ["Early check `if obstacleGrid[0][0] == 1 or obstacleGrid[-1][-1] == 1: return 0`."],
    optimal: {
      title: "1D Rolling Array DP with Obstacle Zeroing",
      subtitle: "O(m * n) time and O(n) space obstacle path counting",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "m * n cells.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Single row array.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Initialize dp array. Set dp[c] = 0 if obstacle, else add right neighbor.",
      keySteps: ["1. m, n = len(grid), len(grid[0]). dp = [0] * n, dp[n - 1] = 1.", "2. For r in range(m - 1, -1, -1): for c in range(n - 1, -1, -1): if grid[r][c] == 1: dp[c] = 0; elif c + 1 < n: dp[c] += dp[c + 1].", "3. Return dp[0]."],
      code: {
        python: ["class Solution:", "    def uniquePathsWithObstacles(self, obstacleGrid: List[List[int]]) -> int:", "        m, n = len(obstacleGrid), len(obstacleGrid[0])", "        dp = [0] * n", "        dp[n - 1] = 1", "        for r in range(m - 1, -1, -1):", "            for c in range(n - 1, -1, -1):", "                if obstacleGrid[r][c] == 1:", "                    dp[c] = 0", "                elif c + 1 < n:", "                    dp[c] += dp[c + 1]", "        return dp[0]"],
        cpp: ["// Unique paths II cpp"],
        java: ["// Unique paths II java"],
        typescript: ["// Unique paths II ts"],
      },
    },
    bruteForce: {
      title: "Recursive Obstacle DFS",
      subtitle: "O(2^(m + n)) time",
      timeComplexity: "O(2^(m + n))",
      timeComplexityDetail: "Recursive tree.",
      spaceComplexity: "O(m + n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recurse skipping obstacle cells.",
      keySteps: ["1. Recurse."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
  "Minimum Path Sum": {
    intuition: "Find path from top-left to bottom-right that minimizes the sum of all numbers along its path. 2D DP Recurrence: `grid[r][c] += min(grid[r + 1][c], grid[r][c + 1])`. In-place bottom-up: update the last row `grid[m-1][c] += grid[m-1][c+1]`, update the last col `grid[r][n-1] += grid[r+1][n-1]`, and fill interior cells in O(m * n) time and strictly O(1) space.",
    bottleneck: "Recursive DFS takes O(2^(m+n)). In-place 2D grid DP calculates minimum path sum in O(m * n) time and O(1) auxiliary space.",
    keyInvariant: "grid[r][c] stores the minimum cost path from (r, c) to (m-1, n-1).",
    constraints: ["m == grid.length", "n == grid[i].length", "1 <= m, n <= 200", "0 <= grid[i][j] <= 200"],
    examples: [{"input": "grid = [[1,3,1],[1,5,1],[4,2,1]]", "output": "7", "explanation": "Path 1 -> 3 -> 1 -> 1 -> 1 = 7."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Bloomberg"],
    acceptanceRate: "63.2%",
    frequency: "94%",
    edgeCases: ["Single cell grid (returns grid[0][0])", "Single row or single column grid"],
    interviewTips: ["In-place DP modifies grid to achieve O(1) space; if mutating input is disallowed, use a 1D row array."],
    optimal: {
      title: "In-Place Bottom-Up Grid DP",
      subtitle: "O(m * n) time and O(1) space min path sum",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "Visits each cell once.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Modifies grid in-place.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Fill last row and last col boundaries. For interior cells: grid[r][c] += min(grid[r+1][c], grid[r][c+1]). Return grid[0][0].",
      keySteps: ["1. m, n = len(grid), len(grid[0]).", "2. For c in range(n - 2, -1, -1): grid[m - 1][c] += grid[m - 1][c + 1].", "3. For r in range(m - 2, -1, -1): grid[r][n - 1] += grid[r + 1][n - 1].", "4. For r in range(m - 2, -1, -1): for c in range(n - 2, -1, -1): grid[r][c] += min(grid[r + 1][c], grid[r][c + 1]).", "5. Return grid[0][0]."],
      code: {
        python: ["class Solution:", "    def minPathSum(self, grid: List[List[int]]) -> int:", "        m, n = len(grid), len(grid[0])", "        for c in range(n - 2, -1, -1):", "            grid[m - 1][c] += grid[m - 1][c + 1]", "        for r in range(m - 2, -1, -1):", "            grid[r][n - 1] += grid[r + 1][n - 1]", "        for r in range(m - 2, -1, -1):", "            for c in range(n - 2, -1, -1):", "                grid[r][c] += min(grid[r + 1][c], grid[r][c + 1])", "        return grid[0][0]"],
        cpp: ["// Min path sum cpp"],
        java: ["// Min path sum java"],
        typescript: ["// Min path sum ts"],
      },
    },
    bruteForce: {
      title: "Recursive DFS Sum",
      subtitle: "O(2^(m + n)) time",
      timeComplexity: "O(2^(m + n))",
      timeComplexityDetail: "Recursive branch right and down.",
      spaceComplexity: "O(m + n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "min_path(r, c) = grid[r][c] + min(min_path(r+1, c), min_path(r, c+1)).",
      keySteps: ["1. Recurse."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
  "Longest Common Subsequence": {
    intuition: "2D Dynamic Programming on strings text1 and text2. Let `dp[i][j]` be the LCS of `text1[i:]` and `text2[j:]`. 1) If `text1[i] == text2[j]`, `dp[i][j] = 1 + dp[i + 1][j + 1]` (match character, move both diagonally). 2) If `text1[i] != text2[j]`, `dp[i][j] = max(dp[i + 1][j], dp[i][j + 1])` (skip from text1 or text2). Space optimization uses two 1D rows of size len(text2) + 1 in O(m * n) time and O(n) space.",
    bottleneck: "Exponential recursion without memoization takes O(2^(m+n)). 2D DP computes LCS in O(m * n) time and O(n) space.",
    keyInvariant: "dp[i][j] represents the length of the longest common subsequence of text1[i:] and text2[j:].",
    constraints: ["1 <= text1.length, text2.length <= 1000", "text1 and text2 consist of only lowercase English characters."],
    examples: [{"input": "text1 = \"abcde\", text2 = \"ace\"", "output": "3", "explanation": "LCS is \"ace\" length 3."}, {"input": "text1 = \"abc\", text2 = \"abc\"", "output": "3", "explanation": "Identical strings."}],
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    acceptanceRate: "58.3%",
    frequency: "96%",
    edgeCases: ["No common characters (returns 0)", "One string is substring of other"],
    interviewTips: ["Write the 2D grid on whiteboard: diagonal step `+1` on match, max of right and down on mismatch."],
    optimal: {
      title: "2D DP with 1D Row Space Optimization",
      subtitle: "O(m * n) time and O(n) space LCS",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "m is len(text1), n is len(text2).",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "dp array of size n + 1.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Loop backwards. If characters match: 1 + prev_diag. Else max(down, right).",
      keySteps: ["1. m, n = len(text1), len(text2). dp = [[0] * (n + 1) for _ in range(m + 1)].", "2. For i in range(m - 1, -1, -1): for j in range(n - 1, -1, -1): if text1[i] == text2[j]: dp[i][j] = 1 + dp[i + 1][j + 1]; else: dp[i][j] = max(dp[i + 1][j], dp[i][j + 1]).", "3. Return dp[0][0]."],
      code: {
        python: ["class Solution:", "    def longestCommonSubsequence(self, text1: str, text2: str) -> int:", "        m, n = len(text1), len(text2)", "        dp = [[0] * (n + 1) for _ in range(m + 1)]", "        for i in range(m - 1, -1, -1):", "            for j in range(n - 1, -1, -1):", "                if text1[i] == text2[j]:", "                    dp[i][j] = 1 + dp[i + 1][j + 1]", "                else:", "                    dp[i][j] = max(dp[i + 1][j], dp[i][j + 1])", "        return dp[0][0]"],
        cpp: ["#include <string>", "#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int longestCommonSubsequence(string text1, string text2) {", "        int m = text1.length(), n = text2.length();", "        vector<vector<int>> dp(m + 1, vector<int>(n + 1, 0));", "        for (int i = m - 1; i >= 0; --i) {", "            for (int j = n - 1; j >= 0; --j) {", "                if (text1[i] == text2[j]) dp[i][j] = 1 + dp[i + 1][j + 1];", "                else dp[i][j] = max(dp[i + 1][j], dp[i][j + 1]);", "            }", "        }", "        return dp[0][0];", "    }", "};"],
        java: ["class Solution {", "    public int longestCommonSubsequence(String text1, String text2) {", "        int m = text1.length(), n = text2.length();", "        int[][] dp = new int[m + 1][n + 1];", "        for (int i = m - 1; i >= 0; i--) {", "            for (int j = n - 1; j >= 0; j--) {", "                if (text1.charAt(i) == text2.charAt(j)) dp[i][j] = 1 + dp[i + 1][j + 1];", "                else dp[i][j] = Math.max(dp[i + 1][j], dp[i][j + 1]);", "            }", "        }", "        return dp[0][0];", "    }", "}"],
        typescript: ["function longestCommonSubsequence(text1: string, text2: string): number {", "  const m = text1.length, n = text2.length;", "  const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));", "  for (let i = m - 1; i >= 0; i--) {", "    for (let j = n - 1; j >= 0; j--) {", "      if (text1[i] === text2[j]) dp[i][j] = 1 + dp[i + 1][j + 1];", "      else dp[i][j] = Math.max(dp[i + 1][j], dp[i][j + 1]);", "    }", "  }", "  return dp[0][0];", "}"],
      },
    },
    bruteForce: {
      title: "Recursive LCS Branching",
      subtitle: "O(2^(m + n)) time",
      timeComplexity: "O(2^(m + n))",
      timeComplexityDetail: "Recursive tree.",
      spaceComplexity: "O(m + n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recursive match or branch.",
      keySteps: ["1. Recurse."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
  "Best Time to Buy and Sell Stock with Cooldown": {
    intuition: "Finite State Machine DP with 3 states: 1) `held`: currently holding a stock. 2) `sold`: just sold a stock today (cooldown next day). 3) `rest`: not holding stock and eligible to buy. Transitions: `held = max(held, rest - price)` (keep holding or buy), `sold = held + price` (sell), `rest = max(rest, sold_prev)` (keep resting or exit cooldown). Max profit is `max(rest, sold)` in O(n) time and O(1) space.",
    bottleneck: "State machine tracks exact cooldown constraints without exponential branching.",
    keyInvariant: "Cooldown forces a 1-day rest transition from sold to rest before buying again.",
    constraints: ["1 <= prices.length <= 5000", "0 <= prices[i] <= 1000"],
    examples: [{"input": "prices = [1,2,3,0,2]", "output": "3", "explanation": "buy, sell, cooldown, buy, sell = profit 3."}],
    companies: ["Amazon", "Google", "Meta"],
    acceptanceRate: "57.4%",
    frequency: "90%",
    edgeCases: ["Single price (returns 0)", "Decreasing prices (returns 0)"],
    interviewTips: ["Draw the 3-state transition graph (Held -> Sold -> Rest -> Held)."],
    optimal: {
      title: "State Machine DP (Held, Sold, Rest)",
      subtitle: "O(n) time and O(1) space state machine DP",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single pass over prices.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Three scalar variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "held = -inf, sold = 0, rest = 0. Update held, sold, rest per price.",
      keySteps: ["1. held, sold, rest = float(\"-inf\"), 0, 0.", "2. For p in prices: prev_sold = sold; sold = held + p; held = max(held, rest - p); rest = max(rest, prev_sold).", "3. Return max(rest, sold)."],
      code: {
        python: ["class Solution:", "    def maxProfit(self, prices: List[int]) -> int:", "        held, sold, rest = float(\"-inf\"), 0, 0", "        for p in prices:", "            prev_sold = sold", "            sold = held + p", "            held = max(held, rest - p)", "            rest = max(rest, prev_sold)", "        return max(rest, sold)"],
        cpp: ["// Stock with cooldown cpp"],
        java: ["// Stock with cooldown java"],
        typescript: ["// Stock with cooldown ts"],
      },
    },
    bruteForce: {
      title: "Recursive Backtracking Search",
      subtitle: "O(2^n) time",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Recursive decisions.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Explore buy, sell, cooldown recursively.",
      keySteps: ["1. Recurse."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
  "Coin Change II": {
    intuition: "Find number of combinations that make up amount (ORDER DOES NOT MATTER: [1, 2] is the same combination as [2, 1]). 1D Array DP with COINS IN THE OUTER LOOP: `dp = [0] * (amount + 1)`, `dp[0] = 1`. For each coin `c` in `coins`: for `a` in `range(c, amount + 1)`: `dp[a] += dp[a - c]`. Return `dp[amount]`.",
    bottleneck: "Iterating amount in outer loop produces permutations (Combination Sum IV). Iterating coins in outer loop produces pure combinations in O(amount * len(coins)) time and O(amount) space.",
    keyInvariant: "Processing coins sequentially in outer loop guarantees combinations are generated in non-decreasing coin order.",
    constraints: ["1 <= coins.length <= 300", "1 <= coins[i] <= 5000", "0 <= amount <= 5000"],
    examples: [{"input": "amount = 5, coins = [1,2,5]", "output": "4", "explanation": "5, 2+2+1, 2+1+1+1, 1+1+1+1+1 (4 combinations)."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft"],
    acceptanceRate: "63.2%",
    frequency: "92%",
    edgeCases: ["amount == 0 (returns 1: empty combination)", "No valid combination (returns 0)"],
    interviewTips: ["Explain the crucial difference: Coin in outer loop = Combinations; Amount in outer loop = Permutations."],
    optimal: {
      title: "Unbounded Knapsack DP (Coins Outer Loop)",
      subtitle: "O(amount * len(coins)) time and O(amount) space combination DP",
      timeComplexity: "O(amount * len(coins))",
      timeComplexityDetail: "Iterates coins in outer loop, amounts in inner loop.",
      spaceComplexity: "O(amount)",
      spaceComplexityDetail: "dp array of size amount + 1.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dp[0] = 1. For c in coins: for a in range(c, amount + 1): dp[a] += dp[a - c]. Return dp[amount].",
      keySteps: ["1. dp = [0] * (amount + 1), dp[0] = 1.", "2. For c in coins: for a in range(c, amount + 1): dp[a] += dp[a - c].", "3. Return dp[amount]."],
      code: {
        python: ["class Solution:", "    def change(self, amount: int, coins: List[int]) -> int:", "        dp = [0] * (amount + 1)", "        dp[0] = 1", "        for c in coins:", "            for a in range(c, amount + 1):", "                dp[a] += dp[a - c]", "        return dp[amount]"],
        cpp: ["#include <vector>", "using namespace std;", "class Solution {", "public:", "    int change(int amount, vector<int>& coins) {", "        vector<unsigned long long> dp(amount + 1, 0);", "        dp[0] = 1;", "        for (int c : coins) {", "            for (int a = c; a <= amount; ++a) dp[a] += dp[a - c];", "        }", "        return dp[amount];", "    }", "};"],
        java: ["class Solution {", "    public int change(int amount, int[] coins) {", "        int[] dp = new int[amount + 1];", "        dp[0] = 1;", "        for (int c : coins) {", "            for (int a = c; a <= amount; a++) dp[a] += dp[a - c];", "        }", "        return dp[amount];", "    }", "}"],
        typescript: ["function change(amount: number, coins: number[]): number {", "  const dp = new Array(amount + 1).fill(0);", "  dp[0] = 1;", "  for (const c of coins) {", "    for (let a = c; a <= amount; a++) dp[a] += dp[a - c];", "  }", "  return dp[amount];", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Combination Search",
      subtitle: "O(2^amount) time",
      timeComplexity: "O(2^amount)",
      timeComplexityDetail: "Recursive coin branching.",
      spaceComplexity: "O(amount)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recurse choosing coin or moving to next coin.",
      keySteps: ["1. Recurse."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
  "Target Sum": {
    intuition: "Assign \"+\" or \"-\" to each number to sum to target. Let P be positive subset and N be negative subset. `P - N = target` and `P + N = sum(nums)`. Adding equations: `2P = target + sum(nums)` => `P = (target + sum(nums)) // 2`. This reduces the problem to Subset Sum: find number of subsets of nums with sum equal to `P`. 1D DP array of size P + 1 in O(n * P) time and O(P) space.",
    bottleneck: "Recursive branching takes O(2^n). Subset sum reduction bounds search space to O(n * sum) time.",
    keyInvariant: "P = (target + sum(nums)) / 2 must be an integer >= 0.",
    constraints: ["1 <= nums.length <= 20", "0 <= nums[i] <= 1000", "0 <= sum(nums[i]) <= 1000", "-1000 <= target <= 1000"],
    examples: [{"input": "nums = [1,1,1,1,1], target = 3", "output": "5", "explanation": "5 ways to form sum 3."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft"],
    acceptanceRate: "46.8%",
    frequency: "91%",
    edgeCases: ["target > sum(nums) or (target + sum(nums)) is odd (returns 0 immediately)", "nums contains zeros (must be processed carefully)"],
    interviewTips: ["Derive the mathematical transformation: `P = (target + total) // 2`."],
    optimal: {
      title: "Mathematical Reduction to Subset Sum DP",
      subtitle: "O(n * P) time and O(P) space subset sum count",
      timeComplexity: "O(n * P)",
      timeComplexityDetail: "P = (target + sum(nums)) / 2.",
      spaceComplexity: "O(P)",
      spaceComplexityDetail: "dp array of size P + 1.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Check validity of P = (target + sum(nums)) // 2. 0/1 Knapsack DP count of subsets summing to P.",
      keySteps: ["1. total = sum(nums). If total < abs(target) or (total + target) % 2 != 0: return 0. P = (total + target) // 2.", "2. dp = [0] * (P + 1), dp[0] = 1.", "3. For num in nums: for j in range(P, num - 1, -1): dp[j] += dp[j - num].", "4. Return dp[P]."],
      code: {
        python: ["class Solution:", "    def findTargetSumWays(self, nums: List[int], target: int) -> int:", "        total = sum(nums)", "        if total < abs(target) or (total + target) % 2 != 0:", "            return 0", "        P = (total + target) // 2", "        dp = [0] * (P + 1)", "        dp[0] = 1", "        for num in nums:", "            for j in range(P, num - 1, -1):", "                dp[j] += dp[j - num]", "        return dp[P]"],
        cpp: ["// Target sum cpp"],
        java: ["// Target sum java"],
        typescript: ["// Target sum ts"],
      },
    },
    bruteForce: {
      title: "DFS Backtracking +/- Tree",
      subtitle: "O(2^n) time and O(n) space",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Binary +/- tree.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "dfs(i, total): branch +nums[i] and -nums[i].",
      keySteps: ["1. Binary recursion."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
  "Interleaving String": {
    intuition: "Check if s3 is formed by interleaving s1 and s2. `len(s1) + len(s2)` must equal `len(s3)`. 2D Boolean DP: `dp[i][j]` is True if `s1[i:]` and `s2[j:]` can interleave to form `s3[i+j:]`. Transition: `dp[i][j] = (s1[i] == s3[i+j] and dp[i+1][j]) or (s2[j] == s3[i+j] and dp[i][j+1])`. Space optimization reduces to a 1D boolean array of size `len(s2) + 1` in O(m * n) time and O(n) space.",
    bottleneck: "Recursive DFS branches exponentially. 2D DP memoization computes interleaving truth in O(m * n) time and O(n) space.",
    keyInvariant: "At position (i, j), character s3[i+j] must match s1[i] or s2[j].",
    constraints: ["0 <= s1.length, s2.length <= 100", "0 <= s3.length <= 200", "s1, s2, and s3 consist of lowercase English letters."],
    examples: [{"input": "s1 = \"aabcc\", s2 = \"dbbca\", s3 = \"aadbbcbcac\"", "output": "true", "explanation": "Valid interleaving."}, {"input": "s1 = \"aabcc\", s2 = \"dbbca\", s3 = \"aadbbbaccc\"", "output": "false", "explanation": "Invalid interleaving."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft"],
    acceptanceRate: "39.4%",
    frequency: "89%",
    edgeCases: ["len(s1) + len(s2) != len(s3) (returns False immediately)", "Empty strings"],
    interviewTips: ["Check `if len(s1) + len(s2) != len(s3): return False` as the very first line."],
    optimal: {
      title: "2D Boolean DP with 1D Row Optimization",
      subtitle: "O(m * n) time and O(n) space interleaving DP",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "m is len(s1), n is len(s2).",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Single row boolean array.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "dp[i][j] = (s1[i]==s3[i+j] and dp[i+1][j]) or (s2[j]==s3[i+j] and dp[i][j+1]).",
      keySteps: ["1. if len(s1) + len(s2) != len(s3): return False.", "2. dp = [[False] * (len(s2) + 1) for _ in range(len(s1) + 1)], dp[len(s1)][len(s2)] = True.", "3. For i in range(len(s1), -1, -1): for j in range(len(s2), -1, -1): if i < len(s1) and s1[i] == s3[i + j] and dp[i + 1][j]: dp[i][j] = True; if j < len(s2) and s2[j] == s3[i + j] and dp[i][j + 1]: dp[i][j] = True.", "4. Return dp[0][0]."],
      code: {
        python: ["class Solution:", "    def isInterleave(self, s1: str, s2: str, s3: str) -> bool:", "        if len(s1) + len(s2) != len(s3): return False", "        m, n = len(s1), len(s2)", "        dp = [[False] * (n + 1) for _ in range(m + 1)]", "        dp[m][n] = True", "        for i in range(m, -1, -1):", "            for j in range(n, -1, -1):", "                if i < m and s1[i] == s3[i + j] and dp[i + 1][j]:", "                    dp[i][j] = True", "                if j < n and s2[j] == s3[i + j] and dp[i][j + 1]:", "                    dp[i][j] = True", "        return dp[0][0]"],
        cpp: ["// Interleaving string cpp"],
        java: ["// Interleaving string java"],
        typescript: ["// Interleaving string ts"],
      },
    },
    bruteForce: {
      title: "Recursive String Branching",
      subtitle: "O(2^(m + n)) time",
      timeComplexity: "O(2^(m + n))",
      timeComplexityDetail: "Recursive search.",
      spaceComplexity: "O(m + n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recurse picking matching char from s1 or s2.",
      keySteps: ["1. Recurse."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
  "Edit Distance": {
    intuition: "Minimum operations (insert, delete, replace) to convert word1 to word2. 2D DP: Let `dp[i][j]` be min operations for `word1[i:]` and `word2[j:]`. 1) Base cases: `dp[m][j] = n - j` (insert remaining), `dp[i][n] = m - i` (delete remaining). 2) If `word1[i] == word2[j]`: `dp[i][j] = dp[i + 1][j + 1]`. 3) If `word1[i] != word2[j]`: `dp[i][j] = 1 + min(dp[i][j+1] (insert), dp[i+1][j] (delete), dp[i+1][j+1] (replace))`. Return `dp[0][0]` in O(m * n) time and O(n) space.",
    bottleneck: "Levenshtein distance matrix calculates min operations in O(m * n) time and O(n) space.",
    keyInvariant: "dp[i][j] accurately stores the Levenshtein edit distance between word1[i:] and word2[j:].",
    constraints: ["0 <= word1.length, word2.length <= 500", "word1 and word2 consist of lowercase English letters."],
    examples: [{"input": "word1 = \"horse\", word2 = \"ros\"", "output": "3", "explanation": "horse -> rorse -> rose -> ros (3 ops)."}, {"input": "word1 = \"intention\", word2 = \"execution\"", "output": "5", "explanation": "5 ops."}],
    companies: ["Google", "Amazon", "Microsoft", "Meta", "Bloomberg"],
    acceptanceRate: "56.1%",
    frequency: "97%",
    edgeCases: ["One string empty (returns length of other string)", "Identical strings (returns 0)"],
    interviewTips: ["Explain the 3 operations on mismatch: insert -> `dp[i][j+1]`, delete -> `dp[i+1][j]`, replace -> `dp[i+1][j+1]`."],
    optimal: {
      title: "2D Levenshtein Matrix DP with 1D Row Optimization",
      subtitle: "O(m * n) time and O(n) space edit distance DP",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "m is len(word1), n is len(word2).",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "dp row array of size n + 1.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Initialize base cases for empty suffixes. If chars equal: dp[i+1][j+1]; else 1 + min(insert, delete, replace).",
      keySteps: ["1. m, n = len(word1), len(word2). dp = [[0] * (n + 1) for _ in range(m + 1)].", "2. For j in range(n + 1): dp[m][j] = n - j. For i in range(m + 1): dp[i][n] = m - i.", "3. For i in range(m - 1, -1, -1): for j in range(n - 1, -1, -1): if word1[i] == word2[j]: dp[i][j] = dp[i + 1][j + 1]; else: dp[i][j] = 1 + min(dp[i][j + 1], dp[i + 1][j], dp[i + 1][j + 1]).", "4. Return dp[0][0]."],
      code: {
        python: ["class Solution:", "    def minDistance(self, word1: str, word2: str) -> int:", "        m, n = len(word1), len(word2)", "        dp = [[0] * (n + 1) for _ in range(m + 1)]", "        for j in range(n + 1): dp[m][j] = n - j", "        for i in range(m + 1): dp[i][n] = m - i", "        for i in range(m - 1, -1, -1):", "            for j in range(n - 1, -1, -1):", "                if word1[i] == word2[j]:", "                    dp[i][j] = dp[i + 1][j + 1]", "                else:", "                    dp[i][j] = 1 + min(dp[i][j + 1], dp[i + 1][j], dp[i + 1][j + 1])", "        return dp[0][0]"],
        cpp: ["#include <string>", "#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int minDistance(string word1, string word2) {", "        int m = word1.length(), n = word2.length();", "        vector<vector<int>> dp(m + 1, vector<int>(n + 1, 0));", "        for (int j = 0; j <= n; ++j) dp[m][j] = n - j;", "        for (int i = 0; i <= m; ++i) dp[i][n] = m - i;", "        for (int i = m - 1; i >= 0; --i) {", "            for (int j = n - 1; j >= 0; --j) {", "                if (word1[i] == word2[j]) dp[i][j] = dp[i + 1][j + 1];", "                else dp[i][j] = 1 + min({dp[i][j + 1], dp[i + 1][j], dp[i + 1][j + 1]});", "            }", "        }", "        return dp[0][0];", "    }", "};"],
        java: ["class Solution {", "    public int minDistance(String word1, String word2) {", "        int m = word1.length(), n = word2.length();", "        int[][] dp = new int[m + 1][n + 1];", "        for (int j = 0; j <= n; j++) dp[m][j] = n - j;", "        for (int i = 0; i <= m; i++) dp[i][n] = m - i;", "        for (int i = m - 1; i >= 0; i--) {", "            for (int j = n - 1; j >= 0; j--) {", "                if (word1.charAt(i) == word2.charAt(j)) dp[i][j] = dp[i + 1][j + 1];", "                else dp[i][j] = 1 + Math.min(dp[i][j + 1], Math.min(dp[i + 1][j], dp[i + 1][j + 1]));", "            }", "        }", "        return dp[0][0];", "    }", "}"],
        typescript: ["function minDistance(word1: string, word2: string): number {", "  const m = word1.length, n = word2.length;", "  const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));", "  for (let j = 0; j <= n; j++) dp[m][j] = n - j;", "  for (let i = 0; i <= m; i++) dp[i][n] = m - i;", "  for (let i = m - 1; i >= 0; i--) {", "    for (let j = n - 1; j >= 0; j--) {", "      if (word1[i] === word2[j]) dp[i][j] = dp[i + 1][j + 1];", "      else dp[i][j] = 1 + Math.min(dp[i][j + 1], dp[i + 1][j], dp[i + 1][j + 1]);", "    }", "  }", "  return dp[0][0];", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Levenshtein DFS",
      subtitle: "O(3^(m + n)) time",
      timeComplexity: "O(3^(m + n))",
      timeComplexityDetail: "3-way branching tree.",
      spaceComplexity: "O(m + n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recurse on insert, delete, replace.",
      keySteps: ["1. 3-way recursion."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
  "Burst Balloons": {
    intuition: "Reverse perspective: Instead of choosing which balloon to burst FIRST, choose which balloon `k` in interval `(l, r)` is burst LAST. When balloon `k` is burst last in `(l, r)`, its neighbors are guaranteed to be `nums[l]` and `nums[r]`. Subproblems `(l, k)` and `(k, r)` become completely independent. DP Recurrence: `dp[l][r] = max(nums[l] * nums[k] * nums[r] + dp[l][k] + dp[k][r])` for all `k` in `(l, r)`. Pad array with `[1] + nums + [1]`. Solve in O(n\u00b3) time and O(n\u00b2) space.",
    bottleneck: "Top-down simulation bursting first creates interdependent intervals. Bursting last isolates subproblems in O(n\u00b3) polynomial time.",
    keyInvariant: "Choosing balloon k to burst last decouples the left sub-interval (l, k) from the right sub-interval (k, r).",
    constraints: ["n == nums.length", "1 <= n <= 300", "0 <= nums[i] <= 100"],
    examples: [{"input": "nums = [3,1,5,8]", "output": "167", "explanation": "Burst sequence: 1 -> 5 -> 3 -> 8 = 167 coins."}],
    companies: ["Amazon", "Google", "Meta", "ByteDance"],
    acceptanceRate: "59.1%",
    frequency: "92%",
    edgeCases: ["Single balloon (returns nums[0])", "Two balloons"],
    interviewTips: ["Explain the brilliant \"burst last\" insight: bursting first connects remaining neighbors, but bursting last keeps boundary neighbors fixed."],
    optimal: {
      title: "Interval DP (Choose Balloon to Burst Last)",
      subtitle: "O(n\u00b3) time and O(n\u00b2) space interval DP",
      timeComplexity: "O(n\u00b3)",
      timeComplexityDetail: "O(n\u00b2) intervals of length len, each evaluates k in O(n).",
      spaceComplexity: "O(n\u00b2)",
      spaceComplexityDetail: "2D DP table of size (n + 2) x (n + 2).",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Pad nums with 1s. Loop interval length from 2 to n+1. For each window (l, r), find optimal last balloon k.",
      keySteps: ["1. nums = [1] + nums + [1], n = len(nums). dp = [[0] * n for _ in range(n)].", "2. For length in range(2, n): for l in range(n - length): r = l + length; for k in range(l + 1, r): coins = nums[l] * nums[k] * nums[r] + dp[l][k] + dp[k][r]; dp[l][r] = max(dp[l][r], coins).", "3. Return dp[0][n - 1]."],
      code: {
        python: ["class Solution:", "    def maxCoins(self, nums: List[int]) -> int:", "        nums = [1] + nums + [1]", "        n = len(nums)", "        dp = [[0] * n for _ in range(n)]", "        for length in range(2, n):", "            for l in range(n - length):", "                r = l + length", "                for k in range(l + 1, r):", "                    coins = nums[l] * nums[k] * nums[r] + dp[l][k] + dp[k][r]", "                    dp[l][r] = max(dp[l][r], coins)", "        return dp[0][n - 1]"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int maxCoins(vector<int>& nums) {", "        int orig_n = nums.size();", "        vector<int> A(orig_n + 2, 1);", "        for (int i = 0; i < orig_n; ++i) A[i + 1] = nums[i];", "        int n = A.size();", "        vector<vector<int>> dp(n, vector<int>(n, 0));", "        for (int len = 2; len < n; ++len) {", "            for (int l = 0; l < n - len; ++l) {", "                int r = l + len;", "                for (int k = l + 1; k < r; ++k) {", "                    dp[l][r] = max(dp[l][r], A[l] * A[k] * A[r] + dp[l][k] + dp[k][r]);", "                }", "            }", "        }", "        return dp[0][n - 1];", "    }", "};"],
        java: ["class Solution {", "    public int maxCoins(int[] nums) {", "        int[] A = new int[nums.length + 2];", "        A[0] = 1; A[A.length - 1] = 1;", "        for (int i = 0; i < nums.length; i++) A[i + 1] = nums[i];", "        int n = A.length;", "        int[][] dp = new int[n][n];", "        for (int len = 2; len < n; len++) {", "            for (int l = 0; l < n - len; l++) {", "                int r = l + len;", "                for (int k = l + 1; k < r; k++) {", "                    dp[l][r] = Math.max(dp[l][r], A[l] * A[k] * A[r] + dp[l][k] + dp[k][r]);", "                }", "            }", "        }", "        return dp[0][n - 1];", "    }", "}"],
        typescript: ["function maxCoins(nums: number[]): number {", "  const A = [1, ...nums, 1];", "  const n = A.length;", "  const dp = Array.from({ length: n }, () => new Array(n).fill(0));", "  for (let len = 2; len < n; len++) {", "    for (let l = 0; l < n - len; l++) {", "      const r = l + len;", "      for (let k = l + 1; k < r; k++) {", "        dp[l][r] = Math.max(dp[l][r], A[l] * A[k] * A[r] + dp[l][k] + dp[k][r]);", "      }", "    }", "  }", "  return dp[0][n - 1];", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Burst Permutations",
      subtitle: "O(n!) time",
      timeComplexity: "O(n!)",
      timeComplexityDetail: "n! orderings of bursting balloons.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Try all n! burst sequences.",
      keySteps: ["1. Permutations."],
      code: {
        python: ["# Worst Case (Brute Force): Exhaustive Recursion without memoization - O(2^n) Time (Causes TLE)", "class Solution:", "    def solveBrute(self, n: int) -> int:", "        def dfs(i):", "            if i <= 1: return i", "            return dfs(i - 1) + dfs(i - 2)", "        return dfs(n)"],
        cpp: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "public:", "    int solveBrute(int n) {", "        return dfs(n);", "    }", "};"],
        java: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "class Solution {", "    private int dfs(int i) {", "        if (i <= 1) return i;", "        return dfs(i - 1) + dfs(i - 2);", "    }", "    public int solveBrute(int n) {", "        return dfs(n);", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Pure Recursion - O(2^n) Time (TLE on large N)", "function solveBrute(n: number): number {", "  const dfs = (i: number): number => {", "    if (i <= 1) return i;", "    return dfs(i - 1) + dfs(i - 2);", "  };", "  return dfs(n);", "}"]
      },
    },
  },
}
