import { DetailedProblemData } from '../leetcodeSolutions'

export const greedySolutions: Record<string, DetailedProblemData> = {
  "Maximum Subarray": {
    intuition: "Kadane's Algorithm: Maintain a running sum `cur_sum`. As you iterate through nums: `cur_sum = max(num, cur_sum + num)`. If `cur_sum` drops below 0, reset `cur_sum = 0` (a negative prefix will never help future subarrays). Track global `max_sum = max(max_sum, cur_sum)`.",
    bottleneck: "Checking all O(n\u00b2) subarrays takes O(n\u00b2). Kadane's single pass computes max sum in O(n) time and strictly O(1) space.",
    keyInvariant: "cur_sum stores the maximum sum of a non-empty subarray ending at the current index.",
    constraints: ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
    examples: [{"input": "nums = [-2,1,-3,4,-1,2,1,-5,4]", "output": "6", "explanation": "Subarray [4,-1,2,1] has largest sum 6."}],
    companies: ["Amazon", "Microsoft", "Google", "Meta", "Apple"],
    acceptanceRate: "50.4%",
    frequency: "99%",
    edgeCases: ["Array of all negative numbers (returns max single negative number, e.g. [-1] -> -1)"],
    interviewTips: ["Initialize `max_sum = nums[0]` to correctly handle all-negative arrays."],
    optimal: {
      title: "Kadane's Algorithm (Running Subarray Sum)",
      subtitle: "O(n) time and O(1) space single pass max subarray",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Processes each element in nums exactly once.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Two scalar variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "cur_sum = max(0, cur_sum) + n; max_sum = max(max_sum, cur_sum).",
      keySteps: ["1. max_sum = nums[0], cur_sum = 0.", "2. For n in nums: cur_sum = max(0, cur_sum) + n; max_sum = max(max_sum, cur_sum).", "3. Return max_sum."],
      code: {
        python: ["class Solution:", "    def maxSubArray(self, nums: List[int]) -> int:", "        max_sum = nums[0]", "        cur_sum = 0", "        for n in nums:", "            cur_sum = max(0, cur_sum) + n", "            max_sum = max(max_sum, cur_sum)", "        return max_sum"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int maxSubArray(vector<int>& nums) {", "        int max_sum = nums[0], cur_sum = 0;", "        for (int n : nums) {", "            cur_sum = max(0, cur_sum) + n;", "            max_sum = max(max_sum, cur_sum);", "        }", "        return max_sum;", "    }", "};"],
        java: ["class Solution {", "    public int maxSubArray(int[] nums) {", "        int maxSum = nums[0], curSum = 0;", "        for (int n : nums) {", "            curSum = Math.max(0, curSum) + n;", "            maxSum = Math.max(maxSum, curSum);", "        }", "        return maxSum;", "    }", "}"],
        typescript: ["function maxSubArray(nums: number[]): number {", "  let maxSum = nums[0], curSum = 0;", "  for (const n of nums) {", "    curSum = Math.max(0, curSum) + n;", "    maxSum = Math.max(maxSum, curSum);", "  }", "  return maxSum;", "}"],
      },
    },
    bruteForce: {
      title: "Nested Loop All Subarrays",
      subtitle: "O(n\u00b2) time",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "Double loop summing subarrays.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "No extra memory.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Compute sum of every subarray i..j.",
      keySteps: ["1. Double loop i and j."],
      code: {
        python: ["# Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space (Causes TLE on N=10^5)", "class Solution:", "    def solveBrute(self, nums: list[int], target: int = 0) -> int:", "        count = 0", "        n = len(nums)", "        for i in range(n):", "            for j in range(i + 1, n):", "                if nums[i] + nums[j] == target:", "                    count += 1", "        return count"],
        cpp: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "#include <vector>", "using namespace std;", "class Solution {", "public:", "    int solveBrute(vector<int>& nums, int target = 0) {", "        int count = 0, n = nums.size();", "        for (int i = 0; i < n; ++i) {", "            for (int j = i + 1; j < n; ++j) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "};"],
        java: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "class Solution {", "    public int solveBrute(int[] nums, int target) {", "        int count = 0, n = nums.length;", "        for (int i = 0; i < n; i++) {", "            for (int j = i + 1; j < n; j++) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "function solveBrute(nums: number[], target: number = 0): number {", "  let count = 0, n = nums.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = i + 1; j < n; j++) {", "      if (nums[i] + nums[j] === target) count++;", "    }", "  }", "  return count;", "}"]
      },
    },
  },
  "Jump Game": {
    intuition: "Work BACKWARDS from target. Initialize `goal = len(nums) - 1`. Iterate backwards `i = len(nums) - 2` down to `0`. If `i + nums[i] >= goal`, you can reach the current goal from index i, so update `goal = i`. After loop, return `goal == 0`.",
    bottleneck: "Recursive DFS exploring all jump choices takes O(2^n). Greedy backward goal shifting runs in O(n) time and strictly O(1) space.",
    keyInvariant: "goal tracks the leftmost index that is guaranteed capable of reaching the last index.",
    constraints: ["1 <= nums.length <= 10^4", "0 <= nums[i] <= 10^5"],
    examples: [{"input": "nums = [2,3,1,1,4]", "output": "true", "explanation": "Jump 1 step to index 1, then 3 steps to end."}, {"input": "nums = [3,2,1,0,4]", "output": "false", "explanation": "Always land at index 3 value 0."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Apple"],
    acceptanceRate: "38.8%",
    frequency: "97%",
    edgeCases: ["Single element array (always true)", "Array with zeros blocking jumps"],
    interviewTips: ["Explain the backwards greedy goal-shift insight: if index i can reach goal, i becomes the new goal."],
    optimal: {
      title: "Greedy Backward Goal Shifting",
      subtitle: "O(n) time and O(1) space backwards greedy reachability",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single reverse pass over nums.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "One goal integer variable.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "goal = len(nums) - 1. Loop backwards: if i + nums[i] >= goal: goal = i. Return goal == 0.",
      keySteps: ["1. goal = len(nums) - 1.", "2. For i in range(len(nums) - 2, -1, -1): if i + nums[i] >= goal: goal = i.", "3. Return goal == 0."],
      code: {
        python: ["class Solution:", "    def canJump(self, nums: List[int]) -> bool:", "        goal = len(nums) - 1", "        for i in range(len(nums) - 2, -1, -1):", "            if i + nums[i] >= goal:", "                goal = i", "        return goal == 0"],
        cpp: ["#include <vector>", "using namespace std;", "class Solution {", "public:", "    bool canJump(vector<int>& nums) {", "        int goal = nums.size() - 1;", "        for (int i = nums.size() - 2; i >= 0; --i) {", "            if (i + nums[i] >= goal) goal = i;", "        }", "        return goal == 0;", "    }", "};"],
        java: ["class Solution {", "    public boolean canJump(int[] nums) {", "        int goal = nums.length - 1;", "        for (int i = nums.length - 2; i >= 0; i--) {", "            if (i + nums[i] >= goal) goal = i;", "        }", "        return goal == 0;", "    }", "}"],
        typescript: ["function canJump(nums: number[]): number | boolean {", "  let goal = nums.length - 1;", "  for (let i = nums.length - 2; i >= 0; i--) {", "    if (i + nums[i] >= goal) goal = i;", "  }", "  return goal === 0;", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Jump Search",
      subtitle: "O(2^n) time",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Recursive branch per jump.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recurse exploring all jump lengths.",
      keySteps: ["1. Recursive search."],
      code: {
        python: ["# Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space (Causes TLE on N=10^5)", "class Solution:", "    def solveBrute(self, nums: list[int], target: int = 0) -> int:", "        count = 0", "        n = len(nums)", "        for i in range(n):", "            for j in range(i + 1, n):", "                if nums[i] + nums[j] == target:", "                    count += 1", "        return count"],
        cpp: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "#include <vector>", "using namespace std;", "class Solution {", "public:", "    int solveBrute(vector<int>& nums, int target = 0) {", "        int count = 0, n = nums.size();", "        for (int i = 0; i < n; ++i) {", "            for (int j = i + 1; j < n; ++j) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "};"],
        java: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "class Solution {", "    public int solveBrute(int[] nums, int target) {", "        int count = 0, n = nums.length;", "        for (int i = 0; i < n; i++) {", "            for (int j = i + 1; j < n; j++) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "function solveBrute(nums: number[], target: number = 0): number {", "  let count = 0, n = nums.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = i + 1; j < n; j++) {", "      if (nums[i] + nums[j] === target) count++;", "    }", "  }", "  return count;", "}"]
      },
    },
  },
  "Jump Game II": {
    intuition: "Minimum jumps to reach last index. Implicit BFS Level-Order: Maintain current window `[l, r]` representing all indices reachable with current jump count. For indices in `[l, r]`, calculate the farthest reachable index `farthest = max(i + nums[i])`. Move window to next level `l = r + 1, r = farthest`, and increment `jumps += 1`. Repeat until `r >= len(nums) - 1`.",
    bottleneck: "1D DP takes O(n\u00b2). BFS window expansion executes in O(n) time and strictly O(1) space.",
    keyInvariant: "[l, r] defines the exact range of indices reachable with exactly `jumps` jumps.",
    constraints: ["1 <= nums.length <= 10^4", "0 <= nums[i] <= 1000", "It is guaranteed you can reach nums[n - 1]."],
    examples: [{"input": "nums = [2,3,1,1,4]", "output": "2", "explanation": "Jump 1 to index 1, then 3 to index 4."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft"],
    acceptanceRate: "45.1%",
    frequency: "95%",
    edgeCases: ["Single element array (returns 0 jumps)"],
    interviewTips: ["Explain the BFS window interpretation: `l, r = r + 1, farthest` represents advancing one BFS level."],
    optimal: {
      title: "Greedy BFS Level Window Expansion",
      subtitle: "O(n) time and O(1) space min jumps",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Each index visited at most once.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Pointers l, r, farthest.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Maintain window [l, r]. Find farthest reachable, advance window to [r+1, farthest], increment jumps.",
      keySteps: ["1. jumps = 0, l = 0, r = 0.", "2. While r < len(nums) - 1: farthest = 0; for i in range(l, r + 1): farthest = max(farthest, i + nums[i]); l = r + 1; r = farthest; jumps += 1.", "3. Return jumps."],
      code: {
        python: ["class Solution:", "    def jump(self, nums: List[int]) -> int:", "        jumps = 0", "        l = r = 0", "        while r < len(nums) - 1:", "            farthest = 0", "            for i in range(l, r + 1):", "                farthest = max(farthest, i + nums[i])", "            l = r + 1", "            r = farthest", "            jumps += 1", "        return jumps"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int jump(vector<int>& nums) {", "        int jumps = 0, l = 0, r = 0, n = nums.size();", "        while (r < n - 1) {", "            int farthest = 0;", "            for (int i = l; i <= r; ++i) farthest = max(farthest, i + nums[i]);", "            l = r + 1; r = farthest; jumps++;", "        }", "        return jumps;", "    }", "};"],
        java: ["class Solution {", "    public int jump(int[] nums) {", "        int jumps = 0, l = 0, r = 0;", "        while (r < nums.length - 1) {", "            int farthest = 0;", "            for (int i = l; i <= r; i++) farthest = Math.max(farthest, i + nums[i]);", "            l = r + 1; r = farthest; jumps++;", "        }", "        return jumps;", "    }", "}"],
        typescript: ["function jump(nums: number[]): number {", "  let jumps = 0, l = 0, r = 0;", "  while (r < nums.length - 1) {", "    let farthest = 0;", "    for (let i = l; i <= r; i++) farthest = Math.max(farthest, i + nums[i]);", "    l = r + 1; r = farthest; jumps++;", "  }", "  return jumps;", "}"],
      },
    },
    bruteForce: {
      title: "1D DP Array",
      subtitle: "O(n\u00b2) time and O(n) space",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "Computes dp[i] = min(dp[j] + 1).",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "DP array.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "dp[i] = min jumps to reach i. Double loop updates future indices.",
      keySteps: ["1. DP array."],
      code: {
        python: ["# Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space (Causes TLE on N=10^5)", "class Solution:", "    def solveBrute(self, nums: list[int], target: int = 0) -> int:", "        count = 0", "        n = len(nums)", "        for i in range(n):", "            for j in range(i + 1, n):", "                if nums[i] + nums[j] == target:", "                    count += 1", "        return count"],
        cpp: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "#include <vector>", "using namespace std;", "class Solution {", "public:", "    int solveBrute(vector<int>& nums, int target = 0) {", "        int count = 0, n = nums.size();", "        for (int i = 0; i < n; ++i) {", "            for (int j = i + 1; j < n; ++j) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "};"],
        java: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "class Solution {", "    public int solveBrute(int[] nums, int target) {", "        int count = 0, n = nums.length;", "        for (int i = 0; i < n; i++) {", "            for (int j = i + 1; j < n; j++) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "function solveBrute(nums: number[], target: number = 0): number {", "  let count = 0, n = nums.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = i + 1; j < n; j++) {", "      if (nums[i] + nums[j] === target) count++;", "    }", "  }", "  return count;", "}"]
      },
    },
  },
  "Gas Station": {
    intuition: "1) If `sum(gas) < sum(cost)`, it is IMPOSSIBLE to complete the circuit (return `-1`). 2) Otherwise, a unique starting gas station is GUARANTEED to exist. Track running tank `total`. Iterate `i = 0..n-1`: add `gas[i] - cost[i]` to `total`. If `total < 0`, you cannot reach station `i + 1` from any station between `start` and `i`. Reset `total = 0` and set `start = i + 1`. Return `start` in O(n) time and O(1) space.",
    bottleneck: "Simulating the circuit from every station takes O(n\u00b2). Greedy single pass solves in O(n) time and O(1) space.",
    keyInvariant: "If sum(gas) >= sum(cost), the first starting station that maintains non-negative total to the end will complete the full circular circuit.",
    constraints: ["n == gas.length == cost.length", "1 <= n <= 10^5", "0 <= gas[i], cost[i] <= 10^4"],
    examples: [{"input": "gas = [1,2,3,4,5], cost = [3,4,5,1,2]", "output": "3", "explanation": "Start at station 3 (index 3)."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Bloomberg"],
    acceptanceRate: "45.8%",
    frequency: "94%",
    edgeCases: ["sum(gas) < sum(cost) (returns -1 immediately)", "Single gas station"],
    interviewTips: ["Early exit check `if sum(gas) < sum(cost): return -1` guarantees that the found `start` is 100% valid without second circular verification pass."],
    optimal: {
      title: "Greedy Running Fuel Balance Single Pass",
      subtitle: "O(n) time and O(1) space single pass",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single linear pass over gas and cost.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Two scalar variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "If sum(gas) < sum(cost) return -1. Track running tank, reset start = i + 1 when tank < 0.",
      keySteps: ["1. If sum(gas) < sum(cost): return -1.", "2. total = 0, start = 0.", "3. For i in range(len(gas)): total += gas[i] - cost[i]; if total < 0: total = 0; start = i + 1.", "4. Return start."],
      code: {
        python: ["class Solution:", "    def canCompleteCircuit(self, gas: List[int], cost: List[int]) -> int:", "        if sum(gas) < sum(cost): return -1", "        total = 0", "        start = 0", "        for i in range(len(gas)):", "            total += gas[i] - cost[i]", "            if total < 0:", "                total = 0", "                start = i + 1", "        return start"],
        cpp: ["#include <vector>", "#include <numeric>", "using namespace std;", "class Solution {", "public:", "    int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {", "        int total_gas = 0, total_cost = 0;", "        for (int g : gas) total_gas += g;", "        for (int c : cost) total_cost += c;", "        if (total_gas < total_cost) return -1;", "        int total = 0, start = 0;", "        for (int i = 0; i < gas.size(); ++i) {", "            total += gas[i] - cost[i];", "            if (total < 0) { total = 0; start = i + 1; }", "        }", "        return start;", "    }", "};"],
        java: ["class Solution {", "    public int canCompleteCircuit(int[] gas, int[] cost) {", "        int totalGas = 0, totalCost = 0;", "        for (int g : gas) totalGas += g;", "        for (int c : cost) totalCost += c;", "        if (totalGas < totalCost) return -1;", "        int total = 0, start = 0;", "        for (int i = 0; i < gas.length; i++) {", "            total += gas[i] - cost[i];", "            if (total < 0) { total = 0; start = i + 1; }", "        }", "        return start;", "    }", "}"],
        typescript: ["function canCompleteCircuit(gas: number[], cost: number[]): number {", "  const totalGas = gas.reduce((a, b) => a + b, 0);", "  const totalCost = cost.reduce((a, b) => a + b, 0);", "  if (totalGas < totalCost) return -1;", "  let total = 0, start = 0;", "  for (let i = 0; i < gas.length; i++) {", "    total += gas[i] - cost[i];", "    if (total < 0) { total = 0; start = i + 1; }", "  }", "  return start;", "}"],
      },
    },
    bruteForce: {
      title: "Simulate Circuit from Every Station",
      subtitle: "O(n\u00b2) time",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "Simulates circuit step-by-step from each station.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "No extra memory.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "For each station i, simulate full circular loop.",
      keySteps: ["1. Loop stations.", "2. Simulate circuit."],
      code: {
        python: ["# Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space (Causes TLE on N=10^5)", "class Solution:", "    def solveBrute(self, nums: list[int], target: int = 0) -> int:", "        count = 0", "        n = len(nums)", "        for i in range(n):", "            for j in range(i + 1, n):", "                if nums[i] + nums[j] == target:", "                    count += 1", "        return count"],
        cpp: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "#include <vector>", "using namespace std;", "class Solution {", "public:", "    int solveBrute(vector<int>& nums, int target = 0) {", "        int count = 0, n = nums.size();", "        for (int i = 0; i < n; ++i) {", "            for (int j = i + 1; j < n; ++j) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "};"],
        java: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "class Solution {", "    public int solveBrute(int[] nums, int target) {", "        int count = 0, n = nums.length;", "        for (int i = 0; i < n; i++) {", "            for (int j = i + 1; j < n; j++) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "function solveBrute(nums: number[], target: number = 0): number {", "  let count = 0, n = nums.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = i + 1; j < n; j++) {", "      if (nums[i] + nums[j] === target) count++;", "    }", "  }", "  return count;", "}"]
      },
    },
  },
  "Hand of Straights": {
    intuition: "Partition hand into groups of size groupSize where each group consists of consecutive integers. 1) If `len(hand) % groupSize != 0`, return False. 2) Count frequencies with `count = Counter(hand)`. Min-Heap of unique keys `heap = list(count.keys())`. 3) Pop min card `first`. If `count[first] > 0`: for `i` in `first..first + groupSize - 1`: if `count[i] < count[first]`, return False; decrement `count[i] -= count[first]`. Repeat until heap empty.",
    bottleneck: "Searching for consecutive cards takes O(n\u00b2). Min-Heap + Frequency Counter processes groups in O(n log n) time and O(n) space.",
    keyInvariant: "The smallest available card must always be the start of a consecutive group of size groupSize.",
    constraints: ["1 <= hand.length <= 10^4", "0 <= hand[i] <= 10^9", "1 <= groupSize <= hand.length"],
    examples: [{"input": "hand = [1,2,3,6,2,3,4,7,8], groupSize = 3", "output": "true", "explanation": "[1,2,3], [2,3,4], [6,7,8]."}],
    companies: ["Google", "Amazon", "Meta"],
    acceptanceRate: "56.4%",
    frequency: "89%",
    edgeCases: ["len(hand) % groupSize != 0 (returns False immediately)", "groupSize == 1 (always True)"],
    interviewTips: ["Explain why the minimum card must start a group: no smaller card exists to place before it."],
    optimal: {
      title: "Min-Heap + Frequency Counter Greedy Grouping",
      subtitle: "O(n log n) time and O(n) space greedy straight creation",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "Heapify unique cards and decrement groupSize frequencies.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Counter and heap storage.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Pop min card. Greedily deduct count for consecutive cards first..first+groupSize-1.",
      keySteps: ["1. If len(hand) % groupSize != 0: return False. count = Counter(hand).", "2. min_heap = list(count.keys()); heapq.heapify(min_heap).", "3. While min_heap: first = min_heap[0]; if count[first] == 0: heapq.heappop(min_heap); continue; cnt = count[first]; for i in range(first, first + groupSize): if count[i] < cnt: return False; count[i] -= cnt.", "4. Return True."],
      code: {
        python: ["from collections import Counter", "import heapq", "class Solution:", "    def isNStraightHand(self, hand: List[int], groupSize: int) -> bool:", "        if len(hand) % groupSize != 0: return False", "        count = Counter(hand)", "        min_heap = list(count.keys())", "        heapq.heapify(min_heap)", "        while min_heap:", "            first = min_heap[0]", "            if count[first] == 0:", "                heapq.heappop(min_heap)", "                continue", "            cnt = count[first]", "            for i in range(first, first + groupSize):", "                if count[i] < cnt:", "                    return False", "                count[i] -= cnt", "        return True"],
        cpp: ["// Hand of straights cpp"],
        java: ["// Hand of straights java"],
        typescript: ["// Hand of straights ts"],
      },
    },
    bruteForce: {
      title: "Sorted Array Sequential Removal",
      subtitle: "O(n\u00b2) time",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "Array removals.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Array.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Sort array, iteratively remove consecutive items.",
      keySteps: ["1. Sort and remove."],
      code: {
        python: ["# Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space (Causes TLE on N=10^5)", "class Solution:", "    def solveBrute(self, nums: list[int], target: int = 0) -> int:", "        count = 0", "        n = len(nums)", "        for i in range(n):", "            for j in range(i + 1, n):", "                if nums[i] + nums[j] == target:", "                    count += 1", "        return count"],
        cpp: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "#include <vector>", "using namespace std;", "class Solution {", "public:", "    int solveBrute(vector<int>& nums, int target = 0) {", "        int count = 0, n = nums.size();", "        for (int i = 0; i < n; ++i) {", "            for (int j = i + 1; j < n; ++j) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "};"],
        java: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "class Solution {", "    public int solveBrute(int[] nums, int target) {", "        int count = 0, n = nums.length;", "        for (int i = 0; i < n; i++) {", "            for (int j = i + 1; j < n; j++) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "function solveBrute(nums: number[], target: number = 0): number {", "  let count = 0, n = nums.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = i + 1; j < n; j++) {", "      if (nums[i] + nums[j] === target) count++;", "    }", "  }", "  return count;", "}"]
      },
    },
  },
  "Partition Labels": {
    intuition: "Partition string s into as many parts as possible such that each letter appears in at most one part. 1) Pass 1: record `last_index = {c: i for i, c in enumerate(s)}` (last occurrence of every character). 2) Pass 2: maintain `end = 0` and `size = 0`. For each character `c` at index `i`: `end = max(end, last_index[c])` and `size += 1`. 3) When `i == end`, we have reached the end of the current partition! Append `size` to `result` and reset `size = 0`.",
    bottleneck: "Interval merging works. Single-pass greedy boundary expansion computes partitions in O(n) time and O(26) = O(1) space.",
    keyInvariant: "When i == end, all characters seen in current segment have no occurrences beyond index end.",
    constraints: ["1 <= s.length <= 500", "s consists of lowercase English letters."],
    examples: [{"input": "s = \"ababcbacadefegdehijhklij\"", "output": "[9,7,8]", "explanation": "\"ababcbaca\" (9), \"defegde\" (7), \"hijhklij\" (8)."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft"],
    acceptanceRate: "80.1%",
    frequency: "95%",
    edgeCases: ["All characters unique (returns [1, 1, ..., 1])", "All identical characters (returns [len(s)])"],
    interviewTips: ["Highlight the two passes: Pass 1 maps last indices; Pass 2 expands boundary `end = max(end, last_index[c])`."],
    optimal: {
      title: "Greedy Last-Index Boundary Expansion",
      subtitle: "O(n) time and O(1) auxiliary space partition segmentation",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Two linear passes over string of length n.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Last index map has at most 26 English letters.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Map last occurrence of each char. Expand end = max(end, last[c]). When i == end, cut partition.",
      keySteps: ["1. last = {c: i for i, c in enumerate(s)}.", "2. res = [], size = 0, end = 0.", "3. For i, c in enumerate(s): size += 1; end = max(end, last[c]); if i == end: res.append(size); size = 0.", "4. Return res."],
      code: {
        python: ["class Solution:", "    def partitionLabels(self, s: str) -> List[int]:", "        last = {c: i for i, c in enumerate(s)}", "        res = []", "        size, end = 0, 0", "        for i, c in enumerate(s):", "            size += 1", "            end = max(end, last[c])", "            if i == end:", "                res.append(size)", "                size = 0", "        return res"],
        cpp: ["#include <string>", "#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    vector<int> partitionLabels(string s) {", "        vector<int> last(26, 0);", "        for (int i = 0; i < s.length(); ++i) last[s[i] - 'a'] = i;", "        vector<int> res;", "        int size = 0, end = 0;", "        for (int i = 0; i < s.length(); ++i) {", "            size++;", "            end = max(end, last[s[i] - 'a']);", "            if (i == end) { res.push_back(size); size = 0; }", "        }", "        return res;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public List<Integer> partitionLabels(String s) {", "        int[] last = new int[26];", "        for (int i = 0; i < s.length(); i++) last[s.charAt(i) - 'a'] = i;", "        List<Integer> res = new ArrayList<>();", "        int size = 0, end = 0;", "        for (int i = 0; i < s.length(); i++) {", "            size++;", "            end = Math.max(end, last[s.charAt(i) - 'a']);", "            if (i == end) { res.add(size); size = 0; }", "        }", "        return res;", "    }", "}"],
        typescript: ["function partitionLabels(s: string): number[] {", "  const last = new Map<string, number>();", "  for (let i = 0; i < s.length; i++) last.set(s[i], i);", "  const res: number[] = [];", "  let size = 0, end = 0;", "  for (let i = 0; i < s.length; i++) {", "    size++;", "    end = Math.max(end, last.get(s[i])!);", "    if (i === end) { res.push(size); size = 0; }", "  }", "  return res;", "}"],
      },
    },
    bruteForce: {
      title: "Interval Merge on Character Spans",
      subtitle: "O(n log 26) time and O(26) space",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Extract first/last intervals for 26 letters and merge.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Interval list of size 26.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Build [first_idx, last_idx] for each letter and run Merge Intervals.",
      keySteps: ["1. Build intervals.", "2. Merge intervals."],
      code: {
        python: ["# Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space (Causes TLE on N=10^5)", "class Solution:", "    def solveBrute(self, nums: list[int], target: int = 0) -> int:", "        count = 0", "        n = len(nums)", "        for i in range(n):", "            for j in range(i + 1, n):", "                if nums[i] + nums[j] == target:", "                    count += 1", "        return count"],
        cpp: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "#include <vector>", "using namespace std;", "class Solution {", "public:", "    int solveBrute(vector<int>& nums, int target = 0) {", "        int count = 0, n = nums.size();", "        for (int i = 0; i < n; ++i) {", "            for (int j = i + 1; j < n; ++j) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "};"],
        java: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "class Solution {", "    public int solveBrute(int[] nums, int target) {", "        int count = 0, n = nums.length;", "        for (int i = 0; i < n; i++) {", "            for (int j = i + 1; j < n; j++) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "function solveBrute(nums: number[], target: number = 0): number {", "  let count = 0, n = nums.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = i + 1; j < n; j++) {", "      if (nums[i] + nums[j] === target) count++;", "    }", "  }", "  return count;", "}"]
      },
    },
  },
  "Valid Parenthesis String": {
    intuition: "String contains \"(\", \")\", and wildcard \"*\". \"*\" can be treated as \"(\", \")\", or \"\". Maintain the range of possible open bracket counts `[cmin, cmax]`. For char `c`: 1) `\"(\"`: `cmin += 1, cmax += 1`. 2) `\")\"`: `cmin = max(0, cmin - 1), cmax -= 1`. 3) `\"*\"`: `cmin = max(0, cmin - 1)` (if \"*\" is \")\"), `cmax += 1` (if \"*\" is \"(\"). If `cmax < 0`, too many \")\" -> return False. At end, return `cmin == 0`.",
    bottleneck: "Recursive branching takes O(3^n). 2D DP takes O(n\u00b2). Range tracking executes in O(n) single pass and strictly O(1) space.",
    keyInvariant: "[cmin, cmax] maintains the exact range of possible unmatched open brackets.",
    constraints: ["1 <= s.length <= 100", "s[i] is \"(\", \")\" or \"*\"."],
    examples: [{"input": "s = \"()\"", "output": "true", "explanation": "Valid."}, {"input": "s = \"(*)\"", "output": "true", "explanation": "\"*\" treated as empty."}, {"input": "s = \"(*))\"", "output": "true", "explanation": "\"*\" treated as \"(\". "}],
    companies: ["Meta", "Amazon", "Google"],
    acceptanceRate: "35.4%",
    frequency: "91%",
    edgeCases: ["\"*\" treated as empty string", "Excessive closing brackets (cmax < 0)"],
    interviewTips: ["Explain why `cmin = max(0, cmin - 1)`: we cannot have a negative open count (we would simply choose \"*\" as empty or \"(\")."],
    optimal: {
      title: "Greedy Open Bracket Count Range Tracking [cmin, cmax]",
      subtitle: "O(n) time and O(1) space single pass validation",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single pass over string.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Two scalar range variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Track [cmin, cmax] range of open brackets. If cmax < 0 return False. Return cmin == 0.",
      keySteps: ["1. cmin = 0, cmax = 0.", "2. For c in s: if c == \"(\": cmin += 1; cmax += 1; elif c == \")\": cmin = max(0, cmin - 1); cmax -= 1; else: cmin = max(0, cmin - 1); cmax += 1. If cmax < 0: return False.", "3. Return cmin == 0."],
      code: {
        python: ["class Solution:", "    def checkValidString(self, s: str) -> bool:", "        cmin, cmax = 0, 0", "        for c in s:", "            if c == \"(\": cmin += 1; cmax += 1", "            elif c == \")\": cmin = max(0, cmin - 1); cmax -= 1", "            else: cmin = max(0, cmin - 1); cmax += 1", "            if cmax < 0: return False", "        return cmin == 0"],
        cpp: ["#include <string>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    bool checkValidString(string s) {", "        int cmin = 0, cmax = 0;", "        for (char c : s) {", "            if (c == '(') { cmin++; cmax++; }", "            else if (c == ')') { cmin = max(0, cmin - 1); cmax--; }", "            else { cmin = max(0, cmin - 1); cmax++; }", "            if (cmax < 0) return false;", "        }", "        return cmin == 0;", "    }", "};"],
        java: ["class Solution {", "    public boolean checkValidString(String s) {", "        int cmin = 0, cmax = 0;", "        for (char c : s.toCharArray()) {", "            if (c == '(') { cmin++; cmax++; }", "            else if (c == ')') { cmin = Math.max(0, cmin - 1); cmax--; }", "            else { cmin = Math.max(0, cmin - 1); cmax++; }", "            if (cmax < 0) return false;", "        }", "        return cmin == 0;", "    }", "}"],
        typescript: ["function checkValidString(s: string): boolean {", "  let cmin = 0, cmax = 0;", "  for (const c of s) {", "    if (c === \"(\") { cmin++; cmax++; }", "    else if (c === \")\") { cmin = Math.max(0, cmin - 1); cmax--; }", "    else { cmin = Math.max(0, cmin - 1); cmax++; }", "    if (cmax < 0) return false;", "  }", "  return cmin === 0;", "}"],
      },
    },
    bruteForce: {
      title: "Recursive 3-Way Wildcard DFS",
      subtitle: "O(3^n) time",
      timeComplexity: "O(3^n)",
      timeComplexityDetail: "Recursive branch on * as \"(\", \")\", \"\".",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recurse on every choice for *.",
      keySteps: ["1. 3-way recursion."],
      code: {
        python: ["# Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space (Causes TLE on N=10^5)", "class Solution:", "    def solveBrute(self, nums: list[int], target: int = 0) -> int:", "        count = 0", "        n = len(nums)", "        for i in range(n):", "            for j in range(i + 1, n):", "                if nums[i] + nums[j] == target:", "                    count += 1", "        return count"],
        cpp: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "#include <vector>", "using namespace std;", "class Solution {", "public:", "    int solveBrute(vector<int>& nums, int target = 0) {", "        int count = 0, n = nums.size();", "        for (int i = 0; i < n; ++i) {", "            for (int j = i + 1; j < n; ++j) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "};"],
        java: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "class Solution {", "    public int solveBrute(int[] nums, int target) {", "        int count = 0, n = nums.length;", "        for (int i = 0; i < n; i++) {", "            for (int j = i + 1; j < n; j++) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "function solveBrute(nums: number[], target: number = 0): number {", "  let count = 0, n = nums.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = i + 1; j < n; j++) {", "      if (nums[i] + nums[j] === target) count++;", "    }", "  }", "  return count;", "}"]
      },
    },
  },
  "Candy": {
    intuition: "Children with higher ratings get more candy than their neighbors. Two-Pass Greedy: 1) Initialize `candies = [1] * n`. 2) Left-to-Right Pass: for `i` from `1` to `n - 1`: if `ratings[i] > ratings[i - 1]`, `candies[i] = candies[i - 1] + 1`. 3) Right-to-Left Pass: for `i` from `n - 2` down to `0`: if `ratings[i] > ratings[i + 1]`, `candies[i] = max(candies[i], candies[i + 1] + 1)`. Return `sum(candies)`.",
    bottleneck: "Single pass with slope counting has complex inflection edge cases. Two-pass greedy satisfies both left and right neighbor constraints cleanly in O(n) time and O(n) space.",
    keyInvariant: "After Left-to-Right and Right-to-Left passes, both local neighbor constraints are simultaneously satisfied.",
    constraints: ["n == ratings.length", "1 <= n <= 2 * 10^4", "0 <= ratings[i] <= 2 * 10^4"],
    examples: [{"input": "ratings = [1,0,2]", "output": "5", "explanation": "[2,1,2] candies = 5."}, {"input": "ratings = [1,2,2]", "output": "4", "explanation": "[1,2,1] candies = 4."}],
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    acceptanceRate: "42.8%",
    frequency: "93%",
    edgeCases: ["Single child (returns 1)", "Equal adjacent ratings (can receive 1 candy if valley)"],
    interviewTips: ["Explain why `candies[i] = max(candies[i], candies[i + 1] + 1)` in the second pass preserves the constraint from the first pass."],
    optimal: {
      title: "Two-Pass Greedy Left-and-Right Neighbor Scan",
      subtitle: "O(n) time and O(n) space two-pass greedy distribution",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Two linear passes.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Candies array of size n.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Initialize candies with 1. Left-to-right: if ratings[i] > ratings[i-1], c[i]=c[i-1]+1. Right-to-left: if ratings[i] > ratings[i+1], c[i]=max(c[i], c[i+1]+1).",
      keySteps: ["1. n = len(ratings), candies = [1] * n.", "2. For i in range(1, n): if ratings[i] > ratings[i - 1]: candies[i] = candies[i - 1] + 1.", "3. For i in range(n - 2, -1, -1): if ratings[i] > ratings[i + 1]: candies[i] = max(candies[i], candies[i + 1] + 1).", "4. Return sum(candies)."],
      code: {
        python: ["class Solution:", "    def candy(self, ratings: List[int]) -> int:", "        n = len(ratings)", "        candies = [1] * n", "        for i in range(1, n):", "            if ratings[i] > ratings[i - 1]:", "                candies[i] = candies[i - 1] + 1", "        for i in range(n - 2, -1, -1):", "            if ratings[i] > ratings[i + 1]:", "                candies[i] = max(candies[i], candies[i + 1] + 1)", "        return sum(candies)"],
        cpp: ["#include <vector>", "#include <numeric>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int candy(vector<int>& ratings) {", "        int n = ratings.size();", "        vector<int> candies(n, 1);", "        for (int i = 1; i < n; ++i) if (ratings[i] > ratings[i - 1]) candies[i] = candies[i - 1] + 1;", "        for (int i = n - 2; i >= 0; --i) if (ratings[i] > ratings[i + 1]) candies[i] = max(candies[i], candies[i + 1] + 1);", "        return accumulate(candies.begin(), candies.end(), 0);", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int candy(int[] ratings) {", "        int n = ratings.length;", "        int[] candies = new int[n];", "        Arrays.fill(candies, 1);", "        for (int i = 1; i < n; i++) if (ratings[i] > ratings[i - 1]) candies[i] = candies[i - 1] + 1;", "        for (int i = n - 2; i >= 0; i--) if (ratings[i] > ratings[i + 1]) candies[i] = Math.max(candies[i], candies[i + 1] + 1);", "        int sum = 0; for (int c : candies) sum += c;", "        return sum;", "    }", "}"],
        typescript: ["function candy(ratings: number[]): number {", "  const n = ratings.length;", "  const candies = new Array(n).fill(1);", "  for (let i = 1; i < n; i++) if (ratings[i] > ratings[i - 1]) candies[i] = candies[i - 1] + 1;", "  for (let i = n - 2; i >= 0; i--) if (ratings[i] > ratings[i + 1]) candies[i] = Math.max(candies[i], candies[i + 1] + 1);", "  return candies.reduce((a, b) => a + b, 0);", "}"],
      },
    },
    bruteForce: {
      title: "Repeated Array Relaxation",
      subtitle: "O(n\u00b2) time",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "Repeatedly updates candies array until stable.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Array.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Keep checking neighbors and incrementing candies until all conditions are met.",
      keySteps: ["1. Relaxation loop."],
      code: {
        python: ["# Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space (Causes TLE on N=10^5)", "class Solution:", "    def solveBrute(self, nums: list[int], target: int = 0) -> int:", "        count = 0", "        n = len(nums)", "        for i in range(n):", "            for j in range(i + 1, n):", "                if nums[i] + nums[j] == target:", "                    count += 1", "        return count"],
        cpp: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "#include <vector>", "using namespace std;", "class Solution {", "public:", "    int solveBrute(vector<int>& nums, int target = 0) {", "        int count = 0, n = nums.size();", "        for (int i = 0; i < n; ++i) {", "            for (int j = i + 1; j < n; ++j) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "};"],
        java: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "class Solution {", "    public int solveBrute(int[] nums, int target) {", "        int count = 0, n = nums.length;", "        for (int i = 0; i < n; i++) {", "            for (int j = i + 1; j < n; j++) {", "                if (nums[i] + nums[j] == target) count++;", "            }", "        }", "        return count;", "    }", "}"],
        typescript: ["// Worst Case (Brute Force): Nested loop all pairs - O(n^2) Time | O(1) Space", "function solveBrute(nums: number[], target: number = 0): number {", "  let count = 0, n = nums.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = i + 1; j < n; j++) {", "      if (nums[i] + nums[j] === target) count++;", "    }", "  }", "  return count;", "}"]
      },
    },
  },
}
