import { DetailedProblemData } from '../leetcodeSolutions'

export const intervalSolutions: Record<string, DetailedProblemData> = {
  "Insert Interval": {
    intuition: "Insert `newInterval = [start, end]` into non-overlapping intervals sorted by start time. 1) Before overlap: while `intervals[i][1] < newInterval[0]`, append `intervals[i]` to `res`. 2) During overlap: while `intervals[i][0] <= newInterval[1]`, merge `newInterval = [min(newInterval[0], intervals[i][0]), max(newInterval[1], intervals[i][1])]`. Append merged `newInterval`. 3) After overlap: append remaining intervals `intervals[i:]`.",
    bottleneck: "Inserting and then sorting takes O(n log n). Single-pass 3-stage linear insertion runs in O(n) time and O(n) space.",
    keyInvariant: "Intervals before newInterval strictly end before newInterval begins; intervals during overlap are merged into single interval.",
    constraints: ["0 <= intervals.length <= 10^4", "intervals[i].length == 2", "0 <= starti <= endi <= 10^5", "intervals is sorted by starti."],
    examples: [{"input": "intervals = [[1,3],[6,9]], newInterval = [2,5]", "output": "[[1,5],[6,9]]", "explanation": "2,5 merged with 1,3 -> 1,5."}],
    companies: ["Google", "Amazon", "Meta", "Microsoft"],
    acceptanceRate: "40.2%",
    frequency: "95%",
    edgeCases: ["Empty intervals array (returns [newInterval])", "newInterval inserted at very beginning or very end"],
    interviewTips: ["Walk through the 3 phases: left non-overlapping, overlapping merge, right non-overlapping."],
    optimal: {
      title: "Three-Phase Single Pass Interval Merge",
      subtitle: "O(n) time and O(n) space single pass insertion",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Single linear pass over intervals.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Output result array.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Add intervals ending before newInterval. Merge all overlapping intervals. Add all intervals starting after newInterval.",
      keySteps: ["1. res = [], i = 0, n = len(intervals).", "2. Phase 1: while i < n and intervals[i][1] < newInterval[0]: res.append(intervals[i]); i += 1.", "3. Phase 2: while i < n and intervals[i][0] <= newInterval[1]: newInterval = [min(newInterval[0], intervals[i][0]), max(newInterval[1], intervals[i][1])]; i += 1. res.append(newInterval).", "4. Phase 3: while i < n: res.append(intervals[i]); i += 1.", "5. Return res."],
      code: {
        python: ["class Solution:", "    def insert(self, intervals: List[List[int]], newInterval: List[int]) -> List[List[int]]:", "        res = []", "        i, n = 0, len(intervals)", "        while i < n and intervals[i][1] < newInterval[0]:", "            res.append(intervals[i])", "            i += 1", "        while i < n and intervals[i][0] <= newInterval[1]:", "            newInterval = [min(newInterval[0], intervals[i][0]), max(newInterval[1], intervals[i][1])]", "            i += 1", "        res.append(newInterval)", "        while i < n:", "            res.append(intervals[i])", "            i += 1", "        return res"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    vector<vector<int>> insert(vector<vector<int>>& intervals, vector<int>& newInterval) {", "        vector<vector<int>> res;", "        int i = 0, n = intervals.size();", "        while (i < n && intervals[i][1] < newInterval[0]) res.push_back(intervals[i++]);", "        while (i < n && intervals[i][0] <= newInterval[1]) {", "            newInterval[0] = min(newInterval[0], intervals[i][0]);", "            newInterval[1] = max(newInterval[1], intervals[i][1]);", "            i++;", "        }", "        res.push_back(newInterval);", "        while (i < n) res.push_back(intervals[i++]);", "        return res;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int[][] insert(int[][] intervals, int[] newInterval) {", "        List<int[]> res = new ArrayList<>();", "        int i = 0, n = intervals.length;", "        while (i < n && intervals[i][1] < newInterval[0]) res.add(intervals[i++]);", "        while (i < n && intervals[i][0] <= newInterval[1]) {", "            newInterval[0] = Math.min(newInterval[0], intervals[i][0]);", "            newInterval[1] = Math.max(newInterval[1], intervals[i][1]);", "            i++;", "        }", "        res.add(newInterval);", "        while (i < n) res.add(intervals[i++]);", "        return res.toArray(new int[res.size()][]);", "    }", "}"],
        typescript: ["function insert(intervals: number[][], newInterval: number[]): number[][] {", "  const res: number[][] = [];", "  let i = 0, n = intervals.length;", "  while (i < n && intervals[i][1] < newInterval[0]) res.push(intervals[i++]);", "  while (i < n && intervals[i][0] <= newInterval[1]) {", "    newInterval[0] = Math.min(newInterval[0], intervals[i][0]);", "    newInterval[1] = Math.max(newInterval[1], intervals[i][1]);", "    i++;", "  }", "  res.push(newInterval);", "  while (i < n) res.push(intervals[i++]);", "  return res;", "}"],
      },
    },
    bruteForce: {
      title: "Append and Merge Intervals",
      subtitle: "O(n log n) time",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "Sorts all intervals.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Array.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Append newInterval, sort by start time, merge overlapping.",
      keySteps: ["1. Append.", "2. Sort and merge."],
      code: {
        python: ["# Append and sort"],
        cpp: ["// Sort"],
        java: ["// Sort"],
        typescript: ["// Sort"],
      },
    },
  },
  "Merge Intervals": {
    intuition: "Merge all overlapping intervals. 1) SORT intervals by start time: `intervals.sort(key=lambda x: x[0])`. 2) Initialize `res = [intervals[0]]`. 3) Iterate through remaining intervals: let `last = res[-1]`. If current interval start `<= last[1]` (overlapping), merge by updating `last[1] = max(last[1], current[1])`. Otherwise (non-overlapping), append current interval to `res`.",
    bottleneck: "Without sorting, comparing all pairs takes O(n\u00b2). Sorting by start time groups overlapping intervals consecutively in O(n log n) time and O(n) space.",
    keyInvariant: "Sorting by start time ensures each interval only needs to be compared with the immediately preceding merged interval.",
    constraints: ["1 <= intervals.length <= 10^4", "intervals[i].length == 2", "0 <= starti <= endi <= 10^4"],
    examples: [{"input": "intervals = [[1,3],[2,6],[8,10],[15,18]]", "output": "[[1,6],[8,10],[15,18]]", "explanation": "[1,3] and [2,6] merge into [1,6]."}],
    companies: ["Amazon", "Meta", "Google", "Microsoft", "Bloomberg", "Apple"],
    acceptanceRate: "47.1%",
    frequency: "99%",
    edgeCases: ["Single interval", "All intervals overlap into one giant interval", "No overlapping intervals"],
    interviewTips: ["State the overlap condition: `if current.start <= prev.end: prev.end = max(prev.end, current.end)`."],
    optimal: {
      title: "Sort by Start Time + Single Pass Merge",
      subtitle: "O(n log n) time and O(n) space interval merge",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "Sorting n intervals takes O(n log n); merge pass takes O(n).",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Output result array.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Sort by start time. If current.start <= res[-1].end: merge. Else append to res.",
      keySteps: ["1. intervals.sort(key=lambda x: x[0]).", "2. res = [intervals[0]].", "3. For start, end in intervals[1:]: last_end = res[-1][1]; if start <= last_end: res[-1][1] = max(last_end, end); else: res.append([start, end]).", "4. Return res."],
      code: {
        python: ["class Solution:", "    def merge(self, intervals: List[List[int]]) -> List[List[int]]:", "        intervals.sort(key=lambda x: x[0])", "        res = [intervals[0]]", "        for start, end in intervals[1:]:", "            last_end = res[-1][1]", "            if start <= last_end:", "                res[-1][1] = max(last_end, end)", "            else:", "                res.append([start, end])", "        return res"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    vector<vector<int>> merge(vector<vector<int>>& intervals) {", "        sort(intervals.begin(), intervals.end());", "        vector<vector<int>> res = {intervals[0]};", "        for (size_t i = 1; i < intervals.size(); ++i) {", "            if (intervals[i][0] <= res.back()[1]) {", "                res.back()[1] = max(res.back()[1], intervals[i][1]);", "            } else {", "                res.push_back(intervals[i]);", "            }", "        }", "        return res;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int[][] merge(int[][] intervals) {", "        Arrays.sort(intervals, (a, b) -> Integer.compare(a[0], b[0]));", "        List<int[]> res = new ArrayList<>();", "        res.add(intervals[0]);", "        for (int i = 1; i < intervals.length; i++) {", "            int[] last = res.get(res.size() - 1);", "            if (intervals[i][0] <= last[1]) {", "                last[1] = Math.max(last[1], intervals[i][1]);", "            } else {", "                res.add(intervals[i]);", "            }", "        }", "        return res.toArray(new int[res.size()][]);", "    }", "}"],
        typescript: ["function merge(intervals: number[][]): number[][] {", "  intervals.sort((a, b) => a[0] - b[0]);", "  const res: number[][] = [intervals[0]];", "  for (let i = 1; i < intervals.length; i++) {", "    const last = res[res.length - 1];", "    if (intervals[i][0] <= last[1]) {", "      last[1] = Math.max(last[1], intervals[i][1]);", "    } else {", "      res.push(intervals[i]);", "    }", "  }", "  return res;", "}"],
      },
    },
    bruteForce: {
      title: "Graph Connected Components Merge",
      subtitle: "O(n\u00b2) time and O(n\u00b2) space",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "Builds overlap graph and finds components.",
      spaceComplexity: "O(n\u00b2)",
      spaceComplexityDetail: "Graph.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Build graph where overlapping intervals have edges, merge components.",
      keySteps: ["1. Overlap graph.", "2. Merge connected components."],
      code: {
        python: ["# Graph merge"],
        cpp: ["// Graph"],
        java: ["// Graph"],
        typescript: ["// Graph"],
      },
    },
  },
  "Non-overlapping Intervals": {
    intuition: "Find minimum number of intervals to remove to make remainder non-overlapping (Interval Scheduling Problem). 1) SORT intervals by END TIME (or start time). 2) Maintain `prev_end = -inf` and `remove_count = 0`. 3) For each interval `[start, end]`: if `start < prev_end` (overlapping), we must remove one; greedily choose to keep the one with the smaller end time (`prev_end = min(prev_end, end)`) and increment `remove_count += 1`. Otherwise (non-overlapping), update `prev_end = end`. Return `remove_count`.",
    bottleneck: "Interval scheduling algorithm proves that keeping the interval that ends earliest maximizes available room for remaining intervals in O(n log n) time and O(1) space.",
    keyInvariant: "Greedily keeping the interval with smaller end time leaves the maximum possible space for future intervals.",
    constraints: ["1 <= intervals.length <= 10^5", "intervals[i].length == 2", "-5 * 10^4 <= starti < endi <= 5 * 10^4"],
    examples: [{"input": "intervals = [[1,2],[2,3],[3,4],[1,3]]", "output": "1", "explanation": "Remove [1,3]."}, {"input": "intervals = [[1,2],[1,2],[1,2]]", "output": "2", "explanation": "Remove 2 duplicates."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft"],
    acceptanceRate: "53.1%",
    frequency: "92%",
    edgeCases: ["Touching intervals (e.g. [1,2] and [2,3] do NOT overlap, 0 removals)"],
    interviewTips: ["Contrast with Merge Intervals: here we remove/skip overlapping intervals, keeping the earliest ending one."],
    optimal: {
      title: "Greedy Interval Scheduling (Earliest End Time)",
      subtitle: "O(n log n) time and O(1) space interval removal",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "Sorting n intervals.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "In-place pointers.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Sort intervals by start. If overlap: remove_count += 1, keep min(prev_end, end). Else prev_end = end.",
      keySteps: ["1. intervals.sort(key=lambda x: x[0]).", "2. count = 0, prev_end = intervals[0][1].", "3. For start, end in intervals[1:]: if start < prev_end: count += 1; prev_end = min(prev_end, end); else: prev_end = end.", "4. Return count."],
      code: {
        python: ["class Solution:", "    def eraseOverlapIntervals(self, intervals: List[List[int]]) -> int:", "        intervals.sort(key=lambda x: x[0])", "        count = 0", "        prev_end = intervals[0][1]", "        for start, end in intervals[1:]:", "            if start < prev_end:", "                count += 1", "                prev_end = min(prev_end, end)", "            else:", "                prev_end = end", "        return count"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int eraseOverlapIntervals(vector<vector<int>>& intervals) {", "        sort(intervals.begin(), intervals.end());", "        int count = 0, prev_end = intervals[0][1];", "        for (size_t i = 1; i < intervals.size(); ++i) {", "            if (intervals[i][0] < prev_end) {", "                count++;", "                prev_end = min(prev_end, intervals[i][1]);", "            } else {", "                prev_end = intervals[i][1];", "            }", "        }", "        return count;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int eraseOverlapIntervals(int[][] intervals) {", "        Arrays.sort(intervals, (a, b) -> Integer.compare(a[0], b[0]));", "        int count = 0, prevEnd = intervals[0][1];", "        for (int i = 1; i < intervals.length; i++) {", "            if (intervals[i][0] < prevEnd) {", "                count++;", "                prevEnd = Math.min(prevEnd, intervals[i][1]);", "            } else {", "                prevEnd = intervals[i][1];", "            }", "        }", "        return count;", "    }", "}"],
        typescript: ["function eraseOverlapIntervals(intervals: number[][]): number {", "  intervals.sort((a, b) => a[0] - b[0]);", "  let count = 0, prevEnd = intervals[0][1];", "  for (let i = 1; i < intervals.length; i++) {", "    if (intervals[i][0] < prevEnd) {", "      count++;", "      prevEnd = Math.min(prevEnd, intervals[i][1]);", "    } else {", "      prevEnd = intervals[i][1];", "    }", "  }", "  return count;", "}"],
      },
    },
    bruteForce: {
      title: "Recursive Inclusion Search",
      subtitle: "O(2^n) time",
      timeComplexity: "O(2^n)",
      timeComplexityDetail: "Recursive subset test.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Recurse picking or removing intervals.",
      keySteps: ["1. Recurse."],
      code: {
        python: ["# Recursive"],
        cpp: ["// Recursive"],
        java: ["// Recursive"],
        typescript: ["// Recursive"],
      },
    },
  },
  "Minimum Number of Arrows to Burst Balloons": {
    intuition: "An arrow shot at position x bursts all balloons where `xstart <= x <= xend`. Equivalent to finding the number of non-overlapping intervals! 1) SORT balloons by END coordinate `xend`: `points.sort(key=lambda x: x[1])`. 2) Shoot first arrow at `arrow_pos = points[0][1]`, initialize `arrows = 1`. 3) For each balloon `[start, end]`: if `start > arrow_pos` (balloon starts AFTER current arrow position), shoot a new arrow at `arrow_pos = end` and increment `arrows += 1`. Return `arrows`.",
    bottleneck: "Greedy sorting by end coordinate guarantees each arrow bursts the maximum number of mutually overlapping balloons in O(n log n) time and O(1) space.",
    keyInvariant: "Shooting at the end of the current balloon guarantees hitting all currently active overlapping balloons.",
    constraints: ["1 <= points.length <= 10^5", "points[i].length == 2", "-2^31 <= xstart < xend <= 2^31 - 1"],
    examples: [{"input": "points = [[10,16],[2,8],[1,6],[7,12]]", "output": "2", "explanation": "Shoot arrow at x = 6 (bursts [2,8] and [1,6]) and x = 12 (bursts [10,16] and [7,12])."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft"],
    acceptanceRate: "57.8%",
    frequency: "89%",
    edgeCases: ["Touching balloons (e.g. [1,2] and [2,3] CAN be burst with 1 arrow at x = 2)"],
    interviewTips: ["Sort by `points[i][1]` (end coordinate) directly for cleanest 1-pass greedy logic."],
    optimal: {
      title: "Greedy End-Coordinate Arrow Placement",
      subtitle: "O(n log n) time and O(1) space min arrows",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "Sorting n intervals.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Only arrow_pos variable.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Sort points by end coordinate. Shoot arrow at points[0][1]. When start > arrow_pos: shoot new arrow.",
      keySteps: ["1. points.sort(key=lambda x: x[1]).", "2. arrows = 1, arrow_pos = points[0][1].", "3. For start, end in points[1:]: if start > arrow_pos: arrows += 1; arrow_pos = end.", "4. Return arrows."],
      code: {
        python: ["class Solution:", "    def findMinArrowShots(self, points: List[List[int]]) -> int:", "        points.sort(key=lambda x: x[1])", "        arrows = 1", "        arrow_pos = points[0][1]", "        for start, end in points[1:]:", "            if start > arrow_pos:", "                arrows += 1", "                arrow_pos = end", "        return arrows"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    int findMinArrowShots(vector<vector<int>>& points) {", "        sort(points.begin(), points.end(), [](const vector<int>& a, const vector<int>& b) {", "            return a[1] < b[1];", "        });", "        int arrows = 1, arrow_pos = points[0][1];", "        for (size_t i = 1; i < points.size(); ++i) {", "            if (points[i][0] > arrow_pos) {", "                arrows++;", "                arrow_pos = points[i][1];", "            }", "        }", "        return arrows;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int findMinArrowShots(int[][] points) {", "        Arrays.sort(points, (a, b) -> Integer.compare(a[1], b[1]));", "        int arrows = 1, arrowPos = points[0][1];", "        for (int i = 1; i < points.length; i++) {", "            if (points[i][0] > arrowPos) {", "                arrows++;", "                arrowPos = points[i][1];", "            }", "        }", "        return arrows;", "    }", "}"],
        typescript: ["function findMinArrowShots(points: number[][]): number {", "  points.sort((a, b) => a[1] - b[1]);", "  let arrows = 1, arrowPos = points[0][1];", "  for (let i = 1; i < points.length; i++) {", "    if (points[i][0] > arrowPos) {", "      arrows++;", "      arrowPos = points[i][1];", "    }", "  }", "  return arrows;", "}"],
      },
    },
    bruteForce: {
      title: "Sort by Start Time with Shrinking End",
      subtitle: "O(n log n) time and O(1) space",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "Sorts by start coordinate.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "No memory.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Sort by start, update prev_end = min(prev_end, end) on overlap.",
      keySteps: ["1. Sort by start.", "2. Min end tracking."],
      code: {
        python: ["# Start sort"],
        cpp: ["// Start sort"],
        java: ["// Start sort"],
        typescript: ["// Start sort"],
      },
    },
  },
  "Interval List Intersections": {
    intuition: "Two pointers `i` and `j` over sorted disjoint interval lists firstList and secondList. For intervals `firstList[i]` and `secondList[j]`: 1) Overlap start: `start = max(firstList[i][0], secondList[j][0])`. 2) Overlap end: `end = min(firstList[i][1], secondList[j][1])`. 3) If `start <= end`, a valid intersection `[start, end]` exists -> append to result. 4) Advance the pointer of whichever interval ends earlier (`if firstList[i][1] < secondList[j][1]: i += 1 else: j += 1`).",
    bottleneck: "Comparing all pairs takes O(M * N). Two pointers exploits sorted order to find all intersections in O(M + N) linear time and O(M + N) space.",
    keyInvariant: "Advancing the interval that ends earlier discards only segments that cannot overlap with any future intervals.",
    constraints: ["0 <= firstList.length, secondList.length <= 1000", "0 <= starti < endi <= 10^9", "Both lists are pairwise disjoint and sorted."],
    examples: [{"input": "firstList = [[0,2],[5,10],[13,23],[24,25]], secondList = [[1,5],[8,12],[15,24],[25,26]]", "output": "[[1,2],[5,5],[8,10],[15,23],[24,24],[25,25]]", "explanation": "Intersections calculated."}],
    companies: ["Meta", "Amazon", "Google", "Microsoft"],
    acceptanceRate: "71.8%",
    frequency: "92%",
    edgeCases: ["One or both lists empty (returns [])", "Single point intersection (e.g. [5,5])"],
    interviewTips: ["Intersection formula: `[max(start1, start2), min(end1, end2)]` if `start <= end`."],
    optimal: {
      title: "Two-Pointer Linear Merge Intersection",
      subtitle: "O(M + N) time and O(M + N) space two pointers",
      timeComplexity: "O(M + N)",
      timeComplexityDetail: "Each interval in firstList and secondList processed once.",
      spaceComplexity: "O(M + N)",
      spaceComplexityDetail: "Output intersection list.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Compute overlap [max(s1,s2), min(e1,e2)]. Advance pointer of interval that ends first.",
      keySteps: ["1. i = 0, j = 0, res = [].", "2. While i < len(firstList) and j < len(secondList): start = max(firstList[i][0], secondList[j][0]); end = min(firstList[i][1], secondList[j][1]); if start <= end: res.append([start, end]); if firstList[i][1] < secondList[j][1]: i += 1; else: j += 1.", "3. Return res."],
      code: {
        python: ["class Solution:", "    def intervalIntersection(self, firstList: List[List[int]], secondList: List[List[int]]) -> List[List[int]]:", "        i, j = 0, 0", "        res = []", "        while i < len(firstList) and j < len(secondList):", "            start = max(firstList[i][0], secondList[j][0])", "            end = min(firstList[i][1], secondList[j][1])", "            if start <= end:", "                res.append([start, end])", "            if firstList[i][1] < secondList[j][1]:", "                i += 1", "            else:", "                j += 1", "        return res"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    vector<vector<int>> intervalIntersection(vector<vector<int>>& firstList, vector<vector<int>>& secondList) {", "        vector<vector<int>> res;", "        size_t i = 0, j = 0;", "        while (i < firstList.size() && j < secondList.size()) {", "            int start = max(firstList[i][0], secondList[j][0]);", "            int end = min(firstList[i][1], secondList[j][1]);", "            if (start <= end) res.push_back({start, end});", "            if (firstList[i][1] < secondList[j][1]) i++;", "            else j++;", "        }", "        return res;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int[][] intervalIntersection(int[][] firstList, int[][] secondList) {", "        List<int[]> res = new ArrayList<>();", "        int i = 0, j = 0;", "        while (i < firstList.length && j < secondList.length) {", "            int start = Math.max(firstList[i][0], secondList[j][0]);", "            int end = Math.min(firstList[i][1], secondList[j][1]);", "            if (start <= end) res.add(new int[]{start, end});", "            if (firstList[i][1] < secondList[j][1]) i++;", "            else j++;", "        }", "        return res.toArray(new int[res.size()][]);", "    }", "}"],
        typescript: ["function intervalIntersection(firstList: number[][], secondList: number[][]): number[][] {", "  const res: number[][] = [];", "  let i = 0, j = 0;", "  while (i < firstList.length && j < secondList.length) {", "    const start = Math.max(firstList[i][0], secondList[j][0]);", "    const end = Math.min(firstList[i][1], secondList[j][1]);", "    if (start <= end) res.push([start, end]);", "    if (firstList[i][1] < secondList[j][1]) i++;", "    else j++;", "  }", "  return res;", "}"],
      },
    },
    bruteForce: {
      title: "Nested Pairwise Intersection Scan",
      subtitle: "O(M * N) time",
      timeComplexity: "O(M * N)",
      timeComplexityDetail: "Compares every interval in first with second.",
      spaceComplexity: "O(M + N)",
      spaceComplexityDetail: "Output array.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Double loop comparing every interval pair.",
      keySteps: ["1. Double loop i and j."],
      code: {
        python: ["# Double loop"],
        cpp: ["// Double loop"],
        java: ["// Double loop"],
        typescript: ["// Double loop"],
      },
    },
  },
}
