import { DetailedProblemData } from '../leetcodeSolutions'

export const mathGeometrySolutions: Record<string, DetailedProblemData> = {
  "Rotate Image": {
    intuition: "Rotate an n x n matrix 90 degrees clockwise in-place. Solve in 2 steps: 1) TRANSPOSE the matrix (swap `matrix[i][j]` with `matrix[j][i]` for all `j > i`). 2) REVERSE each row (swap `matrix[i][l]` with `matrix[i][r]`). The combination of Transpose + Row Reverse exactly performs a 90\u00b0 clockwise rotation in O(n\u00b2) time and O(1) in-place space.",
    bottleneck: "Allocating a new matrix takes O(n\u00b2) auxiliary memory. Transpose + Reverse rotates in-place in O(n\u00b2) time and O(1) space.",
    keyInvariant: "matrix[j][i] transposed followed by horizontal row reflection produces the exact 90\u00b0 clockwise rotation.",
    constraints: ["n == matrix.length == matrix[i].length", "1 <= n <= 20", "-1000 <= matrix[i][j] <= 1000"],
    examples: [{"input": "matrix = [[1,2,3],[4,5,6],[7,8,9]]", "output": "[[7,4,1],[8,5,2],[9,6,3]]", "explanation": "90\u00b0 clockwise rotation in-place."}],
    companies: ["Amazon", "Microsoft", "Google", "Meta", "Apple"],
    acceptanceRate: "74.2%",
    frequency: "97%",
    edgeCases: ["1x1 matrix (no change)", "2x2 matrix"],
    interviewTips: ["Remember: Clockwise = Transpose then Reverse rows; Counter-Clockwise = Reverse rows then Transpose."],
    optimal: {
      title: "In-Place Transpose + Row Reversal",
      subtitle: "O(n\u00b2) time and O(1) space in-place 90\u00b0 rotation",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "Transpose visits n\u00b2/2 elements, reverse visits n\u00b2/2 elements.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "In-place matrix modification.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Step 1: Transpose matrix[i][j] <-> matrix[j][i]. Step 2: Reverse each row.",
      keySteps: ["1. n = len(matrix).", "2. For i in range(n): for j in range(i + 1, n): matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j].", "3. For i in range(n): matrix[i].reverse()."],
      code: {
        python: ["class Solution:", "    def rotate(self, matrix: List[List[int]]) -> None:", "        n = len(matrix)", "        for i in range(n):", "            for j in range(i + 1, n):", "                matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]", "        for i in range(n):", "            matrix[i].reverse()"],
        cpp: ["#include <vector>", "#include <algorithm>", "using namespace std;", "class Solution {", "public:", "    void rotate(vector<vector<int>>& matrix) {", "        int n = matrix.size();", "        for (int i = 0; i < n; ++i)", "            for (int j = i + 1; j < n; ++j) swap(matrix[i][j], matrix[j][i]);", "        for (int i = 0; i < n; ++i) reverse(matrix[i].begin(), matrix[i].end());", "    }", "};"],
        java: ["class Solution {", "    public void rotate(int[][] matrix) {", "        int n = matrix.length;", "        for (int i = 0; i < n; i++) {", "            for (int j = i + 1; j < n; j++) {", "                int tmp = matrix[i][j];", "                matrix[i][j] = matrix[j][i];", "                matrix[j][i] = tmp;", "            }", "        }", "        for (int i = 0; i < n; i++) {", "            int l = 0, r = n - 1;", "            while (l < r) {", "                int tmp = matrix[i][l]; matrix[i][l] = matrix[i][r]; matrix[i][r] = tmp; l++; r--;", "            }", "        }", "    }", "}"],
        typescript: ["function rotate(matrix: number[][]): void {", "  const n = matrix.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = i + 1; j < n; j++) {", "      [matrix[i][j], matrix[j][i]] = [matrix[j][i], matrix[i][j]];", "    }", "  }", "  for (let i = 0; i < n; i++) matrix[i].reverse();", "}"],
      },
    },
    bruteForce: {
      title: "New Matrix Allocation",
      subtitle: "O(n\u00b2) time and O(n\u00b2) space",
      timeComplexity: "O(n\u00b2)",
      timeComplexityDetail: "New matrix.",
      spaceComplexity: "O(n\u00b2)",
      spaceComplexityDetail: "Matrix copies.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "new_mat[j][n - 1 - i] = matrix[i][j], copy back.",
      keySteps: ["1. New matrix copy."],
      code: {
        python: ["# Matrix copy"],
        cpp: ["// Matrix copy"],
        java: ["// Matrix copy"],
        typescript: ["// Matrix copy"],
      },
    },
  },
  "Spiral Matrix": {
    intuition: "Traverse m x n matrix in spiral order. Maintain boundaries `top = 0, bottom = m - 1, left = 0, right = n - 1`. Loop while `left <= right and top <= bottom`: 1) Traverse top row (left -> right), `top += 1`. 2) Traverse right col (top -> bottom), `right -= 1`. 3) Traverse bottom row (right -> left) if `top <= bottom`, `bottom -= 1`. 4) Traverse left col (bottom -> top) if `left <= right`, `left += 1`. Return result.",
    bottleneck: "Tracking visited cells in matrix uses extra space. Boundary pointer shrinking visits each cell once in O(m * n) time and O(1) auxiliary space.",
    keyInvariant: "Four boundary pointers shrink by 1 after each corresponding directional perimeter pass.",
    constraints: ["m == matrix.length", "n == matrix[i].length", "1 <= m, n <= 10", "-100 <= matrix[i][j] <= 100"],
    examples: [{"input": "matrix = [[1,2,3],[4,5,6],[7,8,9]]", "output": "[1,2,3,6,9,8,7,4,5]", "explanation": "Spiral order traversal."}],
    companies: ["Microsoft", "Amazon", "Google", "Meta", "Apple"],
    acceptanceRate: "49.8%",
    frequency: "95%",
    edgeCases: ["Single row or single column matrix (boundary checks top <= bottom and left <= right prevent duplicate reads)"],
    interviewTips: ["Check `if not (left <= right and top <= bottom): break` after updating top and right boundaries."],
    optimal: {
      title: "Four-Boundary Pointer Shrinking Traversal",
      subtitle: "O(m * n) time and O(1) auxiliary space spiral traversal",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "Every cell added to result once.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Pointer variables only.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Shrink top, bottom, left, right boundaries in 4 directional passes per layer.",
      keySteps: ["1. top = 0, bottom = len(matrix) - 1, left = 0, right = len(matrix[0]) - 1, res = [].", "2. While left <= right and top <= bottom:", "   For c in range(left, right + 1): res.append(matrix[top][c]); top += 1.", "   For r in range(top, bottom + 1): res.append(matrix[r][right]); right -= 1.", "   If not (left <= right and top <= bottom): break.", "   For c in range(right, left - 1, -1): res.append(matrix[bottom][c]); bottom -= 1.", "   For r in range(bottom, top - 1, -1): res.append(matrix[r][left]); left += 1.", "3. Return res."],
      code: {
        python: ["class Solution:", "    def spiralOrder(self, matrix: List[List[int]]) -> List[int]:", "        res = []", "        top, bottom = 0, len(matrix) - 1", "        left, right = 0, len(matrix[0]) - 1", "        while left <= right and top <= bottom:", "            for c in range(left, right + 1):", "                res.append(matrix[top][c])", "            top += 1", "            for r in range(top, bottom + 1):", "                res.append(matrix[r][right])", "            right -= 1", "            if not (left <= right and top <= bottom): break", "            for c in range(right, left - 1, -1):", "                res.append(matrix[bottom][c])", "            bottom -= 1", "            for r in range(bottom, top - 1, -1):", "                res.append(matrix[r][left])", "            left += 1", "        return res"],
        cpp: ["// Spiral Order cpp"],
        java: ["// Spiral Order java"],
        typescript: ["// Spiral Order ts"],
      },
    },
    bruteForce: {
      title: "Direction Vector with Visited Grid",
      subtitle: "O(m * n) time and O(m * n) space",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "Direction vector traversal.",
      spaceComplexity: "O(m * n)",
      spaceComplexityDetail: "Visited matrix.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Maintain direction vector (0, 1) -> (1, 0) -> (0, -1) -> (-1, 0) and change direction when hitting visited or wall.",
      keySteps: ["1. Direction simulation."],
      code: {
        python: ["# Direction vector simulation"],
        cpp: ["// Direction vector"],
        java: ["// Direction vector"],
        typescript: ["// Direction vector"],
      },
    },
  },
  "Set Matrix Zeroes": {
    intuition: "If an element in an m x n matrix is 0, set its entire row and column to 0 in-place. Use the FIRST ROW and FIRST COLUMN of the matrix as marker arrays! Track whether the first row itself has a zero using `row_zero = False`. If `matrix[r][c] == 0`: mark `matrix[0][c] = 0` and `matrix[r][0] = 0` (or `row_zero = True` if r == 0). In a second pass, fill zeros for interior cells `(r > 0, c > 0)`. Finally, zero out the first column if `matrix[0][0] == 0` and first row if `row_zero == True`.",
    bottleneck: "Separate marker arrays use O(m + n) space. Using first row and column markers achieves O(m * n) time and strictly O(1) in-place space.",
    keyInvariant: "matrix[0][c] and matrix[r][0] store zero status for column c and row r without extra memory.",
    constraints: ["m == matrix.length", "n == matrix[0].length", "1 <= m, n <= 200", "-2^31 <= matrix[i][j] <= 2^31 - 1"],
    examples: [{"input": "matrix = [[1,1,1],[1,0,1],[1,1,1]]", "output": "[[1,0,1],[0,0,0],[1,0,1]]", "explanation": "Row 1 and col 1 zeroed."}],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Bloomberg"],
    acceptanceRate: "55.4%",
    frequency: "95%",
    edgeCases: ["First row or first column itself contains zero (requires separate boolean flag)"],
    interviewTips: ["Explain why `row_zero` boolean is needed: `matrix[0][0]` represents the first column, so `row_zero` represents the first row."],
    optimal: {
      title: "First Row and First Column In-Place Markers",
      subtitle: "O(m * n) time and O(1) space in-place zeroing",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "Two passes over m x n matrix.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "One boolean variable row_zero.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Mark zeros on first row/col. Fill interior zeros. Fill first col and first row.",
      keySteps: ["1. m, n = len(matrix), len(matrix[0]), row_zero = False.", "2. For r in range(m): for c in range(n): if matrix[r][c] == 0: matrix[0][c] = 0; if r > 0: matrix[r][0] = 0; else: row_zero = True.", "3. For r in range(1, m): for c in range(1, n): if matrix[0][c] == 0 or matrix[r][0] == 0: matrix[r][c] = 0.", "4. If matrix[0][0] == 0: for r in range(m): matrix[r][0] = 0.", "5. If row_zero: for c in range(n): matrix[0][c] = 0."],
      code: {
        python: ["class Solution:", "    def setZeroes(self, matrix: List[List[int]]) -> None:", "        m, n = len(matrix), len(matrix[0])", "        row_zero = False", "        for r in range(m):", "            for c in range(n):", "                if matrix[r][c] == 0:", "                    matrix[0][c] = 0", "                    if r > 0: matrix[r][0] = 0", "                    else: row_zero = True", "        for r in range(1, m):", "            for c in range(1, n):", "                if matrix[0][c] == 0 or matrix[r][0] == 0:", "                    matrix[r][c] = 0", "        if matrix[0][0] == 0:", "            for r in range(m): matrix[r][0] = 0", "        if row_zero:", "            for c in range(n): matrix[0][c] = 0"],
        cpp: ["// Set Matrix Zeroes cpp"],
        java: ["// Set Matrix Zeroes java"],
        typescript: ["// Set Matrix Zeroes ts"],
      },
    },
    bruteForce: {
      title: "Row and Column Marker Arrays",
      subtitle: "O(m * n) time and O(m + n) space",
      timeComplexity: "O(m * n)",
      timeComplexityDetail: "Two passes.",
      spaceComplexity: "O(m + n)",
      spaceComplexityDetail: "Zero row and col arrays.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Track zero rows and cols in boolean arrays of size m and n.",
      keySteps: ["1. Marker arrays."],
      code: {
        python: ["# Marker arrays"],
        cpp: ["// Markers"],
        java: ["// Markers"],
        typescript: ["// Markers"],
      },
    },
  },
  "Happy Number": {
    intuition: "A number is happy if repeatedly replacing it with the sum of the squares of its digits eventually reaches 1. Numbers that are NOT happy enter an infinite cyclic loop (specifically including the cycle `4 -> 16 -> 37 -> 58 -> 89 -> 145 -> 42 -> 20 -> 4`). Use Floyd's Tortoise and Hare cycle detection (or a Hash Set): `slow = sum_sq(n)`, `fast = sum_sq(sum_sq(n))`. Loop while `slow != fast`. Return `slow == 1` in O(log n) time and strictly O(1) space.",
    bottleneck: "Hash set uses O(k) memory. Fast & slow pointers detect the cycle in O(log n) time and O(1) space.",
    keyInvariant: "Every integer n under digit square sum either reaches 1 or falls into a finite cycle.",
    constraints: ["1 <= n <= 2^31 - 1"],
    examples: [{"input": "n = 19", "output": "true", "explanation": "19 -> 82 -> 68 -> 100 -> 1."}, {"input": "n = 2", "output": "false", "explanation": "Enters cycle."}],
    companies: ["Amazon", "Google", "Apple", "Meta"],
    acceptanceRate: "56.1%",
    frequency: "91%",
    edgeCases: ["n = 1 (immediately true)", "n = 7 (happy after 5 steps: 7->49->97->130->10->1)"],
    interviewTips: ["Show helper `sum_sq(n)` using modulo and integer division: `while n: res += (n % 10)**2; n //= 10`."],
    optimal: {
      title: "Floyd's Cycle Finding (Fast & Slow Pointers)",
      subtitle: "O(log n) time and O(1) space cycle detection",
      timeComplexity: "O(log n)",
      timeComplexityDetail: "Digit sum shrinks numbers rapidly; cycle length <= 8.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Two scalar variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "slow = sum_sq(n), fast = sum_sq(sum_sq(n)). Loop while slow != fast. Return slow == 1.",
      keySteps: ["1. sum_sq(n): res = 0; while n: digit = n % 10; res += digit * digit; n //= 10; return res.", "2. slow = n, fast = sum_sq(n).", "3. While fast != 1 and slow != fast: slow = sum_sq(slow); fast = sum_sq(sum_sq(fast)).", "4. Return fast == 1."],
      code: {
        python: ["class Solution:", "    def isHappy(self, n: int) -> bool:", "        def sum_sq(num):", "            res = 0", "            while num:", "                d = num % 10", "                res += d * d", "                num //= 10", "            return res", "        slow = n", "        fast = sum_sq(n)", "        while fast != 1 and slow != fast:", "            slow = sum_sq(slow)", "            fast = sum_sq(sum_sq(fast))", "        return fast == 1"],
        cpp: ["// Happy Number cpp"],
        java: ["// Happy Number java"],
        typescript: ["// Happy Number ts"],
      },
    },
    bruteForce: {
      title: "Hash Set Seen Numbers",
      subtitle: "O(log n) time and O(log n) space",
      timeComplexity: "O(log n)",
      timeComplexityDetail: "Set lookup.",
      spaceComplexity: "O(log n)",
      spaceComplexityDetail: "Set storage.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Add seen numbers to set, return False if duplicate seen.",
      keySteps: ["1. Set tracking."],
      code: {
        python: ["# Hash set"],
        cpp: ["// Set"],
        java: ["// Set"],
        typescript: ["// Set"],
      },
    },
  },
  "Plus One": {
    intuition: "Given large integer as digits array, add 1. Iterate backwards from `n - 1` to `0`: 1) If `digits[i] < 9`: increment `digits[i] += 1` and return `digits` immediately. 2) If `digits[i] == 9`: set `digits[i] = 0` and continue carry to preceding digit. 3) If all digits were 9 (e.g. `[9, 9, 9]`), loop finishes with `[0, 0, 0]`; return `[1] + digits` in O(n) time and O(1) in-place space.",
    bottleneck: "Converting to string/int can exceed language numeric limits. In-place digit ripple runs in O(n) time and O(1) auxiliary space.",
    keyInvariant: "Adding 1 to digit < 9 resolves carry immediately without propagating further.",
    constraints: ["1 <= digits.length <= 100", "0 <= digits[i] <= 9", "digits does not contain any leading 0's."],
    examples: [{"input": "digits = [1,2,3]", "output": "[1,2,4]", "explanation": "123 + 1 = 124."}, {"input": "digits = [9]", "output": "[1,0]", "explanation": "9 + 1 = 10."}],
    companies: ["Google", "Amazon", "Microsoft", "Apple"],
    acceptanceRate: "45.1%",
    frequency: "92%",
    edgeCases: ["All 9s (e.g. [9,9,9] -> [1,0,0,0])", "Single digit 0"],
    interviewTips: ["Show the early exit: whenever `digits[i] < 9`, increment and return immediately."],
    optimal: {
      title: "In-Place Reverse Carry Propagation",
      subtitle: "O(n) time and O(1) auxiliary space digit addition",
      timeComplexity: "O(n)",
      timeComplexityDetail: "At most n iterations.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "In-place array update.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Loop backwards. If digit < 9: digit += 1, return. Else digit = 0. Return [1] + digits if all 9s.",
      keySteps: ["1. For i in range(len(digits) - 1, -1, -1): if digits[i] < 9: digits[i] += 1; return digits. digits[i] = 0.", "2. Return [1] + digits."],
      code: {
        python: ["class Solution:", "    def plusOne(self, digits: List[int]) -> List[int]:", "        for i in range(len(digits) - 1, -1, -1):", "            if digits[i] < 9:", "                digits[i] += 1", "                return digits", "            digits[i] = 0", "        return [1] + digits"],
        cpp: ["#include <vector>", "using namespace std;", "class Solution {", "public:", "    vector<int> plusOne(vector<int>& digits) {", "        for (int i = digits.size() - 1; i >= 0; --i) {", "            if (digits[i] < 9) { digits[i]++; return digits; }", "            digits[i] = 0;", "        }", "        digits.insert(digits.begin(), 1);", "        return digits;", "    }", "};"],
        java: ["class Solution {", "    public int[] plusOne(int[] digits) {", "        for (int i = digits.length - 1; i >= 0; i--) {", "            if (digits[i] < 9) { digits[i]++; return digits; }", "            digits[i] = 0;", "        }", "        int[] res = new int[digits.length + 1];", "        res[0] = 1;", "        return res;", "    }", "}"],
        typescript: ["function plusOne(digits: number[]): number[] {", "  for (let i = digits.length - 1; i >= 0; i--) {", "    if (digits[i] < 9) { digits[i]++; return digits; }", "    digits[i] = 0;", "  }", "  return [1, ...digits];", "}"],
      },
    },
    bruteForce: {
      title: "BigInt String Conversion",
      subtitle: "O(n) time and O(n) space",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Converts array to string, adds 1 with BigInt, splits.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "String copies.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "BigInt(digits.join(\"\")) + 1n and split back into array.",
      keySteps: ["1. BigInt conversion."],
      code: {
        python: ["# BigInt"],
        cpp: ["// BigInt"],
        java: ["// BigInt"],
        typescript: ["// BigInt"],
      },
    },
  },
  "Pow(x, n)": {
    intuition: "Binary Exponentiation (Fast Power): Compute `x^n` by squaring base. 1) If `n < 0`, `x = 1 / x, n = -n`. 2) Base case: `n == 0` returns `1.0`. 3) While `n > 0`: if `n % 2 == 1`, multiply `res *= x`. Square base `x *= x` and halve exponent `n //= 2`. Runs in O(log n) time and O(1) space.",
    bottleneck: "Multiplying x by itself n times takes O(n). Binary exponentiation squares the base on each step, reducing time to O(log n).",
    keyInvariant: "x^n = (x*x)^(n // 2) if n is even; x * (x*x)^(n // 2) if n is odd.",
    constraints: ["-100.0 < x < 100.0", "-2^31 <= n <= 2^31 - 1", "n is an integer.", "Either x is not zero or n > 0."],
    examples: [{"input": "x = 2.00000, n = 10", "output": "1024.00000", "explanation": "2^10 = 1024."}, {"input": "x = 2.00000, n = -2", "output": "0.25000", "explanation": "2^-2 = 1/4 = 0.25."}],
    companies: ["Google", "Meta", "Amazon", "Bloomberg", "Microsoft"],
    acceptanceRate: "34.8%",
    frequency: "95%",
    edgeCases: ["n = -2^31 (in languages with 32-bit signed ints, handle -n overflow with long long)", "x = 0 or 1", "n = 0 (returns 1.0)"],
    interviewTips: ["In C++/Java, convert n to `long long` before negating: `long long N = n; if (N < 0) { x = 1 / x; N = -N; }` to prevent overflow on `n = -2147483648`."],
    optimal: {
      title: "Iterative Binary Exponentiation",
      subtitle: "O(log n) time and O(1) space fast power",
      timeComplexity: "O(log n)",
      timeComplexityDetail: "Halves exponent n in each step.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Only scalar variables.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "If n < 0: x = 1/x, n = -n. While n > 0: if n % 2 == 1: res *= x; x *= x; n //= 2.",
      keySteps: ["1. If n < 0: x = 1 / x, n = -n.", "2. res = 1.0.", "3. While n > 0: if n % 2 == 1: res *= x. x *= x; n //= 2.", "4. Return res."],
      code: {
        python: ["class Solution:", "    def myPow(self, x: float, n: int) -> float:", "        if n < 0:", "            x = 1 / x", "            n = -n", "        res = 1.0", "        while n > 0:", "            if n % 2 == 1:", "                res *= x", "            x *= x", "            n //= 2", "        return res"],
        cpp: ["class Solution {", "public:", "    double myPow(double x, int n) {", "        long long N = n;", "        if (N < 0) { x = 1.0 / x; N = -N; }", "        double res = 1.0;", "        while (N > 0) {", "            if (N % 2 == 1) res *= x;", "            x *= x; N /= 2;", "        }", "        return res;", "    }", "};"],
        java: ["class Solution {", "    public double myPow(double x, int n) {", "        long N = n;", "        if (N < 0) { x = 1.0 / x; N = -N; }", "        double res = 1.0;", "        while (N > 0) {", "            if (N % 2 == 1) res *= x;", "            x *= x; N /= 2;", "        }", "        return res;", "    }", "}"],
        typescript: ["function myPow(x: number, n: number): number {", "  let N = n;", "  if (N < 0) { x = 1 / x; N = -N; }", "  let res = 1.0;", "  while (N > 0) {", "    if (N % 2 === 1) res *= x;", "    x *= x; N = Math.floor(N / 2);", "  }", "  return res;", "}"],
      },
    },
    bruteForce: {
      title: "Linear Multiplication",
      subtitle: "O(n) time",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Multiply x n times.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "No extra memory.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Loop n times multiplying by x.",
      keySteps: ["1. Linear loop."],
      code: {
        python: ["# Linear multiply"],
        cpp: ["// Linear"],
        java: ["// Linear"],
        typescript: ["// Linear"],
      },
    },
  },
}
