import { DetailedProblemData } from '../leetcodeSolutions'

export const twoPointersSolutions: Record<string, DetailedProblemData> = {
  'Valid Palindrome': {
    intuition:
      'A palindrome reads the same backwards as forwards. Using two pointers starting at opposite ends of the string, skip non-alphanumeric characters and compare lowercase characters moving inward in O(n) time and O(1) memory.',
    bottleneck:
      'Creating a filtered reversed string takes O(n) auxiliary memory. Inward two-pointer scanning operates in-place in O(1) memory.',
    keyInvariant:
      'At any step, all characters outside window [l, r] have already been verified to be symmetric matches.',
    constraints: ['1 <= s.length <= 2 * 10^5', 's consists only of printable ASCII characters.'],
    examples: [
      { input: 's = "A man, a plan, a canal: Panama"', output: 'true', explanation: '"amanaplanacanalpanama" is a palindrome.' },
      { input: 's = "race a car"', output: 'false', explanation: '"raceacar" is not a palindrome.' },
    ],
    companies: ['Meta', 'Amazon', 'Microsoft', 'Apple', 'Google'],
    acceptanceRate: '46.8%',
    frequency: '92%',
    edgeCases: ['String with no alphanumeric characters `",,, "` (returns true)', 'Single character string', 'String with mixed casing'],
    interviewTips: ['Show how to skip non-alphanumeric characters with while loops inside the outer loop.'],
    optimal: {
      title: 'Two Pointers Inward Scan',
      subtitle: 'O(n) time and O(1) auxiliary space in-place scan',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Each character visited at most once as l and r converge.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Two pointer indices.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~35ms, Beats 99%)',
      explanation: 'Initialize l=0, r=len(s)-1. Skip non-alphanumeric characters. Compare lowercased characters. If mismatch, return false.',
      keySteps: [
        '1. Set `l = 0`, `r = len(s) - 1`.',
        '2. While `l < r`:',
        '   a. While `l < r` and not `s[l].isalnum()`: `l += 1`.',
        '   b. While `l < r` and not `s[r].isalnum()`: `r -= 1`.',
        '   c. If `s[l].lower() != s[r].lower()`: return `False`.',
        '   d. `l += 1`, `r -= 1`.',
        '3. Return `True`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def isPalindrome(self, s: str) -> bool:',
          '        l, r = 0, len(s) - 1',
          '        while l < r:',
          '            while l < r and not s[l].isalnum():',
          '                l += 1',
          '            while l < r and not s[r].isalnum():',
          '                r -= 1',
          '            if s[l].lower() != s[r].lower():',
          '                return False',
          '            l += 1',
          '            r -= 1',
          '        return True',
        ],
        cpp: [
          '#include <string>',
          '#include <cctype>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    bool isPalindrome(string s) {',
          '        int l = 0, r = s.length() - 1;',
          '        while (l < r) {',
          '            while (l < r && !isalnum(s[l])) l++;',
          '            while (l < r && !isalnum(s[r])) r--;',
          '            if (tolower(s[l]) != tolower(s[r])) return false;',
          '            l++; r--;',
          '        }',
          '        return true;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public boolean isPalindrome(String s) {',
          '        int l = 0, r = s.length() - 1;',
          '        while (l < r) {',
          '            while (l < r && !Character.isLetterOrDigit(s.charAt(l))) l++;',
          '            while (l < r && !Character.isLetterOrDigit(s.charAt(r))) r--;',
          '            if (Character.toLowerCase(s.charAt(l)) != Character.toLowerCase(s.charAt(r))) return false;',
          '            l++; r--;',
          '        }',
          '        return true;',
          '    }',
          '}',
        ],
        typescript: [
          'function isPalindrome(s: string): boolean {',
          '  let l = 0, r = s.length - 1;',
          '  const isAlphaNum = (c: string) => /[a-z0-9]/i.test(c);',
          '  while (l < r) {',
          '    while (l < r && !isAlphaNum(s[l])) l++;',
          '    while (l < r && !isAlphaNum(s[r])) r--;',
          '    if (s[l].toLowerCase() !== s[r].toLowerCase()) return false;',
          '    l++; r--;',
          '  }',
          '  return true;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Filter and Reverse String Copy',
      subtitle: 'Build cleaned string and compare with reverse',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Filtering and reversing take linear time.',
      spaceComplexity: 'O(n)',
      spaceComplexityDetail: 'Allocates cleaned string copy.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Uses extra memory)',
      explanation: 'Filter alphanumeric characters into a new lowercase string and compare with its reversed copy.',
      keySteps: ['1. Filter string `cleaned = "".join(c.lower() for c in s if c.isalnum())`.', '2. Return `cleaned == cleaned[::-1]`.'],
      code: {
        python: [
          'class Solution:',
          '    def isPalindrome(self, s: str) -> bool:',
          '        cleaned = [c.lower() for c in s if c.isalnum()]',
          '        return cleaned == cleaned[::-1]',
        ],
        cpp: [
          '// Filter and reverse copy approach',
        ],
        java: [
          '// Filter and reverse copy approach',
        ],
        typescript: [
          '// Filter and reverse copy approach',
        ],
      },
    },
  },

  'Two Sum II - Input Array Is Sorted': {
    intuition:
      'Because the array is already sorted in non-decreasing order, we can use two pointers at `l = 0` and `r = n - 1`. If `numbers[l] + numbers[r] == target`, we return the 1-based indices. If the sum is too small (< target), increment `l` to increase the sum. If the sum is too large (> target), decrement `r` to decrease the sum.',
    bottleneck:
      'Using a Hash Map takes O(n) space and fails to leverage the sorted property. Two pointers achieves O(n) time and O(1) constant space.',
    keyInvariant:
      'Because the array is sorted, incrementing l strictly increases the sum, and decrementing r strictly decreases the sum.',
    constraints: ['2 <= numbers.length <= 3 * 10^4', '-1000 <= numbers[i] <= 1000', 'numbers is sorted in non-decreasing order.', 'Exactly one solution exists.'],
    examples: [
      { input: 'numbers = [2,7,11,15], target = 9', output: '[1, 2]', explanation: '2 + 7 = 9. 1-indexed output is [1, 2].' },
      { input: 'numbers = [2,3,4], target = 6', output: '[1, 3]', explanation: '2 + 4 = 6. 1-indexed output is [1, 3].' },
    ],
    companies: ['Amazon', 'Apple', 'Google', 'Meta', 'Microsoft'],
    acceptanceRate: '60.9%',
    frequency: '88%',
    edgeCases: ['Array with duplicate numbers (e.g. [0, 0, 3, 4], target = 0)', 'Negative numbers in array'],
    interviewTips: ['Remember 1-based indexing required by problem statement: return `[l + 1, r + 1]`.'],
    optimal: {
      title: 'Two Pointers Shrinking Window',
      subtitle: 'O(n) time and O(1) space two-pointer inward scan',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Each step moves either l right or r left, terminating in at most n steps.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only two index pointers.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~90ms, Beats 98%)',
      explanation: 'Place left pointer at start, right pointer at end. Adjust based on sum comparison with target.',
      keySteps: [
        '1. Set `l = 0`, `r = len(numbers) - 1`.',
        '2. While `l < r`:',
        '   a. `cur = numbers[l] + numbers[r]`.',
        '   b. If `cur == target`: return `[l + 1, r + 1]`.',
        '   c. If `cur < target`: `l += 1`.',
        '   d. If `cur > target`: `r -= 1`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def twoSum(self, numbers: List[int], target: int) -> List[int]:',
          '        l, r = 0, len(numbers) - 1',
          '        while l < r:',
          '            cur = numbers[l] + numbers[r]',
          '            if cur == target:',
          '                return [l + 1, r + 1]',
          '            elif cur < target:',
          '                l += 1',
          '            else:',
          '                r -= 1',
          '        return []',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    vector<int> twoSum(vector<int>& numbers, int target) {',
          '        int l = 0, r = numbers.size() - 1;',
          '        while (l < r) {',
          '            int cur = numbers[l] + numbers[r];',
          '            if (cur == target) return {l + 1, r + 1};',
          '            else if (cur < target) l++;',
          '            else r--;',
          '        }',
          '        return {};',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int[] twoSum(int[] numbers, int target) {',
          '        int l = 0, r = numbers.length - 1;',
          '        while (l < r) {',
          '            int cur = numbers[l] + numbers[r];',
          '            if (cur == target) return new int[]{l + 1, r + 1};',
          '            else if (cur < target) l++;',
          '            else r--;',
          '        }',
          '        return new int[0];',
          '    }',
          '}',
        ],
        typescript: [
          'function twoSum(numbers: number[], target: number): number[] {',
          '  let l = 0, r = numbers.length - 1;',
          '  while (l < r) {',
          '    const cur = numbers[l] + numbers[r];',
          '    if (cur === target) return [l + 1, r + 1];',
          '    else if (cur < target) l++;',
          '    else r--;',
          '  }',
          '  return [];',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Binary Search for Each Element',
      subtitle: 'For each element, binary search for its complement',
      timeComplexity: 'O(n log n)',
      timeComplexityDetail: 'Iterate n elements and binary search remaining array in O(log n).',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Slower than two pointers)',
      explanation: 'For each index i, binary search for target - numbers[i] in subarray [i+1..n-1].',
      keySteps: ['1. Loop `i` from 0 to `n-1`.', '2. Binary search for `target - numbers[i]`.'],
      code: {
        python: [
          'import bisect',
          'class Solution:',
          '    def twoSum(self, numbers: List[int], target: int) -> List[int]:',
          '        for i in range(len(numbers)):',
          '            diff = target - numbers[i]',
          '            idx = bisect.bisect_left(numbers, diff, i + 1)',
          '            if idx < len(numbers) and numbers[idx] == diff:',
          '                return [i + 1, idx + 1]',
        ],
        cpp: [
          '// Binary search approach',
        ],
        java: [
          '// Binary search approach',
        ],
        typescript: [
          '// Binary search approach',
        ],
      },
    },
  },

  '3Sum': {
    intuition:
      'Sort the array first. For each element `nums[i]`, convert the problem into a Two Sum II problem on the remaining subarray `nums[i+1..n-1]` with target `-nums[i]`. Use two pointers `l` and `r` to find pairs summing to `-nums[i]`. To avoid duplicate triplets without sets, skip duplicate elements for `i`, `l`, and `r`.',
    bottleneck:
      'Checking all triplets with 3 nested loops takes O(n³) time and requires set deduplication. Sorting + Two Pointers runs in O(n²) time with O(1) auxiliary space.',
    keyInvariant:
      'Skipping adjacent equal values for i, l, and r guarantees every generated triplet is unique.',
    constraints: ['3 <= nums.length <= 3000', '-10^5 <= nums[i] <= 10^5'],
    examples: [
      { input: 'nums = [-1,0,1,2,-1,-4]', output: '[[-1,-1,2],[-1,0,1]]', explanation: 'Distinct triplets summing to 0.' },
      { input: 'nums = [0,1,1]', output: '[]', explanation: 'No triplet sums to 0.' },
    ],
    companies: ['Amazon', 'Meta', 'Apple', 'Google', 'Microsoft', 'Uber'],
    acceptanceRate: '33.9%',
    frequency: '97%',
    edgeCases: ['All zeros `[0, 0, 0, 0]` (returns `[[0, 0, 0]]`)', 'Array with all positive numbers (returns `[]`)', 'Duplicates causing potential repeat triplets'],
    interviewTips: [
      'Emphasize early termination: if `nums[i] > 0`, break immediately since elements after `i` are all positive.',
      'Explain duplicate skipping logic for `l` and `r` after finding a valid triplet.',
    ],
    optimal: {
      title: 'Sort + Two Pointers with In-Place Duplicate Skipping',
      subtitle: 'O(n²) time and O(1) auxiliary space',
      timeComplexity: 'O(n²)',
      timeComplexityDetail: 'Sorting takes O(n log n). Outer loop runs n times with O(n) two-pointer scan inside.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Excluding return list; sorting takes O(log n) stack space.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~450ms, Beats 96%)',
      explanation: 'Sort array. For each i, if nums[i] == nums[i-1] skip. Run two pointers l=i+1, r=n-1 to find zero sums.',
      keySteps: [
        '1. Sort `nums`.',
        '2. For `i` from 0 to `n - 3`:',
        '   a. If `nums[i] > 0`: break.',
        '   b. If `i > 0` and `nums[i] == nums[i - 1]`: continue.',
        '   c. `l = i + 1`, `r = n - 1`.',
        '   d. While `l < r`:',
        '      - `s = nums[i] + nums[l] + nums[r]`.',
        '      - If `s == 0`: add triplet, advance `l` past duplicates, decrement `r` past duplicates.',
        '      - Else if `s < 0`: `l += 1`.',
        '      - Else: `r -= 1`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def threeSum(self, nums: List[int]) -> List[List[int]]:',
          '        nums.sort()',
          '        res = []',
          '        n = len(nums)',
          '        for i in range(n - 2):',
          '            if nums[i] > 0:',
          '                break',
          '            if i > 0 and nums[i] == nums[i - 1]:',
          '                continue',
          '            l, r = i + 1, n - 1',
          '            while l < r:',
          '                s = nums[i] + nums[l] + nums[r]',
          '                if s == 0:',
          '                    res.append([nums[i], nums[l], nums[r]])',
          '                    while l < r and nums[l] == nums[l + 1]:',
          '                        l += 1',
          '                    while l < r and nums[r] == nums[r - 1]:',
          '                        r -= 1',
          '                    l += 1',
          '                    r -= 1',
          '                elif s < 0:',
          '                    l += 1',
          '                else:',
          '                    r -= 1',
          '        return res',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    vector<vector<int>> threeSum(vector<int>& nums) {',
          '        sort(nums.begin(), nums.end());',
          '        vector<vector<int>> res;',
          '        int n = nums.size();',
          '        for (int i = 0; i < n - 2; ++i) {',
          '            if (nums[i] > 0) break;',
          '            if (i > 0 && nums[i] == nums[i - 1]) continue;',
          '            int l = i + 1, r = n - 1;',
          '            while (l < r) {',
          '                int s = nums[i] + nums[l] + nums[r];',
          '                if (s == 0) {',
          '                    res.push_back({nums[i], nums[l], nums[r]});',
          '                    while (l < r && nums[l] == nums[l + 1]) l++;',
          '                    while (l < r && nums[r] == nums[r - 1]) r--;',
          '                    l++; r--;',
          '                } else if (s < 0) l++;',
          '                else r--;',
          '            }',
          '        }',
          '        return res;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.*;',
          'class Solution {',
          '    public List<List<Integer>> threeSum(int[] nums) {',
          '        Arrays.sort(nums);',
          '        List<List<Integer>> res = new ArrayList<>();',
          '        int n = nums.length;',
          '        for (int i = 0; i < n - 2; i++) {',
          '            if (nums[i] > 0) break;',
          '            if (i > 0 && nums[i] == nums[i - 1]) continue;',
          '            int l = i + 1, r = n - 1;',
          '            while (l < r) {',
          '                int s = nums[i] + nums[l] + nums[r];',
          '                if (s == 0) {',
          '                    res.add(Arrays.asList(nums[i], nums[l], nums[r]));',
          '                    while (l < r && nums[l] == nums[l + 1]) l++;',
          '                    while (l < r && nums[r] == nums[r - 1]) r--;',
          '                    l++; r--;',
          '                } else if (s < 0) l++;',
          '                else r--;',
          '            }',
          '        }',
          '        return res;',
          '    }',
          '}',
        ],
        typescript: [
          'function threeSum(nums: number[]): number[][] {',
          '  nums.sort((a, b) => a - b);',
          '  const res: number[][] = [];',
          '  const n = nums.length;',
          '  for (let i = 0; i < n - 2; i++) {',
          '    if (nums[i] > 0) break;',
          '    if (i > 0 && nums[i] === nums[i - 1]) continue;',
          '    let l = i + 1, r = n - 1;',
          '    while (l < r) {',
          '      const s = nums[i] + nums[l] + nums[r];',
          '      if (s === 0) {',
          '        res.push([nums[i], nums[l], nums[r]]);',
          '        while (l < r && nums[l] === nums[l + 1]) l++;',
          '        while (l < r && nums[r] === nums[r - 1]) r--;',
          '        l++; r--;',
          '      } else if (s < 0) l++;',
          '      else r--;',
          '    }',
          '  }',
          '  return res;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Three Nested Loops + Hash Set',
      subtitle: 'Enumerate all n³ triplets and deduplicate with set',
      timeComplexity: 'O(n³)',
      timeComplexityDetail: 'Three nested loops checking all combinations.',
      spaceComplexity: 'O(n)',
      spaceComplexityDetail: 'Hash set storing serialized triplets.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded on n = 3000',
      explanation: 'Try every triplet (i, j, k). If sum == 0, sort triplet and add to set.',
      keySteps: ['1. Loop `i`, `j`, `k`.', '2. If `sum == 0`, add sorted tuple to `seen`.', '3. Return unique triplets.'],
      code: {
        python: [
          'class Solution:',
          '    def threeSum(self, nums: List[int]) -> List[List[int]]:',
          '        seen = set()',
          '        n = len(nums)',
          '        for i in range(n):',
          '            for j in range(i + 1, n):',
          '                for k in range(j + 1, n):',
          '                    if nums[i] + nums[j] + nums[k] == 0:',
          '                        seen.add(tuple(sorted([nums[i], nums[j], nums[k]])))',
          '        return [list(t) for t in seen]',
        ],
        cpp: [
          '// O(n^3) brute force approach',
        ],
        java: [
          '// O(n^3) brute force approach',
        ],
        typescript: [
          '// O(n^3) brute force approach',
        ],
      },
    },
  },

  '3Sum Closest': {
    intuition:
      'Similar to 3Sum, sort the array first. For each index `i`, use two pointers `l` and `r` to find the triplet sum closest to target. Track `closest_sum` by updating whenever `|current_sum - target| < |closest_sum - target|`. If `current_sum < target`, increment `l`; if `current_sum > target`, decrement `r`; if `current_sum == target`, return immediately.',
    bottleneck:
      'Nested loops evaluating all triplets take O(n³) time. Sorting + Two Pointers evaluates in O(n²) time.',
    keyInvariant:
      'The monotonicity of the sorted array enables directional pointer movement towards target.',
    constraints: ['3 <= nums.length <= 500', '-1000 <= nums[i] <= 1000', '-10^4 <= target <= 10^4'],
    examples: [
      { input: 'nums = [-1,2,1,-4], target = 1', output: '2', explanation: 'Triplet [-1, 2, 1] sum is 2, closest to 1 (diff = 1).' },
      { input: 'nums = [0,0,0], target = 1', output: '0', explanation: 'Triplet [0, 0, 0] sum is 0.' },
    ],
    companies: ['Amazon', 'Google', 'Bloomberg', 'Facebook'],
    acceptanceRate: '45.7%',
    frequency: '75%',
    edgeCases: ['Target matches exact triplet sum (early return)', 'Array of exact length 3'],
    interviewTips: ['Initialize `closest_sum = nums[0] + nums[1] + nums[2]` instead of infinity to avoid integer overflow issues.'],
    optimal: {
      title: 'Sort + Two Pointers Closest Distance Tracking',
      subtitle: 'O(n²) time and O(1) space two-pointer approach',
      timeComplexity: 'O(n²)',
      timeComplexityDetail: 'Outer loop runs n times with O(n) two-pointer convergence inside.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Constant auxiliary space.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~40ms, Beats 98%)',
      explanation: 'Sort nums. Initialize closest sum to first three elements. Scan each i with two pointers l and r, updating closest sum.',
      keySteps: [
        '1. Sort `nums`.',
        '2. Initialize `closest = nums[0] + nums[1] + nums[2]`.',
        '3. For `i` in 0..n-3:',
        '   a. `l = i + 1`, `r = n - 1`.',
        '   b. While `l < r`:',
        '      - `s = nums[i] + nums[l] + nums[r]`.',
        '      - If `abs(s - target) < abs(closest - target)`: `closest = s`.',
        '      - If `s < target`: `l += 1`.',
        '      - Else if `s > target`: `r -= 1`.',
        '      - Else: return `target`.',
        '4. Return `closest`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def threeSumClosest(self, nums: List[int], target: int) -> int:',
          '        nums.sort()',
          '        closest = nums[0] + nums[1] + nums[2]',
          '        n = len(nums)',
          '        for i in range(n - 2):',
          '            l, r = i + 1, n - 1',
          '            while l < r:',
          '                s = nums[i] + nums[l] + nums[r]',
          '                if abs(s - target) < abs(closest - target):',
          '                    closest = s',
          '                if s < target:',
          '                    l += 1',
          '                elif s > target:',
          '                    r -= 1',
          '                else:',
          '                    return target',
          '        return closest',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          '#include <cmath>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int threeSumClosest(vector<int>& nums, int target) {',
          '        sort(nums.begin(), nums.end());',
          '        int closest = nums[0] + nums[1] + nums[2];',
          '        int n = nums.size();',
          '        for (int i = 0; i < n - 2; ++i) {',
          '            int l = i + 1, r = n - 1;',
          '            while (l < r) {',
          '                int s = nums[i] + nums[l] + nums[r];',
          '                if (abs(s - target) < abs(closest - target)) closest = s;',
          '                if (s < target) l++;',
          '                else if (s > target) r--;',
          '                else return target;',
          '            }',
          '        }',
          '        return closest;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.Arrays;',
          'class Solution {',
          '    public int threeSumClosest(int[] nums, int target) {',
          '        Arrays.sort(nums);',
          '        int closest = nums[0] + nums[1] + nums[2];',
          '        int n = nums.length;',
          '        for (int i = 0; i < n - 2; i++) {',
          '            int l = i + 1, r = n - 1;',
          '            while (l < r) {',
          '                int s = nums[i] + nums[l] + nums[r];',
          '                if (Math.abs(s - target) < Math.abs(closest - target)) closest = s;',
          '                if (s < target) l++;',
          '                else if (s > target) r--;',
          '                else return target;',
          '            }',
          '        }',
          '        return closest;',
          '    }',
          '}',
        ],
        typescript: [
          'function threeSumClosest(nums: number[], target: number): number {',
          '  nums.sort((a, b) => a - b);',
          '  let closest = nums[0] + nums[1] + nums[2];',
          '  const n = nums.length;',
          '  for (let i = 0; i < n - 2; i++) {',
          '    let l = i + 1, r = n - 1;',
          '    while (l < r) {',
          '      const s = nums[i] + nums[l] + nums[r];',
          '      if (Math.abs(s - target) < Math.abs(closest - target)) closest = s;',
          '      if (s < target) l++;',
          '      else if (s > target) r--;',
          '      else return target;',
          '    }',
          '  }',
          '  return closest;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Nested Loops Check All Triplets',
      subtitle: 'Exhaustive O(n³) search',
      timeComplexity: 'O(n³)',
      timeComplexityDetail: 'Three nested loops checking all triplets.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Constant memory.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded on larger n',
      explanation: 'Evaluate every triplet (i, j, k) and find minimum difference from target.',
      keySteps: ['1. Loop `i`, `j`, `k`.', '2. Track closest sum.'],
      code: {
        python: [
          'class Solution:',
          '    def threeSumClosest(self, nums: List[int], target: int) -> int:',
          '        n = len(nums)',
          '        closest = float("inf")',
          '        for i in range(n):',
          '            for j in range(i + 1, n):',
          '                for k in range(j + 1, n):',
          '                    s = nums[i] + nums[j] + nums[k]',
          '                    if abs(s - target) < abs(closest - target):',
          '                        closest = s',
          '        return closest',
        ],
        cpp: [
          '// O(n^3) approach',
        ],
        java: [
          '// O(n^3) approach',
        ],
        typescript: [
          '// O(n^3) approach',
        ],
      },
    },
  },

  'Container With Most Water': {
    intuition:
      'The area formed between lines at `l` and `r` is `(r - l) * min(height[l], height[r])`. Starting with maximum width `l = 0` and `r = n - 1`, moving the taller line inward cannot possibly increase the area because width decreases and the height is bounded by the shorter line. Therefore, we must greedily move the SHORTER line inward in search of a taller boundary.',
    bottleneck:
      'Checking all pairs of boundaries takes O(n²) time. Greedily shrinking the shorter boundary achieves optimal O(n) single pass.',
    keyInvariant:
      'Moving the pointer with the smaller height is the only way to potentially find a larger area with smaller width.',
    constraints: ['n == height.length', '2 <= n <= 10^5', '0 <= height[i] <= 10^4'],
    examples: [
      { input: 'height = [1,8,6,2,5,4,8,3,7]', output: '49', explanation: 'Max area between index 1 (height 8) and index 8 (height 7): min(8,7) * (8-1) = 7 * 7 = 49.' },
      { input: 'height = [1,1]', output: '1', explanation: 'min(1,1) * (1-0) = 1.' },
    ],
    companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Bloomberg'],
    acceptanceRate: '54.5%',
    frequency: '96%',
    edgeCases: ['Array with all equal heights', 'Strictly increasing or decreasing heights'],
    interviewTips: ['Formally prove why we discard the shorter line: any other rectangle using that shorter line has strictly smaller width and at most equal height, so it cannot beat the current area.'],
    optimal: {
      title: 'Two Pointers Shrink Shorter Side',
      subtitle: 'O(n) time and O(1) space greedy elimination',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Pointers l and r meet in exactly n - 1 steps.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only max_area, l, and r variables.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~550ms, Beats 97%)',
      explanation: 'Initialize l=0, r=n-1. Calculate area, update max_area, and move the pointer with the smaller height inward.',
      keySteps: [
        '1. `l = 0`, `r = len(height) - 1`, `max_area = 0`.',
        '2. While `l < r`:',
        '   a. `h = min(height[l], height[r])`.',
        '   b. `max_area = max(max_area, h * (r - l))`.',
        '   c. If `height[l] < height[r]`: `l += 1`.',
        '   d. Else: `r -= 1`.',
        '3. Return `max_area`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def maxArea(self, height: List[int]) -> int:',
          '        l, r = 0, len(height) - 1',
          '        max_area = 0',
          '        while l < r:',
          '            h = min(height[l], height[r])',
          '            max_area = max(max_area, h * (r - l))',
          '            if height[l] < height[r]:',
          '                l += 1',
          '            else:',
          '                r -= 1',
          '        return max_area',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int maxArea(vector<int>& height) {',
          '        int l = 0, r = height.size() - 1, max_area = 0;',
          '        while (l < r) {',
          '            int h = min(height[l], height[r]);',
          '            max_area = max(max_area, h * (r - l));',
          '            if (height[l] < height[r]) l++;',
          '            else r--;',
          '        }',
          '        return max_area;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int maxArea(int[] height) {',
          '        int l = 0, r = height.length - 1, maxArea = 0;',
          '        while (l < r) {',
          '            int h = Math.min(height[l], height[r]);',
          '            maxArea = Math.max(maxArea, h * (r - l));',
          '            if (height[l] < height[r]) l++;',
          '            else r--;',
          '        }',
          '        return maxArea;',
          '    }',
          '}',
        ],
        typescript: [
          'function maxArea(height: number[]): number {',
          '  let l = 0, r = height.length - 1, maxArea = 0;',
          '  while (l < r) {',
          '    const h = Math.min(height[l], height[r]);',
          '    maxArea = Math.max(maxArea, h * (r - l));',
          '    if (height[l] < height[r]) l++;',
          '    else r--;',
          '  }',
          '  return maxArea;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Check All Pairs of Lines',
      subtitle: 'Nested loops testing all (i, j)',
      timeComplexity: 'O(n²)',
      timeComplexityDetail: 'Checks all n*(n-1)/2 pairs.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded on n = 10^5',
      explanation: 'Loop i from 0 to n-1 and j from i+1 to n-1, calculating area for every pair.',
      keySteps: ['1. Loop `i`.', '2. Loop `j`.', '3. `max_area = max(max_area, min(height[i], height[j]) * (j - i))`.'],
      code: {
        python: [
          'class Solution:',
          '    def maxArea(self, height: List[int]) -> int:',
          '        max_area = 0',
          '        n = len(height)',
          '        for i in range(n):',
          '            for j in range(i + 1, n):',
          '                max_area = max(max_area, min(height[i], height[j]) * (j - i))',
          '        return max_area',
        ],
        cpp: [
          '// O(n^2) brute force',
        ],
        java: [
          '// O(n^2) brute force',
        ],
        typescript: [
          '// O(n^2) brute force',
        ],
      },
    },
  },

  'Trapping Rain Water': {
    intuition:
      'The water trapped above bar `i` is determined by `min(max_left, max_right) - height[i]`. Using two pointers `l = 0` and `r = n - 1` with running `max_left` and `max_right`, whichever side has the smaller maximum acts as the bottleneck for trapped water on that side. This allows calculating trapped water in a single pass in O(n) time and O(1) auxiliary memory.',
    bottleneck:
      'Computing prefix and suffix max arrays takes O(n) extra space. Two pointers eliminates extra memory entirely.',
    keyInvariant:
      'When `max_left < max_right`, water at position `l` is strictly bounded by `max_left`, regardless of what heights exist between `l` and `r`.',
    constraints: ['n == height.length', '1 <= n <= 2 * 10^4', '0 <= height[i] <= 10^5'],
    examples: [
      { input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6', explanation: '6 units of rain water are trapped.' },
      { input: 'height = [4,2,0,3,2,5]', output: '9', explanation: '9 units of rain water trapped.' },
    ],
    companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Apple', 'Goldman Sachs'],
    acceptanceRate: '60.1%',
    frequency: '98%',
    edgeCases: ['Empty array or length < 3 (returns 0)', 'Array in strictly ascending or descending order (returns 0)', 'Flat array of all equal heights (returns 0)'],
    interviewTips: [
      'Present the intuition of `water[i] = min(max_L, max_R) - h[i]` first, then show how Two Pointers simplifies prefix/suffix arrays into O(1) space.',
    ],
    optimal: {
      title: 'Two Pointers Running Maxima Traversal',
      subtitle: 'O(n) time and O(1) space two-pointer calculation',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Single pass where l and r converge in n steps.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only 4 scalar variables (l, r, max_left, max_right).',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~45ms, Beats 99%)',
      explanation: 'Track max_l and max_r. If max_l < max_r, calculate water at l and increment l; otherwise calculate water at r and decrement r.',
      keySteps: [
        '1. If `not height`: return 0.',
        '2. `l = 0`, `r = len(height) - 1`, `max_l = height[l]`, `max_r = height[r]`, `water = 0`.',
        '3. While `l < r`:',
        '   a. If `max_l < max_r`: `l += 1`, `max_l = max(max_l, height[l])`, `water += max_l - height[l]`.',
        '   b. Else: `r -= 1`, `max_r = max(max_r, height[r])`, `water += max_r - height[r]`.',
        '4. Return `water`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def trap(self, height: List[int]) -> int:',
          '        if not height:',
          '            return 0',
          '        l, r = 0, len(height) - 1',
          '        max_l, max_r = height[l], height[r]',
          '        water = 0',
          '        while l < r:',
          '            if max_l < max_r:',
          '                l += 1',
          '                max_l = max(max_l, height[l])',
          '                water += max_l - height[l]',
          '            else:',
          '                r -= 1',
          '                max_r = max(max_r, height[r])',
          '                water += max_r - height[r]',
          '        return water',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int trap(vector<int>& height) {',
          '        if (height.empty()) return 0;',
          '        int l = 0, r = height.size() - 1;',
          '        int max_l = height[l], max_r = height[r];',
          '        int water = 0;',
          '        while (l < r) {',
          '            if (max_l < max_r) {',
          '                l++;',
          '                max_l = max(max_l, height[l]);',
          '                water += max_l - height[l];',
          '            } else {',
          '                r--;',
          '                max_r = max(max_r, height[r]);',
          '                water += max_r - height[r];',
          '            }',
          '        }',
          '        return water;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int trap(int[] height) {',
          '        if (height == null || height.length == 0) return 0;',
          '        int l = 0, r = height.length - 1;',
          '        int maxL = height[l], maxR = height[r];',
          '        int water = 0;',
          '        while (l < r) {',
          '            if (maxL < maxR) {',
          '                l++;',
          '                maxL = Math.max(maxL, height[l]);',
          '                water += maxL - height[l];',
          '            } else {',
          '                r--;',
          '                maxR = Math.max(maxR, height[r]);',
          '                water += maxR - height[r];',
          '            }',
          '        }',
          '        return water;',
          '    }',
          '}',
        ],
        typescript: [
          'function trap(height: number[]): number {',
          '  if (height.length === 0) return 0;',
          '  let l = 0, r = height.length - 1;',
          '  let maxL = height[l], maxR = height[r];',
          '  let water = 0;',
          '  while (l < r) {',
          '    if (maxL < maxR) {',
          '      l++;',
          '      maxL = Math.max(maxL, height[l]);',
          '      water += maxL - height[l];',
          '    } else {',
          '      r--;',
          '      maxR = Math.max(maxR, height[r]);',
          '      water += maxR - height[r];',
          '    }',
          '  }',
          '  return water;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Prefix and Suffix Max Arrays (DP)',
      subtitle: 'Precompute max_left and max_right arrays in O(n) space',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Three linear passes.',
      spaceComplexity: 'O(n)',
      spaceComplexityDetail: 'Two auxiliary arrays of size n.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Uses O(n) memory)',
      explanation: 'Precompute max_left[i] and max_right[i] arrays, then sum min(max_left[i], max_right[i]) - height[i].',
      keySteps: ['1. Compute `left_max` array.', '2. Compute `right_max` array.', '3. Accumulate `min(left_max[i], right_max[i]) - height[i]`.'],
      code: {
        python: [
          'class Solution:',
          '    def trap(self, height: List[int]) -> int:',
          '        n = len(height)',
          '        if n == 0: return 0',
          '        l_max = [0] * n',
          '        r_max = [0] * n',
          '        l_max[0] = height[0]',
          '        for i in range(1, n): l_max[i] = max(l_max[i - 1], height[i])',
          '        r_max[-1] = height[-1]',
          '        for i in range(n - 2, -1, -1): r_max[i] = max(r_max[i + 1], height[i])',
          '        return sum(min(l_max[i], r_max[i]) - height[i] for i in range(n))',
        ],
        cpp: [
          '// DP array approach',
        ],
        java: [
          '// DP array approach',
        ],
        typescript: [
          '// DP array approach',
        ],
      },
    },
  },

  'Remove Duplicates from Sorted Array': {
    intuition:
      'Because the array is sorted, duplicates are adjacent. Use a slow write pointer `w = 1` and a fast read pointer `r`. When `nums[r] != nums[r - 1]`, write `nums[w] = nums[r]` and increment `w`.',
    bottleneck:
      'Deleting elements from an array causes O(n) shifting per duplicate, yielding O(n²) time. Two-pointer in-place write achieves O(n) time and O(1) space.',
    keyInvariant:
      'Subarray nums[0..w-1] always contains unique sorted elements without duplicates.',
    constraints: ['1 <= nums.length <= 3 * 10^4', '-100 <= nums[i] <= 100', 'nums is sorted in non-decreasing order.'],
    examples: [
      { input: 'nums = [1,1,2]', output: '2, nums = [1,2,_]', explanation: 'Unique elements are 1 and 2.' },
      { input: 'nums = [0,0,1,1,1,2,2,3,3,4]', output: '5, nums = [0,1,2,3,4,_,_,_,_,_]', explanation: 'First 5 elements are [0,1,2,3,4].' },
    ],
    companies: ['Microsoft', 'Amazon', 'Apple', 'Meta', 'Google'],
    acceptanceRate: '54.2%',
    frequency: '88%',
    edgeCases: ['Array of size 1 (returns 1)', 'All elements identical', 'No duplicates'],
    interviewTips: ['Return the count `w` of unique elements, as required by LeetCode judging harness.'],
    optimal: {
      title: 'Two Pointers Slow and Fast Write Pointer',
      subtitle: 'In-place compaction in O(n) time and O(1) space',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Single scan of array from index 1 to n - 1.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only index pointers.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~45ms, Beats 99%)',
      explanation: 'Read pointer scans through array. Whenever a new value appears, copy to write pointer and advance write pointer.',
      keySteps: [
        '1. Set write pointer `w = 1`.',
        '2. For `r` from 1 to `len(nums) - 1`:',
        '   a. If `nums[r] != nums[r - 1]`:',
        '      `nums[w] = nums[r]`',
        '      `w += 1`',
        '3. Return `w`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def removeDuplicates(self, nums: List[int]) -> int:',
          '        if not nums:',
          '            return 0',
          '        w = 1',
          '        for r in range(1, len(nums)):',
          '            if nums[r] != nums[r - 1]:',
          '                nums[w] = nums[r]',
          '                w += 1',
          '        return w',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int removeDuplicates(vector<int>& nums) {',
          '        if (nums.empty()) return 0;',
          '        int w = 1;',
          '        for (int r = 1; r < nums.size(); ++r) {',
          '            if (nums[r] != nums[r - 1]) nums[w++] = nums[r];',
          '        }',
          '        return w;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int removeDuplicates(int[] nums) {',
          '        if (nums.length == 0) return 0;',
          '        int w = 1;',
          '        for (int r = 1; r < nums.length; r++) {',
          '            if (nums[r] != nums[r - 1]) nums[w++] = nums[r];',
          '        }',
          '        return w;',
          '    }',
          '}',
        ],
        typescript: [
          'function removeDuplicates(nums: number[]): number {',
          '  if (nums.length === 0) return 0;',
          '  let w = 1;',
          '  for (let r = 1; r < nums.length; r++) {',
          '    if (nums[r] !== nums[r - 1]) nums[w++] = nums[r];',
          '  }',
          '  return w;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Hash Set Extraction and Overwrite',
      subtitle: 'Extract unique elements with set and sort',
      timeComplexity: 'O(n log n)',
      timeComplexityDetail: 'Set insertion + sorting unique values.',
      spaceComplexity: 'O(n)',
      spaceComplexityDetail: 'Auxiliary set storage.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Uses extra space)',
      explanation: 'Use a set to find unique items, sort them, and write back into nums.',
      keySteps: ['1. Unique elements `u = sorted(set(nums))`.', '2. Overwrite `nums[:len(u)] = u`.', '3. Return `len(u)`.'],
      code: {
        python: [
          'class Solution:',
          '    def removeDuplicates(self, nums: List[int]) -> int:',
          '        u = sorted(set(nums))',
          '        nums[:len(u)] = u',
          '        return len(u)',
        ],
        cpp: [
          '// Set approach',
        ],
        java: [
          '// Set approach',
        ],
        typescript: [
          '// Set approach',
        ],
      },
    },
  },

  'Remove Duplicates from Sorted Array II': {
    intuition:
      'We are allowed to keep at most 2 occurrences of each unique number. Since the array is sorted, an incoming number `num` is valid to append at write position `w` if and only if `w < 2` OR `num > nums[w - 2]`. This generalized rule works for any at-most-k duplicates problem.',
    bottleneck:
      'Tracking frequency counts with a hash map requires O(n) space. Comparing with nums[w - 2] guarantees at most 2 duplicates in O(1) space.',
    keyInvariant:
      'For any index w >= 2, nums[w - 2] < nums[w] ensures no value appears more than twice in the output segment.',
    constraints: ['1 <= nums.length <= 3 * 10^4', '-10^4 <= nums[i] <= 10^4', 'nums is sorted in non-decreasing order.'],
    examples: [
      { input: 'nums = [1,1,1,2,2,3]', output: '5, nums = [1,1,2,2,3,_]', explanation: 'Keeps at most two 1s.' },
      { input: 'nums = [0,0,1,1,1,1,2,3,3]', output: '7, nums = [0,0,1,1,2,3,3,_,_]', explanation: 'Keeps at most two 1s.' },
    ],
    companies: ['Amazon', 'Facebook', 'Microsoft', 'Bloomberg'],
    acceptanceRate: '57.1%',
    frequency: '79%',
    edgeCases: ['Array of size <= 2 (returns len(nums))', 'All elements identical'],
    interviewTips: ['Show the generalized pattern: to keep at most k elements, check `if w < k or num > nums[w - k]: nums[w] = num; w += 1`.'],
    optimal: {
      title: 'At-Most-K In-Place Write Pointer (k = 2)',
      subtitle: 'O(n) time and O(1) space generalized compaction',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Single pass iterating through all elements.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Single write pointer w.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~40ms, Beats 99%)',
      explanation: 'Iterate through all numbers. If write pointer w < 2 or current number > nums[w-2], write to nums[w] and increment w.',
      keySteps: [
        '1. Set `w = 0`.',
        '2. For each `num` in `nums`:',
        '   If `w < 2` or `num > nums[w - 2]`:',
        '      `nums[w] = num`',
        '      `w += 1`',
        '3. Return `w`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def removeDuplicates(self, nums: List[int]) -> int:',
          '        w = 0',
          '        for num in nums:',
          '            if w < 2 or num > nums[w - 2]:',
          '                nums[w] = num',
          '                w += 1',
          '        return w',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int removeDuplicates(vector<int>& nums) {',
          '        int w = 0;',
          '        for (int num : nums) {',
          '            if (w < 2 || num > nums[w - 2]) nums[w++] = num;',
          '        }',
          '        return w;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int removeDuplicates(int[] nums) {',
          '        int w = 0;',
          '        for (int num : nums) {',
          '            if (w < 2 || num > nums[w - 2]) nums[w++] = num;',
          '        }',
          '        return w;',
          '    }',
          '}',
        ],
        typescript: [
          'function removeDuplicates(nums: number[]): number {',
          '  let w = 0;',
          '  for (const num of nums) {',
          '    if (w < 2 || num > nums[w - 2]) nums[w++] = num;',
          '  }',
          '  return w;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Count Frequency with Hash Map',
      subtitle: 'Build auxiliary array capped at 2 per element',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Linear pass with map lookups.',
      spaceComplexity: 'O(n)',
      spaceComplexityDetail: 'Auxiliary frequency storage.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Uses extra space)',
      explanation: 'Track counts of each element and build new array appending at most 2 of each number.',
      keySteps: ['1. Count frequencies.', '2. Rebuild array with min(count, 2).'],
      code: {
        python: [
          'from collections import Counter',
          'class Solution:',
          '    def removeDuplicates(self, nums: List[int]) -> int:',
          '        counts = Counter(nums)',
          '        res = []',
          '        for k in sorted(counts.keys()):',
          '            res.extend([k] * min(2, counts[k]))',
          '        nums[:len(res)] = res',
          '        return len(res)',
        ],
        cpp: [
          '// Counter approach',
        ],
        java: [
          '// Counter approach',
        ],
        typescript: [
          '// Counter approach',
        ],
      },
    },
  },

  'Move Zeroes': {
    intuition:
      'We must shift all 0s to the end of the array while maintaining the relative order of non-zero elements in-place. Maintain a write pointer `w = 0`. For each element `nums[r]`, if it is non-zero, swap `nums[w]` and `nums[r]` and increment `w`.',
    bottleneck:
      'Creating a new array takes O(n) extra space. Shifting elements on each zero deletion takes O(n²). Swap-based compaction runs in O(n) time and O(1) space.',
    keyInvariant:
      'All elements in nums[0..w-1] are non-zero in original relative order, and nums[w..r] are zeros.',
    constraints: ['1 <= nums.length <= 10^4', '-2^31 <= nums[i] <= 2^31 - 1', 'Must modify in-place without copying array.'],
    examples: [
      { input: 'nums = [0,1,0,3,12]', output: '[1,3,12,0,0]', explanation: 'Non-zero order preserved, zeros moved to end.' },
      { input: 'nums = [0]', output: '[0]', explanation: 'Single element zero.' },
    ],
    companies: ['Meta', 'Amazon', 'Apple', 'Microsoft', 'Bloomberg'],
    acceptanceRate: '61.6%',
    frequency: '92%',
    edgeCases: ['Array contains no zeros', 'Array contains all zeros', 'Zeroes at beginning vs end'],
    interviewTips: ['Mention that swapping `nums[w]` and `nums[r]` combines the compaction pass and zero-filling into a single pass.'],
    optimal: {
      title: 'Two Pointers In-Place Swap Compaction',
      subtitle: 'Single pass O(n) time and O(1) space',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Single traversal through array with at most n swaps.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'In-place modifications only.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~120ms, Beats 98%)',
      explanation: 'Maintain write pointer w. For each non-zero element at r, swap nums[w] with nums[r] and increment w.',
      keySteps: [
        '1. Set write pointer `w = 0`.',
        '2. For `r` from 0 to `len(nums) - 1`:',
        '   If `nums[r] != 0`:',
        '      Swap `nums[w]` and `nums[r]`',
        '      `w += 1`',
      ],
      code: {
        python: [
          'class Solution:',
          '    def moveZeroes(self, nums: List[int]) -> None:',
          '        w = 0',
          '        for r in range(len(nums)):',
          '            if nums[r] != 0:',
          '                nums[w], nums[r] = nums[r], nums[w]',
          '                w += 1',
        ],
        cpp: [
          '#include <vector>',
          '#include <utility>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    void moveZeroes(vector<int>& nums) {',
          '        int w = 0;',
          '        for (int r = 0; r < nums.size(); ++r) {',
          '            if (nums[r] != 0) {',
          '                swap(nums[w++], nums[r]);',
          '            }',
          '        }',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public void moveZeroes(int[] nums) {',
          '        int w = 0;',
          '        for (int r = 0; r < nums.length; r++) {',
          '            if (nums[r] != 0) {',
          '                int temp = nums[w];',
          '                nums[w] = nums[r];',
          '                nums[r] = temp;',
          '                w++;',
          '            }',
          '        }',
          '    }',
          '}',
        ],
        typescript: [
          'function moveZeroes(nums: number[]): void {',
          '  let w = 0;',
          '  for (let r = 0; r < nums.length; r++) {',
          '    if (nums[r] !== 0) {',
          '      [nums[w], nums[r]] = [nums[r], nums[w]];',
          '      w++;',
          '    }',
          '  }',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Auxiliary Array Copy and Fill Zeros',
      subtitle: 'Copy non-zeros to extra array and pad with 0s',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Two linear passes.',
      spaceComplexity: 'O(n)',
      spaceComplexityDetail: 'Allocates new array.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Uses extra memory)',
      explanation: 'Filter non-zeros into a temporary array and pad the rest with zeros.',
      keySteps: ['1. `non_zeros = [x for x in nums if x != 0]`.', '2. `nums[:] = non_zeros + [0] * (len(nums) - len(non_zeros))`.'],
      code: {
        python: [
          'class Solution:',
          '    def moveZeroes(self, nums: List[int]) -> None:',
          '        non_zeros = [x for x in nums if x != 0]',
          '        nums[:len(non_zeros)] = non_zeros',
          '        nums[len(non_zeros):] = [0] * (len(nums) - len(non_zeros))',
        ],
        cpp: [
          '// Copy non-zeros approach',
        ],
        java: [
          '// Copy non-zeros approach',
        ],
        typescript: [
          '// Copy non-zeros approach',
        ],
      },
    },
  },

  '4Sum': {
    intuition:
      'Generalize the 3Sum approach using a recursive k-Sum framework or two nested loops + Two Pointers. Sort the array first. Fix the first two elements `nums[i]` and `nums[j]`, then run Two Pointers `l` and `r` to find pairs summing to `target - nums[i] - nums[j]`. Skip duplicates at all 4 levels.',
    bottleneck:
      'Brute force checking all quadruplets takes O(n⁴). Sorting + 2 loops + Two Pointers runs in O(n³) time.',
    keyInvariant:
      'Skipping adjacent equal numbers for indices i, j, l, and r guarantees distinct quadruplets.',
    constraints: ['1 <= nums.length <= 200', '-10^9 <= nums[i] <= 10^9', '-10^9 <= target <= 10^9'],
    examples: [
      { input: 'nums = [1,0,-1,0,-2,2], target = 0', output: '[[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]', explanation: 'Unique quadruplets summing to 0.' },
      { input: 'nums = [2,2,2,2,2], target = 8', output: '[[2,2,2,2]]', explanation: 'Single unique quadruplet.' },
    ],
    companies: ['Amazon', 'Google', 'Apple', 'Meta'],
    acceptanceRate: '36.4%',
    frequency: '72%',
    edgeCases: ['Target sum causes 32-bit integer overflow (use 64-bit int in C++/Java)', 'Array length < 4'],
    interviewTips: ['Show how this generalizes to any k-Sum in O(n^(k-1)) time recursively.'],
    optimal: {
      title: 'Sort + Two Nested Loops with Two Pointers (k-Sum)',
      subtitle: 'O(n³) time and O(1) space duplicate-skipping search',
      timeComplexity: 'O(n³)',
      timeComplexityDetail: 'Two outer loops O(n²) with O(n) two-pointer search inside.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Excluding return list.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~85ms, Beats 97%)',
      explanation: 'Sort array. Loop i and j with duplicate skipping. Use two pointers l and r to find remaining pairs.',
      keySteps: [
        '1. Sort `nums`.',
        '2. Loop `i` from 0 to `n-4`, skipping duplicates.',
        '3. Loop `j` from `i+1` to `n-3`, skipping duplicates.',
        '4. Set `l = j + 1`, `r = n - 1`. While `l < r`:',
        '   - `s = nums[i] + nums[j] + nums[l] + nums[r]`.',
        '   - If `s == target`: record quadruplet, advance `l` and `r` past duplicates.',
        '   - If `s < target`: `l += 1`.',
        '   - Else: `r -= 1`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def fourSum(self, nums: List[int], target: int) -> List[List[int]]:',
          '        nums.sort()',
          '        res = []',
          '        n = len(nums)',
          '        for i in range(n - 3):',
          '            if i > 0 and nums[i] == nums[i - 1]:',
          '                continue',
          '            for j in range(i + 1, n - 2):',
          '                if j > i + 1 and nums[j] == nums[j - 1]:',
          '                    continue',
          '                l, r = j + 1, n - 1',
          '                while l < r:',
          '                    s = nums[i] + nums[j] + nums[l] + nums[r]',
          '                    if s == target:',
          '                        res.append([nums[i], nums[j], nums[l], nums[r]])',
          '                        while l < r and nums[l] == nums[l + 1]:',
          '                            l += 1',
          '                        while l < r and nums[r] == nums[r - 1]:',
          '                            r -= 1',
          '                        l += 1',
          '                        r -= 1',
          '                    elif s < target:',
          '                        l += 1',
          '                    else:',
          '                        r -= 1',
          '        return res',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    vector<vector<int>> fourSum(vector<int>& nums, int target) {',
          '        sort(nums.begin(), nums.end());',
          '        vector<vector<int>> res;',
          '        int n = nums.size();',
          '        for (int i = 0; i < n - 3; ++i) {',
          '            if (i > 0 && nums[i] == nums[i - 1]) continue;',
          '            for (int j = i + 1; j < n - 2; ++j) {',
          '                if (j > i + 1 && nums[j] == nums[j - 1]) continue;',
          '                int l = j + 1, r = n - 1;',
          '                while (l < r) {',
          '                    long long s = (long long)nums[i] + nums[j] + nums[l] + nums[r];',
          '                    if (s == target) {',
          '                        res.push_back({nums[i], nums[j], nums[l], nums[r]});',
          '                        while (l < r && nums[l] == nums[l + 1]) l++;',
          '                        while (l < r && nums[r] == nums[r - 1]) r--;',
          '                        l++; r--;',
          '                    } else if (s < target) l++;',
          '                    else r--;',
          '                }',
          '            }',
          '        }',
          '        return res;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.*;',
          'class Solution {',
          '    public List<List<Integer>> fourSum(int[] nums, int target) {',
          '        Arrays.sort(nums);',
          '        List<List<Integer>> res = new ArrayList<>();',
          '        int n = nums.length;',
          '        for (int i = 0; i < n - 3; i++) {',
          '            if (i > 0 && nums[i] == nums[i - 1]) continue;',
          '            for (int j = i + 1; j < n - 2; j++) {',
          '                if (j > i + 1 && nums[j] == nums[j - 1]) continue;',
          '                int l = j + 1, r = n - 1;',
          '                while (l < r) {',
          '                    long s = (long) nums[i] + nums[j] + nums[l] + nums[r];',
          '                    if (s == target) {',
          '                        res.add(Arrays.asList(nums[i], nums[j], nums[l], nums[r]));',
          '                        while (l < r && nums[l] == nums[l + 1]) l++;',
          '                        while (l < r && nums[r] == nums[r - 1]) r--;',
          '                        l++; r--;',
          '                    } else if (s < target) l++;',
          '                    else r--;',
          '                }',
          '            }',
          '        }',
          '        return res;',
          '    }',
          '}',
        ],
        typescript: [
          'function fourSum(nums: number[], target: number): number[][] {',
          '  nums.sort((a, b) => a - b);',
          '  const res: number[][] = [];',
          '  const n = nums.length;',
          '  for (let i = 0; i < n - 3; i++) {',
          '    if (i > 0 && nums[i] === nums[i - 1]) continue;',
          '    for (let j = i + 1; j < n - 2; j++) {',
          '      if (j > i + 1 && nums[j] === nums[j - 1]) continue;',
          '      let l = j + 1, r = n - 1;',
          '      while (l < r) {',
          '        const s = nums[i] + nums[j] + nums[l] + nums[r];',
          '        if (s === target) {',
          '          res.push([nums[i], nums[j], nums[l], nums[r]]);',
          '          while (l < r && nums[l] === nums[l + 1]) l++;',
          '          while (l < r && nums[r] === nums[r - 1]) r--;',
          '          l++; r--;',
          '        } else if (s < target) l++;',
          '        else r--;',
          '      }',
          '    }',
          '  }',
          '  return res;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Four Nested Loops Exhaustive Enumeration',
      subtitle: 'Check all n⁴ combinations with hash set',
      timeComplexity: 'O(n⁴)',
      timeComplexityDetail: 'Four nested loops.',
      spaceComplexity: 'O(n)',
      spaceComplexityDetail: 'Set to deduplicate.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Enumerate all quadruplets (i, j, k, m) and add matching sums to set.',
      keySteps: ['1. Four nested loops.', '2. Deduplicate with set.'],
      code: {
        python: [
          'class Solution:',
          '    def fourSum(self, nums: List[int], target: int) -> List[List[int]]:',
          '        # Brute force 4 nested loops',
          '        pass',
        ],
        cpp: [
          '// O(n^4) approach',
        ],
        java: [
          '// O(n^4) approach',
        ],
        typescript: [
          '// O(n^4) approach',
        ],
      },
    },
  },

  'Boats to Save People': {
    intuition:
      'Each boat carries at most 2 people with total weight <= `limit`. Sort people by weight. Greedily pair the heaviest person `people[r]` with the lightest person `people[l]`. If their combined weight `people[l] + people[r] <= limit`, both fit in one boat (increment `l`). Regardless, the heaviest person `people[r]` must take this boat (decrement `r`). Count one boat per step.',
    bottleneck:
      'Dynamic programming or combinations exploration takes exponential time. Sorting + Greedy Two Pointers solves it in O(n log n) time and O(1) space.',
    keyInvariant:
      'If the lightest available person cannot share a boat with the heaviest available person, no other available person can share with that heaviest person either.',
    constraints: ['1 <= people.length <= 5 * 10^4', '1 <= people[i] <= limit <= 3 * 10^4'],
    examples: [
      { input: 'people = [1,2], limit = 3', output: '1', explanation: '1 boat carries [1, 2].' },
      { input: 'people = [3,2,2,1], limit = 3', output: '3', explanation: 'Boats: [1, 2], [2], [3].' },
      { input: 'people = [3,5,3,4], limit = 5', output: '4', explanation: 'Boats: [3], [3], [4], [5].' },
    ],
    companies: ['Google', 'Amazon', 'Salesforce'],
    acceptanceRate: '56.3%',
    frequency: '76%',
    edgeCases: ['All people have weight == limit', 'Every pair of people sums <= limit'],
    interviewTips: ['Explain why the greedy choice is mathematically optimal: pairing the heaviest person with the lightest leaves the largest remaining capacity for subsequent pairings.'],
    optimal: {
      title: 'Greedy Heaviest + Lightest Pairing',
      subtitle: 'Sort in O(n log n) and pair inward in O(n) time',
      timeComplexity: 'O(n log n)',
      timeComplexityDetail: 'Sorting takes O(n log n); two-pointer scan takes O(n).',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Constant auxiliary memory.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~380ms, Beats 98%)',
      explanation: 'Sort weights. Pair lightest l with heaviest r. Advance l if both fit. Always decrement r and increment boat count.',
      keySteps: [
        '1. Sort `people`.',
        '2. `l = 0`, `r = len(people) - 1`, `boats = 0`.',
        '3. While `l <= r`:',
        '   a. If `people[l] + people[r] <= limit`: `l += 1`.',
        '   b. `r -= 1`.',
        '   c. `boats += 1`.',
        '4. Return `boats`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def numRescueBoats(self, people: List[int], limit: int) -> int:',
          '        people.sort()',
          '        l, r = 0, len(people) - 1',
          '        boats = 0',
          '        while l <= r:',
          '            if people[l] + people[r] <= limit:',
          '                l += 1',
          '            r -= 1',
          '            boats += 1',
          '        return boats',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int numRescueBoats(vector<int>& people, int limit) {',
          '        sort(people.begin(), people.end());',
          '        int l = 0, r = people.size() - 1, boats = 0;',
          '        while (l <= r) {',
          '            if (people[l] + people[r] <= limit) l++;',
          '            r--;',
          '            boats++;',
          '        }',
          '        return boats;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.Arrays;',
          'class Solution {',
          '    public int numRescueBoats(int[] people, int limit) {',
          '        Arrays.sort(people);',
          '        int l = 0, r = people.length - 1, boats = 0;',
          '        while (l <= r) {',
          '            if (people[l] + people[r] <= limit) l++;',
          '            r--;',
          '            boats++;',
          '        }',
          '        return boats;',
          '    }',
          '}',
        ],
        typescript: [
          'function numRescueBoats(people: number[], limit: number): number {',
          '  people.sort((a, b) => a - b);',
          '  let l = 0, r = people.length - 1, boats = 0;',
          '  while (l <= r) {',
          '    if (people[l] + people[r] <= limit) l++;',
          '    r--;',
          '    boats++;',
          '  }',
          '  return boats;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Counting Sort Buckets Greedy',
      subtitle: 'O(limit) bucket array pairing',
      timeComplexity: 'O(n + limit)',
      timeComplexityDetail: 'Count frequencies and pair from extremes.',
      spaceComplexity: 'O(limit)',
      spaceComplexityDetail: 'Frequency array of size limit + 1.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted',
      explanation: 'Use frequency array since limit <= 30000 to eliminate O(n log n) sorting.',
      keySteps: ['1. Count weights.', '2. Two pointers on frequency array.'],
      code: {
        python: [
          'class Solution:',
          '    def numRescueBoats(self, people: List[int], limit: int) -> int:',
          '        # Same two pointer logic on sorted array',
          '        people.sort()',
          '        l, r, b = 0, len(people) - 1, 0',
          '        while l <= r:',
          '            if people[l] + people[r] <= limit: l += 1',
          '            r -= 1; b += 1',
          '        return b',
        ],
        cpp: [
          '// Bucket sort approach',
        ],
        java: [
          '// Bucket sort approach',
        ],
        typescript: [
          '// Bucket sort approach',
        ],
      },
    },
  },

  'Valid Palindrome II': {
    intuition:
      'We are allowed to delete at most one character to make string `s` a palindrome. Use standard two pointers `l = 0` and `r = len(s) - 1`. If `s[l] == s[r]`, move inward. At the FIRST mismatch where `s[l] != s[r]`, the string can only be a valid palindrome if either `s[l+1..r]` is a palindrome (deleting `s[l]`) OR `s[l..r-1]` is a palindrome (deleting `s[r]`).',
    bottleneck:
      'Testing deletions of all n characters takes O(n²) time. Checking only at the first mismatch takes O(n) time.',
    keyInvariant:
      'Only the first mismatched pair requires branching into 2 sub-verifications; all preceding characters are guaranteed symmetric.',
    constraints: ['1 <= s.length <= 10^5', 's consists of lowercase English letters.'],
    examples: [
      { input: 's = "aba"', output: 'true', explanation: 'Already a palindrome.' },
      { input: 's = "abca"', output: 'true', explanation: 'Delete "c" to get "aba".' },
      { input: 's = "abc"', output: 'false', explanation: 'Cannot become a palindrome by deleting 1 character.' },
    ],
    companies: ['Meta', 'Amazon', 'Google', 'Microsoft', 'Bloomberg'],
    acceptanceRate: '40.2%',
    frequency: '91%',
    edgeCases: ['String is already a palindrome (0 deletions needed)', 'Mismatch occurs at the exact center', 'Neither single deletion produces a palindrome'],
    interviewTips: ['Helper function `is_palindrome_range(l, r)` keeps code clean and modular.'],
    optimal: {
      title: 'Two Pointers with Single Mismatch Branching',
      subtitle: 'O(n) time and O(1) space two-pointer verification',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Initial scan + at most one sub-palindrome check of length at most n.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Constant auxiliary variables.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~50ms, Beats 99%)',
      explanation: 'Scan from ends. At first mismatch, check if substring skipping left char or right char is a palindrome.',
      keySteps: [
        '1. Define helper `is_pal(l, r)`: returns `True` if `s[l..r]` is palindrome.',
        '2. `l = 0`, `r = len(s) - 1`.',
        '3. While `l < r`:',
        '   a. If `s[l] != s[r]`:',
        '      return `is_pal(l + 1, r) or is_pal(l, r - 1)`.',
        '   b. `l += 1`, `r -= 1`.',
        '4. Return `True`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def validPalindrome(self, s: str) -> bool:',
          '        def is_pal(l: int, r: int) -> bool:',
          '            while l < r:',
          '                if s[l] != s[r]:',
          '                    return False',
          '                l += 1',
          '                r -= 1',
          '            return True',
          '',
          '        l, r = 0, len(s) - 1',
          '        while l < r:',
          '            if s[l] != s[r]:',
          '                return is_pal(l + 1, r) or is_pal(l, r - 1)',
          '            l += 1',
          '            r -= 1',
          '        return True',
        ],
        cpp: [
          '#include <string>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    bool isPal(const string& s, int l, int r) {',
          '        while (l < r) {',
          '            if (s[l++] != s[r--]) return false;',
          '        }',
          '        return true;',
          '    }',
          '    bool validPalindrome(string s) {',
          '        int l = 0, r = s.length() - 1;',
          '        while (l < r) {',
          '            if (s[l] != s[r]) {',
          '                return isPal(s, l + 1, r) || isPal(s, l, r - 1);',
          '            }',
          '            l++; r--;',
          '        }',
          '        return true;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    private boolean isPal(String s, int l, int r) {',
          '        while (l < r) {',
          '            if (s.charAt(l++) != s.charAt(r--)) return false;',
          '        }',
          '        return true;',
          '    }',
          '    public boolean validPalindrome(String s) {',
          '        int l = 0, r = s.length() - 1;',
          '        while (l < r) {',
          '            if (s.charAt(l) != s.charAt(r)) {',
          '                return isPal(s, l + 1, r) || isPal(s, l, r - 1);',
          '            }',
          '            l++; r--;',
          '        }',
          '        return true;',
          '    }',
          '}',
        ],
        typescript: [
          'function validPalindrome(s: string): boolean {',
          '  const isPal = (l: number, r: number) => {',
          '    while (l < r) {',
          '      if (s[l++] !== s[r--]) return false;',
          '    }',
          '    return true;',
          '  };',
          '  let l = 0, r = s.length - 1;',
          '  while (l < r) {',
          '    if (s[l] !== s[r]) {',
          '      return isPal(l + 1, r) || isPal(l, r - 1);',
          '    }',
          '    l++; r--;',
          '  }',
          '  return true;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Delete Every Character and Check Palindrome',
      subtitle: 'Try deleting each index i in O(n²) time',
      timeComplexity: 'O(n²)',
      timeComplexityDetail: 'n deletions, each tested in O(n) time.',
      spaceComplexity: 'O(n)',
      spaceComplexityDetail: 'Substring copies.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded on n = 10^5',
      explanation: 'For each character i in s, construct s without s[i] and check if it is a palindrome.',
      keySteps: ['1. For `i` in 0..n-1: test `s[:i] + s[i+1:] == (s[:i] + s[i+1:])[::-1]`.'],
      code: {
        python: [
          'class Solution:',
          '    def validPalindrome(self, s: str) -> bool:',
          '        if s == s[::-1]: return True',
          '        for i in range(len(s)):',
          '            t = s[:i] + s[i+1:]',
          '            if t == t[::-1]: return True',
          '        return False',
        ],
        cpp: [
          '// O(n^2) brute force',
        ],
        java: [
          '// O(n^2) brute force',
        ],
        typescript: [
          '// O(n^2) brute force',
        ],
      },
    },
  },

  'Backspace String Compare': {
    intuition:
      'A backspace `#` deletes the preceding character. Traversing BACKWARDS from right to left allows determining whether each character is deleted by maintaining a `skip` counter. Whenever `#` is seen, increment `skip`. If a regular character is seen with `skip > 0`, decrement `skip`. Compare the surviving characters from both strings moving backwards in O(1) space.',
    bottleneck:
      'Simulating with a Stack takes O(N + M) space. Backward iteration with skip counters achieves O(1) auxiliary memory.',
    keyInvariant:
      'Moving backwards ensures we know if a character is deleted before we ever evaluate it.',
    constraints: ['1 <= s.length, t.length <= 200', 's and t only contain lowercase letters and "#" characters.'],
    examples: [
      { input: 's = "ab#c", t = "ad#c"', output: 'true', explanation: 'Both become "ac".' },
      { input: 's = "ab##", t = "c#d#"', output: 'true', explanation: 'Both become "".' },
      { input: 's = "a#c", t = "b"', output: 'false', explanation: '"c" != "b".' },
    ],
    companies: ['Google', 'Meta', 'Amazon', 'Microsoft'],
    acceptanceRate: '48.9%',
    frequency: '84%',
    edgeCases: ['More backspaces than characters `s = "a###b"`', 'Empty resulting strings', 'Strings of different lengths'],
    interviewTips: ['Show the helper function/loop that moves pointer backwards to next valid non-deleted character.'],
    optimal: {
      title: 'Two Pointers Reverse Traversal with Skip Counters',
      subtitle: 'O(N + M) time and O(1) space in-place comparison',
      timeComplexity: 'O(N + M)',
      timeComplexityDetail: 'Each character in s and t inspected at most twice.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Two pointer indices and two skip counters.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~30ms, Beats 99%)',
      explanation: 'Iterate backwards. Accumulate skip on `#`. Consume skip on valid characters. Compare first active characters.',
      keySteps: [
        '1. `i = len(s) - 1`, `j = len(t) - 1`, `skip_s = 0`, `skip_t = 0`.',
        '2. While `i >= 0` or `j >= 0`:',
        '   a. Find next valid char in `s` moving backward.',
        '   b. Find next valid char in `t` moving backward.',
        '   c. If one string has char and other does not: return `False`.',
        '   d. If both have chars and `s[i] != t[j]`: return `False`.',
        '   e. `i -= 1`, `j -= 1`.',
        '3. Return `True`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def backspaceCompare(self, s: str, t: str) -> bool:',
          '        i, j = len(s) - 1, len(t) - 1',
          '        skip_s = skip_t = 0',
          '        while i >= 0 or j >= 0:',
          '            while i >= 0:',
          '                if s[i] == "#":',
          '                    skip_s += 1',
          '                    i -= 1',
          '                elif skip_s > 0:',
          '                    skip_s -= 1',
          '                    i -= 1',
          '                else:',
          '                    break',
          '            while j >= 0:',
          '                if t[j] == "#":',
          '                    skip_t += 1',
          '                    j -= 1',
          '                elif skip_t > 0:',
          '                    skip_t -= 1',
          '                    j -= 1',
          '                else:',
          '                    break',
          '            if (i >= 0) != (j >= 0):',
          '                return False',
          '            if i >= 0 and j >= 0 and s[i] != t[j]:',
          '                return False',
          '            i -= 1',
          '            j -= 1',
          '        return True',
        ],
        cpp: [
          '#include <string>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    bool backspaceCompare(string s, string t) {',
          '        int i = s.length() - 1, j = t.length() - 1;',
          '        int skip_s = 0, skip_t = 0;',
          '        while (i >= 0 || j >= 0) {',
          '            while (i >= 0) {',
          '                if (s[i] == \'#\') { skip_s++; i--; }',
          '                else if (skip_s > 0) { skip_s--; i--; }',
          '                else break;',
          '            }',
          '            while (j >= 0) {',
          '                if (t[j] == \'#\') { skip_t++; j--; }',
          '                else if (skip_t > 0) { skip_t--; j--; }',
          '                else break;',
          '            }',
          '            if ((i >= 0) != (j >= 0)) return false;',
          '            if (i >= 0 && j >= 0 && s[i] != t[j]) return false;',
          '            i--; j--;',
          '        }',
          '        return true;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public boolean backspaceCompare(String s, String t) {',
          '        int i = s.length() - 1, j = t.length() - 1;',
          '        int skipS = 0, skipT = 0;',
          '        while (i >= 0 || j >= 0) {',
          '            while (i >= 0) {',
          '                if (s.charAt(i) == \'#\') { skipS++; i--; }',
          '                else if (skipS > 0) { skipS--; i--; }',
          '                else break;',
          '            }',
          '            while (j >= 0) {',
          '                if (t.charAt(j) == \'#\') { skipT++; j--; }',
          '                else if (skipT > 0) { skipT--; j--; }',
          '                else break;',
          '            }',
          '            if ((i >= 0) != (j >= 0)) return false;',
          '            if (i >= 0 && j >= 0 && s.charAt(i) != t.charAt(j)) return false;',
          '            i--; j--;',
          '        }',
          '        return true;',
          '    }',
          '}',
        ],
        typescript: [
          'function backspaceCompare(s: string, t: string): boolean {',
          '  let i = s.length - 1, j = t.length - 1;',
          '  let skipS = 0, skipT = 0;',
          '  while (i >= 0 || j >= 0) {',
          '    while (i >= 0) {',
          '      if (s[i] === "#") { skipS++; i--; }',
          '      else if (skipS > 0) { skipS--; i--; }',
          '      else break;',
          '    }',
          '    while (j >= 0) {',
          '      if (t[j] === "#") { skipT++; j--; }',
          '      else if (skipT > 0) { skipT--; j--; }',
          '      else break;',
          '    }',
          '    if ((i >= 0) !== (j >= 0)) return false;',
          '    if (i >= 0 && j >= 0 && s[i] !== t[j]) return false;',
          '    i--; j--;',
          '  }',
          '  return true;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Stack Simulation',
      subtitle: 'Build resulting string using a stack',
      timeComplexity: 'O(N + M)',
      timeComplexityDetail: 'Linear pass pushing and popping.',
      spaceComplexity: 'O(N + M)',
      spaceComplexityDetail: 'Stacks for both strings.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Uses extra space)',
      explanation: 'Use a stack for each string: push characters, pop on `#`. Compare resulting stacks.',
      keySteps: ['1. Helper `build(str)`: push char, pop on `#`.', '2. Return `build(s) == build(t)`.'],
      code: {
        python: [
          'class Solution:',
          '    def backspaceCompare(self, s: str, t: str) -> bool:',
          '        def build(string):',
          '            st = []',
          '            for c in string:',
          '                if c != "#": st.append(c)',
          '                elif st: st.pop()',
          '            return "".join(st)',
          '        return build(s) == build(t)',
        ],
        cpp: [
          '// Stack approach',
        ],
        java: [
          '// Stack approach',
        ],
        typescript: [
          '// Stack approach',
        ],
      },
    },
  },

  'Squares of a Sorted Array': {
    intuition:
      'The array is sorted, but may contain negative numbers. Squaring negative numbers makes them large positives. The largest squares will always be at either the extreme LEFT or extreme RIGHT of the array. Use two pointers `l = 0` and `r = n - 1`, compare `nums[l]²` and `nums[r]²`, and place the larger square at the BACK of the result array moving inward.',
    bottleneck:
      'Squaring every element and calling standard sort takes O(n log n) time. Two pointers exploits the sorted input to place elements in O(n) linear time.',
    keyInvariant:
      'At each step, max(nums[l]², nums[r]²) is the largest remaining square among all unprocessed elements.',
    constraints: ['1 <= nums.length <= 10^4', '-10^4 <= nums[i] <= 10^4', 'nums is sorted in non-decreasing order.'],
    examples: [
      { input: 'nums = [-4,-1,0,3,10]', output: '[0,1,9,16,100]', explanation: 'Squares are [16,1,0,9,100], sorted [0,1,9,16,100].' },
      { input: 'nums = [-7,-3,2,3,11]', output: '[4,9,9,49,121]', explanation: 'Squares sorted.' },
    ],
    companies: ['Meta', 'Amazon', 'Apple', 'Google', 'Microsoft'],
    acceptanceRate: '72.3%',
    frequency: '88%',
    edgeCases: ['All negative numbers', 'All positive numbers', 'Single element array'],
    interviewTips: ['Filling the result array from back to front (index n-1 down to 0) avoids needing to reverse the array at the end.'],
    optimal: {
      title: 'Two Pointers Filling Back-to-Front',
      subtitle: 'O(n) linear time and O(1) auxiliary space (excluding output)',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Each element placed in result array in exactly n steps.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Output array `res` only.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~140ms, Beats 99%)',
      explanation: 'Pointers l=0, r=n-1. Compare squares at l and r, place larger square at result pointer pos (starts at n-1) and decrement pos.',
      keySteps: [
        '1. `n = len(nums)`, `res = [0] * n`, `l = 0`, `r = n - 1`, `pos = n - 1`.',
        '2. While `l <= r`:',
        '   a. `sq_l = nums[l] * nums[l]`, `sq_r = nums[r] * nums[r]`.',
        '   b. If `sq_l > sq_r`: `res[pos] = sq_l`, `l += 1`.',
        '   c. Else: `res[pos] = sq_r`, `r -= 1`.',
        '   d. `pos -= 1`.',
        '3. Return `res`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def sortedSquares(self, nums: List[int]) -> List[int]:',
          '        n = len(nums)',
          '        res = [0] * n',
          '        l, r, pos = 0, n - 1, n - 1',
          '        while l <= r:',
          '            sq_l = nums[l] * nums[l]',
          '            sq_r = nums[r] * nums[r]',
          '            if sq_l > sq_r:',
          '                res[pos] = sq_l',
          '                l += 1',
          '            else:',
          '                res[pos] = sq_r',
          '                r -= 1',
          '            pos -= 1',
          '        return res',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    vector<int> sortedSquares(vector<int>& nums) {',
          '        int n = nums.size();',
          '        vector<int> res(n);',
          '        int l = 0, r = n - 1, pos = n - 1;',
          '        while (l <= r) {',
          '            int sq_l = nums[l] * nums[l];',
          '            int sq_r = nums[r] * nums[r];',
          '            if (sq_l > sq_r) {',
          '                res[pos--] = sq_l;',
          '                l++;',
          '            } else {',
          '                res[pos--] = sq_r;',
          '                r--;',
          '            }',
          '        }',
          '        return res;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int[] sortedSquares(int[] nums) {',
          '        int n = nums.length;',
          '        int[] res = new int[n];',
          '        int l = 0, r = n - 1, pos = n - 1;',
          '        while (l <= r) {',
          '            int sqL = nums[l] * nums[l];',
          '            int sqR = nums[r] * nums[r];',
          '            if (sqL > sqR) {',
          '                res[pos--] = sqL;',
          '                l++;',
          '            } else {',
          '                res[pos--] = sqR;',
          '                r--;',
          '            }',
          '        }',
          '        return res;',
          '    }',
          '}',
        ],
        typescript: [
          'function sortedSquares(nums: number[]): number[] {',
          '  const n = nums.length;',
          '  const res = new Array(n);',
          '  let l = 0, r = n - 1, pos = n - 1;',
          '  while (l <= r) {',
          '    const sqL = nums[l] * nums[l];',
          '    const sqR = nums[r] * nums[r];',
          '    if (sqL > sqR) {',
          '      res[pos--] = sqL;',
          '      l++;',
          '    } else {',
          '      res[pos--] = sqR;',
          '      r--;',
          '    }',
          '  }',
          '  return res;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Square and Sort',
      subtitle: 'Square all elements and sort in O(n log n)',
      timeComplexity: 'O(n log n)',
      timeComplexityDetail: 'Sorting takes O(n log n).',
      spaceComplexity: 'O(1) or O(n)',
      spaceComplexityDetail: 'Sorting memory.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Suboptimal runtime)',
      explanation: 'Square every element in nums and apply standard sort.',
      keySteps: ['1. Return `sorted(x * x for x in nums)`.'],
      code: {
        python: [
          'class Solution:',
          '    def sortedSquares(self, nums: List[int]) -> List[int]:',
          '        return sorted(x * x for x in nums)',
        ],
        cpp: [
          '// Square and sort',
        ],
        java: [
          '// Square and sort',
        ],
        typescript: [
          '// Square and sort',
        ],
      },
    },
  },
}
