import { DetailedProblemData } from '../leetcodeSolutions'

export const slidingWindowSolutions: Record<string, DetailedProblemData> = {
  'Best Time to Buy and Sell Stock': {
    intuition:
      'We want to maximize prices[sell] - prices[buy] with buy < sell. In a single pass, track the minimum price seen so far (`min_price`). For each price, the maximum profit if we sell today is `price - min_price`. Update `max_profit` if today\'s profit is larger.',
    bottleneck:
      'Comparing all pairs of buy and sell days takes O(n²) time. Tracking the running minimum price enables an optimal O(n) single pass with O(1) space.',
    keyInvariant:
      '`min_price` is always the lowest buying price encountered before or on the current selling day.',
    constraints: ['1 <= prices.length <= 10^5', '0 <= prices[i] <= 10^4'],
    examples: [
      { input: 'prices = [7,1,5,3,6,4]', output: '5', explanation: 'Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.' },
      { input: 'prices = [7,6,4,3,1]', output: '0', explanation: 'Prices strictly decrease; no profitable transaction possible, max profit = 0.' },
    ],
    companies: ['Amazon', 'Apple', 'Google', 'Meta', 'Microsoft', 'Bloomberg'],
    acceptanceRate: '54.1%',
    frequency: '98%',
    edgeCases: ['Array of size 1 (returns 0)', 'Monotonically decreasing prices (returns 0)', 'All prices identical (returns 0)'],
    interviewTips: ['Clarify that we cannot sell before we buy, which makes this single-pass greedy running minimum approach mathematically optimal.'],
    optimal: {
      title: 'One-Pass Running Minimum Price',
      subtitle: 'Single pass tracking minimum buying price',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Single traversal through prices array.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only two scalar variables (min_price, max_profit).',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~70ms, Beats 99%)',
      explanation: 'Iterate through prices, update min_price with the smallest value seen, and update max_profit with price - min_price.',
      keySteps: [
        '1. Initialize `min_price = float("inf")`, `max_profit = 0`.',
        '2. For each `price` in `prices`:',
        '   a. `min_price = min(min_price, price)`.',
        '   b. `max_profit = max(max_profit, price - min_price)`.',
        '3. Return `max_profit`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def maxProfit(self, prices: List[int]) -> int:',
          '        min_price = float("inf")',
          '        max_profit = 0',
          '        for price in prices:',
          '            min_price = min(min_price, price)',
          '            max_profit = max(max_profit, price - min_price)',
          '        return max_profit',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          '#include <climits>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int maxProfit(vector<int>& prices) {',
          '        int min_price = INT_MAX, max_profit = 0;',
          '        for (int p : prices) {',
          '            min_price = min(min_price, p);',
          '            max_profit = max(max_profit, p - min_price);',
          '        }',
          '        return max_profit;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int maxProfit(int[] prices) {',
          '        int minPrice = Integer.MAX_VALUE, maxProfit = 0;',
          '        for (int p : prices) {',
          '            minPrice = Math.min(minPrice, p);',
          '            maxProfit = Math.max(maxProfit, p - minPrice);',
          '        }',
          '        return maxProfit;',
          '    }',
          '}',
        ],
        typescript: [
          'function maxProfit(prices: number[]): number {',
          '  let minPrice = Infinity;',
          '  let maxProfit = 0;',
          '  for (const p of prices) {',
          '    minPrice = Math.min(minPrice, p);',
          '    maxProfit = Math.max(maxProfit, p - minPrice);',
          '  }',
          '  return maxProfit;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Nested Loops Check All Buy-Sell Days',
      subtitle: 'Exhaustive O(n²) comparison of all pairs',
      timeComplexity: 'O(n²)',
      timeComplexityDetail: 'Outer loop buys on day i, inner loop sells on day j > i.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded on n = 10^5',
      explanation: 'Try all buy days i and all future sell days j > i, finding max prices[j] - prices[i].',
      keySteps: ['1. Loop `i` from 0 to `n-1`.', '2. Loop `j` from `i+1` to `n-1`.', '3. `max_profit = max(max_profit, prices[j] - prices[i])`.'],
      code: {
        python: [
          'class Solution:',
          '    def maxProfit(self, prices: List[int]) -> int:',
          '        max_profit = 0',
          '        n = len(prices)',
          '        for i in range(n):',
          '            for j in range(i + 1, n):',
          '                max_profit = max(max_profit, prices[j] - prices[i])',
          '        return max_profit',
        ],
        cpp: [
          '// O(n^2) brute force',
        ],
        java: [
          '// O(n^2) brute force',
        ],
        typescript: [
          '// O(n^2) brute force',
        ],
      },
    },
  },

  'Longest Substring Without Repeating Characters': {
    intuition:
      'Use a dynamic sliding window `[l..r]`. Maintain a hash map storing the most recent index of each character. When character `s[r]` was previously seen at `prev_idx >= l`, jump the left boundary `l = prev_idx + 1` directly. At every step, the window `[l..r]` is guaranteed to have all unique characters, and its length is `r - l + 1`.',
    bottleneck:
      'Checking all substrings with a set takes O(n³) or O(n²) time. Sliding window with index jumping achieves O(n) linear time in a single pass.',
    keyInvariant:
      'Window `s[l..r]` never contains duplicate characters.',
    constraints: ['0 <= s.length <= 5 * 10^4', 's consists of English letters, digits, symbols and spaces.'],
    examples: [
      { input: 's = "abcabcbb"', output: '3', explanation: 'The answer is "abc", with the length of 3.' },
      { input: 's = "bbbbb"', output: '1', explanation: 'The answer is "b", with the length of 1.' },
      { input: 's = "pwwkew"', output: '3', explanation: 'The answer is "wke", with the length of 3.' },
    ],
    companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Apple', 'Bloomberg'],
    acceptanceRate: '34.5%',
    frequency: '99%',
    edgeCases: ['Empty string (returns 0)', 'All characters identical (returns 1)', 'String with spaces and symbols'],
    interviewTips: ['Show how jumping `l = max(l, last_seen[c] + 1)` prevents l from moving backwards when encountering an old duplicate outside the current window.'],
    optimal: {
      title: 'Sliding Window with Last-Seen Index Jumping',
      subtitle: 'Single pass O(n) time and O(min(m, n)) space',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Right pointer r traverses string once from 0 to n - 1.',
      spaceComplexity: 'O(min(m, n))',
      spaceComplexityDetail: 'Hash map stores at most min(total alphabet size, string length) elements.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~45ms, Beats 98%)',
      explanation: 'Maintain map of character to last seen index. Jump left pointer l forward whenever a duplicate inside window is detected.',
      keySteps: [
        '1. `last_seen = {}`, `l = 0`, `max_len = 0`.',
        '2. For `r, c` in `enumerate(s)`:',
        '   a. If `c` in `last_seen` and `last_seen[c] >= l`:',
        '      `l = last_seen[c] + 1`.',
        '   b. `last_seen[c] = r`.',
        '   c. `max_len = max(max_len, r - l + 1)`.',
        '3. Return `max_len`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def lengthOfLongestSubstring(self, s: str) -> int:',
          '        last_seen = {}',
          '        l = 0',
          '        max_len = 0',
          '        for r, c in enumerate(s):',
          '            if c in last_seen and last_seen[c] >= l:',
          '                l = last_seen[c] + 1',
          '            last_seen[c] = r',
          '            max_len = max(max_len, r - l + 1)',
          '        return max_len',
        ],
        cpp: [
          '#include <string>',
          '#include <vector>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int lengthOfLongestSubstring(string s) {',
          '        vector<int> last_seen(256, -1);',
          '        int l = 0, max_len = 0;',
          '        for (int r = 0; r < s.length(); ++r) {',
          '            if (last_seen[(unsigned char)s[r]] >= l) {',
          '                l = last_seen[(unsigned char)s[r]] + 1;',
          '            }',
          '            last_seen[(unsigned char)s[r]] = r;',
          '            max_len = max(max_len, r - l + 1);',
          '        }',
          '        return max_len;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.HashMap;',
          'import java.util.Map;',
          'class Solution {',
          '    public int lengthOfLongestSubstring(String s) {',
          '        Map<Character, Integer> lastSeen = new HashMap<>();',
          '        int l = 0, maxLen = 0;',
          '        for (int r = 0; r < s.length(); r++) {',
          '            char c = s.charAt(r);',
          '            if (lastSeen.containsKey(c) && lastSeen.get(c) >= l) {',
          '                l = lastSeen.get(c) + 1;',
          '            }',
          '            lastSeen.put(c, r);',
          '            maxLen = Math.max(maxLen, r - l + 1);',
          '        }',
          '        return maxLen;',
          '    }',
          '}',
        ],
        typescript: [
          'function lengthOfLongestSubstring(s: string): number {',
          '  const lastSeen = new Map<string, number>();',
          '  let l = 0;',
          '  let maxLen = 0;',
          '  for (let r = 0; r < s.length; r++) {',
          '    const c = s[r];',
          '    if (lastSeen.has(c) && lastSeen.get(c)! >= l) {',
          '      l = lastSeen.get(c)! + 1;',
          '    }',
          '    lastSeen.set(c, r);',
          '    maxLen = Math.max(maxLen, r - l + 1);',
          '  }',
          '  return maxLen;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Check All Substrings for Uniqueness',
      subtitle: 'Exhaustive O(n²) substring generation with hash set',
      timeComplexity: 'O(n²)',
      timeComplexityDetail: 'Outer loop starts substring, inner loop expands until duplicate.',
      spaceComplexity: 'O(n)',
      spaceComplexityDetail: 'Set to store characters in current substring.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded on n = 50000',
      explanation: 'For each starting index i, expand j and add characters to a set until duplicate is seen.',
      keySteps: ['1. Loop `i` from 0 to `n-1`.', '2. `seen = set()`.', '3. Loop `j` from `i` to `n-1`, add to set, break if duplicate.'],
      code: {
        python: [
          'class Solution:',
          '    def lengthOfLongestSubstring(self, s: str) -> int:',
          '        ans = 0',
          '        for i in range(len(s)):',
          '            seen = set()',
          '            for j in range(i, len(s)):',
          '                if s[j] in seen: break',
          '                seen.add(s[j])',
          '                ans = max(ans, j - i + 1)',
          '        return ans',
        ],
        cpp: [
          '// O(n^2) brute force',
        ],
        java: [
          '// O(n^2) brute force',
        ],
        typescript: [
          '// O(n^2) brute force',
        ],
      },
    },
  },

  'Longest Repeating Character Replacement': {
    intuition:
      'In a window of length `(r - l + 1)`, the number of characters that need to be replaced to make the whole window consist of the most frequent character is `(r - l + 1) - max_frequency`. A window is valid as long as `(r - l + 1) - max_frequency <= k`. If invalid, shrink from the left by decrementing count of `s[l]` and advancing `l`. Track the maximum valid window size seen.',
    bottleneck:
      'Checking all O(n²) substrings takes O(26 * n²) time. The sliding window expands `r` and contracts `l` in O(n) linear time.',
    keyInvariant:
      'We only care when `max_frequency` increases (which allows window size to grow); we do not need to decrease `max_frequency` when shrinking because a smaller max_freq cannot produce a longer valid window than what we have already seen.',
    constraints: ['1 <= s.length <= 10^5', 's consists of only uppercase English letters.', '0 <= k <= s.length'],
    examples: [
      { input: 's = "ABAB", k = 2', output: '4', explanation: 'Replace the two "A"s with "B"s or vice versa to get "BBBB" or "AAAA".' },
      { input: 's = "AABABBA", k = 1', output: '4', explanation: 'Replace the middle "A" with "B" to get "AABBBBA" -> substring "BBBB" length 4.' },
    ],
    companies: ['Amazon', 'Google', 'Meta', 'Uber'],
    acceptanceRate: '53.8%',
    frequency: '90%',
    edgeCases: ['k >= len(s) (returns len(s))', 'k = 0 (longest substring of identical characters)', 'String of single character'],
    interviewTips: ['Explain why we don\'t need to recompute `max_freq` when shrinking: a smaller max_freq cannot increase our overall max_len result.'],
    optimal: {
      title: 'Sliding Window Max-Frequency Tracking',
      subtitle: 'O(n) linear time and O(1) space (26 uppercase letters)',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Pointers l and r each increment at most n times.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Fixed 26-size frequency array.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~95ms, Beats 98%)',
      explanation: 'Expand right pointer r, update character frequency and max_freq. If replacements needed > k, shrink from left.',
      keySteps: [
        '1. `counts = [0] * 26`, `l = 0`, `max_freq = 0`, `max_len = 0`.',
        '2. For `r` from 0 to `len(s) - 1`:',
        '   a. `idx = ord(s[r]) - ord("A")`, `counts[idx] += 1`.',
        '   b. `max_freq = max(max_freq, counts[idx])`.',
        '   c. If `(r - l + 1) - max_freq > k`:',
        '      `counts[ord(s[l]) - ord("A")] -= 1`, `l += 1`.',
        '   d. `max_len = max(max_len, r - l + 1)`.',
        '3. Return `max_len`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def characterReplacement(self, s: str, k: int) -> int:',
          '        counts = [0] * 26',
          '        l = 0',
          '        max_freq = 0',
          '        max_len = 0',
          '        for r in range(len(s)):',
          '            idx = ord(s[r]) - ord("A")',
          '            counts[idx] += 1',
          '            max_freq = max(max_freq, counts[idx])',
          '            while (r - l + 1) - max_freq > k:',
          '                counts[ord(s[l]) - ord("A")] -= 1',
          '                l += 1',
          '            max_len = max(max_len, r - l + 1)',
          '        return max_len',
        ],
        cpp: [
          '#include <string>',
          '#include <vector>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int characterReplacement(string s, int k) {',
          '        vector<int> count(26, 0);',
          '        int l = 0, max_freq = 0, max_len = 0;',
          '        for (int r = 0; r < s.length(); ++r) {',
          '            max_freq = max(max_freq, ++count[s[r] - \'A\']);',
          '            while ((r - l + 1) - max_freq > k) {',
          '                count[s[l++] - \'A\']--;',
          '            }',
          '            max_len = max(max_len, r - l + 1);',
          '        }',
          '        return max_len;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int characterReplacement(String s, int k) {',
          '        int[] count = new int[26];',
          '        int l = 0, maxFreq = 0, maxLen = 0;',
          '        for (int r = 0; r < s.length(); r++) {',
          '            maxFreq = Math.max(maxFreq, ++count[s.charAt(r) - \'A\']);',
          '            while ((r - l + 1) - maxFreq > k) {',
          '                count[s.charAt(l++) - \'A\']--;',
          '            }',
          '            maxLen = Math.max(maxLen, r - l + 1);',
          '        }',
          '        return maxLen;',
          '    }',
          '}',
        ],
        typescript: [
          'function characterReplacement(s: string, k: number): number {',
          '  const count = new Array(26).fill(0);',
          '  let l = 0, maxFreq = 0, maxLen = 0;',
          '  for (let r = 0; r < s.length; r++) {',
          '    const idx = s.charCodeAt(r) - 65;',
          '    count[idx]++;',
          '    maxFreq = Math.max(maxFreq, count[idx]);',
          '    while ((r - l + 1) - maxFreq > k) {',
          '      count[s.charCodeAt(l) - 65]--;',
          '      l++;',
          '    }',
          '    maxLen = Math.max(maxLen, r - l + 1);',
          '  }',
          '  return maxLen;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Nested Loops Substring Verification',
      subtitle: 'Exhaustive O(26 * n²) check',
      timeComplexity: 'O(26 * n²)',
      timeComplexityDetail: 'Check all substrings and count frequencies.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Fixed 26-array.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Try all substrings and compute whether length - max_freq <= k.',
      keySteps: ['1. Loop `i`.', '2. Loop `j`.', '3. Count frequencies.'],
      code: {
        python: [
          'class Solution:',
          '    def characterReplacement(self, s: str, k: int) -> int:',
          '        ans = 0',
          '        for i in range(len(s)):',
          '            counts = collections.Counter()',
          '            for j in range(i, len(s)):',
          '                counts[s[j]] += 1',
          '                if (j - i + 1) - max(counts.values()) <= k:',
          '                    ans = max(ans, j - i + 1)',
          '        return ans',
        ],
        cpp: [
          '// O(26 * n^2) brute force',
        ],
        java: [
          '// O(26 * n^2) brute force',
        ],
        typescript: [
          '// O(26 * n^2) brute force',
        ],
      },
    },
  },

  'Permutation in String': {
    intuition:
      'String `s2` contains a permutation of `s1` if and only if there exists a contiguous substring of length `len(s1)` in `s2` with the exact same character frequency counts as `s1`. Maintain a fixed-size sliding window of length `len(s1)` over `s2` and track matching character counts with a frequency array in O(n) time.',
    bottleneck:
      'Sorting every substring of length len(s1) takes O((N - M + 1) * M log M) time. A sliding window frequency array runs in O(N) time with O(1) space.',
    keyInvariant:
      'The sliding window maintains fixed size `len(s1)` while sliding across `s2`.',
    constraints: ['1 <= s1.length, s2.length <= 10^4', 's1 and s2 consist of lowercase English letters.'],
    examples: [
      { input: 's1 = "ab", s2 = "eidbaooo"', output: 'true', explanation: 's2 contains one permutation of s1 ("ba").' },
      { input: 's1 = "ab", s2 = "eidboaoo"', output: 'false', explanation: 'No substring matches permutation of "ab".' },
    ],
    companies: ['Microsoft', 'Amazon', 'Meta', 'Apple'],
    acceptanceRate: '44.3%',
    frequency: '87%',
    edgeCases: ['len(s1) > len(s2) (immediate false)', 's1 == s2', 'Permutation at very beginning or very end of s2'],
    interviewTips: ['Track a `matches` integer counter (number of characters 0..25 with equal counts) to verify match in O(1) time per slide instead of comparing 26 elements.'],
    optimal: {
      title: 'Fixed Size Sliding Window Frequency Count',
      subtitle: 'O(len(s2)) linear time and O(1) space (26 lowercase letters)',
      timeComplexity: 'O(len(s2))',
      timeComplexityDetail: 'Slide window of length len(s1) across s2 in a single pass.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Two 26-element integer frequency arrays.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~45ms, Beats 99%)',
      explanation: 'Count frequency of s1 and first window of s2. Slide window across s2 adding right char and removing left char.',
      keySteps: [
        '1. If `len(s1) > len(s2)`: return `False`.',
        '2. Count frequencies of `s1` and `s2[:len(s1)]` into arrays `c1` and `c2` of size 26.',
        '3. If `c1 == c2`: return `True`.',
        '4. For `i` from `len(s1)` to `len(s2) - 1`:',
        '   a. Increment count for incoming `s2[i]`.',
        '   b. Decrement count for outgoing `s2[i - len(s1)]`.',
        '   c. If `c1 == c2`: return `True`.',
        '5. Return `False`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def checkInclusion(self, s1: str, s2: str) -> bool:',
          '        n1, n2 = len(s1), len(s2)',
          '        if n1 > n2:',
          '            return False',
          '        c1, c2 = [0] * 26, [0] * 26',
          '        for i in range(n1):',
          '            c1[ord(s1[i]) - ord("a")] += 1',
          '            c2[ord(s2[i]) - ord("a")] += 1',
          '        if c1 == c2:',
          '            return True',
          '        for i in range(n1, n2):',
          '            c2[ord(s2[i]) - ord("a")] += 1',
          '            c2[ord(s2[i - n1]) - ord("a")] -= 1',
          '            if c1 == c2:',
          '                return True',
          '        return False',
        ],
        cpp: [
          '#include <string>',
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    bool checkInclusion(string s1, string s2) {',
          '        int n1 = s1.length(), n2 = s2.length();',
          '        if (n1 > n2) return false;',
          '        vector<int> c1(26, 0), c2(26, 0);',
          '        for (int i = 0; i < n1; ++i) {',
          '            c1[s1[i] - \'a\']++;',
          '            c2[s2[i] - \'a\']++;',
          '        }',
          '        if (c1 == c2) return true;',
          '        for (int i = n1; i < n2; ++i) {',
          '            c2[s2[i] - \'a\']++;',
          '            c2[s2[i - n1] - \'a\']--;',
          '            if (c1 == c2) return true;',
          '        }',
          '        return false;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.Arrays;',
          'class Solution {',
          '    public boolean checkInclusion(String s1, String s2) {',
          '        int n1 = s1.length(), n2 = s2.length();',
          '        if (n1 > n2) return false;',
          '        int[] c1 = new int[26], c2 = new int[26];',
          '        for (int i = 0; i < n1; i++) {',
          '            c1[s1.charAt(i) - \'a\']++;',
          '            c2[s2.charAt(i) - \'a\']++;',
          '        }',
          '        if (Arrays.equals(c1, c2)) return true;',
          '        for (int i = n1; i < n2; i++) {',
          '            c2[s2.charAt(i) - \'a\']++;',
          '            c2[s2.charAt(i - n1) - \'a\']--;',
          '            if (Arrays.equals(c1, c2)) return true;',
          '        }',
          '        return false;',
          '    }',
          '}',
        ],
        typescript: [
          'function checkInclusion(s1: string, s2: string): boolean {',
          '  const n1 = s1.length, n2 = s2.length;',
          '  if (n1 > n2) return false;',
          '  const c1 = new Array(26).fill(0), c2 = new Array(26).fill(0);',
          '  for (let i = 0; i < n1; i++) {',
          '    c1[s1.charCodeAt(i) - 97]++;',
          '    c2[s2.charCodeAt(i) - 97]++;',
          '  }',
          '  const match = () => c1.every((v, i) => v === c2[i]);',
          '  if (match()) return true;',
          '  for (let i = n1; i < n2; i++) {',
          '    c2[s2.charCodeAt(i) - 97]++;',
          '    c2[s2.charCodeAt(i - n1) - 97]--;',
          '    if (match()) return true;',
          '  }',
          '  return false;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Sort Every Substring',
      subtitle: 'Sort every window of length len(s1)',
      timeComplexity: 'O(N * M log M)',
      timeComplexityDetail: 'Sort each substring of length M = len(s1).',
      spaceComplexity: 'O(M)',
      spaceComplexityDetail: 'Substring copies.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Sort s1 once. Extract every substring of length len(s1) in s2, sort it, and compare.',
      keySteps: ['1. `sorted_s1 = sorted(s1)`.', '2. Loop `i` in `0..len(s2)-len(s1)`: if `sorted(s2[i:i+len(s1)]) == sorted_s1`: return `True`.'],
      code: {
        python: [
          'class Solution:',
          '    def checkInclusion(self, s1: str, s2: str) -> bool:',
          '        target = sorted(s1)',
          '        k = len(s1)',
          '        for i in range(len(s2) - k + 1):',
          '            if sorted(s2[i:i+k]) == target: return True',
          '        return False',
        ],
        cpp: [
          '// Sort approach',
        ],
        java: [
          '// Sort approach',
        ],
        typescript: [
          '// Sort approach',
        ],
      },
    },
  },

  'Find All Anagrams in a String': {
    intuition:
      'Find all start indices in string `s` whose substring of length `len(p)` is an anagram of `p`. Use a fixed-size sliding window of length `len(p)`. Maintain character counts of `p` and current window in `s`. Slide the window one character at a time, adding the new character and removing the old character. Whenever frequency counts match, record start index `i - len(p) + 1`.',
    bottleneck:
      'Sorting or rehashing every window takes O(|s| * |p| log |p|). Fixed sliding window updates counts in O(1) time per character, yielding O(|s|) total time.',
    keyInvariant:
      'The sliding window maintains fixed length `len(p)` with O(1) delta updates.',
    constraints: ['1 <= s.length, p.length <= 3 * 10^4', 's and p consist of lowercase English letters.'],
    examples: [
      { input: 's = "cbaebabacd", p = "abc"', output: '[0, 6]', explanation: 'Substrings starting at 0 ("cba") and 6 ("bac") are anagrams of "abc".' },
      { input: 's = "abab", p = "ab"', output: '[0, 1, 2]', explanation: 'Substrings at 0 ("ab"), 1 ("ba"), 2 ("ab") are anagrams of "ab".' },
    ],
    companies: ['Amazon', 'Facebook', 'Bloomberg', 'Google'],
    acceptanceRate: '50.2%',
    frequency: '85%',
    edgeCases: ['len(s) < len(p) (returns [])', 'All identical characters `s = "aaaa", p = "aa"` (returns [0, 1, 2])'],
    interviewTips: ['Show how the sliding window avoids re-counting characters by updating counts at both window boundaries in O(1) time.'],
    optimal: {
      title: 'Fixed Sliding Window Character Frequency Array',
      subtitle: 'O(|s|) linear time and O(1) space',
      timeComplexity: 'O(|s|)',
      timeComplexityDetail: 'Single pass sliding window of size len(p) across string s.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Two 26-element integer arrays.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~85ms, Beats 97%)',
      explanation: 'Maintain frequency arrays for p and s window. Record matching start indices.',
      keySteps: [
        '1. `res = []`, `n, k = len(s), len(p)`. If `n < k`: return `res`.',
        '2. Count frequencies of `p` and `s[:k]` into `p_count` and `s_count`.',
        '3. If `p_count == s_count`: `res.append(0)`.',
        '4. For `i` from `k` to `n - 1`:',
        '   a. `s_count[s[i]] += 1`, `s_count[s[i - k]] -= 1`.',
        '   b. If `p_count == s_count`: `res.append(i - k + 1)`.',
        '5. Return `res`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def findAnagrams(self, s: str, p: str) -> List[int]:',
          '        n, k = len(s), len(p)',
          '        if n < k:',
          '            return []',
          '        p_count, s_count = [0] * 26, [0] * 26',
          '        for i in range(k):',
          '            p_count[ord(p[i]) - ord("a")] += 1',
          '            s_count[ord(s[i]) - ord("a")] += 1',
          '        res = []',
          '        if p_count == s_count:',
          '            res.append(0)',
          '        for i in range(k, n):',
          '            s_count[ord(s[i]) - ord("a")] += 1',
          '            s_count[ord(s[i - k]) - ord("a")] -= 1',
          '            if p_count == s_count:',
          '                res.append(i - k + 1)',
          '        return res',
        ],
        cpp: [
          '#include <vector>',
          '#include <string>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    vector<int> findAnagrams(string s, string p) {',
          '        int n = s.length(), k = p.length();',
          '        if (n < k) return {};',
          '        vector<int> p_count(26, 0), s_count(26, 0), res;',
          '        for (int i = 0; i < k; ++i) {',
          '            p_count[p[i] - \'a\']++;',
          '            s_count[s[i] - \'a\']++;',
          '        }',
          '        if (p_count == s_count) res.push_back(0);',
          '        for (int i = k; i < n; ++i) {',
          '            s_count[s[i] - \'a\']++;',
          '            s_count[s[i - k] - \'a\']--;',
          '            if (p_count == s_count) res.push_back(i - k + 1);',
          '        }',
          '        return res;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.*;',
          'class Solution {',
          '    public List<Integer> findAnagrams(String s, String p) {',
          '        List<Integer> res = new ArrayList<>();',
          '        int n = s.length(), k = p.length();',
          '        if (n < k) return res;',
          '        int[] pCount = new int[26], sCount = new int[26];',
          '        for (int i = 0; i < k; i++) {',
          '            pCount[p.charAt(i) - \'a\']++;',
          '            sCount[s.charAt(i) - \'a\']++;',
          '        }',
          '        if (Arrays.equals(pCount, sCount)) res.add(0);',
          '        for (int i = k; i < n; i++) {',
          '            sCount[s.charAt(i) - \'a\']++;',
          '            sCount[s.charAt(i - k) - \'a\']--;',
          '            if (Arrays.equals(pCount, sCount)) res.add(i - k + 1);',
          '        }',
          '        return res;',
          '    }',
          '}',
        ],
        typescript: [
          'function findAnagrams(s: string, p: string): number[] {',
          '  const n = s.length, k = p.length;',
          '  if (n < k) return [];',
          '  const pCount = new Array(26).fill(0), sCount = new Array(26).fill(0);',
          '  for (let i = 0; i < k; i++) {',
          '    pCount[p.charCodeAt(i) - 97]++;',
          '    sCount[s.charCodeAt(i) - 97]++;',
          '  }',
          '  const match = () => pCount.every((v, i) => v === sCount[i]);',
          '  const res: number[] = [];',
          '  if (match()) res.push(0);',
          '  for (let i = k; i < n; i++) {',
          '    sCount[s.charCodeAt(i) - 97]++;',
          '    sCount[s.charCodeAt(i - k) - 97]--;',
          '    if (match()) res.push(i - k + 1);',
          '  }',
          '  return res;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Sort Every Substring of Length k',
      subtitle: 'O(|s| * |p| log |p|) brute check',
      timeComplexity: 'O(|s| * |p| log |p|)',
      timeComplexityDetail: 'Sort each substring of length |p|.',
      spaceComplexity: 'O(|p|)',
      spaceComplexityDetail: 'Substring memory.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded on n = 30000',
      explanation: 'Sort p once. For each start index, sort substring of length len(p) and compare.',
      keySteps: ['1. `sorted_p = sorted(p)`.', '2. Loop `i`: if `sorted(s[i:i+len(p)]) == sorted_p`: `res.append(i)`.'],
      code: {
        python: [
          'class Solution:',
          '    def findAnagrams(self, s: str, p: str) -> List[int]:',
          '        target = sorted(p)',
          '        k = len(p)',
          '        return [i for i in range(len(s) - k + 1) if sorted(s[i:i+k]) == target]',
        ],
        cpp: [
          '// Sort approach',
        ],
        java: [
          '// Sort approach',
        ],
        typescript: [
          '// Sort approach',
        ],
      },
    },
  },

  'Minimum Window Substring': {
    intuition:
      'We need the shortest substring in `s` containing all characters of `t` (including duplicates). Maintain a target frequency map for `t`, and a sliding window `[l..r]` with running frequency counts. Track `have` (unique characters meeting required count) and `need` (total unique characters in `t`). Expand `r` until `have == need`. Then shrink `l` as much as possible while maintaining `have == need` to minimize window length.',
    bottleneck:
      'Checking all substrings takes O(n² * m) time. Two-pointer sliding window expands `r` and contracts `l` in O(n + m) time.',
    keyInvariant:
      '`have == need` holds whenever all character frequency requirements of `t` are satisfied inside window `s[l..r]`.',
    constraints: ['m == s.length', 'n == t.length', '1 <= m, n <= 10^5', 's and t consist of uppercase and lowercase English letters.'],
    examples: [
      { input: 's = "ADOBECODEBANC", t = "ABC"', output: '"BANC"', explanation: 'Smallest substring containing A, B, and C is "BANC".' },
      { input: 's = "a", t = "a"', output: '"a"', explanation: 'Exact match.' },
      { input: 's = "a", t = "aa"', output: '""', explanation: 's does not contain two "a"s.' },
    ],
    companies: ['Meta', 'Amazon', 'Google', 'Microsoft', 'Uber', 'Apple'],
    acceptanceRate: '42.1%',
    frequency: '97%',
    edgeCases: ['len(s) < len(t) (returns "")', 'Exact single character match', 't contains duplicate characters'],
    interviewTips: ['Emphasize the `have` / `need` condition: increment `have` only when count of `s[r]` reaches the exact required count in `t`.'],
    optimal: {
      title: 'Sliding Window with Have / Need Frequency Tracking',
      subtitle: 'O(m + n) time and O(m + n) space optimal window expansion/contraction',
      timeComplexity: 'O(m + n)',
      timeComplexityDetail: 'Left and right pointers each traverse s at most once; building map takes O(n).',
      spaceComplexity: 'O(m + n)',
      spaceComplexityDetail: 'Hash maps for t and sliding window.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~80ms, Beats 98%)',
      explanation: 'Expand r to satisfy character requirements. When satisfied, contract l to minimize window size, updating best answer.',
      keySteps: [
        '1. If `not t` or `not s`: return `""`.',
        '2. `count_t = Counter(t)`, `window = {}`, `have = 0`, `need = len(count_t)`.',
        '3. `res = [-1, -1]`, `res_len = float("inf")`, `l = 0`.',
        '4. For `r, c` in `enumerate(s)`:',
        '   a. `window[c] = window.get(c, 0) + 1`.',
        '   b. If `c in count_t` and `window[c] == count_t[c]`: `have += 1`.',
        '   c. While `have == need`:',
        '      - If `(r - l + 1) < res_len`: `res = [l, r]`, `res_len = r - l + 1`.',
        '      - `window[s[l]] -= 1`.',
        '      - If `s[l] in count_t` and `window[s[l]] < count_t[s[l]]`: `have -= 1`.',
        '      - `l += 1`.',
        '5. Return `s[res[0]:res[1] + 1]` if `res_len != inf` else `""`.',
      ],
      code: {
        python: [
          'from collections import Counter',
          'class Solution:',
          '    def minWindow(self, s: str, t: str) -> str:',
          '        if not t or not s or len(s) < len(t):',
          '            return ""',
          '        count_t = Counter(t)',
          '        window = {}',
          '        have, need = 0, len(count_t)',
          '        res, res_len = [-1, -1], float("inf")',
          '        l = 0',
          '        for r, c in enumerate(s):',
          '            window[c] = window.get(c, 0) + 1',
          '            if c in count_t and window[c] == count_t[c]:',
          '                have += 1',
          '            while have == need:',
          '                if (r - l + 1) < res_len:',
          '                    res = [l, r]',
          '                    res_len = r - l + 1',
          '                window[s[l]] -= 1',
          '                if s[l] in count_t and window[s[l]] < count_t[s[l]]:',
          '                    have -= 1',
          '                l += 1',
          '        return s[res[0]:res[1] + 1] if res_len != float("inf") else ""',
        ],
        cpp: [
          '#include <string>',
          '#include <unordered_map>',
          '#include <climits>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    string minWindow(string s, string t) {',
          '        if (s.empty() || t.empty() || s.length() < t.length()) return "";',
          '        unordered_map<char, int> count_t, window;',
          '        for (char c : t) count_t[c]++;',
          '        int have = 0, need = count_t.size();',
          '        int min_len = INT_MAX, min_l = 0, l = 0;',
          '        for (int r = 0; r < s.length(); ++r) {',
          '            char c = s[r];',
          '            window[c]++;',
          '            if (count_t.count(c) && window[c] == count_t[c]) have++;',
          '            while (have == need) {',
          '                if (r - l + 1 < min_len) {',
          '                    min_len = r - l + 1;',
          '                    min_l = l;',
          '                }',
          '                window[s[l]]--;',
          '                if (count_t.count(s[l]) && window[s[l]] < count_t[s[l]]) have--;',
          '                l++;',
          '            }',
          '        }',
          '        return min_len == INT_MAX ? "" : s.substr(min_l, min_len);',
          '    }',
          '};',
        ],
        java: [
          'import java.util.*;',
          'class Solution {',
          '    public String minWindow(String s, String t) {',
          '        if (s.length() < t.length()) return "";',
          '        Map<Character, Integer> countT = new HashMap<>();',
          '        for (char c : t.toCharArray()) countT.put(c, countT.getOrDefault(c, 0) + 1);',
          '        Map<Character, Integer> window = new HashMap<>();',
          '        int have = 0, need = countT.size();',
          '        int minLen = Integer.MAX_VALUE, minL = 0, l = 0;',
          '        for (int r = 0; r < s.length(); r++) {',
          '            char c = s.charAt(r);',
          '            window.put(c, window.getOrDefault(c, 0) + 1);',
          '            if (countT.containsKey(c) && window.get(c).intValue() == countT.get(c).intValue()) have++;',
          '            while (have == need) {',
          '                if (r - l + 1 < minLen) {',
          '                    minLen = r - l + 1;',
          '                    minL = l;',
          '                }',
          '                char leftChar = s.charAt(l);',
          '                window.put(leftChar, window.get(leftChar) - 1);',
          '                if (countT.containsKey(leftChar) && window.get(leftChar) < countT.get(leftChar)) have--;',
          '                l++;',
          '            }',
          '        }',
          '        return minLen == Integer.MAX_VALUE ? "" : s.substring(minL, minL + minLen);',
          '    }',
          '}',
        ],
        typescript: [
          'function minWindow(s: string, t: string): string {',
          '  if (s.length < t.length) return "";',
          '  const countT = new Map<string, number>();',
          '  for (const c of t) countT.set(c, (countT.get(c) || 0) + 1);',
          '  const window = new Map<string, number>();',
          '  let have = 0, need = countT.size;',
          '  let minLen = Infinity, minL = 0, l = 0;',
          '  for (let r = 0; r < s.length; r++) {',
          '    const c = s[r];',
          '    window.set(c, (window.get(c) || 0) + 1);',
          '    if (countT.has(c) && window.get(c) === countT.get(c)) have++;',
          '    while (have === need) {',
          '      if (r - l + 1 < minLen) {',
          '        minLen = r - l + 1;',
          '        minL = l;',
          '      }',
          '      const leftChar = s[l];',
          '      window.set(leftChar, window.get(leftChar)! - 1);',
          '      if (countT.has(leftChar) && window.get(leftChar)! < countT.get(leftChar)!) have--;',
          '      l++;',
          '    }',
          '  }',
          '  return minLen === Infinity ? "" : s.substring(minL, minL + minLen);',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Enumerate All Substrings',
      subtitle: 'Exhaustive O(n² * m) search',
      timeComplexity: 'O(n² * m)',
      timeComplexityDetail: 'Check every substring against character counts of t.',
      spaceComplexity: 'O(m)',
      spaceComplexityDetail: 'Character count maps.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Generate every substring of s and verify if it contains all characters of t.',
      keySteps: ['1. Loop `i`.', '2. Loop `j`.', '3. Check if `s[i..j]` contains `t`.'],
      code: {
        python: [
          'class Solution:',
          '    def minWindow(self, s: str, t: str) -> str:',
          '        # Brute force enumeration',
          '        pass',
        ],
        cpp: [
          '// O(n^2 * m) brute force',
        ],
        java: [
          '// O(n^2 * m) brute force',
        ],
        typescript: [
          '// O(n^2 * m) brute force',
        ],
      },
    },
  },

  'Sliding Window Maximum': {
    intuition:
      'We need the maximum of every contiguous window of size `k`. Using a Monotonic Decreasing Deque (queue storing indices where elements are strictly decreasing), the front of the deque `q[0]` always holds the index of the MAXIMUM element in the current window. As we slide: 1) Pop indices from the front that fell outside the window (`q[0] <= i - k`). 2) Pop smaller elements from the back before inserting `nums[i]`. 3) Add `nums[q[0]]` to results for all `i >= k - 1`.',
    bottleneck:
      'Recomputing max in each window takes O(n * k) time. Max-heap takes O(n log k) with lazy removal. Monotonic deque processes each element at most twice (one push, one pop) for true O(n) linear time.',
    keyInvariant:
      'The deque stores indices of elements in strictly decreasing order of their values: `nums[q[0]] > nums[q[1]] > ...`.',
    constraints: ['1 <= nums.length <= 10^5', '-10^4 <= nums[i] <= 10^4', '1 <= k <= nums.length'],
    examples: [
      { input: 'nums = [1,3,-1,-3,5,3,6,7], k = 3', output: '[3,3,5,5,6,7]', explanation: 'Window maxes: [1,3,-1]->3, [3,-1,-3]->3, [-1,-3,5]->5, [-3,5,3]->5, [5,3,6]->6, [3,6,7]->7.' },
      { input: 'nums = [1], k = 1', output: '[1]', explanation: 'Single element window.' },
    ],
    companies: ['Amazon', 'Google', 'Meta', 'Microsoft', 'Uber'],
    acceptanceRate: '46.5%',
    frequency: '95%',
    edgeCases: ['k == 1 (returns nums copy)', 'k == len(nums) (returns single max value)', 'Monotonically decreasing/increasing array'],
    interviewTips: ['Explain why we store indices instead of values in the deque: storing indices allows O(1) detection of elements that have expired outside the window (`q[0] <= i - k`).'],
    optimal: {
      title: 'Monotonic Decreasing Deque',
      subtitle: 'O(n) linear time and O(k) space deque maintaining candidate maxima',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Each index pushed into and popped from deque at most once.',
      spaceComplexity: 'O(k)',
      spaceComplexityDetail: 'Deque holds at most k indices.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~350ms, Beats 99%)',
      explanation: 'Maintain deque of indices in decreasing order. Front of deque is current window maximum.',
      keySteps: [
        '1. Initialize `q = collections.deque()`, `res = []`.',
        '2. For `i` from 0 to `len(nums) - 1`:',
        '   a. If `q` and `q[0] <= i - k`: `q.popleft()` (expired).',
        '   b. While `q` and `nums[q[-1]] < nums[i]`: `q.pop()` (smaller elements useless).',
        '   c. `q.append(i)`.',
        '   d. If `i >= k - 1`: `res.append(nums[q[0]])`.',
        '3. Return `res`.',
      ],
      code: {
        python: [
          'from collections import deque',
          'class Solution:',
          '    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:',
          '        q = deque()',
          '        res = []',
          '        for i, n in enumerate(nums):',
          '            if q and q[0] <= i - k:',
          '                q.popleft()',
          '            while q and nums[q[-1]] < n:',
          '                q.pop()',
          '            q.append(i)',
          '            if i >= k - 1:',
          '                res.append(nums[q[0]])',
          '        return res',
        ],
        cpp: [
          '#include <vector>',
          '#include <deque>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    vector<int> maxSlidingWindow(vector<int>& nums, int k) {',
          '        deque<int> q;',
          '        vector<int> res;',
          '        for (int i = 0; i < nums.size(); ++i) {',
          '            if (!q.empty() && q.front() <= i - k) q.pop_front();',
          '            while (!q.empty() && nums[q.back()] < nums[i]) q.pop_back();',
          '            q.push_back(i);',
          '            if (i >= k - 1) res.push_back(nums[q.front()]);',
          '        }',
          '        return res;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.*;',
          'class Solution {',
          '    public int[] maxSlidingWindow(int[] nums, int k) {',
          '        int n = nums.length;',
          '        int[] res = new int[n - k + 1];',
          '        Deque<Integer> q = new ArrayDeque<>();',
          '        int idx = 0;',
          '        for (int i = 0; i < n; i++) {',
          '            if (!q.isEmpty() && q.peekFirst() <= i - k) q.pollFirst();',
          '            while (!q.isEmpty() && nums[q.peekLast()] < nums[i]) q.pollLast();',
          '            q.offerLast(i);',
          '            if (i >= k - 1) res[idx++] = nums[q.peekFirst()];',
          '        }',
          '        return res;',
          '    }',
          '}',
        ],
        typescript: [
          'function maxSlidingWindow(nums: number[], k: number): number[] {',
          '  const q: number[] = [];',
          '  const res: number[] = [];',
          '  for (let i = 0; i < nums.length; i++) {',
          '    if (q.length > 0 && q[0] <= i - k) q.shift();',
          '    while (q.length > 0 && nums[q[q.length - 1]] < nums[i]) q.pop();',
          '    q.push(i);',
          '    if (i >= k - 1) res.push(nums[q[0]]);',
          '  }',
          '  return res;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Scan Each Window for Max',
      subtitle: 'O((n - k + 1) * k) naive slice max',
      timeComplexity: 'O(n * k)',
      timeComplexityDetail: 'Find maximum across k elements for each of the n - k + 1 windows.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Output array only.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded on n = 10^5, k = 50000',
      explanation: 'For each starting index i from 0 to n-k, calculate max(nums[i:i+k]).',
      keySteps: ['1. Loop `i` from 0 to `n - k`.', '2. `res.append(max(nums[i:i+k]))`.'],
      code: {
        python: [
          'class Solution:',
          '    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:',
          '        return [max(nums[i:i+k]) for i in range(len(nums) - k + 1)]',
        ],
        cpp: [
          '// O(n*k) brute force',
        ],
        java: [
          '// O(n*k) brute force',
        ],
        typescript: [
          '// O(n*k) brute force',
        ],
      },
    },
  },

  'Minimum Size Subarray Sum': {
    intuition:
      'Because all elements in `nums` are positive integers, the cumulative sum monotonically increases as the window expands. Use a sliding window `[l..r]`. Expand `r` adding `nums[r]` to `total`. While `total >= target`, record the window size `r - l + 1` and shrink from the left by subtracting `nums[l]` and advancing `l`.',
    bottleneck:
      'Evaluating all subarrays takes O(n²) time. Monotonicity of positive sums guarantees each element enters and exits the window at most once, enabling O(n) linear time.',
    keyInvariant:
      'Because nums[i] > 0, shrinking l strictly decreases total, allowing exact minimal window discovery.',
    constraints: ['1 <= target <= 10^9', '1 <= nums.length <= 10^5', '1 <= nums[i] <= 10^4'],
    examples: [
      { input: 'target = 7, nums = [2,3,1,2,4,3]', output: '2', explanation: 'Subarray [4,3] has minimal length 2 with sum >= 7.' },
      { input: 'target = 4, nums = [1,4,4]', output: '1', explanation: 'Subarray [4] has length 1.' },
      { input: 'target = 11, nums = [1,1,1,1,1,1,1,1]', output: '0', explanation: 'Total sum is 8 < 11; impossible, return 0.' },
    ],
    companies: ['Meta', 'Amazon', 'Google', 'Microsoft', 'Apple'],
    acceptanceRate: '46.1%',
    frequency: '85%',
    edgeCases: ['Sum of entire array < target (returns 0)', 'Single element >= target (returns 1)'],
    interviewTips: ['Contrast with Subarray Sum Equals K: here nums are strictly POSITIVE, which is why sliding window works instead of prefix sum hash map.'],
    optimal: {
      title: 'Dynamic Sliding Window Shrink',
      subtitle: 'O(n) time and O(1) space two-pointer expansion and contraction',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Left and right pointers each move at most n steps.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only 4 scalar variables (l, total, min_len, r).',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~50ms, Beats 99%)',
      explanation: 'Expand r, add to total. While total >= target, update min_len, subtract nums[l], and advance l.',
      keySteps: [
        '1. `l = 0`, `total = 0`, `min_len = float("inf")`.',
        '2. For `r` from 0 to `len(nums) - 1`:',
        '   a. `total += nums[r]`.',
        '   b. While `total >= target`:',
        '      `min_len = min(min_len, r - l + 1)`',
        '      `total -= nums[l]`',
        '      `l += 1`',
        '3. Return `min_len` if `min_len != inf` else `0`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def minSubArrayLen(self, target: int, nums: List[int]) -> int:',
          '        l = 0',
          '        total = 0',
          '        min_len = float("inf")',
          '        for r in range(len(nums)):',
          '            total += nums[r]',
          '            while total >= target:',
          '                min_len = min(min_len, r - l + 1)',
          '                total -= nums[l]',
          '                l += 1',
          '        return min_len if min_len != float("inf") else 0',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          '#include <climits>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int minSubArrayLen(int target, vector<int>& nums) {',
          '        int l = 0, total = 0, min_len = INT_MAX;',
          '        for (int r = 0; r < nums.size(); ++r) {',
          '            total += nums[r];',
          '            while (total >= target) {',
          '                min_len = min(min_len, r - l + 1);',
          '                total -= nums[l++];',
          '            }',
          '        }',
          '        return min_len == INT_MAX ? 0 : min_len;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int minSubArrayLen(int target, int[] nums) {',
          '        int l = 0, total = 0, minLen = Integer.MAX_VALUE;',
          '        for (int r = 0; r < nums.length; r++) {',
          '            total += nums[r];',
          '            while (total >= target) {',
          '                minLen = Math.min(minLen, r - l + 1);',
          '                total -= nums[l++];',
          '            }',
          '        }',
          '        return minLen == Integer.MAX_VALUE ? 0 : minLen;',
          '    }',
          '}',
        ],
        typescript: [
          'function minSubArrayLen(target: number, nums: number[]): number {',
          '  let l = 0, total = 0, minLen = Infinity;',
          '  for (let r = 0; r < nums.length; r++) {',
          '    total += nums[r];',
          '    while (total >= target) {',
          '      minLen = Math.min(minLen, r - l + 1);',
          '      total -= nums[l++];',
          '    }',
          '  }',
          '  return minLen === Infinity ? 0 : minLen;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Nested Loops Subarray Check',
      subtitle: 'Exhaustive O(n²) search',
      timeComplexity: 'O(n²)',
      timeComplexityDetail: 'Outer loop starts subarray, inner loop accumulates sum.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Try every possible starting index i and extend until sum >= target.',
      keySteps: ['1. Loop `i`.', '2. Loop `j` accumulating sum.', '3. Update `min_len`.'],
      code: {
        python: [
          'class Solution:',
          '    def minSubArrayLen(self, target: int, nums: List[int]) -> int:',
          '        min_len = float("inf")',
          '        for i in range(len(nums)):',
          '            s = 0',
          '            for j in range(i, len(nums)):',
          '                s += nums[j]',
          '                if s >= target:',
          '                    min_len = min(min_len, j - i + 1)',
          '                    break',
          '        return min_len if min_len != float("inf") else 0',
        ],
        cpp: [
          '// O(n^2) brute force',
        ],
        java: [
          '// O(n^2) brute force',
        ],
        typescript: [
          '// O(n^2) brute force',
        ],
      },
    },
  },

  'Max Consecutive Ones III': {
    intuition:
      'We want the longest subarray containing at most `k` zeros (which can be flipped to 1s). Use a sliding window `[l..r]`. Maintain `zero_count`. Expand `r`: if `nums[r] == 0`, increment `zero_count`. While `zero_count > k`, shrink from left: if `nums[l] == 0`, decrement `zero_count`, and increment `l`. Record max window size `r - l + 1`.',
    bottleneck:
      'Checking all substrings takes O(n²). Sliding window maintains zero budget in O(n) linear time with O(1) memory.',
    keyInvariant:
      'Window `[l..r]` never contains more than `k` zeros.',
    constraints: ['1 <= nums.length <= 10^5', 'nums[i] is either 0 or 1.', '0 <= k <= nums.length'],
    examples: [
      { input: 'nums = [1,1,1,0,0,0,1,1,1,1,0], k = 2', output: '6', explanation: 'Flip 2 zeros to get [1,1,1,0,0,1,1,1,1,1,1], longest 6.' },
      { input: 'nums = [0,0,1,1,0,0,1,1,1,0,1,1,0,0,0,1,1,1,1], k = 3', output: '10', explanation: 'Longest 10.' },
    ],
    companies: ['Meta', 'Google', 'Amazon', 'Microsoft'],
    acceptanceRate: '63.4%',
    frequency: '89%',
    edgeCases: ['k = 0 (longest streak of consecutive 1s)', 'k >= count of zeros in array (returns len(nums))', 'All zeros / all ones'],
    interviewTips: ['Show how the problem reduces to: "Find the longest subarray with at most k zeros".'],
    optimal: {
      title: 'Sliding Window Zero Budget Tracking',
      subtitle: 'O(n) time and O(1) space sliding window',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Left and right pointers each advance at most n times.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only l, zero_count, max_len variables.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~320ms, Beats 99%)',
      explanation: 'Expand r, increment zero count on 0. When zeros > k, contract l. Max window is r - l + 1.',
      keySteps: [
        '1. `l = 0`, `zero_count = 0`, `max_len = 0`.',
        '2. For `r` in 0..len(nums)-1:',
        '   a. If `nums[r] == 0`: `zero_count += 1`.',
        '   b. While `zero_count > k`:',
        '      If `nums[l] == 0`: `zero_count -= 1`.',
        '      `l += 1`.',
        '   c. `max_len = max(max_len, r - l + 1)`.',
        '3. Return `max_len`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def longestOnes(self, nums: List[int], k: int) -> int:',
          '        l = 0',
          '        zero_count = 0',
          '        max_len = 0',
          '        for r in range(len(nums)):',
          '            if nums[r] == 0:',
          '                zero_count += 1',
          '            while zero_count > k:',
          '                if nums[l] == 0:',
          '                    zero_count -= 1',
          '                l += 1',
          '            max_len = max(max_len, r - l + 1)',
          '        return max_len',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int longestOnes(vector<int>& nums, int k) {',
          '        int l = 0, zeros = 0, max_len = 0;',
          '        for (int r = 0; r < nums.size(); ++r) {',
          '            if (nums[r] == 0) zeros++;',
          '            while (zeros > k) {',
          '                if (nums[l++] == 0) zeros--;',
          '            }',
          '            max_len = max(max_len, r - l + 1);',
          '        }',
          '        return max_len;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int longestOnes(int[] nums, int k) {',
          '        int l = 0, zeros = 0, maxLen = 0;',
          '        for (int r = 0; r < nums.length; r++) {',
          '            if (nums[r] == 0) zeros++;',
          '            while (zeros > k) {',
          '                if (nums[l++] == 0) zeros--;',
          '            }',
          '            maxLen = Math.max(maxLen, r - l + 1);',
          '        }',
          '        return maxLen;',
          '    }',
          '}',
        ],
        typescript: [
          'function longestOnes(nums: number[], k: number): number {',
          '  let l = 0, zeros = 0, maxLen = 0;',
          '  for (let r = 0; r < nums.length; r++) {',
          '    if (nums[r] === 0) zeros++;',
          '    while (zeros > k) {',
          '      if (nums[l++] === 0) zeros--;',
          '    }',
          '    maxLen = Math.max(maxLen, r - l + 1);',
          '  }',
          '  return maxLen;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Nested Loops Count Zeros',
      subtitle: 'O(n²) check of all subarrays',
      timeComplexity: 'O(n²)',
      timeComplexityDetail: 'Outer loop starts subarray, inner loop counts zeros.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Try all starting positions i, expand j, stop when zero count exceeds k.',
      keySteps: ['1. Loop `i`.', '2. Loop `j` counting zeros.', '3. Break if `zeros > k`.'],
      code: {
        python: [
          'class Solution:',
          '    def longestOnes(self, nums: List[int], k: int) -> int:',
          '        ans = 0',
          '        for i in range(len(nums)):',
          '            z = 0',
          '            for j in range(i, len(nums)):',
          '                if nums[j] == 0: z += 1',
          '                if z > k: break',
          '                ans = max(ans, j - i + 1)',
          '        return ans',
        ],
        cpp: [
          '// O(n^2) brute force',
        ],
        java: [
          '// O(n^2) brute force',
        ],
        typescript: [
          '// O(n^2) brute force',
        ],
      },
    },
  },

  'Fruit Into Baskets': {
    intuition:
      'We want the longest contiguous subarray containing at most 2 distinct fruit types. Use a sliding window `[l..r]`. Maintain a hash map of fruit types to their counts in the current window. Expand `r`: add `fruits[r]` to map. While `len(map) > 2`, shrink `l`: decrement count of `fruits[l]`, delete if 0, and advance `l`. Record max window size `r - l + 1`.',
    bottleneck:
      'Checking all subarrays takes O(n²). Sliding window maintains at most 2 distinct elements in O(n) linear time with O(1) space (at most 3 keys in map).',
    keyInvariant:
      'The window `[l..r]` always contains at most 2 distinct fruit keys.',
    constraints: ['1 <= fruits.length <= 10^5', '0 <= fruits[i] < fruits.length'],
    examples: [
      { input: 'fruits = [1,2,1]', output: '3', explanation: 'All 3 fruits can be picked.' },
      { input: 'fruits = [0,1,2,2]', output: '3', explanation: 'Subarray [1, 2, 2] length 3.' },
      { input: 'fruits = [1,2,3,2,2]', output: '4', explanation: 'Subarray [2, 3, 2, 2] length 4.' },
    ],
    companies: ['Google', 'Amazon', 'Microsoft'],
    acceptanceRate: '44.2%',
    frequency: '78%',
    edgeCases: ['Array has only 1 or 2 fruit types (returns len(fruits))', 'All fruits distinct (returns 2)'],
    interviewTips: ['Recognize this as equivalent to "Longest Substring with At Most 2 Distinct Characters".'],
    optimal: {
      title: 'Sliding Window Distinct Types Map',
      subtitle: 'O(n) time and O(1) space window tracking at most 2 fruit types',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Pointers l and r each increment at most n times.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Hash map stores at most 3 distinct keys at any time.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~350ms, Beats 98%)',
      explanation: 'Expand r, record fruit count. When distinct fruits > 2, shrink l until distinct count <= 2.',
      keySteps: [
        '1. `count = {}`, `l = 0`, `max_fruits = 0`.',
        '2. For `r, f` in `enumerate(fruits)`:',
        '   a. `count[f] = count.get(f, 0) + 1`.',
        '   b. While `len(count) > 2`:',
        '      `count[fruits[l]] -= 1`',
        '      if `count[fruits[l]] == 0`: `del count[fruits[l]]`',
        '      `l += 1`',
        '   c. `max_fruits = max(max_fruits, r - l + 1)`.',
        '3. Return `max_fruits`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def totalFruit(self, fruits: List[int]) -> int:',
          '        count = {}',
          '        l = 0',
          '        max_fruits = 0',
          '        for r, f in enumerate(fruits):',
          '            count[f] = count.get(f, 0) + 1',
          '            while len(count) > 2:',
          '                count[fruits[l]] -= 1',
          '                if count[fruits[l]] == 0:',
          '                    del count[fruits[l]]',
          '                l += 1',
          '            max_fruits = max(max_fruits, r - l + 1)',
          '        return max_fruits',
        ],
        cpp: [
          '#include <vector>',
          '#include <unordered_map>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int totalFruit(vector<int>& fruits) {',
          '        unordered_map<int, int> count;',
          '        int l = 0, max_fruits = 0;',
          '        for (int r = 0; r < fruits.size(); ++r) {',
          '            count[fruits[r]]++;',
          '            while (count.size() > 2) {',
          '                if (--count[fruits[l]] == 0) count.erase(fruits[l]);',
          '                l++;',
          '            }',
          '            max_fruits = max(max_fruits, r - l + 1);',
          '        }',
          '        return max_fruits;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.*;',
          'class Solution {',
          '    public int totalFruit(int[] fruits) {',
          '        Map<Integer, Integer> count = new HashMap<>();',
          '        int l = 0, maxFruits = 0;',
          '        for (int r = 0; r < fruits.length; r++) {',
          '            count.put(fruits[r], count.getOrDefault(fruits[r], 0) + 1);',
          '            while (count.size() > 2) {',
          '                count.put(fruits[l], count.get(fruits[l]) - 1);',
          '                if (count.get(fruits[l]) == 0) count.remove(fruits[l]);',
          '                l++;',
          '            }',
          '            maxFruits = Math.max(maxFruits, r - l + 1);',
          '        }',
          '        return maxFruits;',
          '    }',
          '}',
        ],
        typescript: [
          'function totalFruit(fruits: number[]): number {',
          '  const count = new Map<number, number>();',
          '  let l = 0, maxFruits = 0;',
          '  for (let r = 0; r < fruits.length; r++) {',
          '    count.set(fruits[r], (count.get(fruits[r]) || 0) + 1);',
          '    while (count.size > 2) {',
          '      count.set(fruits[l], count.get(fruits[l])! - 1);',
          '      if (count.get(fruits[l]) === 0) count.delete(fruits[l]);',
          '      l++;',
          '    }',
          '    maxFruits = Math.max(maxFruits, r - l + 1);',
          '  }',
          '  return maxFruits;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Nested Loops Distinct Set',
      subtitle: 'O(n²) check with set',
      timeComplexity: 'O(n²)',
      timeComplexityDetail: 'Outer loop starts subarray, inner loop adds to set.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Set holds at most 3 items.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Try all start positions and expand while set length <= 2.',
      keySteps: ['1. Loop `i`.', '2. Loop `j` adding to set.', '3. Break when `len(set) > 2`.'],
      code: {
        python: [
          'class Solution:',
          '    def totalFruit(self, fruits: List[int]) -> int:',
          '        ans = 0',
          '        for i in range(len(fruits)):',
          '            s = set()',
          '            for j in range(i, len(fruits)):',
          '                s.add(fruits[j])',
          '                if len(s) > 2: break',
          '                ans = max(ans, j - i + 1)',
          '        return ans',
        ],
        cpp: [
          '// O(n^2) brute force',
        ],
        java: [
          '// O(n^2) brute force',
        ],
        typescript: [
          '// O(n^2) brute force',
        ],
      },
    },
  },

  'Maximum Average Subarray I': {
    intuition:
      'We need the maximum average of any contiguous subarray of fixed length `k`. Finding the maximum average of fixed size `k` is mathematically equivalent to finding the maximum sum of fixed size `k` divided by `k`. Compute the sum of the first `k` elements. Then slide the window across the array by adding `nums[i]` and subtracting `nums[i - k]`.',
    bottleneck:
      'Summing every window of length k from scratch takes O(n * k). Sliding window adds and subtracts in O(1) time per step for O(n) total time.',
    keyInvariant:
      'Window sum is updated in O(1) via `curr_sum += nums[i] - nums[i - k]`.',
    constraints: ['n == nums.length', '1 <= k <= n <= 10^5', '-10^4 <= nums[i] <= 10^4'],
    examples: [
      { input: 'nums = [1,12,-5,-6,50,3], k = 4', output: '12.75000', explanation: 'Max sum subarray is [12, -5, -6, 50] with sum 51, avg = 51 / 4 = 12.75.' },
      { input: 'nums = [5], k = 1', output: '5.00000', explanation: '5 / 1 = 5.0.' },
    ],
    companies: ['Google', 'Meta', 'Amazon'],
    acceptanceRate: '44.8%',
    frequency: '75%',
    edgeCases: ['k == len(nums)', 'All negative numbers in array', 'k = 1'],
    interviewTips: ['Divide by k only once at the very end to minimize floating point arithmetic and avoid precision loss.'],
    optimal: {
      title: 'Fixed Size k Sliding Window Accumulator',
      subtitle: 'O(n) time and O(1) auxiliary space',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Single pass sliding window of size k.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only curr_sum and max_sum variables.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~700ms, Beats 99%)',
      explanation: 'Sum first k elements. Slide window from k to n-1 updating sum. Return max_sum / k.',
      keySteps: [
        '1. `curr_sum = sum(nums[:k])`, `max_sum = curr_sum`.',
        '2. For `i` from `k` to `len(nums) - 1`:',
        '   `curr_sum += nums[i] - nums[i - k]`',
        '   `max_sum = max(max_sum, curr_sum)`',
        '3. Return `max_sum / k`.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def findMaxAverage(self, nums: List[int], k: int) -> float:',
          '        curr_sum = sum(nums[:k])',
          '        max_sum = curr_sum',
          '        for i in range(k, len(nums)):',
          '            curr_sum += nums[i] - nums[i - k]',
          '            max_sum = max(max_sum, curr_sum)',
          '        return max_sum / k',
        ],
        cpp: [
          '#include <vector>',
          '#include <numeric>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    double findMaxAverage(vector<int>& nums, int k) {',
          '        double curr_sum = 0;',
          '        for (int i = 0; i < k; ++i) curr_sum += nums[i];',
          '        double max_sum = curr_sum;',
          '        for (int i = k; i < nums.size(); ++i) {',
          '            curr_sum += nums[i] - nums[i - k];',
          '            max_sum = max(max_sum, curr_sum);',
          '        }',
          '        return max_sum / k;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public double findMaxAverage(int[] nums, int k) {',
          '        double currSum = 0;',
          '        for (int i = 0; i < k; i++) currSum += nums[i];',
          '        double maxSum = currSum;',
          '        for (int i = k; i < nums.length; i++) {',
          '            currSum += nums[i] - nums[i - k];',
          '            maxSum = Math.max(maxSum, currSum);',
          '        }',
          '        return maxSum / k;',
          '    }',
          '}',
        ],
        typescript: [
          'function findMaxAverage(nums: number[], k: number): number {',
          '  let currSum = 0;',
          '  for (let i = 0; i < k; i++) currSum += nums[i];',
          '  let maxSum = currSum;',
          '  for (let i = k; i < nums.length; i++) {',
          '    currSum += nums[i] - nums[i - k];',
          '    maxSum = Math.max(maxSum, currSum);',
          '  }',
          '  return maxSum / k;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Sum Every Subarray of Length k',
      subtitle: 'O((n - k + 1) * k) naive slice sum',
      timeComplexity: 'O(n * k)',
      timeComplexityDetail: 'Sum k elements for each window.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Constant memory.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Calculate sum(nums[i:i+k]) for each start index i.',
      keySteps: ['1. Loop `i` from 0 to `n - k`.', '2. `max_sum = max(max_sum, sum(nums[i:i+k]))`.'],
      code: {
        python: [
          'class Solution:',
          '    def findMaxAverage(self, nums: List[int], k: int) -> float:',
          '        return max(sum(nums[i:i+k]) for i in range(len(nums) - k + 1)) / k',
        ],
        cpp: [
          '// O(n*k) brute force',
        ],
        java: [
          '// O(n*k) brute force',
        ],
        typescript: [
          '// O(n*k) brute force',
        ],
      },
    },
  },
}
