import { DetailedProblemData } from '../leetcodeSolutions'

export const binarySearchSolutions: Record<string, DetailedProblemData> = {
  'Binary Search': {
    intuition: 'Because the array is sorted, comparing target with the middle element nums[mid] determines whether target lies in the left half (nums[mid] > target) or right half (nums[mid] < target), halving the search space in each iteration.',
    bottleneck: 'Linear search takes O(n) time. Binary search takes O(log n) time by eliminating half the remaining elements per comparison.',
    keyInvariant: 'If target exists in nums, it is guaranteed to be within the search interval [l, r].',
    constraints: ['1 <= nums.length <= 10^4', '-10^4 < nums[i], target < 10^4', 'All integers in nums are unique.', 'nums is sorted in ascending order.'],
    examples: [
      { input: 'nums = [-1,0,3,5,9,12], target = 9', output: '4', explanation: '9 exists in nums and its index is 4.' },
      { input: 'nums = [-1,0,3,5,9,12], target = 2', output: '-1', explanation: '2 does not exist in nums so return -1.' },
    ],
    companies: ['Amazon', 'Apple', 'Google', 'Microsoft'],
    acceptanceRate: '57.4%',
    frequency: '92%',
    edgeCases: ['Array with 1 element', 'Target smaller than nums[0] or larger than nums[-1]', 'Target at exact boundaries (index 0 or n-1)'],
    interviewTips: ['Use `mid = l + (r - l) // 2` instead of `(l + r) // 2` to prevent potential 32-bit integer overflow in languages like C++ and Java.'],
    optimal: {
      title: 'Standard Iterative Binary Search',
      subtitle: 'O(log n) time and O(1) space interval halving',
      timeComplexity: 'O(log n)',
      timeComplexityDetail: 'Search interval is halved in each step.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only index pointers.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~180ms, Beats 99%)',
      explanation: 'Maintain pointers l=0, r=len(nums)-1. While l <= r, calculate mid, compare with target, shrink bounds.',
      keySteps: [
        '1. l = 0, r = len(nums) - 1.',
        '2. While l <= r:',
        '   a. mid = l + (r - l) // 2.',
        '   b. If nums[mid] == target: return mid.',
        '   c. If nums[mid] < target: l = mid + 1.',
        '   d. Else: r = mid - 1.',
        '3. Return -1.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def search(self, nums: List[int], target: int) -> int:',
          '        l, r = 0, len(nums) - 1',
          '        while l <= r:',
          '            mid = l + (r - l) // 2',
          '            if nums[mid] == target:',
          '                return mid',
          '            elif nums[mid] < target:',
          '                l = mid + 1',
          '            else:',
          '                r = mid - 1',
          '        return -1',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int search(vector<int>& nums, int target) {',
          '        int l = 0, r = nums.size() - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] == target) return mid;',
          '            else if (nums[mid] < target) l = mid + 1;',
          '            else r = mid - 1;',
          '        }',
          '        return -1;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int search(int[] nums, int target) {',
          '        int l = 0, r = nums.length - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] == target) return mid;',
          '            else if (nums[mid] < target) l = mid + 1;',
          '            else r = mid - 1;',
          '        }',
          '        return -1;',
          '    }',
          '}',
        ],
        typescript: [
          'function search(nums: number[], target: number): number {',
          '  let l = 0, r = nums.length - 1;',
          '  while (l <= r) {',
          '    const mid = l + Math.floor((r - l) / 2);',
          '    if (nums[mid] === target) return mid;',
          '    else if (nums[mid] < target) l = mid + 1;',
          '    else r = mid - 1;',
          '  }',
          '  return -1;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Linear Scan',
      subtitle: 'O(n) sequential scan',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Checks elements one by one.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '✅ Accepted (Suboptimal)',
      explanation: 'Iterate from index 0 to n-1 and return index if nums[i] == target.',
      keySteps: ['1. Loop i in 0..n-1: if nums[i] == target: return i.', '2. Return -1.'],
      code: {
        python: [
          'class Solution:',
          '    def search(self, nums: List[int], target: int) -> int:',
          '        for i, val in enumerate(nums):',
          '            if val == target: return i',
          '        return -1',
        ],
        cpp: ['// Linear scan'],
        java: ['// Linear scan'],
        typescript: ['// Linear scan'],
      },
    },
  },

  'Search a 2D Matrix': {
    intuition: 'The m x n matrix is sorted row by row and the first integer of each row is greater than the last integer of the previous row. This means the entire 2D matrix can be treated as a flattened 1D sorted array of length m * n. A 1D index `mid` maps to 2D matrix coordinate `matrix[mid // n][mid % n]`. We can perform standard binary search over range [0, m * n - 1] in O(log(m * n)) time.',
    bottleneck: 'Searching row-by-row takes O(m * log n) or O(m * n). Virtual 1D binary search runs in O(log(m * n)) time.',
    keyInvariant: '1D index idx maps directly to 2D cell (idx // cols, idx % cols) preserving strict sorted order.',
    constraints: ['m == matrix.length', 'n == matrix[i].length', '1 <= m, n <= 100', '-10^4 <= matrix[i][j], target <= 10^4'],
    examples: [
      { input: 'matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3', output: 'true', explanation: '3 is present.' },
      { input: 'matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 13', output: 'false', explanation: '13 is not present.' },
    ],
    companies: ['Amazon', 'Microsoft', 'Google', 'Meta'],
    acceptanceRate: '49.8%',
    frequency: '88%',
    edgeCases: ['1x1 matrix', 'Single row or single column matrix', 'Target smaller than minimum or larger than maximum'],
    interviewTips: ['Show the index mapping formulas: `r = mid // cols`, `c = mid % cols`.'],
    optimal: {
      title: 'Virtual 1D Binary Search',
      subtitle: 'O(log(m * n)) time and O(1) space binary search',
      timeComplexity: 'O(log(m * n))',
      timeComplexityDetail: 'Standard binary search over m * n total elements.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only index pointers.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~35ms, Beats 99%)',
      explanation: 'Binary search between 0 and m*n - 1. Map mid to matrix[mid // n][mid % n].',
      keySteps: [
        '1. m = len(matrix), n = len(matrix[0]).',
        '2. l = 0, r = m * n - 1.',
        '3. While l <= r:',
        '   a. mid = l + (r - l) // 2.',
        '   b. val = matrix[mid // n][mid % n].',
        '   c. If val == target: return True.',
        '   d. If val < target: l = mid + 1.',
        '   e. Else: r = mid - 1.',
        '4. Return False.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:',
          '        if not matrix or not matrix[0]: return False',
          '        m, n = len(matrix), len(matrix[0])',
          '        l, r = 0, m * n - 1',
          '        while l <= r:',
          '            mid = l + (r - l) // 2',
          '            val = matrix[mid // n][mid % n]',
          '            if val == target: return True',
          '            elif val < target: l = mid + 1',
          '            else: r = mid - 1',
          '        return False',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    bool searchMatrix(vector<vector<int>>& matrix, int target) {',
          '        if (matrix.empty() || matrix[0].empty()) return false;',
          '        int m = matrix.size(), n = matrix[0].size();',
          '        int l = 0, r = m * n - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            int val = matrix[mid / n][mid % n];',
          '            if (val == target) return true;',
          '            else if (val < target) l = mid + 1;',
          '            else r = mid - 1;',
          '        }',
          '        return false;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public boolean searchMatrix(int[][] matrix, int target) {',
          '        if (matrix.length == 0 || matrix[0].length == 0) return false;',
          '        int m = matrix.length, n = matrix[0].length;',
          '        int l = 0, r = m * n - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            int val = matrix[mid / n][mid % n];',
          '            if (val == target) return true;',
          '            else if (val < target) l = mid + 1;',
          '            else r = mid - 1;',
          '        }',
          '        return false;',
          '    }',
          '}',
        ],
        typescript: [
          'function searchMatrix(matrix: number[][], target: number): boolean {',
          '  if (matrix.length === 0 || matrix[0].length === 0) return false;',
          '  const m = matrix.length, n = matrix[0].length;',
          '  let l = 0, r = m * n - 1;',
          '  while (l <= r) {',
          '    const mid = l + Math.floor((r - l) / 2);',
          '    const val = matrix[Math.floor(mid / n)][mid % n];',
          '    if (val === target) return true;',
          '    else if (val < target) l = mid + 1;',
          '    else r = mid - 1;',
          '  }',
          '  return false;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Scan Every Row and Col',
      subtitle: 'O(m * n) full traversal',
      timeComplexity: 'O(m * n)',
      timeComplexityDetail: 'Checks all cells sequentially.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra space.',
      status: 'brute',
      leetcodeStatus: '✅ Accepted (Suboptimal)',
      explanation: 'Iterate over all cells and check if any equals target.',
      keySteps: ['1. Double loop over r and c.'],
      code: {
        python: [
          'class Solution:',
          '    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:',
          '        for row in matrix: if target in row: return True',
          '        return False',
        ],
        cpp: ['// Linear scan'],
        java: ['// Linear scan'],
        typescript: ['// Linear scan'],
      },
    },
  },

  'Search a 2D Matrix II': {
    intuition: 'Each row is sorted left-to-right, and each column is sorted top-to-bottom (unlike 2D Matrix I, row ends do not connect to next row starts). Start at the TOP-RIGHT corner `(r = 0, c = cols - 1)`. If `matrix[r][c] == target`, found! If `matrix[r][c] > target`, the target cannot be in column `c` (decrement `c`). If `matrix[r][c] < target`, the target cannot be in row `r` (increment `r`).',
    bottleneck: 'Binary searching each row takes O(m log n). Top-right corner search eliminates one entire row or column per comparison in O(m + n) time.',
    keyInvariant: 'From top-right corner, moving left decreases the value, and moving down increases the value.',
    constraints: ['m == matrix.length', 'n == matrix[i].length', '1 <= m, n <= 300', '-10^9 <= matrix[i][j], target <= 10^9'],
    examples: [
      { input: 'matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], target = 5', output: 'true', explanation: '5 is present.' },
      { input: 'matrix = [...], target = 20', output: 'false', explanation: '20 is not present.' },
    ],
    companies: ['Amazon', 'Microsoft', 'Google', 'Meta', 'Apple'],
    acceptanceRate: '51.9%',
    frequency: '89%',
    edgeCases: ['Target smaller than top-left corner', 'Target larger than bottom-right corner', 'Matrix of dimensions 1xN or Nx1'],
    interviewTips: ['Explain why starting at top-left does NOT work (moving right and down both increase values), whereas top-right has opposing directional gradients.'],
    optimal: {
      title: 'Top-Right Corner Step-Wise Elimination',
      subtitle: 'O(m + n) time and O(1) space corner traversal',
      timeComplexity: 'O(m + n)',
      timeComplexityDetail: 'At each step, increment r or decrement c; at most m + n steps.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only r and c coordinate pointers.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~120ms, Beats 99%)',
      explanation: 'Start at r=0, c=cols-1. If value > target: c -= 1. If value < target: r += 1.',
      keySteps: [
        '1. r = 0, c = len(matrix[0]) - 1.',
        '2. While r < len(matrix) and c >= 0:',
        '   a. If matrix[r][c] == target: return True.',
        '   b. If matrix[r][c] > target: c -= 1.',
        '   c. Else: r += 1.',
        '3. Return False.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:',
          '        if not matrix or not matrix[0]: return False',
          '        r, c = 0, len(matrix[0]) - 1',
          '        while r < len(matrix) and c >= 0:',
          '            val = matrix[r][c]',
          '            if val == target: return True',
          '            elif val > target: c -= 1',
          '            else: r += 1',
          '        return False',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    bool searchMatrix(vector<vector<int>>& matrix, int target) {',
          '        if (matrix.empty() || matrix[0].empty()) return false;',
          '        int r = 0, c = matrix[0].size() - 1;',
          '        while (r < matrix.size() && c >= 0) {',
          '            if (matrix[r][c] == target) return true;',
          '            else if (matrix[r][c] > target) c--;',
          '            else r++;',
          '        }',
          '        return false;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public boolean searchMatrix(int[][] matrix, int target) {',
          '        if (matrix.length == 0 || matrix[0].length == 0) return false;',
          '        int r = 0, c = matrix[0].length - 1;',
          '        while (r < matrix.length && c >= 0) {',
          '            if (matrix[r][c] == target) return true;',
          '            else if (matrix[r][c] > target) c--;',
          '            else r++;',
          '        }',
          '        return false;',
          '    }',
          '}',
        ],
        typescript: [
          'function searchMatrix(matrix: number[][], target: number): boolean {',
          '  if (matrix.length === 0 || matrix[0].length === 0) return false;',
          '  let r = 0, c = matrix[0].length - 1;',
          '  while (r < matrix.length && c >= 0) {',
          '    if (matrix[r][c] === target) return true;',
          '    else if (matrix[r][c] > target) c--;',
          '    else r++;',
          '  }',
          '  return false;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Binary Search Each Row Independently',
      subtitle: 'O(m log n) row-by-row binary search',
      timeComplexity: 'O(m log n)',
      timeComplexityDetail: 'm rows, binary searching across n columns.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Suboptimal)',
      explanation: 'For each row, run binary search for target.',
      keySteps: ['1. For row in matrix: binary search row.'],
      code: {
        python: [
          'import bisect',
          'class Solution:',
          '    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:',
          '        for row in matrix:',
          '            idx = bisect.bisect_left(row, target)',
          '            if idx < len(row) and row[idx] == target: return True',
          '        return False',
        ],
        cpp: ['// Binary search each row'],
        java: ['// Binary search each row'],
        typescript: ['// Binary search each row'],
      },
    },
  },

  'Koko Eating Bananas': {
    intuition: 'We want the minimum integer eating speed k (bananas/hour) such that Koko can eat all piles within h hours. The eating speed k lies in range [1, max(piles)]. The function `total_hours(k) = sum(ceil(pile / k))` is MONOTONICALLY DECREASING with respect to k. This allows Binary Search on the Answer space [1, max(piles)] to find the smallest valid k in O(n * log(max(piles))) time.',
    bottleneck: 'Testing speeds sequentially from 1 to max(piles) takes O(max(piles) * n). Binary search on speed space reduces this to O(n * log(max(piles))).',
    keyInvariant: 'For any speed k where total_hours(k) <= h, all speeds > k are also valid, enabling binary search lower bound.',
    constraints: ['1 <= piles.length <= 10^4', 'piles.length <= h <= 10^9', '1 <= piles[i] <= 10^9'],
    examples: [
      { input: 'piles = [3,6,7,11], h = 8', output: '4', explanation: 'At speed 4: ceil(3/4)+ceil(6/4)+ceil(7/4)+ceil(11/4) = 1+2+2+3 = 8 <= 8.' },
      { input: 'piles = [30,11,23,4,20], h = 5', output: '30', explanation: 'h == len(piles), so k must equal max pile 30.' },
    ],
    companies: ['Google', 'Amazon', 'Meta', 'Bloomberg'],
    acceptanceRate: '51.4%',
    frequency: '95%',
    edgeCases: ['h == len(piles) (speed must equal max(piles))', 'Large values of piles and h', 'piles with single element'],
    interviewTips: ['Calculate hours per pile using integer math: `(pile + k - 1) // k` to avoid floating point division.'],
    optimal: {
      title: 'Binary Search on Speed Answer Space [1..max(piles)]',
      subtitle: 'O(n log(max_pile)) time and O(1) space',
      timeComplexity: 'O(n log(max_pile))',
      timeComplexityDetail: 'Binary search range [1, 10^9] takes ~30 steps, each checking n piles.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only index pointers.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~280ms, Beats 98%)',
      explanation: 'Binary search for k in [1, max(piles)]. If hours needed <= h, search left half (r = mid); else search right half (l = mid + 1).',
      keySteps: [
        '1. l = 1, r = max(piles).',
        '2. While l < r:',
        '   a. mid = l + (r - l) // 2.',
        '   b. hours = sum((p + mid - 1) // mid for p in piles).',
        '   c. If hours <= h: r = mid (can potentially eat slower).',
        '   d. Else: l = mid + 1 (must eat faster).',
        '3. Return l.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def minEatingSpeed(self, piles: List[int], h: int) -> int:',
          '        l, r = 1, max(piles)',
          '        while l < r:',
          '            mid = l + (r - l) // 2',
          '            hours = sum((p + mid - 1) // mid for p in piles)',
          '            if hours <= h:',
          '                r = mid',
          '            else:',
          '                l = mid + 1',
          '        return l',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int minEatingSpeed(vector<int>& piles, int h) {',
          '        int l = 1, r = *max_element(piles.begin(), piles.end());',
          '        while (l < r) {',
          '            int mid = l + (r - l) / 2;',
          '            long long hours = 0;',
          '            for (int p : piles) hours += (p + mid - 1) / mid;',
          '            if (hours <= h) r = mid;',
          '            else l = mid + 1;',
          '        }',
          '        return l;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int minEatingSpeed(int[] piles, int h) {',
          '        int l = 1, r = 1;',
          '        for (int p : piles) r = Math.max(r, p);',
          '        while (l < r) {',
          '            int mid = l + (r - l) / 2;',
          '            long hours = 0;',
          '            for (int p : piles) hours += (p + mid - 1) / mid;',
          '            if (hours <= h) r = mid;',
          '            else l = mid + 1;',
          '        }',
          '        return l;',
          '    }',
          '}',
        ],
        typescript: [
          'function minEatingSpeed(piles: number[], h: number): number {',
          '  let l = 1, r = Math.max(...piles);',
          '  while (l < r) {',
          '    const mid = l + Math.floor((r - l) / 2);',
          '    let hours = 0;',
          '    for (const p of piles) hours += Math.ceil(p / mid);',
          '    if (hours <= h) r = mid;',
          '    else l = mid + 1;',
          '  }',
          '  return l;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Sequential Linear Speed Search',
      subtitle: 'O(max(piles) * n) brute check',
      timeComplexity: 'O(max(piles) * n)',
      timeComplexityDetail: 'Test speed 1, 2, 3... until total hours <= h.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Try speed k = 1, 2, 3... and compute total hours until <= h.',
      keySteps: ['1. Loop k from 1 to max(piles).', '2. If hours(k) <= h: return k.'],
      code: {
        python: [
          'class Solution:',
          '    def minEatingSpeed(self, piles: List[int], h: int) -> int:',
          '        for k in range(1, max(piles) + 1):',
          '            if sum((p + k - 1) // k for p in piles) <= h: return k',
        ],
        cpp: ['// Linear speed search'],
        java: ['// Linear speed search'],
        typescript: ['// Linear speed search'],
      },
    },
  },

  'Search in Rotated Sorted Array': {
    intuition: 'A rotated sorted array is partitioned into two sorted halves by the pivot. At least ONE half (left [l..mid] or right [mid..r]) is always strictly sorted. We check which half is sorted: 1) If left half is sorted (`nums[l] <= nums[mid]`): check if target is inside `[nums[l], nums[mid]]`. If so, search left (`r = mid - 1`); else search right (`l = mid + 1`). 2) If right half is sorted: check if target is inside `[nums[mid], nums[r]]`. If so, search right (`l = mid + 1`); else search left (`r = mid - 1`).',
    bottleneck: 'Linear search takes O(n). Identifying the sorted half achieves O(log n) binary search in a single pass.',
    keyInvariant: 'One of the two sub-intervals [l, mid] or [mid, r] is always strictly monotonically increasing.',
    constraints: ['1 <= nums.length <= 5000', '-10^4 <= nums[i], target <= 10^4', 'All values of nums are unique.'],
    examples: [
      { input: 'nums = [4,5,6,7,0,1,2], target = 0', output: '4', explanation: '0 is at index 4.' },
      { input: 'nums = [4,5,6,7,0,1,2], target = 3', output: '-1', explanation: '3 is not in array.' },
    ],
    companies: ['Amazon', 'Microsoft', 'Google', 'Meta', 'Apple'],
    acceptanceRate: '40.2%',
    frequency: '98%',
    edgeCases: ['Array not rotated (standard sorted array)', 'Array of size 1 or 2', 'Target at pivot or boundaries'],
    interviewTips: ['Write out the condition `nums[l] <= nums[mid]` and walk through the bounds check `nums[l] <= target < nums[mid]` carefully.'],
    optimal: {
      title: 'Modified Binary Search with Sorted-Half Identification',
      subtitle: 'O(log n) time and O(1) space one-pass search',
      timeComplexity: 'O(log n)',
      timeComplexityDetail: 'Halves the search space on each step.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only index pointers.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~35ms, Beats 99%)',
      explanation: 'At each mid, determine whether [l..mid] or [mid..r] is sorted, then check if target is inside sorted range.',
      keySteps: [
        '1. l = 0, r = len(nums) - 1.',
        '2. While l <= r:',
        '   a. mid = l + (r - l) // 2.',
        '   b. If nums[mid] == target: return mid.',
        '   c. If nums[l] <= nums[mid] (left half sorted):',
        '      If nums[l] <= target < nums[mid]: r = mid - 1.',
        '      Else: l = mid + 1.',
        '   d. Else (right half sorted):',
        '      If nums[mid] < target <= nums[r]: l = mid + 1.',
        '      Else: r = mid - 1.',
        '3. Return -1.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def search(self, nums: List[int], target: int) -> int:',
          '        l, r = 0, len(nums) - 1',
          '        while l <= r:',
          '            mid = l + (r - l) // 2',
          '            if nums[mid] == target:',
          '                return mid',
          '            if nums[l] <= nums[mid]:',
          '                if nums[l] <= target < nums[mid]:',
          '                    r = mid - 1',
          '                else:',
          '                    l = mid + 1',
          '            else:',
          '                if nums[mid] < target <= nums[r]:',
          '                    l = mid + 1',
          '                else:',
          '                    r = mid - 1',
          '        return -1',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int search(vector<int>& nums, int target) {',
          '        int l = 0, r = nums.size() - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] == target) return mid;',
          '            if (nums[l] <= nums[mid]) {',
          '                if (nums[l] <= target && target < nums[mid]) r = mid - 1;',
          '                else l = mid + 1;',
          '            } else {',
          '                if (nums[mid] < target && target <= nums[r]) l = mid + 1;',
          '                else r = mid - 1;',
          '            }',
          '        }',
          '        return -1;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int search(int[] nums, int target) {',
          '        int l = 0, r = nums.length - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] == target) return mid;',
          '            if (nums[l] <= nums[mid]) {',
          '                if (nums[l] <= target && target < nums[mid]) r = mid - 1;',
          '                else l = mid + 1;',
          '            } else {',
          '                if (nums[mid] < target && target <= nums[r]) l = mid + 1;',
          '                else r = mid - 1;',
          '            }',
          '        }',
          '        return -1;',
          '    }',
          '}',
        ],
        typescript: [
          'function search(nums: number[], target: number): number {',
          '  let l = 0, r = nums.length - 1;',
          '  while (l <= r) {',
          '    const mid = l + Math.floor((r - l) / 2);',
          '    if (nums[mid] === target) return mid;',
          '    if (nums[l] <= nums[mid]) {',
          '      if (nums[l] <= target && target < nums[mid]) r = mid - 1;',
          '      else l = mid + 1;',
          '    } else {',
          '      if (nums[mid] < target && target <= nums[r]) l = mid + 1;',
          '      else r = mid - 1;',
          '    }',
          '  }',
          '  return -1;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Linear Scan',
      subtitle: 'O(n) search',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Scan through array elements.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '✅ Accepted (Suboptimal)',
      explanation: 'Search linearly for target in array.',
      keySteps: ['1. Loop through array.'],
      code: {
        python: [
          'class Solution:',
          '    def search(self, nums: List[int], target: int) -> int:',
          '        for i, val in enumerate(nums):',
          '            if val == target: return i',
          '        return -1',
        ],
        cpp: ['// Linear scan'],
        java: ['// Linear scan'],
        typescript: ['// Linear scan'],
      },
    },
  },

  'Search in Rotated Sorted Array II': {
    intuition: 'Array contains DUPLICATES. When `nums[l] == nums[mid] == nums[r]`, we cannot determine which half is sorted. In this ambiguous case, we safely shrink boundaries by incrementing `l` and decrementing `r` (`l += 1`, `r -= 1`). Otherwise, use the standard Rotated Binary Search logic.',
    bottleneck: 'In the worst case (e.g. `[1, 1, 1, 1, 1, 2, 1]`), duplicate ambiguity degrades performance to O(n). Average time remains O(log n).',
    keyInvariant: 'Shrinking l and r when `nums[l] == nums[mid] == nums[r]` preserves target existence because target != nums[mid].',
    constraints: ['1 <= nums.length <= 5000', '-10^4 <= nums[i], target <= 10^4', 'nums may contain duplicates.'],
    examples: [
      { input: 'nums = [2,5,6,0,0,1,2], target = 0', output: 'true', explanation: '0 is in array.' },
      { input: 'nums = [2,5,6,0,0,1,2], target = 3', output: 'false', explanation: '3 is not in array.' },
    ],
    companies: ['Amazon', 'Google', 'Microsoft'],
    acceptanceRate: '37.1%',
    frequency: '76%',
    edgeCases: ['Array of all identical elements except one (e.g. `[1,1,1,2,1]`)', 'Target is the duplicate value'],
    interviewTips: ['State clearly that worst-case time is O(n) due to duplicates, but average time is O(log n).'],
    optimal: {
      title: 'Rotated Binary Search with Duplicate Boundary Shrinking',
      subtitle: 'O(log n) average time, O(n) worst-case time, O(1) space',
      timeComplexity: 'O(log n) average, O(n) worst-case',
      timeComplexityDetail: 'When nums[l] == nums[mid] == nums[r], shrinks linearly; otherwise halves search space.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only index pointers.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~40ms, Beats 99%)',
      explanation: 'Check if nums[l] == nums[mid] == nums[r]; if so, l += 1, r -= 1. Otherwise perform standard rotated binary search.',
      keySteps: [
        '1. l = 0, r = len(nums) - 1.',
        '2. While l <= r:',
        '   a. mid = l + (r - l) // 2.',
        '   b. If nums[mid] == target: return True.',
        '   c. If nums[l] == nums[mid] == nums[r]: l += 1, r -= 1, continue.',
        '   d. If nums[l] <= nums[mid]:',
        '      If nums[l] <= target < nums[mid]: r = mid - 1.',
        '      Else: l = mid + 1.',
        '   e. Else:',
        '      If nums[mid] < target <= nums[r]: l = mid + 1.',
        '      Else: r = mid - 1.',
        '3. Return False.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def search(self, nums: List[int], target: int) -> bool:',
          '        l, r = 0, len(nums) - 1',
          '        while l <= r:',
          '            mid = l + (r - l) // 2',
          '            if nums[mid] == target:',
          '                return True',
          '            if nums[l] == nums[mid] == nums[r]:',
          '                l += 1',
          '                r -= 1',
          '            elif nums[l] <= nums[mid]:',
          '                if nums[l] <= target < nums[mid]:',
          '                    r = mid - 1',
          '                else:',
          '                    l = mid + 1',
          '            else:',
          '                if nums[mid] < target <= nums[r]:',
          '                    l = mid + 1',
          '                else:',
          '                    r = mid - 1',
          '        return False',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    bool search(vector<int>& nums, int target) {',
          '        int l = 0, r = nums.size() - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] == target) return true;',
          '            if (nums[l] == nums[mid] && nums[mid] == nums[r]) {',
          '                l++; r--;',
          '            } else if (nums[l] <= nums[mid]) {',
          '                if (nums[l] <= target && target < nums[mid]) r = mid - 1;',
          '                else l = mid + 1;',
          '            } else {',
          '                if (nums[mid] < target && target <= nums[r]) l = mid + 1;',
          '                else r = mid - 1;',
          '            }',
          '        }',
          '        return false;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public boolean search(int[] nums, int target) {',
          '        int l = 0, r = nums.length - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] == target) return true;',
          '            if (nums[l] == nums[mid] && nums[mid] == nums[r]) {',
          '                l++; r--;',
          '            } else if (nums[l] <= nums[mid]) {',
          '                if (nums[l] <= target && target < nums[mid]) r = mid - 1;',
          '                else l = mid + 1;',
          '            } else {',
          '                if (nums[mid] < target && target <= nums[r]) l = mid + 1;',
          '                else r = mid - 1;',
          '            }',
          '        }',
          '        return false;',
          '    }',
          '}',
        ],
        typescript: [
          'function search(nums: number[], target: number): boolean {',
          '  let l = 0, r = nums.length - 1;',
          '  while (l <= r) {',
          '    const mid = l + Math.floor((r - l) / 2);',
          '    if (nums[mid] === target) return true;',
          '    if (nums[l] === nums[mid] && nums[mid] === nums[r]) {',
          '      l++; r--;',
          '    } else if (nums[l] <= nums[mid]) {',
          '      if (nums[l] <= target && target < nums[mid]) r = mid - 1;',
          '      else l = mid + 1;',
          '    } else {',
          '      if (nums[mid] < target && target <= nums[r]) l = mid + 1;',
          '      else r = mid - 1;',
          '    }',
          '  }',
          '  return false;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Linear Scan',
      subtitle: 'O(n) scan',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Scan array elements.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '✅ Accepted',
      explanation: 'Iterate through nums and return True if target found.',
      keySteps: ['1. Return target in nums.'],
      code: {
        python: [
          'class Solution:',
          '    def search(self, nums: List[int], target: int) -> bool:',
          '        return target in nums',
        ],
        cpp: ['// Linear scan'],
        java: ['// Linear scan'],
        typescript: ['// Linear scan'],
      },
    },
  },

  'Find Minimum in Rotated Sorted Array': {
    intuition: 'The minimum element is the pivot point where the rotation occurred. Compare `nums[mid]` with `nums[r]`. If `nums[mid] > nums[r]`, the minimum must lie strictly to the right of `mid` (set `l = mid + 1`). If `nums[mid] <= nums[r]`, the minimum is at `mid` or to its left (set `r = mid`). When `l == r`, `nums[l]` is the minimum.',
    bottleneck: 'Scanning the whole array takes O(n). Binary search compares with right boundary to locate the inflection in O(log n) time.',
    keyInvariant: 'The minimum element is always contained within the interval [l, r].',
    constraints: ['n == nums.length', '1 <= n <= 5000', '-5000 <= nums[i] <= 5000', 'All integers of nums are unique.', 'nums was originally sorted and rotated between 1 and n times.'],
    examples: [
      { input: 'nums = [3,4,5,1,2]', output: '1', explanation: 'Original was [1,2,3,4,5] rotated 3 times.' },
      { input: 'nums = [4,5,6,7,0,1,2]', output: '0', explanation: 'Original rotated 4 times.' },
      { input: 'nums = [11,13,15,17]', output: '11', explanation: 'Rotated 4 times (fully sorted).' },
    ],
    companies: ['Amazon', 'Microsoft', 'Google', 'Meta', 'Apple'],
    acceptanceRate: '50.1%',
    frequency: '94%',
    edgeCases: ['Array rotated 0/n times (already fully sorted: returns nums[0])', 'Single element array', 'Array of size 2'],
    interviewTips: ['Explain why we compare with `nums[r]` rather than `nums[l]`: comparing with `nums[r]` unambiguously tells whether the pivot is in the right half.'],
    optimal: {
      title: 'Binary Search Pivot Detection',
      subtitle: 'O(log n) time and O(1) space binary search',
      timeComplexity: 'O(log n)',
      timeComplexityDetail: 'Halves the interval in each iteration.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only pointer variables.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~35ms, Beats 99%)',
      explanation: 'Binary search with l=0, r=len(nums)-1. If nums[mid] > nums[r]: l = mid + 1; else r = mid. Return nums[l].',
      keySteps: [
        '1. l = 0, r = len(nums) - 1.',
        '2. While l < r:',
        '   a. mid = l + (r - l) // 2.',
        '   b. If nums[mid] > nums[r]: l = mid + 1.',
        '   c. Else: r = mid.',
        '3. Return nums[l].',
      ],
      code: {
        python: [
          'class Solution:',
          '    def findMin(self, nums: List[int]) -> int:',
          '        l, r = 0, len(nums) - 1',
          '        while l < r:',
          '            mid = l + (r - l) // 2',
          '            if nums[mid] > nums[r]:',
          '                l = mid + 1',
          '            else:',
          '                r = mid',
          '        return nums[l]',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int findMin(vector<int>& nums) {',
          '        int l = 0, r = nums.size() - 1;',
          '        while (l < r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] > nums[r]) l = mid + 1;',
          '            else r = mid;',
          '        }',
          '        return nums[l];',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int findMin(int[] nums) {',
          '        int l = 0, r = nums.length - 1;',
          '        while (l < r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] > nums[r]) l = mid + 1;',
          '            else r = mid;',
          '        }',
          '        return nums[l];',
          '    }',
          '}',
        ],
        typescript: [
          'function findMin(nums: number[]): number {',
          '  let l = 0, r = nums.length - 1;',
          '  while (l < r) {',
          '    const mid = l + Math.floor((r - l) / 2);',
          '    if (nums[mid] > nums[r]) l = mid + 1;',
          '    else r = mid;',
          '  }',
          '  return nums[l];',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Linear Min Search',
      subtitle: 'O(n) scan',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Scan through array to find minimum.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '✅ Accepted (Suboptimal)',
      explanation: 'Use min() function or iterate to find minimum value in array.',
      keySteps: ['1. Return min(nums).'],
      code: {
        python: [
          'class Solution:',
          '    def findMin(self, nums: List[int]) -> int:',
          '        return min(nums)',
        ],
        cpp: ['// min_element'],
        java: ['// linear min'],
        typescript: ['// Math.min'],
      },
    },
  },

  'Time Based Key-Value Store': {
    intuition: 'Timestamps for each key are strictly increasing on calls to `set()`. Store values for each key in an array of `(timestamp, value)` pairs. On `get(key, timestamp)`, use Binary Search (or bisect) to find the rightmost timestamp that is `<= query_timestamp`.',
    bottleneck: 'Linearly scanning timestamps takes O(total_sets) per get. Binary search executes each get in O(log N) time.',
    keyInvariant: 'Timestamp arrays are naturally sorted in strictly ascending order because timestamps are strictly increasing.',
    constraints: ['1 <= key.length, value.length <= 100', '1 <= timestamp <= 10^7', 'All timestamp values of set are strictly increasing.', 'At most 2 * 10^5 calls to set and get.'],
    examples: [
      { input: '["TimeMap","set","get","get","set","get","get"]\\n[[],["foo","bar",1],["foo",1],["foo",3],["foo","bar2",4],["foo",4],["foo",5]]', output: '[null,null,"bar","bar",null,"bar2","bar2"]', explanation: 'Binary search correctly retrieves latest value <= timestamp.' }
    ],
    companies: ['Google', 'Amazon', 'Meta', 'Netflix', 'Apple'],
    acceptanceRate: '53.8%',
    frequency: '92%',
    edgeCases: ['Query timestamp smaller than first stored timestamp (returns "")', 'Exact timestamp match', 'Multiple set calls for same key'],
    interviewTips: ['Show how rightmost binary search (`bisect_right`) cleanly finds the largest timestamp <= target.'],
    optimal: {
      title: 'Hash Map of Timestamp-Sorted Arrays + Binary Search',
      subtitle: 'O(1) set() and O(log N) get() time',
      timeComplexity: 'O(1) set, O(log N) get',
      timeComplexityDetail: 'Set appends to list in O(1); get binary searches timestamp list in O(log N).',
      spaceComplexity: 'O(N)',
      spaceComplexityDetail: 'Stores all key-value-timestamp entries.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~480ms, Beats 98%)',
      explanation: 'Map each key to list of [timestamp, value]. On get, binary search for latest timestamp <= query.',
      keySteps: [
        '1. self.store = collections.defaultdict(list).',
        '2. set(key, value, timestamp): self.store[key].append((timestamp, value)).',
        '3. get(key, timestamp): binary search on self.store[key] for largest t <= timestamp.',
      ],
      code: {
        python: [
          'from collections import defaultdict',
          'class TimeMap:',
          '    def __init__(self):',
          '        self.store = defaultdict(list)',
          '',
          '    def set(self, key: str, value: str, timestamp: int) -> None:',
          '        self.store[key].append((timestamp, value))',
          '',
          '    def get(self, key: str, timestamp: int) -> str:',
          '        if key not in self.store: return ""',
          '        arr = self.store[key]',
          '        l, r = 0, len(arr) - 1',
          '        res = ""',
          '        while l <= r:',
          '            mid = l + (r - l) // 2',
          '            if arr[mid][0] <= timestamp:',
          '                res = arr[mid][1]',
          '                l = mid + 1',
          '            else:',
          '                r = mid - 1',
          '        return res',
        ],
        cpp: [
          '#include <string>',
          '#include <unordered_map>',
          '#include <vector>',
          'using namespace std;',
          'class TimeMap {',
          '    unordered_map<string, vector<pair<int, string>>> store;',
          'public:',
          '    TimeMap() {}',
          '    void set(string key, string value, int timestamp) {',
          '        store[key].push_back({timestamp, value});',
          '    }',
          '    string get(string key, int timestamp) {',
          '        if (!store.count(key)) return "";',
          '        auto& arr = store[key];',
          '        int l = 0, r = arr.size() - 1;',
          '        string res = "";',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (arr[mid].first <= timestamp) {',
          '                res = arr[mid].second;',
          '                l = mid + 1;',
          '            } else r = mid - 1;',
          '        }',
          '        return res;',
          '    }',
          '};',
        ],
        java: [
          'import java.util.*;',
          'class TimeMap {',
          '    private Map<String, List<Pair>> store = new HashMap<>();',
          '    private static class Pair {',
          '        int timestamp; String value;',
          '        Pair(int timestamp, String value) { this.timestamp = timestamp; this.value = value; }',
          '    }',
          '    public TimeMap() {}',
          '    public void set(String key, String value, int timestamp) {',
          '        store.computeIfAbsent(key, k -> new ArrayList<>()).add(new Pair(timestamp, value));',
          '    }',
          '    public String get(String key, int timestamp) {',
          '        if (!store.containsKey(key)) return "";',
          '        List<Pair> arr = store.get(key);',
          '        int l = 0, r = arr.size() - 1; String res = "";',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (arr.get(mid).timestamp <= timestamp) {',
          '                res = arr.get(mid).value;',
          '                l = mid + 1;',
          '            } else r = mid - 1;',
          '        }',
          '        return res;',
          '    }',
          '}',
        ],
        typescript: [
          'class TimeMap {',
          '  private store = new Map<string, [number, string][]>();',
          '  set(key: string, value: string, timestamp: number): void {',
          '    if (!this.store.has(key)) this.store.set(key, []);',
          '    this.store.get(key)!.push([timestamp, value]);',
          '  }',
          '  get(key: string, timestamp: number): string {',
          '    const arr = this.store.get(key);',
          '    if (!arr) return "";',
          '    let l = 0, r = arr.length - 1, res = "";',
          '    while (l <= r) {',
          '      const mid = l + Math.floor((r - l) / 2);',
          '      if (arr[mid][0] <= timestamp) {',
          '        res = arr[mid][1];',
          '        l = mid + 1;',
          '      } else r = mid - 1;',
          '    }',
          '    return res;',
          '  }',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Linear Scan on Timestamp List',
      subtitle: 'O(N) search per get',
      timeComplexity: 'O(N) per get',
      timeComplexityDetail: 'Scan backwards through all timestamps.',
      spaceComplexity: 'O(N)',
      spaceComplexityDetail: 'Storage for pairs.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Iterate backwards from end of timestamp list until timestamp <= query.',
      keySteps: ['1. Loop backwards in list.'],
      code: {
        python: [
          'class TimeMap:',
          '    def __init__(self): self.store = collections.defaultdict(list)',
          '    def set(self, k, v, t): self.store[k].append((t, v))',
          '    def get(self, k, t):',
          '        for timestamp, val in reversed(self.store[k]):',
          '            if timestamp <= t: return val',
          '        return ""',
        ],
        cpp: ['// Linear scan'],
        java: ['// Linear scan'],
        typescript: ['// Linear scan'],
      },
    },
  },

  'Median of Two Sorted Arrays': {
    intuition: 'We partition nums1 into left1/right1 of size `i`, and nums2 into left2/right2 of size `j = (m + n + 1) // 2 - i`, such that the combined left partition contains exactly half the total elements. The partition is correct when `max(left1) <= min(right2)` and `max(left2) <= min(right1)`. We binary search for `i` in range `[0, m]` on the smaller array in O(log(min(m, n))) time.',
    bottleneck: 'Merging arrays takes O(m + n) time. Binary search on the partition cut achieves O(log(min(m, n))) optimal logarithmic runtime.',
    keyInvariant: 'Every element in combined left partition is <= every element in combined right partition.',
    constraints: ['nums1.length == m', 'nums2.length == n', '0 <= m <= 1000', '0 <= n <= 1000', '1 <= m + n <= 2000', '-10^6 <= nums1[i], nums2[i] <= 10^6'],
    examples: [
      { input: 'nums1 = [1,3], nums2 = [2]', output: '2.00000', explanation: 'Merged is [1,2,3], median = 2.' },
      { input: 'nums1 = [1,2], nums2 = [3,4]', output: '2.50000', explanation: 'Merged is [1,2,3,4], median = (2 + 3) / 2 = 2.5.' },
    ],
    companies: ['Google', 'Amazon', 'Meta', 'Microsoft', 'Apple', 'Goldman Sachs'],
    acceptanceRate: '38.8%',
    frequency: '96%',
    edgeCases: ['One array is empty', 'Total elements odd vs even', 'Disjoint ranges (all elements in nums1 smaller than nums2)'],
    interviewTips: ['Always binary search on the SHORTER array so that partition size j is guaranteed >= 0 and binary search takes O(log(min(m, n))).'],
    optimal: {
      title: 'Binary Search on Partition Cut of Shorter Array',
      subtitle: 'O(log(min(m, n))) time and O(1) space optimal partition search',
      timeComplexity: 'O(log(min(m, n)))',
      timeComplexityDetail: 'Binary search on index i in range [0, min(m, n)].',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only partition variables.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~60ms, Beats 99%)',
      explanation: 'Binary search cut i in shorter array A. Compute cut j in B. Check boundary conditions, adjust search interval.',
      keySteps: [
        '1. Ensure A is shorter than B (swap if needed). m, n = len(A), len(B), half = (m + n + 1) // 2.',
        '2. l = 0, r = m.',
        '3. While l <= r:',
        '   a. i = (l + r) // 2, j = half - i.',
        '   b. A_left = A[i-1] if i > 0 else -inf; A_right = A[i] if i < m else inf.',
        '   c. B_left = B[j-1] if j > 0 else -inf; B_right = B[j] if j < n else inf.',
        '   d. If A_left <= B_right and B_left <= A_right:',
        '      If (m + n) % 2 != 0: return max(A_left, B_left).',
        '      Else: return (max(A_left, B_left) + min(A_right, B_right)) / 2.0.',
        '   e. If A_left > B_right: r = i - 1.',
        '   f. Else: l = i + 1.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:',
          '        A, B = nums1, nums2',
          '        if len(A) > len(B):',
          '            A, B = B, A',
          '        m, n = len(A), len(B)',
          '        half = (m + n + 1) // 2',
          '        l, r = 0, m',
          '        while l <= r:',
          '            i = (l + r) // 2',
          '            j = half - i',
          '            A_left = A[i - 1] if i > 0 else float("-inf")',
          '            A_right = A[i] if i < m else float("inf")',
          '            B_left = B[j - 1] if j > 0 else float("-inf")',
          '            B_right = B[j] if j < n else float("inf")',
          '            if A_left <= B_right and B_left <= A_right:',
          '                if (m + n) % 2 != 0:',
          '                    return float(max(A_left, B_left))',
          '                return (max(A_left, B_left) + min(A_right, B_right)) / 2.0',
          '            elif A_left > B_right:',
          '                r = i - 1',
          '            else:',
          '                l = i + 1',
          '        return 0.0',
        ],
        cpp: [
          '#include <vector>',
          '#include <algorithm>',
          '#include <climits>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {',
          '        if (nums1.size() > nums2.size()) return findMedianSortedArrays(nums2, nums1);',
          '        int m = nums1.size(), n = nums2.size();',
          '        int half = (m + n + 1) / 2;',
          '        int l = 0, r = m;',
          '        while (l <= r) {',
          '            int i = l + (r - l) / 2;',
          '            int j = half - i;',
          '            int A_left = (i > 0) ? nums1[i - 1] : INT_MIN;',
          '            int A_right = (i < m) ? nums1[i] : INT_MAX;',
          '            int B_left = (j > 0) ? nums2[j - 1] : INT_MIN;',
          '            int B_right = (j < n) ? nums2[j] : INT_MAX;',
          '            if (A_left <= B_right && B_left <= A_right) {',
          '                if ((m + n) % 2 != 0) return max(A_left, B_left);',
          '                return (max(A_left, B_left) + min(A_right, B_right)) / 2.0;',
          '            } else if (A_left > B_right) r = i - 1;',
          '            else l = i + 1;',
          '        }',
          '        return 0.0;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public double findMedianSortedArrays(int[] nums1, int[] nums2) {',
          '        if (nums1.length > nums2.length) return findMedianSortedArrays(nums2, nums1);',
          '        int m = nums1.length, n = nums2.length;',
          '        int half = (m + n + 1) / 2;',
          '        int l = 0, r = m;',
          '        while (l <= r) {',
          '            int i = l + (r - l) / 2;',
          '            int j = half - i;',
          '            int A_left = (i > 0) ? nums1[i - 1] : Integer.MIN_VALUE;',
          '            int A_right = (i < m) ? nums1[i] : Integer.MAX_VALUE;',
          '            int B_left = (j > 0) ? nums2[j - 1] : Integer.MIN_VALUE;',
          '            int B_right = (j < n) ? nums2[j] : Integer.MAX_VALUE;',
          '            if (A_left <= B_right && B_left <= A_right) {',
          '                if ((m + n) % 2 != 0) return Math.max(A_left, B_left);',
          '                return (Math.max(A_left, B_left) + Math.min(A_right, B_right)) / 2.0;',
          '            } else if (A_left > B_right) r = i - 1;',
          '            else l = i + 1;',
          '        }',
          '        return 0.0;',
          '    }',
          '}',
        ],
        typescript: [
          'function findMedianSortedArrays(nums1: number[], nums2: number[]): number {',
          '  if (nums1.length > nums2.length) return findMedianSortedArrays(nums2, nums1);',
          '  const m = nums1.length, n = nums2.length;',
          '  const half = Math.floor((m + n + 1) / 2);',
          '  let l = 0, r = m;',
          '  while (l <= r) {',
          '    const i = l + Math.floor((r - l) / 2);',
          '    const j = half - i;',
          '    const A_left = i > 0 ? nums1[i - 1] : -Infinity;',
          '    const A_right = i < m ? nums1[i] : Infinity;',
          '    const B_left = j > 0 ? nums2[j - 1] : -Infinity;',
          '    const B_right = j < n ? nums2[j] : Infinity;',
          '    if (A_left <= B_right && B_left <= A_right) {',
          '      if ((m + n) % 2 !== 0) return Math.max(A_left, B_left);',
          '      return (Math.max(A_left, B_left) + Math.min(A_right, B_right)) / 2.0;',
          '    } else if (A_left > B_right) r = i - 1;',
          '    else l = i + 1;',
          '  }',
          '  return 0.0;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Merge Arrays and Take Middle',
      subtitle: 'O(m + n) two-pointer merge',
      timeComplexity: 'O(m + n)',
      timeComplexityDetail: 'Merge both sorted arrays into single array.',
      spaceComplexity: 'O(m + n)',
      spaceComplexityDetail: 'Merged array storage.',
      status: 'better',
      leetcodeStatus: '✅ Accepted (Suboptimal runtime)',
      explanation: 'Merge nums1 and nums2 using standard two pointers, then return element at (m+n)//2.',
      keySteps: ['1. Merge nums1 and nums2.', '2. Compute median.'],
      code: {
        python: [
          'class Solution:',
          '    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:',
          '        merged = sorted(nums1 + nums2)',
          '        n = len(merged)',
          '        if n % 2 == 1: return float(merged[n // 2])',
          '        return (merged[n // 2 - 1] + merged[n // 2]) / 2.0',
        ],
        cpp: ['// Merge and sort'],
        java: ['// Merge and sort'],
        typescript: ['// Merge and sort'],
      },
    },
  },

  'Search Insert Position': {
    intuition: 'We need the index where target exists, or the index where it would be inserted in sorted order. In binary search, when target is not found, the left pointer `l` always converges to the exact lower bound index where target should be inserted.',
    bottleneck: 'Linear search takes O(n). Binary search lower bound runs in O(log n) time.',
    keyInvariant: 'At termination, l is the index of the first element >= target.',
    constraints: ['1 <= nums.length <= 10^4', '-10^4 <= nums[i], target <= 10^4', 'nums contains distinct values sorted in ascending order.'],
    examples: [
      { input: 'nums = [1,3,5,6], target = 5', output: '2', explanation: '5 is at index 2.' },
      { input: 'nums = [1,3,5,6], target = 2', output: '1', explanation: '2 would be inserted at index 1.' },
      { input: 'nums = [1,3,5,6], target = 7', output: '4', explanation: '7 inserted at end (index 4).' },
    ],
    companies: ['Google', 'Amazon', 'Apple', 'Microsoft'],
    acceptanceRate: '45.1%',
    frequency: '85%',
    edgeCases: ['Target smaller than all elements (returns 0)', 'Target larger than all elements (returns len(nums))'],
    interviewTips: ['Explain why returning `l` after loop `while l <= r` automatically handles both found and not-found insertion points.'],
    optimal: {
      title: 'Binary Search Lower Bound',
      subtitle: 'O(log n) time and O(1) space insertion position',
      timeComplexity: 'O(log n)',
      timeComplexityDetail: 'Standard binary search halving search space.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only index pointers.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~35ms, Beats 99%)',
      explanation: 'Binary search with l=0, r=len(nums)-1. When target > nums[mid], l = mid + 1; else r = mid - 1. Return l.',
      keySteps: [
        '1. l = 0, r = len(nums) - 1.',
        '2. While l <= r:',
        '   a. mid = l + (r - l) // 2.',
        '   b. If nums[mid] == target: return mid.',
        '   c. If nums[mid] < target: l = mid + 1.',
        '   d. Else: r = mid - 1.',
        '3. Return l.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def searchInsert(self, nums: List[int], target: int) -> int:',
          '        l, r = 0, len(nums) - 1',
          '        while l <= r:',
          '            mid = l + (r - l) // 2',
          '            if nums[mid] == target:',
          '                return mid',
          '            elif nums[mid] < target:',
          '                l = mid + 1',
          '            else:',
          '                r = mid - 1',
          '        return l',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int searchInsert(vector<int>& nums, int target) {',
          '        int l = 0, r = nums.size() - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] == target) return mid;',
          '            else if (nums[mid] < target) l = mid + 1;',
          '            else r = mid - 1;',
          '        }',
          '        return l;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int searchInsert(int[] nums, int target) {',
          '        int l = 0, r = nums.length - 1;',
          '        while (l <= r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] == target) return mid;',
          '            else if (nums[mid] < target) l = mid + 1;',
          '            else r = mid - 1;',
          '        }',
          '        return l;',
          '    }',
          '}',
        ],
        typescript: [
          'function searchInsert(nums: number[], target: number): number {',
          '  let l = 0, r = nums.length - 1;',
          '  while (l <= r) {',
          '    const mid = l + Math.floor((r - l) / 2);',
          '    if (nums[mid] === target) return mid;',
          '    else if (nums[mid] < target) l = mid + 1;',
          '    else r = mid - 1;',
          '  }',
          '  return l;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Linear Scan',
      subtitle: 'O(n) sequential scan',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Scan until element >= target.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '✅ Accepted (Suboptimal)',
      explanation: 'Iterate i from 0 to n-1: if nums[i] >= target: return i. Return n.',
      keySteps: ['1. Loop i in 0..n-1: if nums[i] >= target: return i.', '2. Return n.'],
      code: {
        python: [
          'class Solution:',
          '    def searchInsert(self, nums: List[int], target: int) -> int:',
          '        for i, val in enumerate(nums):',
          '            if val >= target: return i',
          '        return len(nums)',
        ],
        cpp: ['// Linear scan'],
        java: ['// Linear scan'],
        typescript: ['// Linear scan'],
      },
    },
  },

  'Find Peak Element': {
    intuition: 'A peak element is strictly greater than its neighbors. Boundary conditions treat `nums[-1] = nums[n] = -inf`. Using Binary Search: compare `nums[mid]` with `nums[mid + 1]`. If `nums[mid] < nums[mid + 1]`, the array is rising to the right, guaranteeing at least one peak exists in `[mid + 1, r]`. If `nums[mid] > nums[mid + 1]`, a peak exists at `mid` or to its left in `[l, mid]`.',
    bottleneck: 'Linear search takes O(n). Gradient ascent binary search finds a peak in O(log n) time.',
    keyInvariant: 'Following the ascending slope guarantees encountering a local maximum.',
    constraints: ['1 <= nums.length <= 1000', '-2^31 <= nums[i] <= 2^31 - 1', 'nums[i] != nums[i + 1] for all valid i.'],
    examples: [
      { input: 'nums = [1,2,3,1]', output: '2', explanation: 'Index 2 (value 3) is a peak.' },
      { input: 'nums = [1,2,1,3,5,6,4]', output: '5', explanation: 'Index 5 (value 6) or index 1 (value 2) is a peak.' },
    ],
    companies: ['Meta', 'Amazon', 'Google', 'Microsoft'],
    acceptanceRate: '46.1%',
    frequency: '92%',
    edgeCases: ['Array strictly increasing (peak is last element)', 'Array strictly decreasing (peak is first element)', 'Single element array (returns 0)'],
    interviewTips: ['Explain why binary search works on unsorted arrays here: we are climbing up a slope where an ascent must eventually peak before boundary -inf.'],
    optimal: {
      title: 'Binary Search Gradient Ascent',
      subtitle: 'O(log n) time and O(1) space peak discovery',
      timeComplexity: 'O(log n)',
      timeComplexityDetail: 'Halves the search space on each step.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only pointer variables.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~35ms, Beats 99%)',
      explanation: 'Binary search with l=0, r=len(nums)-1. If nums[mid] < nums[mid+1]: l = mid + 1; else r = mid. Return l.',
      keySteps: [
        '1. l = 0, r = len(nums) - 1.',
        '2. While l < r:',
        '   a. mid = l + (r - l) // 2.',
        '   b. If nums[mid] < nums[mid + 1]: l = mid + 1.',
        '   c. Else: r = mid.',
        '3. Return l.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def findPeakElement(self, nums: List[int]) -> int:',
          '        l, r = 0, len(nums) - 1',
          '        while l < r:',
          '            mid = l + (r - l) // 2',
          '            if nums[mid] < nums[mid + 1]:',
          '                l = mid + 1',
          '            else:',
          '                r = mid',
          '        return l',
        ],
        cpp: [
          '#include <vector>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int findPeakElement(vector<int>& nums) {',
          '        int l = 0, r = nums.size() - 1;',
          '        while (l < r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] < nums[mid + 1]) l = mid + 1;',
          '            else r = mid;',
          '        }',
          '        return l;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int findPeakElement(int[] nums) {',
          '        int l = 0, r = nums.length - 1;',
          '        while (l < r) {',
          '            int mid = l + (r - l) / 2;',
          '            if (nums[mid] < nums[mid + 1]) l = mid + 1;',
          '            else r = mid;',
          '        }',
          '        return l;',
          '    }',
          '}',
        ],
        typescript: [
          'function findPeakElement(nums: number[]): number {',
          '  let l = 0, r = nums.length - 1;',
          '  while (l < r) {',
          '    const mid = l + Math.floor((r - l) / 2);',
          '    if (nums[mid] < nums[mid + 1]) l = mid + 1;',
          '    else r = mid;',
          '  }',
          '  return l;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Linear Peak Scan',
      subtitle: 'O(n) scan',
      timeComplexity: 'O(n)',
      timeComplexityDetail: 'Scan until element > next element.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '✅ Accepted (Suboptimal)',
      explanation: 'First index i where nums[i] > nums[i+1] is a peak.',
      keySteps: ['1. Loop i in 0..n-2: if nums[i] > nums[i+1]: return i.', '2. Return n-1.'],
      code: {
        python: [
          'class Solution:',
          '    def findPeakElement(self, nums: List[int]) -> int:',
          '        for i in range(len(nums) - 1):',
          '            if nums[i] > nums[i + 1]: return i',
          '        return len(nums) - 1',
        ],
        cpp: ['// Linear scan'],
        java: ['// Linear scan'],
        typescript: ['// Linear scan'],
      },
    },
  },

  'Capacity To Ship Packages Within D Days': {
    intuition: 'We need the minimum ship capacity to deliver all packages within `days`. The capacity `cap` must be in range `[max(weights), sum(weights)]`. The number of days required to ship packages with capacity `cap` is a monotonically decreasing function of `cap`. We binary search the capacity range [max(weights), sum(weights)] in O(n * log(sum(weights))) time.',
    bottleneck: 'Testing capacities linearly takes O(sum(weights) * n). Binary search on capacity evaluates in logarithmic steps.',
    keyInvariant: 'If capacity `cap` ships all packages within `days`, any capacity > `cap` also can, enabling lower bound binary search.',
    constraints: ['1 <= days <= weights.length <= 5 * 10^4', '1 <= weights[i] <= 500'],
    examples: [
      { input: 'weights = [1,2,3,4,5,6,7,8,9,10], days = 5', output: '15', explanation: 'Capacity 15 ships: [1..5], [6,7], [8], [9], [10] in 5 days.' },
      { input: 'weights = [3,2,2,4,1,4], days = 3', output: '6', explanation: 'Capacity 6 ships in 3 days.' },
    ],
    companies: ['Google', 'Amazon', 'Meta', 'Microsoft'],
    acceptanceRate: '69.1%',
    frequency: '88%',
    edgeCases: ['days == len(weights) (capacity is max(weights))', 'days == 1 (capacity is sum(weights))'],
    interviewTips: ['Lower bound is max(weights) because the ship must be capable of carrying the heaviest single package.'],
    optimal: {
      title: 'Binary Search on Capacity Range [max(weights)..sum(weights)]',
      subtitle: 'O(n log(sum_weight)) time and O(1) space',
      timeComplexity: 'O(n log(sum_weight))',
      timeComplexityDetail: 'Binary search on range [max(w), sum(w)], each step checks in O(n) time.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'Only pointer variables.',
      status: 'optimal',
      leetcodeStatus: '✅ Accepted (Runtime: ~320ms, Beats 98%)',
      explanation: 'Binary search capacity. Helper function checks days needed. If days <= target: r = mid; else l = mid + 1.',
      keySteps: [
        '1. l = max(weights), r = sum(weights).',
        '2. While l < r:',
        '   a. mid = l + (r - l) // 2.',
        '   b. Count days needed with capacity mid: cur = 0, d = 1. For w in weights: if cur + w > mid: d += 1, cur = 0; cur += w.',
        '   c. If d <= days: r = mid.',
        '   d. Else: l = mid + 1.',
        '3. Return l.',
      ],
      code: {
        python: [
          'class Solution:',
          '    def shipWithinDays(self, weights: List[int], days: int) -> int:',
          '        l, r = max(weights), sum(weights)',
          '        while l < r:',
          '            mid = l + (r - l) // 2',
          '            needed_days = 1',
          '            cur_weight = 0',
          '            for w in weights:',
          '                if cur_weight + w > mid:',
          '                    needed_days += 1',
          '                    cur_weight = 0',
          '                cur_weight += w',
          '            if needed_days <= days:',
          '                r = mid',
          '            else:',
          '                l = mid + 1',
          '        return l',
        ],
        cpp: [
          '#include <vector>',
          '#include <numeric>',
          '#include <algorithm>',
          'using namespace std;',
          'class Solution {',
          'public:',
          '    int shipWithinDays(vector<int>& weights, int days) {',
          '        int l = *max_element(weights.begin(), weights.end());',
          '        int r = accumulate(weights.begin(), weights.end(), 0);',
          '        while (l < r) {',
          '            int mid = l + (r - l) / 2;',
          '            int needed = 1, cur = 0;',
          '            for (int w : weights) {',
          '                if (cur + w > mid) { needed++; cur = 0; }',
          '                cur += w;',
          '            }',
          '            if (needed <= days) r = mid;',
          '            else l = mid + 1;',
          '        }',
          '        return l;',
          '    }',
          '};',
        ],
        java: [
          'class Solution {',
          '    public int shipWithinDays(int[] weights, int days) {',
          '        int l = 0, r = 0;',
          '        for (int w : weights) { l = Math.max(l, w); r += w; }',
          '        while (l < r) {',
          '            int mid = l + (r - l) / 2;',
          '            int needed = 1, cur = 0;',
          '            for (int w : weights) {',
          '                if (cur + w > mid) { needed++; cur = 0; }',
          '                cur += w;',
          '            }',
          '            if (needed <= days) r = mid;',
          '            else l = mid + 1;',
          '        }',
          '        return l;',
          '    }',
          '}',
        ],
        typescript: [
          'function shipWithinDays(weights: number[], days: number): number {',
          '  let l = Math.max(...weights);',
          '  let r = weights.reduce((a, b) => a + b, 0);',
          '  while (l < r) {',
          '    const mid = l + Math.floor((r - l) / 2);',
          '    let needed = 1, cur = 0;',
          '    for (const w of weights) {',
          '      if (cur + w > mid) { needed++; cur = 0; }',
          '      cur += w;',
          '    }',
          '    if (needed <= days) r = mid;',
          '    else l = mid + 1;',
          '  }',
          '  return l;',
          '}',
        ],
      },
    },
    bruteForce: {
      title: 'Linear Capacity Search',
      subtitle: 'O((sum - max) * n) brute check',
      timeComplexity: 'O((sum - max) * n)',
      timeComplexityDetail: 'Test each capacity sequentially.',
      spaceComplexity: 'O(1)',
      spaceComplexityDetail: 'No extra memory.',
      status: 'brute',
      leetcodeStatus: '❌ Time Limit Exceeded',
      explanation: 'Try each capacity from max(weights) upward until it can ship within days.',
      keySteps: ['1. Loop cap from max(weights) to sum(weights).', '2. If canShip(cap): return cap.'],
      code: {
        python: [
          'class Solution:',
          '    def shipWithinDays(self, weights: List[int], days: int) -> int:',
          '        # Brute force capacity check',
          '        pass',
        ],
        cpp: ['// Linear capacity search'],
        java: ['// Linear capacity search'],
        typescript: ['// Linear capacity search'],
      },
    },
  },
}
