import { DetailedProblemData } from '../leetcodeSolutions'

export const trieSolutions: Record<string, DetailedProblemData> = {
  "Implement Trie (Prefix Tree)": {
    intuition: "A Trie (Prefix Tree) is a tree where each node represents a character and contains: 1) `children = {}` (map of char -> TrieNode), and 2) `is_end = False` (boolean marking end of complete word). insert: traverse/create nodes, set is_end=True. search: traverse nodes, return is_end. startsWith: traverse nodes, return True if prefix path exists.",
    bottleneck: "Hash set cannot do startsWith prefix checks in O(prefix_len). Trie performs all three operations in exact O(word_len) time.",
    keyInvariant: "Every path from root down represents a unique prefix shared among inserted words.",
    constraints: ["1 <= word.length, prefix.length <= 2000", "word and prefix consist only of lowercase English letters.", "At most 3 * 10^4 calls in total to insert, search, and startsWith."],
    examples: [{"input": "[\"Trie\", \"insert\", \"search\", \"search\", \"startsWith\", \"insert\", \"search\"]\\n[[], [\"apple\"], [\"apple\"], [\"app\"], [\"app\"], [\"app\"], [\"app\"]]", "output": "[null, null, true, false, true, null, true]", "explanation": "Prefix tree operations."}],
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Apple"],
    acceptanceRate: "64.2%",
    frequency: "95%",
    edgeCases: ["Searching prefix of inserted word before word inserted", "Single character word"],
    interviewTips: ["Highlight why Trie is optimal for autocomplete search engines."],
    optimal: {
      title: "TrieNode with Children Hash Map and is_end Flag",
      subtitle: "O(L) time per operation and O(Total Characters) space",
      timeComplexity: "O(L) for insert, search, startsWith",
      timeComplexityDetail: "L is word/prefix length.",
      spaceComplexity: "O(Total Characters)",
      spaceComplexityDetail: "Stores all prefix branches.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Create TrieNode class. Navigate children map character by character for all operations.",
      keySteps: ["1. TrieNode: children = {}, is_end = False.", "2. insert(word): curr = root. For c in word: if c not in curr.children: curr.children[c] = TrieNode(); curr = curr.children[c]. curr.is_end = True.", "3. search(word): curr = root. For c in word: if c not in curr.children: return False; curr = curr.children[c]. Return curr.is_end.", "4. startsWith(prefix): curr = root. For c in prefix: if c not in curr.children: return False; curr = curr.children[c]. Return True."],
      code: {
        python: ["class TrieNode:", "    def __init__(self):", "        self.children = {}", "        self.is_end = False", "", "class Trie:", "    def __init__(self):", "        self.root = TrieNode()", "", "    def insert(self, word: str) -> None:", "        curr = self.root", "        for c in word:", "            if c not in curr.children:", "                curr.children[c] = TrieNode()", "            curr = curr.children[c]", "        curr.is_end = True", "", "    def search(self, word: str) -> bool:", "        curr = self.root", "        for c in word:", "            if c not in curr.children:", "                return False", "            curr = curr.children[c]", "        return curr.is_end", "", "    def startsWith(self, prefix: str) -> bool:", "        curr = self.root", "        for c in prefix:", "            if c not in curr.children:", "                return False", "            curr = curr.children[c]", "        return True"],
        cpp: ["#include <string>", "#include <unordered_map>", "using namespace std;", "class TrieNode {", "public:", "    unordered_map<char, TrieNode*> children;", "    bool is_end = false;", "};", "class Trie {", "    TrieNode* root;", "public:", "    Trie() { root = new TrieNode(); }", "    void insert(string word) {", "        TrieNode* curr = root;", "        for (char c : word) {", "            if (!curr->children.count(c)) curr->children[c] = new TrieNode();", "            curr = curr->children[c];", "        }", "        curr->is_end = true;", "    }", "    bool search(string word) {", "        TrieNode* curr = root;", "        for (char c : word) {", "            if (!curr->children.count(c)) return false;", "            curr = curr->children[c];", "        }", "        return curr->is_end;", "    }", "    bool startsWith(string prefix) {", "        TrieNode* curr = root;", "        for (char c : prefix) {", "            if (!curr->children.count(c)) return false;", "            curr = curr->children[c];", "        }", "        return true;", "    }", "};"],
        java: ["import java.util.*;", "class TrieNode {", "    Map<Character, TrieNode> children = new HashMap<>();", "    boolean isEnd = false;", "}", "class Trie {", "    private TrieNode root = new TrieNode();", "    public void insert(String word) {", "        TrieNode curr = root;", "        for (char c : word.toCharArray()) {", "            curr.children.putIfAbsent(c, new TrieNode());", "            curr = curr.children.get(c);", "        }", "        curr.isEnd = true;", "    }", "    public boolean search(String word) {", "        TrieNode curr = root;", "        for (char c : word.toCharArray()) {", "            if (!curr.children.containsKey(c)) return false;", "            curr = curr.children.get(c);", "        }", "        return curr.isEnd;", "    }", "    public boolean startsWith(String prefix) {", "        TrieNode curr = root;", "        for (char c : prefix.toCharArray()) {", "            if (!curr.children.containsKey(c)) return false;", "            curr = curr.children.get(c);", "        }", "        return true;", "    }", "}"],
        typescript: ["class TrieNode {", "  children = new Map<string, TrieNode>();", "  isEnd = false;", "}", "class Trie {", "  private root = new TrieNode();", "  insert(word: string): void {", "    let curr = this.root;", "    for (const c of word) {", "      if (!curr.children.has(c)) curr.children.set(c, new TrieNode());", "      curr = curr.children.get(c)!;", "    }", "    curr.isEnd = true;", "  }", "  search(word: string): boolean {", "    let curr = this.root;", "    for (const c of word) {", "      if (!curr.children.has(c)) return false;", "      curr = curr.children.get(c)!;", "    }", "    return curr.isEnd;", "  }", "  startsWith(prefix: string): boolean {", "    let curr = this.root;", "    for (const c of prefix) {", "      if (!curr.children.has(c)) return false;", "      curr = curr.children.get(c)!;", "    }", "    return true;", "  }", "}"],
      },
    },
    bruteForce: {
      title: "Hash Set + StartsWith Scan",
      subtitle: "O(N * L) for startsWith",
      timeComplexity: "O(N * L) startsWith",
      timeComplexityDetail: "Linear scan across all words.",
      spaceComplexity: "O(N * L)",
      spaceComplexityDetail: "Stores all words in set.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Store words in a set, scan all words for startsWith prefix match.",
      keySteps: ["1. Set insert.", "2. Scan words on startsWith."],
      code: {
        python: ["# Hash set"],
        cpp: ["// Set"],
        java: ["// Set"],
        typescript: ["// Set"],
      },
    },
  },
  "Design Add and Search Words Data Structure": {
    intuition: "WordDictionary supports \".\" wildcard which matches any character. Store words in a Trie. When searching: standard characters follow `curr.children[c]`. When `c == \".\"`, explore ALL children branches using DFS backtracking. If any child path returns True, the search succeeds.",
    bottleneck: "Regex compilation on large word lists takes exponential time. Trie DFS with wildcard branching executes in O(M) for exact words and O(26^dots) in worst case.",
    keyInvariant: "Wildcard \".\" branches into all existing children at the current Trie depth level.",
    constraints: ["1 <= word.length <= 25", "word in addWord consists of lowercase English letters.", "word in search consists of \".\" or lowercase English letters.", "At most 2 dots in search queries.", "At most 10^4 calls."],
    examples: [{"input": "[\"WordDictionary\",\"addWord\",\"addWord\",\"addWord\",\"search\",\"search\",\"search\",\"search\"]\\n[[],[\"bad\"],[\"dad\"],[\"mad\"],[\"pad\"],[\"bad\"],[\".ad\"],[\"b..\"]]", "output": "[null,null,null,null,false,true,true,true]", "explanation": "Wildcards successfully match."}],
    companies: ["Meta", "Amazon", "Google", "Microsoft"],
    acceptanceRate: "45.1%",
    frequency: "92%",
    edgeCases: ["All dots query (e.g. \"...\": matches any 3-letter word)", "Word longer than any word in Trie"],
    interviewTips: ["Show helper `dfs(index, node)`: when char is dot, loop `for child in node.children.values(): if dfs(i + 1, child): return True`."],
    optimal: {
      title: "Trie + DFS Backtracking for Wildcard \".\" Matching",
      subtitle: "O(L) exact / O(26^dots) wildcard time and O(N*L) space",
      timeComplexity: "O(L) exact, O(26^dots) wildcard",
      timeComplexityDetail: "Branches only on dot characters.",
      spaceComplexity: "O(N * L)",
      spaceComplexityDetail: "Trie node storage.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "addWord inserts into Trie. search runs dfs(idx, node) exploring all child nodes on dot.",
      keySteps: ["1. addWord(word): standard Trie insertion.", "2. search(word): dfs(j, node): for i from j to len(word): c = word[i]; if c == \".\": for child in node.children.values(): if dfs(i + 1, child): return True; return False. elif c not in node.children: return False. Else: node = node.children[c]. Return node.is_end. Return dfs(0, root)."],
      code: {
        python: ["class TrieNode:", "    def __init__(self):", "        self.children = {}", "        self.is_end = False", "", "class WordDictionary:", "    def __init__(self):", "        self.root = TrieNode()", "", "    def addWord(self, word: str) -> None:", "        curr = self.root", "        for c in word:", "            if c not in curr.children: curr.children[c] = TrieNode()", "            curr = curr.children[c]", "        curr.is_end = True", "", "    def search(self, word: str) -> bool:", "        def dfs(j, node):", "            curr = node", "            for i in range(j, len(word)):", "                c = word[i]", "                if c == \".\":", "                    for child in curr.children.values():", "                        if dfs(i + 1, child): return True", "                    return False", "                else:", "                    if c not in curr.children: return False", "                    curr = curr.children[c]", "            return curr.is_end", "        return dfs(0, self.root)"],
        cpp: ["// Wildcard trie cpp"],
        java: ["// Wildcard trie java"],
        typescript: ["// Wildcard trie ts"],
      },
    },
    bruteForce: {
      title: "Length-Indexed Hash Map + Regex Search",
      subtitle: "O(N * L) search",
      timeComplexity: "O(N * L)",
      timeComplexityDetail: "Scans all words of matching length.",
      spaceComplexity: "O(N * L)",
      spaceComplexityDetail: "Dictionary storage.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Group words by length in dict, compare each word with query.",
      keySteps: ["1. Group by length.", "2. Scan words."],
      code: {
        python: ["# Length dict"],
        cpp: ["// Length dict"],
        java: ["// Length dict"],
        typescript: ["// Length dict"],
      },
    },
  },
  "Word Search II": {
    intuition: "We need to find all dictionary words present on an m x n board of characters. Build a Trie of all words in the dictionary. Run DFS / Backtracking from every cell `(r, c)` on the board. In DFS: match board character against Trie node children. If match found, mark cell visited (`\"#\"`) to prevent reuse, recurse to 4 adjacent neighbors, and restore character on backtrack. When reaching `node.is_end`, add word to results and set `node.is_end = False` to prevent duplicates (prune Trie nodes with no remaining children for speedup).",
    bottleneck: "Searching for each word individually on the board takes O(W * m * n * 4^L). Prefix Trie searches all W words simultaneously in O(m * n * 4^L) time.",
    keyInvariant: "DFS path on board corresponds directly to root-to-leaf path in Trie.",
    constraints: ["m == board.length", "n == board[i].length", "1 <= m, n <= 12", "1 <= words.length <= 3 * 10^4", "1 <= words[i].length <= 10", "board and words consist of lowercase English letters."],
    examples: [{"input": "board = [[\"o\",\"a\",\"a\",\"n\"],[\"e\",\"t\",\"a\",\"e\"],[\"i\",\"h\",\"k\",\"r\"],[\"i\",\"f\",\"l\",\"v\"]], words = [\"oath\",\"pea\",\"eat\",\"rain\"]", "output": "[\"eat\",\"oath\"]", "explanation": "Matching words on board."}],
    companies: ["Amazon", "Microsoft", "Google", "Meta", "Apple", "Uber"],
    acceptanceRate: "36.8%",
    frequency: "95%",
    edgeCases: ["Overlapping prefixes (e.g. \"app\", \"apple\")", "Word appears multiple times on board (deduplicate with set or clearing is_end)"],
    interviewTips: ["Store `node.word = word` at end of Trie path so you can append word directly without string joining."],
    optimal: {
      title: "Prefix Trie + Grid DFS Backtracking with Trie Pruning",
      subtitle: "O(m * n * 4^L) time and O(Total Characters) space",
      timeComplexity: "O(m * n * 4^L)",
      timeComplexityDetail: "L is max word length (<= 10).",
      spaceComplexity: "O(Total Characters)",
      spaceComplexityDetail: "Trie node storage.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Build Trie with node.word attribute. DFS from each cell checking Trie children, marking board cells visited in-place.",
      keySteps: ["1. Build Trie: for w in words: curr = root; for c in w: curr = curr.children.setdefault(c, TrieNode()); curr.word = w.", "2. dfs(r, c, parent): c = board[r][c]; curr = parent.children[c]; if curr.word: res.append(curr.word); curr.word = None; board[r][c] = \"#\"; for nr, nc in neighbors: if 0 <= nr < m and 0 <= nc < n and board[nr][nc] in curr.children: dfs(nr, nc, curr); board[r][c] = c.", "3. For r in range(m): for c in range(n): if board[r][c] in root.children: dfs(r, c, root).", "4. Return res."],
      code: {
        python: ["class TrieNode:", "    def __init__(self):", "        self.children = {}", "        self.word = None", "", "class Solution:", "    def findWords(self, board: List[List[str]], words: List[str]) -> List[str]:", "        root = TrieNode()", "        for w in words:", "            curr = root", "            for c in w:", "                if c not in curr.children: curr.children[c] = TrieNode()", "                curr = curr.children[c]", "            curr.word = w", "", "        m, n = len(board), len(board[0])", "        res = []", "", "        def dfs(r, c, parent):", "            char = board[r][c]", "            curr = parent.children[char]", "            if curr.word:", "                res.append(curr.word)", "                curr.word = None  # avoid duplicates", "", "            board[r][c] = \"#\"", "            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:", "                nr, nc = r + dr, c + dc", "                if 0 <= nr < m and 0 <= nc < n and board[nr][nc] in curr.children:", "                    dfs(nr, nc, curr)", "            board[r][c] = char", "", "        for r in range(m):", "            for c in range(n):", "                if board[r][c] in root.children:", "                    dfs(r, c, root)", "        return res"],
        cpp: ["// Word search II cpp"],
        java: ["// Word search II java"],
        typescript: ["// Word search II ts"],
      },
    },
    bruteForce: {
      title: "Word Search I for Every Word",
      subtitle: "O(W * m * n * 4^L) brute search",
      timeComplexity: "O(W * m * n * 4^L)",
      timeComplexityDetail: "Runs Word Search I independently for every word in list.",
      spaceComplexity: "O(L)",
      spaceComplexityDetail: "Recursion stack.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Iterate through words array and run individual DFS word search on board.",
      keySteps: ["1. For each word in words: run exist(board, word)."],
      code: {
        python: ["# Word Search I repeated"],
        cpp: ["// Word Search I repeated"],
        java: ["// Repeated"],
        typescript: ["// Repeated"],
      },
    },
  },
}
