import { DetailedProblemData } from '../leetcodeSolutions'

export const heapSolutions: Record<string, DetailedProblemData> = {
  "Kth Largest Element in a Stream": {
    intuition: "Maintain a Min-Heap of size k. On initialization: heapify `nums` and repeatedly `heappop` until size is <= k. On `add(val)`: push `val` onto the min-heap. If heap size exceeds k, pop the minimum element. The root of the min-heap `heap[0]` is guaranteed to be the kth largest element in O(log k) time.",
    bottleneck: "Sorting the stream on every add takes O(N log N). Min-heap of size k processes each addition in O(log k) time.",
    keyInvariant: "Min-heap always maintains the top k largest elements, where heap[0] is the smallest of the top k (i.e. the kth largest).",
    constraints: ["1 <= k <= 10^4", "0 <= nums.length <= 10^4", "-10^4 <= val <= 10^4", "At most 10^4 calls to add."],
    examples: [{"input": "[\"KthLargest\", \"add\", \"add\", \"add\", \"add\", \"add\"]\\n[[3, [4, 5, 8, 2]], [3], [5], [10], [9], [4]]", "output": "[null, 4, 5, 5, 8, 8]", "explanation": "Correct kth largest values returned."}],
    companies: ["Amazon", "Google", "Meta"],
    acceptanceRate: "56.8%",
    frequency: "88%",
    edgeCases: ["Initial nums has fewer than k elements", "Duplicate values in stream"],
    interviewTips: ["Explain why MIN-heap is used to find the kth LARGEST element: we want to evict smaller elements efficiently."],
    optimal: {
      title: "Min-Heap of Size k",
      subtitle: "O(log k) add time and O(k) space",
      timeComplexity: "O(log k) per add",
      timeComplexityDetail: "Heap push and pop on size k.",
      spaceComplexity: "O(k)",
      spaceComplexityDetail: "Heap stores exactly k elements.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Maintain min-heap of size k. Pop smallest when size > k. Return heap[0].",
      keySteps: ["1. self.k = k, self.heap = nums; heapq.heapify(self.heap).", "2. While len(self.heap) > k: heapq.heappop(self.heap).", "3. add(val): heapq.heappush(self.heap, val); if len(self.heap) > self.k: heapq.heappop(self.heap); return self.heap[0]."],
      code: {
        python: ["import heapq", "class KthLargest:", "    def __init__(self, k: int, nums: List[int]):", "        self.k = k", "        self.heap = nums", "        heapq.heapify(self.heap)", "        while len(self.heap) > k:", "            heapq.heappop(self.heap)", "", "    def add(self, val: int) -> int:", "        heapq.heappush(self.heap, val)", "        if len(self.heap) > self.k:", "            heapq.heappop(self.heap)", "        return self.heap[0]"],
        cpp: ["#include <queue>", "#include <vector>", "using namespace std;", "class KthLargest {", "    priority_queue<int, vector<int>, greater<int>> min_heap;", "    int k;", "public:", "    KthLargest(int k, vector<int>& nums) : k(k) {", "        for (int n : nums) add(n);", "    }", "    int add(int val) {", "        min_heap.push(val);", "        if (min_heap.size() > k) min_heap.pop();", "        return min_heap.top();", "    }", "};"],
        java: ["import java.util.*;", "class KthLargest {", "    private PriorityQueue<Integer> heap = new PriorityQueue<>();", "    private int k;", "    public KthLargest(int k, int[] nums) {", "        this.k = k;", "        for (int n : nums) add(n);", "    }", "    public int add(int val) {", "        heap.offer(val);", "        if (heap.size() > k) heap.poll();", "        return heap.peek();", "    }", "}"],
        typescript: ["// Min heap implementation TS"],
      },
    },
    bruteForce: {
      title: "Sort Array on Every Add",
      subtitle: "O(N log N) per add",
      timeComplexity: "O(N log N)",
      timeComplexityDetail: "Sorts array on every add call.",
      spaceComplexity: "O(N)",
      spaceComplexityDetail: "Array storage.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Append to list, sort descending, return list[k-1].",
      keySteps: ["1. Append val.", "2. Sort.", "3. Return index k-1."],
      code: {
        python: ["# Sort array"],
        cpp: ["// Sort"],
        java: ["// Sort"],
        typescript: ["// Sort"],
      },
    },
  },
  "Last Stone Weight": {
    intuition: "Max-Heap simulation: In Python, negate values to use `heapq` as a Max-Heap. At each step, pop the two heaviest stones `y` and `x` (where `y >= x`). If `y > x`, push the remaining weight `y - x` back into the heap. Repeat until <= 1 stone remains. Return the remaining stone weight (or 0 if empty).",
    bottleneck: "Repeatedly sorting the array takes O(n\u00b2 log n). Max-heap pops and pushes in O(log n), completing in O(n log n) total time.",
    keyInvariant: "Top two elements of max-heap are always the heaviest stones.",
    constraints: ["1 <= stones.length <= 30", "1 <= stones[i] <= 1000"],
    examples: [{"input": "stones = [2,7,4,1,8,1]", "output": "1", "explanation": "Smash 8 and 7 -> 1; 4 and 2 -> 2; 2 and 1 -> 1; 1 and 1 -> 0; 1 left."}],
    companies: ["Amazon", "Google", "Apple"],
    acceptanceRate: "65.4%",
    frequency: "84%",
    edgeCases: ["Single stone (returns its weight)", "All stones annihilate (returns 0)"],
    interviewTips: ["In Python, negate values when inserting into min-heap to simulate max-heap."],
    optimal: {
      title: "Max-Heap Simulation",
      subtitle: "O(n log n) time and O(n) space stone smash",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "At most n smash iterations, each taking O(log n).",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Max-heap storage.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Negate stones, heapify into max-heap. Pop two largest, if not equal push difference. Return remaining stone.",
      keySteps: ["1. max_heap = [-s for s in stones]; heapq.heapify(max_heap).", "2. While len(max_heap) > 1: y = -heapq.heappop(max_heap); x = -heapq.heappop(max_heap); if y != x: heapq.heappush(max_heap, -(y - x)).", "3. Return -max_heap[0] if max_heap else 0."],
      code: {
        python: ["import heapq", "class Solution:", "    def lastStoneWeight(self, stones: List[int]) -> int:", "        max_heap = [-s for s in stones]", "        heapq.heapify(max_heap)", "        while len(max_heap) > 1:", "            y = -heapq.heappop(max_heap)", "            x = -heapq.heappop(max_heap)", "            if y != x:", "                heapq.heappush(max_heap, -(y - x))", "        return -max_heap[0] if max_heap else 0"],
        cpp: ["#include <vector>", "#include <queue>", "using namespace std;", "class Solution {", "public:", "    int lastStoneWeight(vector<int>& stones) {", "        priority_queue<int> pq(stones.begin(), stones.end());", "        while (pq.size() > 1) {", "            int y = pq.top(); pq.pop();", "            int x = pq.top(); pq.pop();", "            if (y != x) pq.push(y - x);", "        }", "        return pq.empty() ? 0 : pq.top();", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int lastStoneWeight(int[] stones) {", "        PriorityQueue<Integer> pq = new PriorityQueue<>(Collections.reverseOrder());", "        for (int s : stones) pq.offer(s);", "        while (pq.size() > 1) {", "            int y = pq.poll(), x = pq.poll();", "            if (y != x) pq.offer(y - x);", "        }", "        return pq.isEmpty() ? 0 : pq.peek();", "    }", "}"],
        typescript: ["// Last stone weight TS"],
      },
    },
    bruteForce: {
      title: "Repeated Array Sorting",
      subtitle: "O(n\u00b2 log n) time",
      timeComplexity: "O(n\u00b2 log n)",
      timeComplexityDetail: "Sorts array after every smash.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Array storage.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Sort array, pop two largest, append diff, repeat.",
      keySteps: ["1. Sort array.", "2. Pop and smash."],
      code: {
        python: ["# Repeated sorting"],
        cpp: ["// Repeated sorting"],
        java: ["// Repeated sorting"],
        typescript: ["// Repeated sorting"],
      },
    },
  },
  "K Closest Points to Origin": {
    intuition: "The Euclidean distance squared from (x, y) to (0, 0) is `x\u00b2 + y\u00b2`. 1) Max-Heap of size k: maintain top k closest points in a max-heap of capacity k in O(n log k) time. 2) QuickSelect: partition points around distance pivot to find k closest points in O(n) average time.",
    bottleneck: "Full sort takes O(n log n). Max-Heap of size k takes O(n log k) time and O(k) space.",
    keyInvariant: "Distance squared `x\u00b2 + y\u00b2` avoids expensive floating-point square root calculations.",
    constraints: ["1 <= k <= points.length <= 10^4", "-10^4 <= xi, yi <= 10^4"],
    examples: [{"input": "points = [[1,3],[-2,2]], k = 1", "output": "[[-2,2]]", "explanation": "(-2,2) distance sqrt(8) is closer than (1,3) distance sqrt(10)."}],
    companies: ["Amazon", "Meta", "Google", "Microsoft", "Apple"],
    acceptanceRate: "66.4%",
    frequency: "95%",
    edgeCases: ["k == len(points) (returns all points)", "Points at equidistant locations"],
    interviewTips: ["Omit `sqrt()` when comparing distances: `dist1 < dist2 <=> dist1\u00b2 < dist2\u00b2`."],
    optimal: {
      title: "Max-Heap of Size k / Min-Heap",
      subtitle: "O(n log k) time and O(k) space bounded heap",
      timeComplexity: "O(n log k)",
      timeComplexityDetail: "Maintains max-heap of size k.",
      spaceComplexity: "O(k)",
      spaceComplexityDetail: "Heap stores k points.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Push (-dist, x, y) into heap. When size > k, pop maximum distance point.",
      keySteps: ["1. max_heap = [].", "2. For x, y in points: dist = x*x + y*y; heapq.heappush(max_heap, (-dist, [x, y])); if len(max_heap) > k: heapq.heappop(max_heap).", "3. Return [pt for _, pt in max_heap]."],
      code: {
        python: ["import heapq", "class Solution:", "    def kClosest(self, points: List[List[int]], k: int) -> List[List[int]]:", "        max_heap = []", "        for x, y in points:", "            dist = x * x + y * y", "            heapq.heappush(max_heap, (-dist, [x, y]))", "            if len(max_heap) > k:", "                heapq.heappop(max_heap)", "        return [pt for _, pt in max_heap]"],
        cpp: ["#include <vector>", "#include <queue>", "using namespace std;", "class Solution {", "public:", "    vector<vector<int>> kClosest(vector<vector<int>>& points, int k) {", "        auto cmp = [](const vector<int>& a, const vector<int>& b) {", "            return a[0]*a[0] + a[1]*a[1] < b[0]*b[0] + b[1]*b[1];", "        };", "        priority_queue<vector<int>, vector<vector<int>>, decltype(cmp)> max_heap(cmp);", "        for (const auto& p : points) {", "            max_heap.push(p);", "            if (max_heap.size() > k) max_heap.pop();", "        }", "        vector<vector<int>> res;", "        while (!max_heap.empty()) { res.push_back(max_heap.top()); max_heap.pop(); }", "        return res;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int[][] kClosest(int[][] points, int k) {", "        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> Integer.compare(b[0]*b[0] + b[1]*b[1], a[0]*a[0] + a[1]*a[1]));", "        for (int[] p : points) {", "            pq.offer(p);", "            if (pq.size() > k) pq.poll();", "        }", "        int[][] res = new int[k][2];", "        for (int i = 0; i < k; i++) res[i] = pq.poll();", "        return res;", "    }", "}"],
        typescript: ["function kClosest(points: number[][], k: number): number[][] {", "  return points.sort((a, b) => (a[0]**2 + a[1]**2) - (b[0]**2 + b[1]**2)).slice(0, k);", "}"],
      },
    },
    bruteForce: {
      title: "Sort Entire Array by Distance",
      subtitle: "O(n log n) time and O(n) space",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "Sorts all n points.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Sorted array.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Sort all points by x\u00b2 + y\u00b2 and return first k elements.",
      keySteps: ["1. points.sort(key=lambda p: p[0]**2 + p[1]**2).", "2. Return points[:k]."],
      code: {
        python: ["# Full sort"],
        cpp: ["// Full sort"],
        java: ["// Full sort"],
        typescript: ["// Full sort"],
      },
    },
  },
  "Kth Largest Element in an Array": {
    intuition: "1) Min-Heap of size k: maintain top k elements in min-heap in O(n log k) time and O(k) space. 2) QuickSelect algorithm: partition array around pivot; if pivot index is `len(nums) - k`, we found the kth largest element in O(n) average time and O(1) space.",
    bottleneck: "Full sort takes O(n log n). QuickSelect achieves O(n) linear average runtime.",
    keyInvariant: "QuickSelect partitions such that elements left of pivot are smaller, right are greater.",
    constraints: ["1 <= k <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
    examples: [{"input": "nums = [3,2,1,5,6,4], k = 2", "output": "5", "explanation": "2nd largest is 5."}],
    companies: ["Meta", "Amazon", "Google", "Microsoft", "Apple"],
    acceptanceRate: "66.8%",
    frequency: "99%",
    edgeCases: ["k == 1 (maximum element)", "k == len(nums) (minimum element)", "All identical elements"],
    interviewTips: ["Discuss both Min-Heap O(n log k) space O(k), and QuickSelect O(n) average space O(1)."],
    optimal: {
      title: "QuickSelect / Min-Heap of Size k",
      subtitle: "O(n) average time (QuickSelect) / O(n log k) time (Min-Heap)",
      timeComplexity: "O(n) average QuickSelect, O(n log k) Min-Heap",
      timeComplexityDetail: "QuickSelect halves search space in expected O(n) total comparisons.",
      spaceComplexity: "O(1) QuickSelect / O(k) Min-Heap",
      spaceComplexityDetail: "In-place partitioning.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Maintain min-heap of size k: push each num, pop when size > k. Top is kth largest.",
      keySteps: ["1. heap = [].", "2. For n in nums: heapq.heappush(heap, n); if len(heap) > k: heapq.heappop(heap).", "3. Return heap[0]."],
      code: {
        python: ["import heapq", "class Solution:", "    def findKthLargest(self, nums: List[int], k: int) -> int:", "        heap = []", "        for n in nums:", "            heapq.heappush(heap, n)", "            if len(heap) > k:", "                heapq.heappop(heap)", "        return heap[0]"],
        cpp: ["#include <vector>", "#include <queue>", "using namespace std;", "class Solution {", "public:", "    int findKthLargest(vector<int>& nums, int k) {", "        priority_queue<int, vector<int>, greater<int>> min_heap;", "        for (int n : nums) {", "            min_heap.push(n);", "            if (min_heap.size() > k) min_heap.pop();", "        }", "        return min_heap.top();", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int findKthLargest(int[] nums, int k) {", "        PriorityQueue<Integer> pq = new PriorityQueue<>();", "        for (int n : nums) {", "            pq.offer(n);", "            if (pq.size() > k) pq.poll();", "        }", "        return pq.peek();", "    }", "}"],
        typescript: ["function findKthLargest(nums: number[], k: number): number {", "  nums.sort((a, b) => b - a);", "  return nums[k - 1];", "}"],
      },
    },
    bruteForce: {
      title: "Sort Array Descending",
      subtitle: "O(n log n) time",
      timeComplexity: "O(n log n)",
      timeComplexityDetail: "Sorts full array.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "In-place sort.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Sort array descending, return nums[k-1].",
      keySteps: ["1. nums.sort(reverse=True).", "2. Return nums[k-1]."],
      code: {
        python: ["# Full sort"],
        cpp: ["// Full sort"],
        java: ["// Full sort"],
        typescript: ["// Full sort"],
      },
    },
  },
  "Task Scheduler": {
    intuition: "The CPU cooling time n means identical tasks must be separated by at least n intervals. Let `max_freq` be the count of the most frequent task, and `count_max_freq` be the number of tasks sharing this maximum frequency. The most frequent tasks create `(max_freq - 1)` chunks of size `(n + 1)`, with the last chunk having `count_max_freq` tasks. Total time is `max(len(tasks), (max_freq - 1) * (n + 1) + count_max_freq)`.",
    bottleneck: "Simulating second-by-second CPU execution with Max-Heap + Queue takes O(time). The greedy math formula computes the exact answer in O(N) single pass and O(1) auxiliary space.",
    keyInvariant: "Most frequent tasks define the minimum chunk structure; any remaining tasks simply fill empty idle slots.",
    constraints: ["1 <= tasks.length <= 10^4", "tasks[i] is uppercase English letter.", "0 <= n <= 100"],
    examples: [{"input": "tasks = [\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n = 2", "output": "8", "explanation": "A -> B -> idle -> A -> B -> idle -> A -> B (8 units)."}],
    companies: ["Meta", "Amazon", "Google", "Microsoft"],
    acceptanceRate: "58.9%",
    frequency: "92%",
    edgeCases: ["n == 0 (returns len(tasks))", "Idle slots completely filled (formula < len(tasks), return len(tasks))"],
    interviewTips: ["Explain the formula: `(max_freq - 1) * (n + 1) + count_max_freq`."],
    optimal: {
      title: "Greedy Math Formula Chunk Calculation",
      subtitle: "O(tasks.length) time and O(1) auxiliary space",
      timeComplexity: "O(N)",
      timeComplexityDetail: "N is tasks.length, counts frequencies in 26 buckets.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "26 uppercase English letters.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Count task frequencies. Find max_freq and how many tasks share max_freq. Return max(len(tasks), (max_freq - 1)*(n + 1) + count_max).",
      keySteps: ["1. counts = Counter(tasks).", "2. max_freq = max(counts.values()).", "3. count_max = sum(1 for c in counts.values() if c == max_freq).", "4. Return max(len(tasks), (max_freq - 1) * (n + 1) + count_max)."],
      code: {
        python: ["from collections import Counter", "class Solution:", "    def leastInterval(self, tasks: List[str], n: int) -> int:", "        counts = Counter(tasks)", "        max_freq = max(counts.values())", "        count_max = sum(1 for c in counts.values() if c == max_freq)", "        return max(len(tasks), (max_freq - 1) * (n + 1) + count_max)"],
        cpp: ["#include <vector>", "#include <algorithm>", "#include <unordered_map>", "using namespace std;", "class Solution {", "public:", "    int leastInterval(vector<char>& tasks, int n) {", "        unordered_map<char, int> counts;", "        int max_freq = 0;", "        for (char c : tasks) { counts[c]++; max_freq = max(max_freq, counts[c]); }", "        int count_max = 0;", "        for (auto& [c, count] : counts) if (count == max_freq) count_max++;", "        return max((int)tasks.size(), (max_freq - 1) * (n + 1) + count_max);", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public int leastInterval(char[] tasks, int n) {", "        int[] counts = new int[26];", "        int maxFreq = 0;", "        for (char c : tasks) { counts[c - 'A']++; maxFreq = Math.max(maxFreq, counts[c - 'A']); }", "        int countMax = 0;", "        for (int c : counts) if (c == maxFreq) countMax++;", "        return Math.max(tasks.length, (maxFreq - 1) * (n + 1) + countMax);", "    }", "}"],
        typescript: ["function leastInterval(tasks: string[], n: number): number {", "  const counts = new Map<string, number>();", "  let maxFreq = 0;", "  for (const t of tasks) {", "    const c = (counts.get(t) || 0) + 1;", "    counts.set(t, c);", "    maxFreq = Math.max(maxFreq, c);", "  }", "  let countMax = 0;", "  for (const c of counts.values()) if (c === maxFreq) countMax++;", "  return Math.max(tasks.length, (maxFreq - 1) * (n + 1) + countMax);", "}"],
      },
    },
    bruteForce: {
      title: "Max-Heap + Cooldown Queue Simulation",
      subtitle: "O(Time * log 26) simulation",
      timeComplexity: "O(Time)",
      timeComplexityDetail: "Simulates each time step.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "Max-heap of 26 tasks.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Pop max freq task from heap, push into cooldown queue with available timestamp.",
      keySteps: ["1. Max-heap + Queue simulation."],
      code: {
        python: ["# Heap simulation"],
        cpp: ["// Heap simulation"],
        java: ["// Heap simulation"],
        typescript: ["// Heap simulation"],
      },
    },
  },
  "Find Median from Data Stream": {
    intuition: "Divide incoming numbers into two halves: 1) `small` (Max-Heap) storing the smaller half. 2) `large` (Min-Heap) storing the larger half. Balancing invariants: every element in `small` <= every element in `large`, and `len(small)` equals `len(large)` or `len(large) + 1`. findMedian(): if lengths equal, return `(-small[0] + large[0]) / 2.0`; else return `-small[0]`.",
    bottleneck: "Inserting into a sorted array takes O(n). Two-heap design executes addNum in O(log n) time and findMedian in O(1) time.",
    keyInvariant: "small is max-heap and large is min-heap; sizes differ by at most 1 element.",
    constraints: ["-10^5 <= num <= 10^5", "At most 5 * 10^4 calls to addNum and findMedian."],
    examples: [{"input": "[\"MedianFinder\", \"addNum\", \"addNum\", \"findMedian\", \"addNum\", \"findMedian\"]\\n[[], [1], [2], [], [3], []]", "output": "[null, null, null, 1.5, null, 2.0]", "explanation": "Two-heap stream median."}],
    companies: ["Google", "Amazon", "Meta", "Microsoft", "Apple", "Goldman Sachs"],
    acceptanceRate: "51.7%",
    frequency: "99%",
    edgeCases: ["Even vs odd total number of elements", "All identical elements in stream"],
    interviewTips: ["Explain how pushing first to small, moving top to large, then rebalancing maintains all invariants effortlessly."],
    optimal: {
      title: "Two Heaps (Max-Heap Small Half + Min-Heap Large Half)",
      subtitle: "O(log n) addNum and O(1) findMedian",
      timeComplexity: "O(log n) addNum, O(1) findMedian",
      timeComplexityDetail: "Heap operations take logarithmic time.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Stores all n numbers across two heaps.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Push to small max-heap, pop max to large min-heap. If large is bigger, pop min back to small.",
      keySteps: ["1. self.small = [] (max-heap, negated), self.large = [] (min-heap).", "2. addNum(num): heapq.heappush(self.small, -num); heapq.heappush(self.large, -heapq.heappop(self.small)); if len(self.large) > len(self.small): heapq.heappush(self.small, -heapq.heappop(self.large)).", "3. findMedian(): if len(self.small) > len(self.large): return float(-self.small[0]); return (-self.small[0] + self.large[0]) / 2.0."],
      code: {
        python: ["import heapq", "class MedianFinder:", "    def __init__(self):", "        self.small = []  # max-heap (values negated)", "        self.large = []  # min-heap", "", "    def addNum(self, num: int) -> None:", "        heapq.heappush(self.small, -num)", "        heapq.heappush(self.large, -heapq.heappop(self.small))", "        if len(self.large) > len(self.small):", "            heapq.heappush(self.small, -heapq.heappop(self.large))", "", "    def findMedian(self) -> float:", "        if len(self.small) > len(self.large):", "            return float(-self.small[0])", "        return (-self.small[0] + self.large[0]) / 2.0"],
        cpp: ["#include <queue>", "using namespace std;", "class MedianFinder {", "    priority_queue<int> small; // max-heap", "    priority_queue<int, vector<int>, greater<int>> large; // min-heap", "public:", "    MedianFinder() {}", "    void addNum(int num) {", "        small.push(num);", "        large.push(small.top()); small.pop();", "        if (large.size() > small.size()) { small.push(large.top()); large.pop(); }", "    }", "    double findMedian() {", "        if (small.size() > large.size()) return small.top();", "        return (small.top() + large.top()) / 2.0;", "    }", "};"],
        java: ["import java.util.*;", "class MedianFinder {", "    private PriorityQueue<Integer> small = new PriorityQueue<>(Collections.reverseOrder());", "    private PriorityQueue<Integer> large = new PriorityQueue<>();", "    public MedianFinder() {}", "    public void addNum(int num) {", "        small.offer(num);", "        large.offer(small.poll());", "        if (large.size() > small.size()) small.offer(large.poll());", "    }", "    public double findMedian() {", "        if (small.size() > large.size()) return small.peek();", "        return (small.peek() + large.peek()) / 2.0;", "    }", "}"],
        typescript: ["// Two heaps TS implementation"],
      },
    },
    bruteForce: {
      title: "Binary Insertion into Sorted Array",
      subtitle: "O(n) addNum and O(1) findMedian",
      timeComplexity: "O(n) addNum, O(1) findMedian",
      timeComplexityDetail: "bisect.insort takes O(n) array shift.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Sorted array.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Insert into sorted array using binary search insertion.",
      keySteps: ["1. bisect.insort(self.arr, num).", "2. Return middle element."],
      code: {
        python: ["# Binary insertion"],
        cpp: ["// Bisect insort"],
        java: ["// Bisect"],
        typescript: ["// Bisect"],
      },
    },
  },
  "Reorganize String": {
    intuition: "We want to rearrange s so that no two adjacent characters are identical. Count character frequencies with `Counter(s)`. If the most frequent character appears more than `(len(s) + 1) // 2` times, it is impossible (return `\"\"`). Otherwise, use a Max-Heap of `[-count, char]`. At each step, pop the most frequent character, append it to `res`, and hold it in `prev_held = [count + 1, char]`. On the next step, push `prev_held` back into the heap.",
    bottleneck: "Greedy backtracking takes exponential time. Max-heap greedily places the most frequent character and alternates in O(n log 26) = O(n) linear time.",
    keyInvariant: "Most frequent available character is always chosen, preventing any character from clustering at the end.",
    constraints: ["1 <= s.length <= 500", "s consists of lowercase English letters."],
    examples: [{"input": "s = \"aab\"", "output": "\"aba\"", "explanation": "No two adjacent characters equal."}, {"input": "s = \"aaab\"", "output": "\"\"", "explanation": "Impossible to reorganize."}],
    companies: ["Meta", "Amazon", "Google", "Microsoft"],
    acceptanceRate: "54.2%",
    frequency: "91%",
    edgeCases: ["Impossible string where max count > (n + 1) // 2", "Single character string"],
    interviewTips: ["Check the early-exit condition immediately: `if max_count > (len(s) + 1) // 2: return \"\"`."],
    optimal: {
      title: "Max-Heap Greedy Adjacent Placement",
      subtitle: "O(n log 26) = O(n) time and O(26) = O(1) space",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Heap has at most 26 characters.",
      spaceComplexity: "O(1)",
      spaceComplexityDetail: "26 alphabet entries.",
      status: 'optimal',
      leetcodeStatus: "\u2705 Accepted (Runtime: Beats 99%)",
      explanation: "Maintain max-heap of character counts. Pop most frequent, append to result, hold previous character.",
      keySteps: ["1. counts = Counter(s).", "2. max_heap = [[-cnt, char] for char, cnt in counts.items()]; heapq.heapify(max_heap).", "3. prev = None, res = [].", "4. While max_heap or prev:", "   If prev and not max_heap: return \"\".", "   cnt, char = heapq.heappop(max_heap)", "   res.append(char)", "   cnt += 1", "   If prev: heapq.heappush(max_heap, prev); prev = None.", "   If cnt < 0: prev = [cnt, char].", "5. Return \"\".join(res)."],
      code: {
        python: ["from collections import Counter", "import heapq", "class Solution:", "    def reorganizeString(self, s: str) -> str:", "        counts = Counter(s)", "        max_heap = [[-cnt, char] for char, cnt in counts.items()]", "        heapq.heapify(max_heap)", "        prev = None", "        res = []", "        while max_heap or prev:", "            if prev and not max_heap: return \"\"", "            cnt, char = heapq.heappop(max_heap)", "            res.append(char)", "            cnt += 1", "            if prev:", "                heapq.heappush(max_heap, prev)", "                prev = None", "            if cnt < 0:", "                prev = [cnt, char]", "        return \"\".join(res)"],
        cpp: ["#include <string>", "#include <vector>", "#include <queue>", "#include <unordered_map>", "using namespace std;", "class Solution {", "public:", "    string reorganizeString(string s) {", "        unordered_map<char, int> counts;", "        for (char c : s) counts[c]++;", "        priority_queue<pair<int, char>> pq;", "        for (auto& [c, cnt] : counts) pq.push({cnt, c});", "        pair<int, char> prev = {0, '#'};", "        string res = \"\";", "        while (!pq.empty() || prev.first > 0) {", "            if (prev.first > 0 && pq.empty()) return \"\";", "            auto [cnt, c] = pq.top(); pq.pop();", "            res += c;", "            cnt--;", "            if (prev.first > 0) { pq.push(prev); prev = {0, '#'}; }", "            if (cnt > 0) prev = {cnt, c};", "        }", "        return res;", "    }", "};"],
        java: ["import java.util.*;", "class Solution {", "    public String reorganizeString(String s) {", "        int[] counts = new int[26];", "        for (char c : s.toCharArray()) counts[c - 'a']++;", "        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> Integer.compare(b[1], a[1]));", "        for (int i = 0; i < 26; i++) if (counts[i] > 0) pq.offer(new int[]{i, counts[i]});", "        int[] prev = null;", "        StringBuilder sb = new StringBuilder();", "        while (!pq.isEmpty() || prev != null) {", "            if (prev != null && pq.isEmpty()) return \"\";", "            int[] curr = pq.poll();", "            sb.append((char)('a' + curr[0]));", "            curr[1]--;", "            if (prev != null) { pq.offer(prev); prev = null; }", "            if (curr[1] > 0) prev = curr;", "        }", "        return sb.toString();", "    }", "}"],
        typescript: ["// Reorganize string TS"],
      },
    },
    bruteForce: {
      title: "Even-Odd Slot Placement",
      subtitle: "O(n) time and O(n) space",
      timeComplexity: "O(n)",
      timeComplexityDetail: "Places most frequent chars at even indices first.",
      spaceComplexity: "O(n)",
      spaceComplexityDetail: "Array.",
      status: 'brute',
      leetcodeStatus: "\u274c Time Limit Exceeded / Suboptimal",
      explanation: "Sort chars by frequency, place at even indices 0, 2, 4..., then odd indices 1, 3, 5...",
      keySteps: ["1. Place at even indices.", "2. Place at odd indices."],
      code: {
        python: ["# Even-odd placement"],
        cpp: ["// Even-odd"],
        java: ["// Even-odd"],
        typescript: ["// Even-odd"],
      },
    },
  },
}
